# Generated by Django 5.1.15 on 2026-09-23 22:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        ('crm', '0025_alter_webhook_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNurtureEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('replied', 'Replied'), ('converted', 'Converted')], default='pending', max_length=12)),
                ('trigger_kind', models.CharField(choices=[('manual', 'Manual'), ('score_threshold', 'Score Threshold'), ('form_source', 'Form Source'), ('qualification', 'Qualification'), ('recycled', 'Recycled')], default='manual', max_length=20)),
                ('score_at_enrollment', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consent_evidence', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_touch_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_touch_at', models.DateTimeField(blank=True, null=True)),
                ('touch_count', models.PositiveIntegerField(default=0, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('replied', 'Replied'), ('converted', 'Converted'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('manual', 'Manual')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consent_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_nurture_enrollments', to='core.consentpurpose')),
                ('email_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_nurture_enrollments', to='crm.emailcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_nurture_enrollments', to='crm.lead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_nurture_enrollments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'next_touch_at'], name='sales_lne_tnt_status_idx'), models.Index(fields=['tenant', 'email_campaign', 'status'], name='sales_lne_tnt_campaign_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'lead', 'email_campaign'), name='sales_lne_tenant_lead_campaign_uniq')],
            },
        ),
        migrations.CreateModel(
            name='LeadQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.CharField(choices=[('bant', 'BANT'), ('meddic', 'MEDDIC'), ('both', 'BANT + MEDDIC')], default='bant', max_length=10)),
                ('status', models.CharField(choices=[('unassessed', 'Unassessed'), ('partially_qualified', 'Partially Qualified'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('archived', 'Archived')], default='unassessed', max_length=24)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('seniority', models.CharField(choices=[('unknown', 'Unknown'), ('individual_contributor', 'Individual Contributor'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive'), ('owner', 'Owner')], default='unknown', max_length=24)),
                ('budget_status', models.CharField(choices=[('unknown', 'Unknown'), ('not_confirmed', 'Not Confirmed'), ('confirmed', 'Confirmed'), ('adequate', 'Adequate'), ('insufficient', 'Insufficient')], default='unknown', max_length=24)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('authority_level', models.CharField(choices=[('unknown', 'Unknown'), ('influencer', 'Influencer'), ('user', 'User'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive'), ('owner', 'Owner')], default='unknown', max_length=24)),
                ('need_summary', models.TextField(blank=True)),
                ('expected_purchase_on', models.DateField(blank=True, null=True)),
                ('economic_buyer', models.TextField(blank=True)),
                ('decision_criteria', models.TextField(blank=True)),
                ('decision_process', models.TextField(blank=True)),
                ('technical_requirements', models.TextField(blank=True)),
                ('pain_points', models.TextField(blank=True)),
                ('success_metrics', models.TextField(blank=True)),
                ('disqualification_reason', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_review_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lead_assessments', to=settings.AUTH_USER_MODEL)),
                ('budget_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currency')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_qualification', to='crm.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='sales_lq_tnt_status_idx'), models.Index(fields=['tenant', 'framework'], name='sales_lq_tnt_framework_idx'), models.Index(fields=['tenant', 'next_review_on'], name='sales_lq_tnt_review_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('match_mode', models.CharField(choices=[('all', 'All conditions'), ('any', 'Any condition')], default='all', max_length=10)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('assignment_mode', models.CharField(choices=[('fixed_owner', 'Fixed Owner'), ('territory_manager', 'Territory Manager'), ('round_robin', 'Round Robin')], max_length=20)),
                ('max_open_leads', models.PositiveIntegerField(blank=True, null=True)),
                ('cursor', models.PositiveIntegerField(default=0, editable=False)),
                ('last_assigned_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('default_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_default_routing_rules', to=settings.AUTH_USER_MODEL)),
                ('eligible_owners', models.ManyToManyField(blank=True, related_name='sales_routing_rules', to=settings.AUTH_USER_MODEL)),
                ('fallback_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_fallback_routing_rules', to=settings.AUTH_USER_MODEL)),
                ('last_assigned_owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_last_routing_rules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_routing_rules', to='crm.territory')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'priority'], name='sales_lrr_tnt_active_idx'), models.Index(fields=['tenant', 'assignment_mode'], name='sales_lrr_tnt_mode_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='sales_lrr_tenant_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='LeadScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal_category', models.CharField(choices=[('behavioral', 'Behavioral'), ('demographic', 'Demographic'), ('qualification', 'Qualification'), ('manual', 'Manual'), ('decay', 'Decay'), ('correction', 'Correction')], max_length=20)),
                ('event_type', models.CharField(choices=[('form_submitted', 'Form Submitted'), ('email_open', 'Email Open'), ('email_click', 'Email Click'), ('web_visit', 'Website Visit'), ('content_download', 'Content Download'), ('event_attendance', 'Event Attendance'), ('meeting_booked', 'Meeting Booked'), ('demo_request', 'Demo Request'), ('call_connected', 'Call Connected'), ('reply_received', 'Reply Received'), ('fit_match', 'Fit Match'), ('fit_mismatch', 'Fit Mismatch'), ('unsubscribe', 'Unsubscribe'), ('manual_adjustment', 'Manual Adjustment'), ('decay', 'Score Decay'), ('correction', 'Correction')], max_length=32)),
                ('score_delta', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('source_kind', models.CharField(choices=[('form_submission', 'Form Submission'), ('campaign_member', 'Campaign Member'), ('communication_log', 'Communication Log'), ('qualification', 'Qualification'), ('web_tracking', 'Web Tracking'), ('api', 'API'), ('manual', 'Manual')], max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('corrects_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='sales.leadscoreevent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_score_events', to='crm.lead')),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_recorded_score_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'lead', '-occurred_at'], name='sales_lse_tnt_lead_idx'), models.Index(fields=['tenant', 'event_type', '-occurred_at'], name='sales_lse_tnt_type_idx'), models.Index(fields=['tenant', 'source_kind', 'source_ref'], name='sales_lse_tnt_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='sales_lse_tenant_key_uniq')],
            },
        ),
    ]
