# Generated by Django 5.1.15 on 2026-09-24 06:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        ('crm', '0025_alter_webhook_secret'),
        ('sales', '0003_leadnurtureenrollment_tenant_number_uniq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('strategic', 'Strategic'), ('key', 'Key'), ('growth', 'Growth'), ('nurture', 'Nurture')], default='growth', max_length=16)),
                ('lifecycle_stage', models.CharField(choices=[('prospect', 'Prospect'), ('active_customer', 'Active Customer'), ('expansion_candidate', 'Expansion Candidate'), ('dormant', 'Dormant'), ('former_customer', 'Former Customer')], default='prospect', max_length=24)),
                ('strategic_priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=12)),
                ('revenue_potential', models.CharField(choices=[('very_high', 'Very High'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('wallet_category', models.CharField(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('full_wallet', 'Full Wallet')], default='none', max_length=16)),
                ('rationale', models.TextField()),
                ('effective_on', models.DateField(default=django.utils.timezone.localdate)),
                ('review_due_on', models.DateField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_account_classification', to='core.party')),
                ('classified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_account_classifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-effective_on', 'account__name'],
                'indexes': [models.Index(fields=['tenant', 'tier', 'lifecycle_stage'], name='sales_aclass_tnt_tier_life_idx'), models.Index(fields=['tenant', 'strategic_priority', 'review_due_on'], name='sales_aclass_prio_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'account'), name='sales_aclass_tenant_account_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('review_due', 'Review Due'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('business_drivers', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('strategy', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('opportunities', models.TextField(blank=True)),
                ('threats', models.TextField(blank=True)),
                ('white_space_assessment', models.TextField(blank=True)),
                ('growth_initiatives', models.TextField(blank=True)),
                ('risk_summary', models.TextField(blank=True)),
                ('next_review_on', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_account_plans', to='core.party')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_owned_account_plans', to=settings.AUTH_USER_MODEL)),
                ('related_opportunities', models.ManyToManyField(blank=True, related_name='sales_account_plans', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'account', 'status'], name='sales_acpl_acct_status_idx'), models.Index(fields=['tenant', 'owner', 'next_review_on'], name='sales_acpl_owner_rev_idx'), models.Index(fields=['tenant', 'status', 'next_review_on'], name='sales_acpl_stat_rev_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'number'), name='sales_acpl_tenant_number_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AccountStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('decision_maker', 'Decision Maker'), ('economic_buyer', 'Economic Buyer'), ('champion', 'Champion'), ('influencer', 'Influencer'), ('blocker', 'Blocker'), ('technical_evaluator', 'Technical Evaluator'), ('procurement', 'Procurement'), ('end_user', 'End User'), ('advisor', 'Advisor'), ('other', 'Other')], max_length=24)),
                ('influence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('attitude', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('relationship_strength', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('former', 'Former')], default='active', max_length=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_account_stakeholders', to='core.party')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_stakeholder_contacts', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['account__name', 'contact__name', 'role'],
                'indexes': [models.Index(fields=['tenant', 'account', 'status'], name='sales_ast_acct_status_idx'), models.Index(fields=['tenant', 'contact', 'status'], name='sales_ast_contact_status_idx'), models.Index(fields=['tenant', 'role', 'attitude'], name='sales_ast_role_attitude_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'account', 'contact', 'role'), name='sales_ast_tenant_account_contact_role_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PartyEnrichmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('firmographic', 'Firmographic'), ('contact', 'Contact'), ('email_validation', 'Email validation'), ('phone_validation', 'Phone validation'), ('social', 'Social profile'), ('employment_change', 'Employment change'), ('duplicate_check', 'Duplicate check')], max_length=24)),
                ('source_kind', models.CharField(choices=[('manual', 'Manual'), ('provider', 'Provider'), ('email_signature', 'Email signature'), ('linkedin', 'LinkedIn'), ('import', 'Import'), ('api', 'API')], max_length=24)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('no_match', 'No match'), ('failed', 'Failed')], default='proposed', max_length=12)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('legal_basis_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_enrichment_events', to='core.consentpurpose')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_enrichment_events', to='core.party')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_requested_enrichment_events', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reviewed_enrichment_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'party', '-occurred_at'], name='sales_pee_tnt_party_idx'), models.Index(fields=['tenant', 'status', '-occurred_at'], name='sales_pee_tnt_status_idx'), models.Index(fields=['tenant', 'kind', '-occurred_at'], name='sales_pee_tnt_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='sales_pee_tenant_key_uniq'), models.CheckConstraint(condition=models.Q(('match_confidence__isnull', True), models.Q(('match_confidence__gte', 0), ('match_confidence__lte', 1)), _connector='OR'), name='sales_pee_confidence_valid')],
            },
        ),
    ]
