# Generated by Django 5.1.15 on 2026-09-25 13:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        ('crm', '0026_opportunity_currency_opportunity_next_step_due_date_and_more'),
        ('sales', '0004_accountclassification_accountplan_accountstakeholder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('aliases', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('market_positioning', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('differentiators', models.TextField(blank=True)),
                ('objection_handling', models.TextField(blank=True)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_competitor_profile', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['party__name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('identified', 'Identified'), ('evaluating', 'Evaluating'), ('shortlisted', 'Shortlisted'), ('preferred', 'Preferred'), ('incumbent', 'Incumbent'), ('eliminated', 'Eliminated'), ('lost_to', 'Lost To'), ('beaten', 'Beaten'), ('withdrew', 'Withdrew')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('pricing_notes', models.TextField(blank=True)),
                ('deal_notes', models.TextField(blank=True)),
                ('positioning_notes', models.TextField(blank=True)),
                ('competitor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.competitorprofile')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_competitors', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_primary', 'relationship', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('role', models.CharField(choices=[('co_owner', 'Co-Owner'), ('collaborator', 'Collaborator'), ('sales_support', 'Sales Support'), ('solution_consultant', 'Solution Consultant'), ('executive_sponsor', 'Executive Sponsor'), ('approver', 'Approver'), ('observer', 'Observer')], max_length=20)),
                ('responsibility', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_team_members', to='crm.opportunity')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_active', 'role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('stage_kind', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=10)),
                ('crm_stage_key', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('forecast_category', models.CharField(choices=[('omitted', 'Omitted'), ('pipeline', 'Pipeline'), ('best_case', 'Best Case'), ('commit', 'Commit'), ('closed', 'Closed')], default='pipeline', max_length=12)),
                ('entry_guidance', models.TextField(blank=True)),
                ('exit_guidance', models.TextField(blank=True)),
                ('entry_criteria', models.JSONField(blank=True, default=list)),
                ('exit_criteria', models.JSONField(blank=True, default=list)),
                ('target_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('is_active', models.BooleanField(default=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sales.pipeline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['pipeline', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityPipelinePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('probability_override', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_pipeline_placement', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='sales.pipeline')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_placements', to='sales.pipelinestage')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WinLossReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('result', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('both', 'Both')], default='both', max_length=10)),
                ('category', models.CharField(choices=[('price', 'Price'), ('product_fit', 'Product Fit'), ('timing', 'Timing'), ('competition', 'Competition'), ('relationship', 'Relationship'), ('authority', 'Authority'), ('budget', 'Budget'), ('no_decision', 'No Decision'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['result', 'sequence', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('result', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('competitor_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.opportunitycompetitor')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_outcomes', to='crm.opportunity')),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.winlossreason')),
            ],
            options={
                'ordering': ['-closed_at', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='competitorprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='sales_cmp_tenant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitorprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_cmp_tenant_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='opportunitycompetitor',
            index=models.Index(fields=['tenant', 'opportunity', 'relationship'], name='sales_oc_tno_relationship_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitycompetitor',
            index=models.Index(fields=['tenant', 'opportunity', 'is_primary'], name='sales_oc_tno_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunitycompetitor',
            constraint=models.UniqueConstraint(fields=('tenant', 'opportunity', 'competitor_profile'), name='sales_oc_tno_profile_uniq'),
        ),
        migrations.AddIndex(
            model_name='opportunityteammember',
            index=models.Index(fields=['tenant', 'opportunity', 'is_active'], name='sales_otm_tno_active_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityteammember',
            index=models.Index(fields=['tenant', 'user'], name='sales_otm_tenant_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityteammember',
            constraint=models.UniqueConstraint(fields=('tenant', 'opportunity', 'user', 'role'), name='sales_otm_tno_ur_uniq'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['tenant', 'is_active'], name='sales_pipe_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['tenant', 'is_default'], name='sales_pipe_tenant_default_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_pipe_tenant_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['tenant', 'pipeline', 'sequence'], name='sales_pstage_tp_sequence_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['tenant', 'stage_kind', 'is_active'], name='sales_pstage_tenant_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('tenant', 'pipeline', 'code'), name='sales_pstage_tp_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('tenant', 'pipeline', 'sequence'), name='sales_pstage_tp_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='sales_pstage_sequence_valid'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', 0), ('probability__lte', 100)), name='sales_pstage_probability_valid'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(('target_days__isnull', True), models.Q(('target_days__gte', 1), ('target_days__lte', 3650)), _connector='OR'), name='sales_pstage_target_days_valid'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(('stage_kind__in', ('open', 'won', 'lost'))), name='sales_pstage_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage_kind', 'open'), _negated=True), models.Q(('crm_stage_key__in', ('prospecting', 'qualification', 'proposal', 'negotiation')), ('forecast_category__in', ('omitted', 'pipeline', 'best_case', 'commit')), ('probability__gte', 1), ('probability__lte', 99), ('stage_kind', 'open')), _connector='OR'), name='sales_pstage_open_integrity'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage_kind', 'won'), _negated=True), models.Q(('crm_stage_key', 'closed_won'), ('forecast_category', 'closed'), ('probability', 100), ('stage_kind', 'won')), _connector='OR'), name='sales_pstage_won_integrity'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage_kind', 'lost'), _negated=True), models.Q(('crm_stage_key', 'closed_lost'), ('forecast_category', 'closed'), ('probability', 0), ('stage_kind', 'lost')), _connector='OR'), name='sales_pstage_lost_integrity'),
        ),
        migrations.AddIndex(
            model_name='opportunitypipelineplacement',
            index=models.Index(fields=['tenant', 'opportunity'], name='sales_opp_place_tenant_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitypipelineplacement',
            index=models.Index(fields=['tenant', 'pipeline'], name='sales_opp_place_tnt_pipe_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunitypipelineplacement',
            constraint=models.CheckConstraint(condition=models.Q(('probability_override__isnull', True), models.Q(('probability_override__gte', 0), ('probability_override__lte', 100)), _connector='OR'), name='sales_opp_place_override_valid'),
        ),
        migrations.AddIndex(
            model_name='winlossreason',
            index=models.Index(fields=['tenant', 'result', 'is_active'], name='sales_wlr_result_active_idx'),
        ),
        migrations.AddIndex(
            model_name='winlossreason',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='sales_wlr_category_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='winlossreason',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_wlr_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='winlossreason',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='sales_wlr_tenant_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='opportunityoutcome',
            index=models.Index(fields=['tenant', 'result', 'closed_at'], name='sales_out_result_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityoutcome',
            index=models.Index(fields=['tenant', 'opportunity', 'closed_at'], name='sales_out_opp_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityoutcome',
            index=models.Index(fields=['tenant', 'reason'], name='sales_out_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityoutcome',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_out_tenant_number_uniq'),
        ),
    ]
