# Generated by Django 5.1.15 on 2026-09-25 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        ('crm', '0026_opportunity_currency_opportunity_next_step_due_date_and_more'),
        ('sales', '0005_competitorprofile_opportunitycompetitor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='opportunitycompetitor',
            index=models.Index(fields=['tenant', 'competitor_profile'], name='sales_oc_tenant_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityoutcome',
            index=models.Index(fields=['tenant', 'closed_at'], name='sales_out_tenant_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitypipelineplacement',
            index=models.Index(fields=['tenant', 'pipeline', 'current_stage'], name='sales_opp_place_tp_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitypipelineplacement',
            index=models.Index(fields=['tenant', 'stage_entered_at'], name='sales_opp_place_stage_at_idx'),
        ),
    ]
