# Generated by Django 5.1.15 on 2026-09-26 11:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0015_alertrule_alertevent_servicecomponent_incident_and_more'),
        ('crm', '0026_opportunity_currency_opportunity_next_step_due_date_and_more'),
        ('sales', '0006_opportunitycompetitor_sales_oc_tenant_profile_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('period_type', models.CharField(choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Annual')], default='quarter', max_length=10)),
                ('period_year', models.PositiveSmallIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)])),
                ('period_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField(editable=False)),
                ('end_date', models.DateField(editable=False)),
                ('rollup_dimension', models.CharField(choices=[('user', 'Sales Representative'), ('org_unit', 'Organizational Unit'), ('territory', 'Territory')], default='user', max_length=12)),
                ('fx_rate_source_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('reporting_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_periods', to='accounting.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'forecast periods',
                'ordering': ['-period_year', 'period_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('scenario_type', models.CharField(choices=[('upside', 'Upside'), ('base', 'Base'), ('downside', 'Downside'), ('custom', 'Custom')], default='custom', max_length=12)),
                ('probability_pct', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_baseline', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('pipeline_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
                ('best_case_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
                ('commit_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
                ('projected_commit_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('projected_total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('assumption_notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_scenarios', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='sales.forecastperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'forecast scenarios',
                'ordering': ['-is_baseline', 'name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=12)),
                ('omitted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pipeline_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('best_case_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('commit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weighted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quota_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('ai_predicted_pipeline', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ai_predicted_best_case', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ai_predicted_commit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ai_confidence_pct', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_model_name', models.CharField(blank=True, max_length=120)),
                ('ai_model_version', models.CharField(blank=True, max_length=60)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_explanation', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_submissions', to='core.orgunit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_submissions', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='sales.forecastperiod')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_submissions', to='sales.pipeline')),
                ('quota_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_submissions', to='crm.salesquota')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_submissions', to='crm.territory')),
            ],
            options={
                'verbose_name_plural': 'forecast submissions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('adjustment_kind', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('revert', 'Revert')], default='direct', max_length=12)),
                ('target_field', models.CharField(choices=[('category', 'Forecast Category'), ('amount', 'Amount')], default='category', max_length=12)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adjusted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('original_category', models.CharField(blank=True, choices=[('omitted', 'Omitted'), ('pipeline', 'Pipeline'), ('best_case', 'Best Case'), ('commit', 'Commit'), ('closed', 'Closed')], max_length=12, null=True)),
                ('adjusted_category', models.CharField(blank=True, choices=[('omitted', 'Omitted'), ('pipeline', 'Pipeline'), ('best_case', 'Best Case'), ('commit', 'Commit'), ('closed', 'Closed')], max_length=12, null=True)),
                ('reason_code', models.CharField(choices=[('new_deal', 'New Deal Added'), ('deal_advanced', 'Deal Advanced A Stage'), ('deal_slipped', 'Deal Slipped'), ('deal_lost', 'Deal Lost'), ('deal_won', 'Deal Won'), ('amount_revised', 'Amount Revised'), ('timing_revised', 'Timing Revised'), ('territory_reassigned', 'Territory Reassigned'), ('manager_judgement', 'Manager Judgement'), ('correction', 'Data Correction')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('is_reverted', models.BooleanField(default=False)),
                ('reverted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revert_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_adjustments', to='crm.opportunity')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecast_adjustments', to='sales.opportunitypipelineplacement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='sales.forecastsubmission')),
            ],
            options={
                'verbose_name_plural': 'forecast adjustments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='forecastperiod',
            index=models.Index(fields=['tenant', 'is_active'], name='sales_fcp_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastperiod',
            index=models.Index(fields=['tenant', 'period_type', 'period_year'], name='sales_fcp_tnt_type_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_fcp_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='forecastperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_type', 'period_year', 'period_number'), name='sales_fcp_tpt_ypn_uniq'),
        ),
        migrations.AddConstraint(
            model_name='forecastperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_number__gte', 1), ('period_number__lte', 12)), name='sales_fcp_period_number_valid'),
        ),
        migrations.AddIndex(
            model_name='forecastscenario',
            index=models.Index(fields=['tenant', 'period'], name='sales_fsc_tnt_period_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastscenario',
            index=models.Index(fields=['tenant', 'is_selected'], name='sales_fsc_tnt_selected_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastscenario',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_fsc_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='forecastscenario',
            constraint=models.UniqueConstraint(fields=('tenant', 'period', 'name'), name='sales_fsc_tnt_period_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='forecastscenario',
            constraint=models.CheckConstraint(condition=models.Q(('probability_pct__gte', 0), ('probability_pct__lte', 100)), name='sales_fsc_probability_valid'),
        ),
        migrations.AddConstraint(
            model_name='forecastscenario',
            constraint=models.CheckConstraint(condition=models.Q(('is_baseline', False), models.Q(('is_baseline', True), ('is_selected', True)), _connector='OR'), name='sales_fsc_baseline_selected'),
        ),
        migrations.AddIndex(
            model_name='forecastsubmission',
            index=models.Index(fields=['tenant', 'period', 'status'], name='sales_fcs_tnt_p_status_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastsubmission',
            index=models.Index(fields=['tenant', 'owner'], name='sales_fcs_tnt_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastsubmission',
            index=models.Index(fields=['tenant', 'period', 'org_unit'], name='sales_fcs_tnt_p_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastsubmission',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_fcs_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='forecastsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('omitted_amount__gte', 0), ('pipeline_amount__gte', 0), ('best_case_amount__gte', 0), ('commit_amount__gte', 0), ('closed_amount__gte', 0), ('weighted_amount__gte', 0), ('quota_amount__gte', 0), ('actual_amount__gte', 0)), name='sales_fcs_amounts_nonneg'),
        ),
        migrations.AddIndex(
            model_name='forecastadjustment',
            index=models.Index(fields=['tenant', 'submission'], name='sales_fad_tnt_submission_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastadjustment',
            index=models.Index(fields=['tenant', 'reason_code'], name='sales_fad_tnt_reason_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastadjustment',
            index=models.Index(fields=['tenant', 'adjustment_kind'], name='sales_fad_tnt_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastadjustment',
            index=models.Index(fields=['tenant', 'opportunity'], name='sales_fad_tnt_opp_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastadjustment',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_fad_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='forecastadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('is_reverted', False), models.Q(('is_reverted', True), ('reverted_at__isnull', False)), _connector='OR'), name='sales_fad_reverted_stamped'),
        ),
    ]
