# Generated by Django 5.1.15 on 2026-09-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alertrule_alertevent_servicecomponent_incident_and_more'),
        ('sales', '0008_quoteapprovalrule_cpqquote_cpqquoteline_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cpqquote',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='productbundleoption',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='quoteapprovalrule',
            unique_together={('tenant', 'number')},
        ),
    ]
