# Generated by Django 5.1.15 on 2026-09-26 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0015_alertrule_alertevent_servicecomponent_incident_and_more'),
        ('crm', '0026_opportunity_currency_opportunity_next_step_due_date_and_more'),
        ('sales', '0009_alter_cpqquote_unique_together_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cpqquote',
            index=models.Index(fields=['tenant', 'number'], name='sales_cpq_tnt_num_idx'),
        ),
        migrations.AddIndex(
            model_name='cpqquote',
            index=models.Index(fields=['tenant', 'approval_status'], name='sales_cpq_tnt_appr_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundleoption',
            index=models.Index(fields=['tenant', 'number'], name='sales_bnd_tnt_num_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundleoption',
            index=models.Index(fields=['tenant', 'is_active'], name='sales_bnd_tnt_act_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteapprovalrule',
            index=models.Index(fields=['tenant', 'number'], name='sales_qar_tnt_num_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteapprovalrule',
            index=models.Index(fields=['tenant', 'is_active'], name='sales_qar_tnt_act_idx'),
        ),
    ]
