# Generated by Django 5.1.15 on 2026-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_cpqquote_sales_cpq_tnt_num_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpqquote',
            name='signer_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
