# Generated by Django 5.1.15 on 2026-09-29 13:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0019_complianceaudit_auditfinding_auditevidence_and_more'),
        ('sales', '0011_cpqquote_signer_ip_address'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('change_type', models.CharField(choices=[('quantity', 'Quantity Change'), ('price', 'Price Change'), ('add_line', 'Add Line'), ('remove_line', 'Remove Line'), ('cancel', 'Cancel Order')], default='quantity', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('withdrawn', 'Withdrawn'), ('superseded', 'Superseded')], default='draft', editable=False, max_length=12)),
                ('reason', models.TextField()),
                ('impact_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_amendments_applied', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_amendments_decided', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_amendments', to='core.document')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_amendments_requested', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_amendments', to='scm.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderAmendmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('remove', 'Remove')], default='update', max_length=8)),
                ('new_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('new_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.orderamendment')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_amendment_lines', to='scm.salesorderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('credit_limit', 'Credit Limit Exceeded'), ('order_value', 'Order Value Ceiling'), ('margin_floor', 'Margin Floor'), ('discount_ceiling', 'Line Discount Ceiling'), ('unmapped_item', 'Unmapped Item Present'), ('missing_ship_to', 'Missing Ship-To Address'), ('expired_quote', 'Source Quote Expired'), ('inactive_item', 'Inactive Item On Order')], default='credit_limit', max_length=24)),
                ('severity', models.CharField(choices=[('block', 'Block Submission'), ('hold', 'Place On Hold'), ('warn', 'Warn Only')], default='hold', max_length=12)),
                ('active_on', models.CharField(choices=[('submit', 'On Submit'), ('amendment', 'On Amendment'), ('both', 'On Submit And Amendment')], default='submit', max_length=12)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON thresholds for this rule type, e.g. {"amount": 5000} or {"pct": 12.5}.')),
                ('priority', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_validation_rules', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'number'],
            },
        ),
        migrations.CreateModel(
            name='OrderHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('hold_type', models.CharField(choices=[('credit', 'Credit Hold'), ('fraud', 'Fraud Review'), ('validation', 'Validation Failure'), ('manual', 'Manual Hold')], default='credit', max_length=24)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('block', 'Block Submission'), ('hold', 'Place On Hold'), ('warn', 'Warn Only')], default='hold', editable=False, max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared'), ('superseded', 'Superseded')], default='open', editable=False, max_length=12)),
                ('evaluation_snapshot', models.JSONField(blank=True, default=dict, editable=False, help_text='Frozen, server-generated evidence of the evaluation that raised this hold.')),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('checked_out_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('clear_note', models.TextField(blank=True)),
                ('checked_out_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_holds_checked_out', to=settings.AUTH_USER_MODEL)),
                ('cleared_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_holds_cleared', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, help_text="The customer this hold is about. Defaults to the order's own customer.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_holds', to='core.party')),
                ('raised_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_holds_raised', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_holds', to='scm.salesorder')),
                ('superseded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='sales.orderhold')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('rule', models.ForeignKey(blank=True, help_text='The rule that fired, if this hold came from the rule set. Blank = placed by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_holds', to='sales.ordervalidationrule')),
            ],
            options={
                'ordering': ['-raised_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('complete', 'Complete'), ('void', 'Void')], default='draft', max_length=12)),
                ('method', models.CharField(choices=[('point_in_time', 'Point In Time'), ('over_time', 'Over Time'), ('milestone', 'Milestone')], default='over_time', max_length=20)),
                ('compliance_standard', models.CharField(choices=[('asc606', 'ASC 606'), ('ifrs15', 'IFRS 15'), ('both', 'ASC 606 & IFRS 15')], default='asc606', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_schedules', to='accounting.fiscalperiod')),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_schedules', to='accounting.journalentry')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_schedules', to='scm.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('goods', 'Goods'), ('services', 'Services'), ('subscription', 'Subscription'), ('milestone', 'Milestone'), ('warranty', 'Warranty')], default='goods', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('allocation_pct', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('recognition_method', models.CharField(choices=[('point_in_time', 'Point In Time'), ('over_time', 'Over Time'), ('milestone', 'Milestone')], default='over_time', max_length=20)),
                ('recognize_on', models.DateField(blank=True, null=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('recognized_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('milestone_label', models.CharField(blank=True, max_length=120)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_obligations', to='scm.item')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_obligations', to='scm.salesorderline')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='sales.revenueschedule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orderamendment',
            index=models.Index(fields=['tenant', 'status'], name='sales_amd_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderamendment',
            index=models.Index(fields=['tenant', 'sales_order'], name='sales_amd_tnt_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderamendment',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_amd_tenant_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='ordervalidationrule',
            index=models.Index(fields=['tenant', 'rule_type'], name='sales_ovr_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ordervalidationrule',
            index=models.Index(fields=['tenant', 'is_active'], name='sales_ovr_tnt_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordervalidationrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_ovr_tenant_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='orderhold',
            index=models.Index(fields=['tenant', 'status'], name='sales_ohd_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhold',
            index=models.Index(fields=['tenant', 'sales_order'], name='sales_ohd_tnt_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderhold',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_ohd_tenant_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='revenueschedule',
            index=models.Index(fields=['tenant', 'status'], name='sales_rvs_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueschedule',
            index=models.Index(fields=['tenant', 'sales_order'], name='sales_rvs_tnt_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenueschedule',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='sales_rvs_tenant_number_uniq'),
        ),
    ]
