# Generated by Django 5.1.15 on 2026-09-29 19:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_complianceaudit_auditfinding_auditevidence_and_more'),
        ('crm', '0026_opportunity_currency_opportunity_next_step_due_date_and_more'),
        ('sales', '0012_orderamendment_orderamendmentline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('segment_type', models.CharField(choices=[('geographic', 'Geographic'), ('industry', 'Industry'), ('account_size', 'Account Size'), ('product_line', 'Product Line'), ('named_account', 'Named Account'), ('mixed', 'Mixed')], default='geographic', max_length=20)),
                ('match_mode', models.CharField(choices=[('all', 'All conditions'), ('any', 'Any condition')], default='all', max_length=8)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('alignment_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('overlay', 'Overlay')], default='primary', max_length=9)),
                ('assignment_scope', models.CharField(choices=[('exact', 'This Territory Only'), ('subtree', 'This Territory And Children')], default='exact', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_run_matched_count', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('target_territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_territory_rules', to='crm.territory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountTerritoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('alignment_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('overlay', 'Overlay')], default='primary', max_length=9)),
                ('assignment_source', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Assignment Rule'), ('named_account', 'Named Account'), ('inherited', 'Inherited From Parent')], default='manual', max_length=16)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_territory_assignments', to='core.party')),
                ('assigned_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_territory_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_territory_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_account_assignments', to='crm.territory')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assignments', to='sales.territoryrule')),
            ],
            options={
                'ordering': ['account__name', 'alignment_type', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='QuotaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('method', models.CharField(choices=[('top_down', 'Top-Down'), ('bottom_up', 'Bottom-Up')], max_length=10)),
                ('allocation_basis', models.CharField(choices=[('historical_revenue', 'Historical Revenue'), ('pipeline', 'Open Pipeline'), ('account_count', 'Account Count'), ('territory_potential', 'Territory Potential'), ('manual', 'Manual')], default='historical_revenue', max_length=20)),
                ('baseline_source', models.CharField(choices=[('previous_period', 'Previous Period'), ('previous_year', 'Previous Year'), ('custom', 'Custom')], default='previous_year', max_length=16)),
                ('growth_target_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attrition_relief_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stretch_target_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uplift_allowed', models.BooleanField(default=False)),
                ('target_type', models.CharField(choices=[('revenue', 'Revenue'), ('units', 'Units'), ('bookings', 'Bookings')], default='revenue', max_length=10)),
                ('phasing', models.CharField(choices=[('equal', 'Equal'), ('seasonal', 'Seasonal')], default='equal', max_length=8)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_approved_quota_plans', to=settings.AUTH_USER_MODEL)),
                ('forecast_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_plans', to='sales.forecastperiod')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quota_plans', to=settings.AUTH_USER_MODEL)),
                ('quota_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_quota_plans', to='crm.salesquota')),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_submitted_quota_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quota_plans', to='crm.territory')),
            ],
            options={
                'ordering': ['-forecast_period__period_year', 'owner'],
                'indexes': [models.Index(fields=['tenant', 'method'], name='sales_qplan_tnt_method_idx'), models.Index(fields=['tenant', 'territory'], name='sales_qplan_tnt_terr_idx'), models.Index(fields=['tenant', 'status'], name='sales_qplan_tnt_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'quota_ref'), name='sales_qplan_tenant_quota_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TerritoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('member_role', models.CharField(choices=[('hunter', 'Hunter'), ('farmer', 'Farmer'), ('sdr', 'SDR'), ('ae', 'Account Executive'), ('overlay_specialist', 'Overlay Specialist')], max_length=20)),
                ('assignment_type', models.CharField(choices=[('direct', 'Direct'), ('shared', 'Shared')], default='direct', max_length=12)),
                ('coverage_split_pct', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_primary', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('paired_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_paired_territory_members', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_members', to='crm.territory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_territory_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['territory__name', '-is_primary', 'member_role'],
                'indexes': [models.Index(fields=['tenant', 'user'], name='sales_tmember_tnt_user_idx'), models.Index(fields=['tenant', 'territory', 'is_primary'], name='sales_tmember_tnt_terr_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'territory', 'user', 'member_role'), name='sales_tmember_tnt_terr_user_role_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='territoryrule',
            index=models.Index(fields=['tenant', 'is_active', 'priority'], name='sales_trule_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='territoryrule',
            index=models.Index(fields=['tenant', 'segment_type'], name='sales_trule_tnt_seg_idx'),
        ),
        migrations.AddConstraint(
            model_name='territoryrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='sales_trule_tenant_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='accountterritoryassignment',
            index=models.Index(fields=['tenant', 'account'], name='sales_atas_tnt_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='accountterritoryassignment',
            index=models.Index(fields=['tenant', 'territory', 'alignment_type'], name='sales_atas_tnt_terr_align_idx'),
        ),
        migrations.AddIndex(
            model_name='accountterritoryassignment',
            index=models.Index(fields=['tenant', 'effective_to'], name='sales_atas_tnt_effto_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountterritoryassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'account', 'territory'), name='sales_atas_tenant_account_terr_uniq'),
        ),
    ]
