# Generated by Django 5.1.15 on 2026-09-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_territoryrule_accountterritoryassignment_quotaplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorymember',
            name='assignment_type',
            field=models.CharField(choices=[('direct', 'Direct Coverage'), ('shared', 'Shared / Split Coverage'), ('overlay', 'Overlay Coverage')], default='direct', max_length=12),
        ),
        migrations.AlterField(
            model_name='territorymember',
            name='member_role',
            field=models.CharField(choices=[('hunter', 'Hunter / New Business'), ('farmer', 'Farmer / Existing Business'), ('sdr', 'SDR / Business Development'), ('ae', 'Account Executive'), ('overlay_specialist', 'Overlay Specialist'), ('sales_engineer', 'Sales Engineer')], max_length=20),
        ),
    ]
