# Generated by Django 5.1.15 on 2026-09-30 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_complianceaudit_auditfinding_auditevidence_and_more'),
        ('crm', '0026_opportunity_currency_opportunity_next_step_due_date_and_more'),
        ('sales', '0014_alter_territorymember_assignment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountterritoryassignment',
            options={'ordering': ['alignment_type', '-effective_from', 'id']},
        ),
        migrations.AlterModelOptions(
            name='quotaplan',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='territorymember',
            options={'ordering': ['-is_primary', 'member_role', '-effective_from', 'id']},
        ),
        migrations.AddIndex(
            model_name='accountterritoryassignment',
            index=models.Index(fields=['tenant', 'territory', 'effective_to'], name='sales_atas_tnt_terr_effto_idx'),
        ),
        migrations.AddIndex(
            model_name='territorymember',
            index=models.Index(fields=['tenant', 'territory', 'effective_to'], name='sales_tmember_tnt_effto_idx'),
        ),
    ]
