# Generated by Django 5.1.15 on 2026-09-07 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('crm', '0025_alter_webhook_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('methodology', models.CharField(choices=[('waterfall', 'Waterfall'), ('agile', 'Agile'), ('hybrid', 'Hybrid')], default='hybrid', max_length=12)),
                ('in_scope', models.TextField(blank=True)),
                ('out_of_scope', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True, help_text='Measurable — PM².')),
                ('assumptions', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('risk_summary', models.TextField(blank=True, help_text="Charter-level summary; the risk register is 7.5's.")),
                ('start_date', models.DateField(blank=True, help_text="Charter target; the frozen baseline is 7.2's.", null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('charter_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('charter_approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('chartered', 'Chartered'), ('kickoff', 'Kickoff'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('charter_approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('charter_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_charters', to='core.document')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_projects', to='core.party')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executive_sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_projects', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.orgunit')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('request_type', models.CharField(choices=[('new_project', 'New Project'), ('enhancement', 'Enhancement'), ('change_request', 'Change Request'), ('defect', 'Defect Repair'), ('idea', 'Idea')], default='new_project', max_length=20)),
                ('source', models.CharField(choices=[('portal', 'Portal'), ('internal', 'Internal'), ('idea', 'Idea'), ('opportunity', 'Opportunity'), ('email', 'Email')], default='internal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('strategic_alignment', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('feasibility', models.CharField(choices=[('not_assessed', 'Not Assessed'), ('feasible', 'Feasible'), ('feasible_with_constraints', 'Feasible with Constraints'), ('not_feasible', 'Not Feasible')], default='not_assessed', max_length=32)),
                ('feasibility_notes', models.TextField(blank=True)),
                ('alternatives_considered', models.TextField(blank=True)),
                ('required_resources', models.TextField(blank=True, help_text="Free text — real resourcing is 7.3 Resource Management's.")),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('needs_information', 'Needs Information'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('converted', 'Converted')], default='draft', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('go', 'Go'), ('no_go', 'No-Go'), ('hold', 'Hold'), ('deferred', 'Deferred')], default='', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('information_requested', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prq_to_approve', to=settings.AUTH_USER_MODEL)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prq_to_review', to=settings.AUTH_USER_MODEL)),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='projects.project')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to='accounting.currency')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to='core.orgunit')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prq_filed', to=settings.AUTH_USER_MODEL)),
                ('requester_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to='core.party')),
                ('source_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectrequest'),
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('stakeholder_type', models.CharField(choices=[('sponsor', 'Sponsor'), ('approver', 'Approver'), ('resource_provider', 'Resource Provider'), ('subject_matter_expert', 'Subject Matter Expert'), ('affected', 'Affected Party'), ('team_member', 'Team Member'), ('other', 'Other')], default='other', max_length=24)),
                ('raci_role', models.CharField(choices=[('r', 'R (Responsible)'), ('a', 'A (Accountable)'), ('c', 'C (Consulted)'), ('i', 'I (Informed)')], default='i', max_length=1)),
                ('raci_scope', models.CharField(blank=True, help_text="What this RACI assignment covers, e.g. 'charter approval'.", max_length=120)),
                ('influence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('interest', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('comms_preference', models.CharField(choices=[('email', 'Email'), ('meeting', 'Meeting'), ('written_report', 'Written Report'), ('portal', 'Portal'), ('none', 'None')], default='email', max_length=16)),
                ('comms_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('at_milestone', 'At Milestone'), ('ad_hoc', 'Ad-hoc')], default='weekly', max_length=16)),
                ('attending_kickoff', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stakeholders', to='core.party')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stakeholders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectKickoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('location_or_link', models.CharField(blank=True, max_length=255)),
                ('agenda_template', models.CharField(choices=[('standard', 'Standard'), ('agile', 'Agile'), ('client_facing', 'Client-Facing'), ('custom', 'Custom')], default='standard', max_length=16)),
                ('agenda', models.TextField(blank=True)),
                ('attendee_summary', models.TextField(blank=True, help_text='External attendees not on the stakeholder register.')),
                ('onboarding_notes', models.TextField(blank=True, help_text="Individual items are core.Activity(kind='task') rows on the project.")),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('held', 'Held'), ('completed', 'Completed')], default='planned', max_length=12)),
                ('baseline_acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('baseline_acknowledged_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kickoffs', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'project'], name='pko_tnt_project_idx'), models.Index(fields=['tenant', 'status'], name='pko_tnt_status_idx')],
                'unique_together': {('tenant', 'number'), ('tenant', 'project')},
            },
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['tenant', 'status'], name='prq_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['tenant', 'request_type'], name='prq_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['tenant', 'org_unit'], name='prq_tnt_ou_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequest',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'status'], name='prj_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'charter_status'], name='prj_tnt_charter_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'client'], name='prj_tnt_client_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'org_unit'], name='prj_tnt_ou_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectstakeholder',
            index=models.Index(fields=['tenant', 'project'], name='pst_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstakeholder',
            index=models.Index(fields=['tenant', 'stakeholder_type'], name='pst_tnt_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstakeholder',
            unique_together={('tenant', 'number'), ('tenant', 'project', 'party', 'raci_scope')},
        ),
    ]
