# Generated by Django 5.1.15 on 2026-09-07 19:32

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('crm', '0025_alter_webhook_secret'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectkickoff',
            name='pko_tnt_project_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectstakeholder',
            name='pst_tnt_project_idx',
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='estimated_benefit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', '-created_at'], name='prj_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectkickoff',
            index=models.Index(fields=['tenant', '-created_at'], name='pko_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['tenant', '-created_at'], name='prq_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstakeholder',
            index=models.Index(fields=['tenant', '-created_at'], name='pst_tnt_created_idx'),
        ),
    ]
