# Generated by Django 5.1.15 on 2026-09-09 20:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0002_ordering_indexes_and_nonnegative_estimates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('node_type', models.CharField(choices=[('deliverable', 'Deliverable'), ('work_package', 'Work Package')], default='work_package', help_text='Deliverable = summary node rolled up from its children; work package = the schedulable leaf.', max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', help_text="Planning status. Execution workflow (assignments, actuals) is 7.8's.", max_length=12)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('effort_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated effort for this work package.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estimation_method', models.CharField(choices=[('bottom_up', 'Bottom-Up'), ('top_down', 'Top-Down'), ('analogous', 'Analogous'), ('parametric', 'Parametric')], default='bottom_up', max_length=12)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='Order among siblings in the WBS.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_project_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='WBS parent. A node without one roots the tree for its project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['project_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('is_phase_gate', models.BooleanField(default=False, help_text='A governed decision point — carries entry/exit criteria and a go/no-go.')),
                ('entry_criteria', models.TextField(blank=True, help_text='What must be true to enter the gate review.')),
                ('exit_criteria', models.TextField(blank=True, help_text='What must be true to pass the gate.')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_review', 'In Review'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('actual_date', models.DateField(blank=True, editable=False, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('anchor_task', models.ForeignKey(blank=True, help_text='Optional WBS node this milestone lands on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='projects.projecttask')),
            ],
            options={
                'ordering': ['target_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('baseline_type', models.CharField(choices=[('baseline', 'Frozen Baseline'), ('what_if', 'What-If Scenario')], default='baseline', max_length=8)),
                ('is_active', models.BooleanField(default=False, help_text='The baseline this project is managed against. Exactly one per project — the activate/promote verbs keep it that way atomically.')),
                ('frozen_on', models.DateField(blank=True, editable=False, null=True)),
                ('planned_finish', models.DateField(blank=True, editable=False, null=True)),
                ('task_count', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('total_effort_hours', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('strategy_note', models.TextField(blank=True, help_text='Schedule compression applied — fast-tracking, crashing.')),
                ('note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_baselines', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('link_type', models.CharField(choices=[('finish_to_start', 'Finish-to-Start'), ('start_to_start', 'Start-to-Start'), ('finish_to_finish', 'Finish-to-Finish'), ('start_to_finish', 'Start-to-Finish')], default='finish_to_start', max_length=16)),
                ('lag_days', models.SmallIntegerField(default=0, help_text='Days between the linked points — positive = lag, negative = lead.')),
                ('note', models.TextField(blank=True)),
                ('predecessor', models.ForeignKey(help_text='The earlier work package the successor waits on.', on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='projects.projecttask')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='projects.projecttask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'project'], name='tsk_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'status'], name='tsk_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'project', 'parent'], name='tsk_tnt_prj_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'node_type'], name='tsk_tnt_ntype_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttask',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['tenant', 'project'], name='mst_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['tenant', 'status'], name='mst_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmilestone',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='schedulebaseline',
            index=models.Index(fields=['tenant', 'project'], name='bsl_tnt_project_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulebaseline',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['tenant', 'successor'], name='dep_tnt_succ_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('tenant', 'number'), ('tenant', 'predecessor', 'successor')},
        ),
    ]
