# Generated by Django 5.1.15 on 2026-09-09 23:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0061_engagement_filter_indexes'),
        ('projects', '0003_projecttask_projectmilestone_schedulebaseline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('resource_type', models.CharField(choices=[('internal', 'Internal'), ('contractor', 'Contractor'), ('freelancer', 'Freelancer'), ('consultant', 'Consultant')], default='internal', max_length=12)),
                ('default_role', models.CharField(help_text="The role bookings copy when they don't name one.", max_length=80)),
                ('skill_summary', models.CharField(blank=True, help_text="Quick filter text. The matrix itself is HRM 3.40's EmployeeSkill register.", max_length=255)),
                ('weekly_capacity_hours', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Bookable hours per week — the denominator of every capacity computation.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('utilization_target_pct', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('available_from', models.DateField(blank=True, help_text='Engagement window start (contractors).', null=True)),
                ('available_to', models.DateField(blank=True, help_text='Engagement window end (contractors).', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Internal staff. Exactly one of employee/party.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_profiles', to='hrm.employeeprofile')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Home team — the pool filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_profiles', to='core.orgunit')),
                ('party', models.ForeignKey(blank=True, help_text='External contractor/freelancer identity. Exactly one of employee/party.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_profiles', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['employee__party__name', 'party__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('role_name', models.CharField(max_length=80)),
                ('skill_requirements', models.CharField(blank=True, max_length=255)),
                ('allocation_unit', models.CharField(choices=[('hours_per_week', 'Hours per Week'), ('pct_capacity', '% of Capacity'), ('total_hours', 'Total Hours')], default='hours_per_week', max_length=14)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pct_capacity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for an ongoing booking.', null=True)),
                ('booking_status', models.CharField(choices=[('requested', 'Requested'), ('soft', 'Soft Booked'), ('firm', 'Firm Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('released', 'Released')], default='requested', help_text='Verb-driven — moves through assign/commit/complete/cancel, never a form.', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.project')),
                ('project_request', models.ForeignKey(blank=True, help_text='Pipeline demand with no project yet (approved, unconverted request).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='projects.projectrequest')),
                ('project_task', models.ForeignKey(blank=True, help_text='Optional task-grain booking (planning grain only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='projects.projecttask')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_allocations', to=settings.AUTH_USER_MODEL)),
                ('substitute_of', models.ForeignKey(blank=True, help_text='The released booking this successor replaced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_by', to='projects.resourceallocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('resource', models.ForeignKey(blank=True, help_text='Leave blank for a placeholder role that still needs someone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='projects.resourceprofile')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('entry_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, help_text='Positive — 0.01 is the smallest loggable unit.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('task_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Verb-driven — submit/approve/reject are the only writers.', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True, help_text='The rejection reason, when rejected.')),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Non-project time (training, internal) is loggable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.project')),
                ('project_task', models.ForeignKey(blank=True, help_text='Optional work package — 7.8 extends the task in place with execution fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.projecttask')),
                ('resource', models.ForeignKey(help_text='An entry dies with its person (mirrors hrm.Timesheet.employee).', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.resourceprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['resource_id', '-entry_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['tenant', 'resource_type'], name='rsp_tnt_rtype_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['tenant', 'status'], name='rsp_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['tenant', 'employee'], name='rsp_tnt_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['tenant', 'party'], name='rsp_tnt_party_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceprofile',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'resource'], name='ral_tnt_resource_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'project'], name='ral_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'project_request'], name='ral_tnt_request_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'booking_status'], name='ral_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'start_date'], name='ral_tnt_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceallocation',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='resourcetimeentry',
            index=models.Index(fields=['tenant', 'resource', 'entry_date'], name='rte_tnt_res_date_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcetimeentry',
            index=models.Index(fields=['tenant', 'project', 'entry_date'], name='rte_tnt_prj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcetimeentry',
            index=models.Index(fields=['tenant', 'status'], name='rte_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcetimeentry',
            unique_together={('tenant', 'number')},
        ),
    ]
