# Generated by Django 5.1.15 on 2026-09-09 23:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0004_resourceprofile_resourceallocation_resourcetimeentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('revision_no', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('reason', models.TextField(help_text='Why this change is being proposed.')),
                ('impact_note', models.TextField(blank=True, help_text='Cost impact analysis — what moves, by how much.')),
                ('schedule_impact_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bvr_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_revisions', to='accounting.currency')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bvr_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_revisions', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bvr_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CostControlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30)),
                ('contingency', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('percent_complete', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Attested work progress feeding EV. Task-level execution (7.8) supersedes this figure.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('closed', 'Closed')], default='planning', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_control_accounts', to='accounting.glaccount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_accounts', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, help_text='WBS node this account measures — a deliverable or the project root.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_accounts', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('material', 'Material'), ('equipment', 'Equipment'), ('subcontract', 'Subcontract'), ('overhead', 'Overhead'), ('contingency', 'Contingency'), ('other', 'Other')], max_length=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.TextField(blank=True)),
                ('budget_revision', models.ForeignKey(help_text='The budget version this line belongs to — the approved-and-activated revision is the cost baseline.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='projects.budgetrevision')),
                ('control_account', models.ForeignKey(blank=True, help_text="EVM lens: the active baseline's lines per account are that account's BAC.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='projects.costcontrolaccount')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_budget_lines', to='accounting.glaccount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, help_text='Work package this money is planned against — the bottom-up rollup source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('entry_type', models.CharField(choices=[('commitment', 'Commitment'), ('actual', 'Actual'), ('accrual', 'Accrual')], default='actual', max_length=10)),
                ('source_kind', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('supplier_invoice', 'Supplier Invoice'), ('contract', 'Contract'), ('timesheet', 'Timesheet'), ('manual', 'Manual'), ('accrual', 'Accrual')], default='manual', max_length=16)),
                ('source_number', models.CharField(blank=True, help_text='Reference in the owning system, e.g. PO-00042 or SIV-00187 — soft, never an FK.', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Non-negative — reversals are a paired void plus an adjustment row.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.costcontrolaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pex_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses', to='accounting.currency')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_expenses', to='accounting.glaccount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses', to='core.party')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetrevision',
            index=models.Index(fields=['tenant', 'project', 'status'], name='bvr_tnt_prj_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetrevision',
            unique_together={('tenant', 'number'), ('tenant', 'project', 'revision_no')},
        ),
        migrations.AddIndex(
            model_name='costcontrolaccount',
            index=models.Index(fields=['tenant', 'project'], name='cca_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='costcontrolaccount',
            index=models.Index(fields=['tenant', 'status'], name='cca_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcontrolaccount',
            unique_together={('tenant', 'number'), ('tenant', 'project', 'code')},
        ),
        migrations.AddIndex(
            model_name='projectbudgetline',
            index=models.Index(fields=['tenant', 'project'], name='pbl_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetline',
            index=models.Index(fields=['tenant', 'budget_revision'], name='pbl_tnt_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetline',
            index=models.Index(fields=['tenant', 'control_account'], name='pbl_tnt_ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectbudgetline',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['tenant', 'project'], name='pex_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['tenant', 'control_account'], name='pex_tnt_ca_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['tenant', 'entry_type'], name='pex_tnt_etype_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['tenant', 'entry_date'], name='pex_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectexpense',
            unique_together={('tenant', 'number')},
        ),
    ]
