# Generated by Django 5.1.15 on 2026-09-10 22:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0005_budgetrevision_costcontrolaccount_projectbudgetline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cause', models.TextField(blank=True)),
                ('effect', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('schedule', 'Schedule'), ('cost', 'Cost'), ('resource', 'Resource'), ('external', 'External'), ('organizational', 'Organizational'), ('quality', 'Quality'), ('compliance', 'Compliance'), ('other', 'Other')], default='other', max_length=16)),
                ('risk_type', models.CharField(choices=[('threat', 'Threat'), ('opportunity', 'Opportunity')], default='threat', help_text='ISO 31000 is two-sided: a threat hurts, an opportunity helps.', max_length=12)),
                ('probability', models.PositiveSmallIntegerField(help_text='1 (rare) … 5 (almost certain).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.PositiveSmallIntegerField(help_text='1 (negligible) … 5 (severe).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cost_impact', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monetary exposure if the risk is realized — the EMV and simulation input.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('schedule_impact_days', models.PositiveIntegerField(blank=True, help_text='Days of schedule exposure if realized (recorded only).', null=True)),
                ('response_strategy', models.CharField(choices=[('avoid', 'Avoid'), ('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('accept', 'Accept'), ('exploit', 'Exploit'), ('escalate', 'Escalate')], default='mitigate', max_length=12)),
                ('response_note', models.TextField(blank=True)),
                ('trigger', models.TextField(blank=True)),
                ('contingency_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessing', 'Assessing'), ('response_planned', 'Response Planned'), ('monitoring', 'Monitoring'), ('realized', 'Realized'), ('closed', 'Closed')], default='identified', max_length=16)),
                ('identified_date', models.DateField(default=django.utils.timezone.localdate)),
                ('review_date', models.DateField(blank=True, help_text='The next scheduled review of this risk.', null=True)),
                ('residual_probability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_impact', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lessons_learned', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('contingency_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='projects.costcontrolaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsk_created', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_risks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('issue', 'Issue'), ('action_item', 'Action Item'), ('decision', 'Decision'), ('other', 'Other')], default='issue', max_length=12)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('identified_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, help_text='When this issue needs to be resolved by.', null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('escalated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iss_created', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_issues', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.projecttask')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.projectrisk')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RiskResponseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('strategy', models.CharField(choices=[('avoid', 'Avoid'), ('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('accept', 'Accept'), ('exploit', 'Exploit'), ('escalate', 'Escalate')], default='mitigate', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="The action's estimated cost — an estimate, not a 7.4 posting.", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('trigger', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('residual_probability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_impact', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rra_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_actions', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_actions', to='projects.projectrisk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IssueEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('level', models.PositiveSmallIntegerField(help_text='1 (team lead) … 4 (executive sponsor).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('target_role', models.CharField(blank=True, max_length=80)),
                ('reason', models.TextField()),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esc_created', to=settings.AUTH_USER_MODEL)),
                ('escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_raised', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_escalations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='projects.projectissue')),
            ],
            options={
                'ordering': ['issue_id', 'level', 'id'],
                'indexes': [models.Index(fields=['tenant', 'issue'], name='esc_tnt_issue_idx'), models.Index(fields=['tenant', 'level'], name='esc_tnt_level_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['tenant', 'project'], name='rsk_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['tenant', 'status'], name='rsk_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['tenant', 'category'], name='rsk_tnt_category_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['tenant', 'risk_type'], name='rsk_tnt_rtype_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['tenant', '-created_at'], name='rsk_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrisk',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['tenant', 'project'], name='iss_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['tenant', 'status'], name='iss_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['tenant', 'severity'], name='iss_tnt_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['tenant', 'escalation_level'], name='iss_tnt_esc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['tenant', '-created_at'], name='iss_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectissue',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='riskresponseaction',
            index=models.Index(fields=['tenant', 'risk'], name='rra_tnt_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='riskresponseaction',
            index=models.Index(fields=['tenant', 'status'], name='rra_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='riskresponseaction',
            index=models.Index(fields=['tenant', 'owner'], name='rra_tnt_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='riskresponseaction',
            index=models.Index(fields=['tenant', 'due_date'], name='rra_tnt_due_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskresponseaction',
            unique_together={('tenant', 'number')},
        ),
    ]
