# Generated by Django 5.1.15 on 2026-09-10 22:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0006_projectrisk_projectissue_riskresponseaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirement_type', models.CharField(choices=[('functional', 'Functional'), ('non_functional', 'Non-Functional'), ('business', 'Business'), ('technical', 'Technical'), ('regulatory', 'Regulatory'), ('interface', 'Interface')], default='functional', max_length=16)),
                ('elicitation_method', models.CharField(choices=[('interview', 'Interview'), ('workshop', 'Workshop'), ('survey', 'Survey'), ('user_story', 'User Story Mapping'), ('observation', 'Observation'), ('document_analysis', 'Document Analysis'), ('prototype', 'Prototype'), ('brainstorm', 'Brainstorming')], default='interview', max_length=20)),
                ('elicitation_note', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('must', 'Must Have'), ('should', 'Should Have'), ('could', 'Could Have'), ('wont', "Won't Have")], default='must', max_length=12)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('verification_method', models.CharField(choices=[('inspection', 'Inspection'), ('analysis', 'Analysis'), ('demonstration', 'Demonstration'), ('test', 'Test')], default='test', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('verified', 'Verified'), ('deferred', 'Deferred')], default='draft', max_length=12)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verification_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requirements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='req_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_requirements', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text="The requirement this one derives from (an epic, a story's parent).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.requirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_requirements', to=settings.AUTH_USER_MODEL)),
                ('source_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_requirements', to=settings.AUTH_USER_MODEL)),
                ('wbs_node', models.ForeignKey(blank=True, help_text='The WBS work package that delivers this requirement — the traceability link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScopeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('justification', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client'), ('regulatory', 'Regulatory'), ('vendor', 'Vendor'), ('technical', 'Technical')], default='internal', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=12)),
                ('schedule_impact_days', models.PositiveIntegerField(blank=True, help_text='Days of schedule impact if approved.', null=True)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Budget impact if approved. Sizing only — 7.4 owns the budget re-baseline.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quality_impact', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=12)),
                ('quality_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='draft', max_length=16)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scr_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_scope_changes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_changes', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_scope_changes', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='projects.requirement')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_changes', to='projects.projectrisk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('item_type', models.CharField(choices=[('in_scope', 'In Scope'), ('out_of_scope', 'Out of Scope'), ('assumption', 'Assumption'), ('constraint', 'Constraint'), ('dependency', 'Dependency')], default='assumption', max_length=12)),
                ('statement', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('impact_area', models.CharField(choices=[('schedule', 'Schedule'), ('cost', 'Cost'), ('quality', 'Quality'), ('scope', 'Scope'), ('resource', 'Resource'), ('compliance', 'Compliance')], default='scope', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('validated', 'Validated'), ('realized', 'Realized'), ('retired', 'Retired')], default='open', max_length=12)),
                ('identified_date', models.DateField(default=django.utils.timezone.localdate)),
                ('review_date', models.DateField(blank=True, help_text='The next scheduled review of this item.', null=True)),
                ('outcome', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sci_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_scope_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='projects.project')),
                ('requirement', models.ForeignKey(blank=True, help_text='The requirement this item qualifies, when it attaches to one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_items', to='projects.requirement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScopeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('deliverable', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('inspection', 'Inspection'), ('test', 'Test'), ('demonstration', 'Demonstration'), ('analysis', 'Analysis'), ('review', 'Peer Review')], default='inspection', max_length=16)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('conditional', 'Conditional Pass'), ('fail', 'Fail')], default='pass', max_length=12)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waived', 'Waived')], default='pending', max_length=12)),
                ('inspection_date', models.DateField(default=django.utils.timezone.localdate)),
                ('findings', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_scope_deliverables', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='svr_created', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_scope_deliverables', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_verifications', to='projects.project')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_verifications', to='projects.requirement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_verifications', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', 'project'], name='req_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', 'status'], name='req_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', 'requirement_type'], name='req_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', 'priority'], name='req_tnt_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', '-created_at'], name='req_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='scopechangerequest',
            index=models.Index(fields=['tenant', 'project'], name='scr_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='scopechangerequest',
            index=models.Index(fields=['tenant', 'status'], name='scr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scopechangerequest',
            index=models.Index(fields=['tenant', 'priority'], name='scr_tnt_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='scopechangerequest',
            index=models.Index(fields=['tenant', 'source'], name='scr_tnt_source_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scopechangerequest',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='scopeitem',
            index=models.Index(fields=['tenant', 'project'], name='sci_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeitem',
            index=models.Index(fields=['tenant', 'item_type'], name='sci_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeitem',
            index=models.Index(fields=['tenant', 'status'], name='sci_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeitem',
            index=models.Index(fields=['tenant', 'impact_area'], name='sci_tnt_impact_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scopeitem',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='scopeverification',
            index=models.Index(fields=['tenant', 'project'], name='svr_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeverification',
            index=models.Index(fields=['tenant', 'acceptance_status'], name='svr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeverification',
            index=models.Index(fields=['tenant', 'result'], name='svr_tnt_result_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scopeverification',
            unique_together={('tenant', 'number')},
        ),
    ]
