# Generated by Django 5.1.15 on 2026-09-11 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0007_requirement_scopechangerequest_scopeitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['tenant', 'issue_type'], name='iss_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['tenant', 'due_date'], name='iss_tnt_due_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['tenant', 'review_date'], name='rsk_tnt_review_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['tenant', 'owner'], name='rsk_tnt_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='riskresponseaction',
            index=models.Index(fields=['tenant', 'strategy'], name='rra_tnt_strategy_idx'),
        ),
        migrations.AddIndex(
            model_name='riskresponseaction',
            index=models.Index(fields=['tenant', '-created_at'], name='rra_tnt_created_idx'),
        ),
    ]
