# Generated by Django 5.1.15 on 2026-09-11 23:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0008_projectissue_iss_tnt_type_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inspection_type', models.CharField(choices=[('review', 'Review'), ('testing', 'Testing'), ('demonstration', 'Demonstration'), ('walkthrough', 'Walkthrough'), ('acceptance', 'Acceptance')], default='review', max_length=16)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('inspected_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional'), ('not_applicable', 'Not Applicable')], default='pending', max_length=14)),
                ('usage_decision', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('accept_with_deviation', 'Accept with Deviation'), ('reject', 'Reject'), ('rework', 'Rework')], default='pending', max_length=24)),
                ('findings', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acceptance_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('accepted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_inspections', to=settings.AUTH_USER_MODEL)),
                ('accepted_by_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_inspections', to='core.party')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qci_created', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField()),
                ('verification_method', models.CharField(choices=[('inspection', 'Inspection'), ('testing', 'Testing'), ('demonstration', 'Demonstration'), ('review', 'Review'), ('analysis', 'Analysis'), ('audit', 'Audit')], default='inspection', max_length=16)),
                ('standard_reference', models.CharField(blank=True, max_length=120)),
                ('regulatory_requirement', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('planned_review_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quality_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qpl_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quality_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_plans', to='projects.project')),
                ('source_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_plans', to='projects.projectrisk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_plans', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('defect_category', models.CharField(choices=[('functional', 'Functional'), ('performance', 'Performance'), ('documentation', 'Documentation'), ('compliance', 'Compliance'), ('dimensional', 'Dimensional'), ('workmanship', 'Workmanship'), ('usability', 'Usability'), ('other', 'Other')], default='other', max_length=16)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('observation', 'Observation')], default='minor', max_length=12)),
                ('disposition', models.CharField(choices=[('open', 'Open'), ('rework', 'Rework'), ('repair', 'Repair'), ('resubmit', 'Resubmit'), ('accept_as_is', 'Accept As Is'), ('reject', 'Reject'), ('deferred', 'Deferred')], default='open', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('identified_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qdf_created', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='projects.deliverableinspection')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quality_defects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_defects', to='projects.project')),
                ('project_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_defects', to='projects.projectissue')),
                ('resolved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_quality_defects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_defects', to='projects.projecttask')),
                ('quality_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='projects.qualityplan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='deliverableinspection',
            name='quality_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='projects.qualityplan'),
        ),
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('review_type', models.CharField(choices=[('methodology_review', 'Methodology Review'), ('compliance_check', 'Compliance Check'), ('gate_review', 'Gate Review'), ('kaizen_event', 'Kaizen Event'), ('retrospective', 'Retrospective'), ('maturity_assessment', 'Maturity Assessment')], default='methodology_review', max_length=24)),
                ('checklist', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('reported', 'Reported'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('maturity_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('improvement_action', models.TextField(blank=True)),
                ('improvement_due_date', models.DateField(blank=True, null=True)),
                ('improvement_status', models.CharField(choices=[('n_a', 'N/A'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done')], default='n_a', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrv_created', to=settings.AUTH_USER_MODEL)),
                ('improvement_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quality_reviews', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to='projects.project')),
                ('quality_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='projects.qualityplan')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_quality_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reviews', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-review_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='qualityplan',
            index=models.Index(fields=['tenant', 'project'], name='qpl_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityplan',
            index=models.Index(fields=['tenant', 'status'], name='qpl_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityplan',
            index=models.Index(fields=['tenant', 'wbs_node'], name='qpl_tnt_wbs_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityplan',
            index=models.Index(fields=['tenant', '-created_at'], name='qpl_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qualityplan',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='qualitydefect',
            index=models.Index(fields=['tenant', 'project'], name='qdf_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydefect',
            index=models.Index(fields=['tenant', 'status'], name='qdf_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydefect',
            index=models.Index(fields=['tenant', 'severity'], name='qdf_tnt_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydefect',
            index=models.Index(fields=['tenant', 'disposition'], name='qdf_tnt_disp_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydefect',
            index=models.Index(fields=['tenant', '-created_at'], name='qdf_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qualitydefect',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='deliverableinspection',
            index=models.Index(fields=['tenant', 'project'], name='qci_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverableinspection',
            index=models.Index(fields=['tenant', 'status'], name='qci_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverableinspection',
            index=models.Index(fields=['tenant', 'result'], name='qci_tnt_result_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverableinspection',
            index=models.Index(fields=['tenant', 'usage_decision'], name='qci_tnt_decision_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverableinspection',
            index=models.Index(fields=['tenant', 'wbs_node'], name='qci_tnt_wbs_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverableinspection',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='qualityreview',
            index=models.Index(fields=['tenant', 'project'], name='qrv_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityreview',
            index=models.Index(fields=['tenant', 'review_type'], name='qrv_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityreview',
            index=models.Index(fields=['tenant', 'status'], name='qrv_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityreview',
            index=models.Index(fields=['tenant', 'improvement_status'], name='qrv_tnt_imp_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityreview',
            index=models.Index(fields=['tenant', '-review_date'], name='qrv_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qualityreview',
            unique_together={('tenant', 'number')},
        ),
    ]
