# Generated by Django 5.1.15 on 2026-09-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_deliverableinspection_qualityplan_qualitydefect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeitem',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('validated', 'Validated'), ('realized', 'Realized'), ('retired', 'Retired'), ('violated', 'Violated')], default='open', max_length=12),
        ),
    ]
