# Generated by Django 5.1.15 on 2026-09-12 10:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0010_alter_scopeitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('reason', models.TextField()),
                ('unblock_criteria', models.TextField()),
                ('resolution_note', models.TextField(blank=True)),
                ('blocked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('unblocked_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['task_id', 'sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='actual_end',
            field=models.DateField(blank=True, editable=False, help_text='VERB-WRITTEN by tsk_complete only (which also stamps percent_complete=100).', null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='actual_start',
            field=models.DateField(blank=True, editable=False, help_text='VERB-WRITTEN by tsk_start only — the 7.4/7.6 verb-written-stamp idiom.', null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='The doer. The accountable manager stays owner; team bookings live on ResourceAllocation (7.3 staffing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='moscow',
            field=models.CharField(blank=True, choices=[('must_have', 'Must Have'), ('should_have', 'Should Have'), ('could_have', 'Could Have'), ('wont_have', "Won't Have")], help_text='MoSCoW classification. No default on purpose — unclassified is a state, not a value.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='percent_complete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Task-grain attestation (0–100). A deliverable's rollup is computed on read, never stored; the attested CostControlAccount.percent_complete (7.4) is superseded by this figure, not written by it.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=8),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'assignee'], name='tsk_tnt_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'priority'], name='tsk_tnt_priority_idx'),
        ),
        migrations.AddField(
            model_name='taskblock',
            name='blocked_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_blocks_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskblock',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskblock',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='taskblock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='taskblock',
            name='unblocked_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_blocks_cleared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='done_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_task_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='taskblock',
            index=models.Index(fields=['tenant', 'task'], name='tbk_tnt_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskblock',
            index=models.Index(fields=['tenant', 'unblocked_at'], name='tbk_tnt_unblocked_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskblock',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='taskchecklistitem',
            index=models.Index(fields=['tenant', 'task'], name='tcl_tnt_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskchecklistitem',
            index=models.Index(fields=['tenant', 'is_done'], name='tcl_tnt_done_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskchecklistitem',
            unique_together={('tenant', 'number')},
        ),
    ]
