# Generated by Django 5.1.15 on 2026-09-14 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0011_taskblock_taskchecklistitem_projecttask_actual_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('discussion', 'Discussion'), ('announcement', 'Announcement')], default='discussion', max_length=12)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['project_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.channel')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='channel_mentions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.channelmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['channel_id', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('access_level', models.CharField(choices=[('view', 'View only'), ('comment', 'Comment'), ('edit', 'Can edit')], default='view', max_length=8)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_shares', to='projects.channel')),
                ('claimed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shares', to='core.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='projects.project')),
                ('revoked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_document_shares', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('standup', 'Standup'), ('review', 'Review'), ('steering', 'Steering Committee'), ('workshop', 'Workshop'), ('other', 'Other')], default='standup', max_length=12)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('in_person', 'In person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='virtual', max_length=10)),
                ('recurrence', models.CharField(choices=[('none', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('minutes', models.TextField(blank=True)),
                ('minutes_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actual_start', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actual_end', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('minutes_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_action_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='projects.meeting')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_action_items', to='projects.projecttask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['meeting_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('is_covered', models.BooleanField(default=False)),
                ('covered_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('covered_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='projects.meeting')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_agenda_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['meeting_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('kind', models.CharField(choices=[('mention', 'Mention'), ('assignment', 'Assignment'), ('due_date', 'Due Date'), ('status_change', 'Status Change'), ('system', 'System')], default='system', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notifications', to='projects.channel')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notifications', to='projects.meeting')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notifications', to='projects.channelmessage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notifications', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notifications', to='projects.projecttask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tenant', 'project'], name='chn_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tenant', 'is_archived'], name='chn_tnt_archived_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('tenant', 'number'), ('tenant', 'project', 'name')},
        ),
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['tenant', 'channel'], name='chm_tnt_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['tenant', 'parent'], name='chm_tnt_parent_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmessage',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['tenant', 'project'], name='dsh_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['tenant', 'is_active'], name='dsh_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['tenant', 'document'], name='dsh_tnt_document_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant', 'project'], name='mtg_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant', 'status'], name='mtg_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant', 'scheduled_start'], name='mtg_tnt_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['tenant', 'meeting'], name='mait_tnt_meeting_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['tenant', 'is_done'], name='mait_tnt_done_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['tenant', 'assignee'], name='mait_tnt_assignee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingactionitem',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='meetingagendaitem',
            index=models.Index(fields=['tenant', 'meeting'], name='agi_tnt_meeting_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingagendaitem',
            index=models.Index(fields=['tenant', 'is_covered'], name='agi_tnt_covered_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingagendaitem',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectnotification',
            index=models.Index(fields=['tenant', 'recipient', 'is_read'], name='ntf_tnt_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnotification',
            index=models.Index(fields=['tenant', 'kind'], name='ntf_tnt_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnotification',
            index=models.Index(fields=['tenant', 'project'], name='ntf_tnt_project_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectnotification',
            unique_together={('tenant', 'number')},
        ),
    ]
