# Generated by Django 5.1.15 on 2026-09-14 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0012_channel_channelmessage_documentshare_meeting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['tenant', '-created_at'], name='chm_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['tenant', '-created_at'], name='dsh_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant', '-created_at'], name='mtg_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnotification',
            index=models.Index(fields=['tenant', '-created_at'], name='ntf_tnt_created_idx'),
        ),
    ]
