# Generated by Django 5.1.15 on 2026-09-15 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0013_channelmessage_chm_tnt_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_folders', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['sequence', 'name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('charter', 'Charter'), ('plan', 'Plan'), ('schedule', 'Schedule'), ('report', 'Report'), ('status_update', 'Status Update'), ('minutes', 'Minutes'), ('specification', 'Specification'), ('drawing', 'Drawing'), ('test_result', 'Test Result'), ('handover', 'Handover'), ('other', 'Other')], default='other', max_length=20)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='internal', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('expected', 'Expected'), ('in_review', 'In Review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('checked_out_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('retention_months', models.PositiveSmallIntegerField(blank=True, help_text='How long this record is kept, in months. A flag a human reads — nothing in 7.10 deletes anything on a schedule (Module 13 enforces retention).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('review_on', models.DateField(blank=True, help_text='The date somebody should look at this again.', null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_legal_hold', models.BooleanField(default=False, help_text='While held, this record may not be archived or deleted.')),
                ('hold_reason', models.CharField(blank=True, max_length=255)),
                ('held_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('current_revision_no', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('extracted_text', models.TextField(blank=True, editable=False)),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('held_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.projectmilestone')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_project_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.projecttask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='projects.projectfolder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('charter', 'Charter'), ('plan', 'Plan'), ('schedule', 'Schedule'), ('report', 'Report'), ('status_update', 'Status Update'), ('minutes', 'Minutes'), ('register', 'Register'), ('checklist', 'Checklist'), ('other', 'Other')], default='other', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/templates/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_format_locked', models.BooleanField(default=False, help_text="Records that this format is frozen by policy. It is an intent, not an enforcement — authoring and lockdown are Module 13's.")),
                ('review_on', models.DateField(blank=True, help_text='The date somebody should look at the standard again.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_document_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['category', 'name', '-id'],
                'indexes': [models.Index(fields=['tenant', 'category'], name='dtm_tnt_category_idx'), models.Index(fields=['tenant', 'is_active'], name='dtm_tnt_active_idx')],
                'unique_together': {('tenant', 'name', 'version'), ('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('lesson_learned', 'Lesson Learned'), ('retrospective', 'Retrospective'), ('playbook', 'Playbook'), ('checklist', 'Checklist'), ('best_practice', 'Best Practice'), ('template', 'Template (content only)'), ('standard', 'Standard (content only)')], default='lesson_learned', max_length=20)),
                ('summary', models.CharField(blank=True, help_text='One line somebody can scan in the register.', max_length=255)),
                ('body', models.TextField(blank=True, help_text='The insight itself, in plain text.')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('review_on', models.DateField(blank=True, help_text='The date somebody should re-read this.', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_knowledge_entries', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='projects.projectdocument')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'kind'], name='kne_tnt_kind_idx'), models.Index(fields=['tenant', 'status'], name='kne_tnt_status_idx'), models.Index(fields=['tenant', 'is_featured'], name='kne_tnt_feat_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_no', models.PositiveSmallIntegerField(default=1)),
                ('file', models.FileField(upload_to='projects/documents/%Y/%m/')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64)),
                ('change_note', models.CharField(blank=True, help_text='What changed in this revision.', max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('extracted_text', models.TextField(blank=True, editable=False)),
                ('extraction_note', models.CharField(blank=True, editable=False, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.projectdocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revision_no', '-id'],
                'indexes': [models.Index(fields=['tenant', 'document'], name='pdv_tnt_document_idx')],
                'unique_together': {('tenant', 'document', 'revision_no')},
            },
        ),
        migrations.AddIndex(
            model_name='projectfolder',
            index=models.Index(fields=['tenant', 'project'], name='pfd_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfolder',
            index=models.Index(fields=['tenant', 'parent'], name='pfd_tnt_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfolder',
            index=models.Index(fields=['tenant', 'is_archived'], name='pfd_tnt_archived_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfolder',
            unique_together={('tenant', 'number'), ('tenant', 'project', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['tenant', 'project'], name='pdm_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['tenant', 'folder'], name='pdm_tnt_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['tenant', 'status'], name='pdm_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['tenant', 'document_type'], name='pdm_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['tenant', 'is_archived'], name='pdm_tnt_archived_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdocument',
            unique_together={('tenant', 'number')},
        ),
    ]
