# Generated by Django 5.1.15 on 2026-09-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectfolder_projectdocument_documenttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='pre_archive_status',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
