# Generated by Django 5.1.15 on 2026-09-16 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectdocument_pre_archive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentry',
            name='body',
            field=models.TextField(blank=True, help_text='The insight itself, in plain text.', validators=[django.core.validators.MaxLengthValidator(200000)]),
        ),
    ]
