# Generated by Django 5.1.15 on 2026-09-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_knowledgeentry_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetimeentry',
            name='activity_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='resourcetimeentry',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
    ]
