# Generated by Django 5.1.15 on 2026-09-17 17:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0017_resourcetimeentry_activity_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('standard_daily_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Standard daily hours threshold before daily overtime begins.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('standard_weekly_hours', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Standard weekly hours threshold before weekly overtime begins.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('168.00'))])),
                ('daily_overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Pay multiplier for standard daily overtime.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('weekly_overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Pay multiplier for hours exceeding the weekly threshold.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Pay multiplier for work performed on non-working weekend days.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Pay multiplier for work performed on public/company holidays.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('requires_pre_approval', models.BooleanField(default=False, help_text='Whether overtime must be pre-approved before logging.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, help_text='Optional project scope. When blank, applies as tenant-wide default policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_rules', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_active', 'name', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='otr_tnt_active_idx'), models.Index(fields=['tenant', 'project'], name='otr_tnt_prj_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectOvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('date', models.DateField(help_text='Date overtime was worked.')),
                ('overtime_hours', models.DecimalField(decimal_places=2, help_text='Overtime hours worked.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('overtime_type', models.CharField(choices=[('daily', 'Daily Overtime (>8h)'), ('weekly', 'Weekly Overtime (>40h)'), ('weekend', 'Weekend Work'), ('holiday', 'Holiday Work')], default='daily', max_length=16)),
                ('pay_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Pay rate multiplier.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('billable_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Billing multiplier charged to the client.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('is_billable', models.BooleanField(default=True, help_text='Whether overtime is billable to the client.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Verb-driven: draft -> submitted -> approved / rejected.', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True, help_text='Reason when rejected.')),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project to which overtime hours are charged.', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='projects.project')),
                ('project_task', models.ForeignKey(blank=True, help_text='Optional work package/task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='projects.projecttask')),
                ('resource', models.ForeignKey(help_text='Resource claiming the overtime.', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='projects.resourceprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('time_entry', models.ForeignKey(blank=True, help_text='Optional link to a primary daily time log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='projects.resourcetimeentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'resource', 'date'], name='pot_tnt_res_date_idx'), models.Index(fields=['tenant', 'project', 'date'], name='pot_tnt_prj_date_idx'), models.Index(fields=['tenant', 'status'], name='pot_tnt_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TimeActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(help_text='Unique short code (e.g. DEV, QA, PM, MTG, ADMIN, TRN).', max_length=30)),
                ('name', models.CharField(help_text='Descriptive name of the activity.', max_length=100)),
                ('category', models.CharField(choices=[('direct_project', 'Direct Project Work'), ('client_service', 'Client Consulting & Support'), ('internal_overhead', 'Internal Overhead'), ('general_admin', 'General Administrative'), ('training', 'Training & Professional Development'), ('research_dev', 'Internal R&D')], default='direct_project', help_text='Overhead allocation category driving utilization reporting.', max_length=24)),
                ('is_billable_default', models.BooleanField(default=True, help_text='Default billable flag when this code is selected in time entries.')),
                ('is_active', models.BooleanField(default=True, help_text='Active codes appear in time logging dropdowns.')),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['tenant', 'category'], name='tac_tnt_category_idx'), models.Index(fields=['tenant', 'is_active'], name='tac_tnt_active_idx')],
                'unique_together': {('tenant', 'code'), ('tenant', 'number')},
            },
        ),
    ]
