# Generated by Django 5.1.15 on 2026-09-17 20:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0018_overtimerule_projectovertimerecord_timeactivitycode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('strategic_theme', models.CharField(choices=[('growth', 'Growth & Market Expansion'), ('efficiency', 'Operational Efficiency'), ('transformation', 'Digital Transformation'), ('compliance', 'Regulatory & Compliance'), ('innovation', 'Innovation & R&D'), ('customer_experience', 'Customer Experience')], default='transformation', max_length=30)),
                ('budget_envelope', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currency')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_portfolios', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=12)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True)),
                ('budget_target', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='projects.portfolio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['portfolio_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('under_review', 'Under Review'), ('funded', 'Funded'), ('deferred', 'Deferred'), ('rejected', 'Rejected')], default='proposed', max_length=15)),
                ('strategic_fit', models.PositiveSmallIntegerField(default=50, help_text='Alignment to strategic goals and OKRs (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('financial_return', models.PositiveSmallIntegerField(default=50, help_text='Expected ROI, NPV or cost reduction (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('delivery_risk', models.PositiveSmallIntegerField(default=50, help_text='Risk score: 100 = minimal risk / easiest execution, 0 = highest risk.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('capacity_fit', models.PositiveSmallIntegerField(default=50, help_text='Resource availability and skills suitability (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_strategic', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_financial', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_risk', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_capacity', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='projects.portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_investments', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='projects.program')),
            ],
            options={
                'ordering': ['portfolio_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('dependency_type', models.CharField(choices=[('finish_to_start', 'Finish to Start (FS)'), ('start_to_start', 'Start to Start (SS)'), ('shared_resource', 'Shared Resource'), ('deliverable_handover', 'Deliverable Handover'), ('governance_gate', 'Governance Gate')], default='finish_to_start', max_length=25)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('cleared', 'Cleared'), ('waived', 'Waived')], default='open', max_length=12)),
                ('lead_lag_days', models.IntegerField(default=0, help_text='Lead (negative) or lag (positive) days.')),
                ('description', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencies', to='projects.program')),
                ('source_project', models.ForeignKey(help_text='Predecessor project.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_program_dependencies', to='projects.project')),
                ('target_project', models.ForeignKey(help_text='Successor project that depends on the predecessor.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_program_dependencies', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, help_text='High-level feature summary and scope.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('target_start', models.DateField(blank=True, null=True)),
                ('target_end', models.DateField(blank=True, null=True)),
                ('color_code', models.CharField(default='#3b82f6', help_text='Hex color code for visual badges.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$', 'Enter a valid hex color code (e.g. #3b82f6 or #fff).')])),
                ('owner', models.ForeignKey(blank=True, help_text='Product owner / lead responsible for this epic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_epics', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this epic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('version_tag', models.CharField(help_text='Version identifier (e.g. v1.0.0, 2026.3).', max_length=50)),
                ('status', models.CharField(choices=[('unreleased', 'Unreleased'), ('in_progress', 'In Progress'), ('released', 'Released'), ('archived', 'Archived')], default='unreleased', max_length=15)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True, help_text='Release notes and changelog.')),
                ('feature_flags', models.TextField(blank=True, help_text='Feature flags or toggles enabled in this release train.')),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('project', models.ForeignKey(help_text='Project this release belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.project')),
                ('released_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_releases', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, help_text='Sprint goal agreed by the team.')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('committed_points', models.PositiveIntegerField(default=0, help_text='Committed story points snapshot taken when sprint is activated.')),
                ('standup_notes', models.TextField(blank=True, help_text='Daily standup notes, impediments summary, and progress log.')),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('project', models.ForeignKey(help_text='Project this sprint belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
                ('scrum_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_master_sprints', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintImpediment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the obstacle or blocker.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='How this impediment was unblocked or resolved.')),
                ('owner', models.ForeignKey(blank=True, help_text='Person assigned to resolve this impediment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_impediments', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(help_text='Sprint blocked by this impediment.', on_delete=django.db.models.deletion.CASCADE, related_name='impediments', to='projects.sprint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('conducted_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open / In Review'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('sentiment_score', models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='Average team sentiment / health score (1.0 = Very Negative to 5.0 = Very Positive).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('what_went_well', models.TextField(blank=True, help_text='Positive highlights, victories, and good practices.')),
                ('what_needs_improvement', models.TextField(blank=True, help_text='Areas to improve, friction points, and bottlenecks.')),
                ('action_items', models.TextField(blank=True, help_text='Agreed improvement actions, owners, and commitments.')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('conducted_by', models.ForeignKey(blank=True, help_text='Facilitator / Scrum Master who ran the retro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_retrospectives', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(help_text='Sprint being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='projects.sprint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-conducted_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['tenant', 'status'], name='prt_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['tenant', 'strategic_theme'], name='prt_tnt_theme_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['tenant', 'portfolio'], name='pgm_tnt_portfolio_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['tenant', 'status'], name='pgm_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('tenant', 'number'), ('tenant', 'portfolio', 'name')},
        ),
        migrations.AddIndex(
            model_name='portfolioinvestment',
            index=models.Index(fields=['tenant', 'portfolio'], name='pin_tnt_portfolio_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioinvestment',
            index=models.Index(fields=['tenant', 'status'], name='pin_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioinvestment',
            unique_together={('tenant', 'number'), ('tenant', 'portfolio', 'project')},
        ),
        migrations.AddIndex(
            model_name='programdependency',
            index=models.Index(fields=['tenant', 'source_project'], name='pdep_tnt_source_idx'),
        ),
        migrations.AddIndex(
            model_name='programdependency',
            index=models.Index(fields=['tenant', 'target_project'], name='pdep_tnt_target_idx'),
        ),
        migrations.AddIndex(
            model_name='programdependency',
            index=models.Index(fields=['tenant', 'status'], name='pdep_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programdependency',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectepic',
            index=models.Index(fields=['tenant', 'project'], name='epc_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectepic',
            index=models.Index(fields=['tenant', 'status'], name='epc_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectepic',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectrelease',
            index=models.Index(fields=['tenant', 'project'], name='rel_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrelease',
            index=models.Index(fields=['tenant', 'status'], name='rel_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrelease',
            index=models.Index(fields=['tenant', 'version_tag'], name='rel_tnt_version_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrelease',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant', 'project'], name='spt_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant', 'status'], name='spt_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant', 'start_date'], name='spt_tnt_sdate_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='sprintimpediment',
            index=models.Index(fields=['tenant', 'sprint'], name='imp_tnt_sprint_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintimpediment',
            index=models.Index(fields=['tenant', 'status'], name='imp_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintimpediment',
            index=models.Index(fields=['tenant', 'severity'], name='imp_tnt_severity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprintimpediment',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='sprintretrospective',
            index=models.Index(fields=['tenant', 'sprint'], name='ret_tnt_sprint_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintretrospective',
            index=models.Index(fields=['tenant', 'status'], name='ret_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprintretrospective',
            unique_together={('tenant', 'number')},
        ),
    ]
