# Generated by Django 5.1.15 on 2026-09-18 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0019_portfolio_program_portfolioinvestment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Parent epic/feature for cross-sprint tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectepic'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='release',
            field=models.ForeignKey(blank=True, help_text='Target release train or version milestone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectrelease'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='sprint',
            field=models.ForeignKey(blank=True, help_text='Active or planned sprint. Null indicates a backlog item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='story_points',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Agile story points estimation (Fibonacci / numeric).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'sprint'], name='tsk_tnt_sprint_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'epic'], name='tsk_tnt_epic_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['tenant', 'release'], name='tsk_tnt_release_idx'),
        ),
    ]
