# Generated by Django 5.1.15 on 2026-09-18 15:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0020_projecttask_epic_projecttask_release_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('sow_code', models.CharField(blank=True, max_length=64)),
                ('billing_type', models.CharField(choices=[('fixed_fee', 'Fixed Fee'), ('time_and_materials', 'Time & Materials'), ('milestone_based', 'Milestone-Based'), ('retainer', 'Retainer')], default='fixed_fee', max_length=25)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Active'), ('amended', 'Amended'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('scope_summary', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sows', to='core.party')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements_of_work', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SOWAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('amendment_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('effective_date', models.DateField()),
                ('value_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('revised_scope', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='projects.statementofwork')),
            ],
            options={
                'ordering': ['amendment_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('billing_type', models.CharField(choices=[('fixed_fee', 'Fixed Fee'), ('time_and_materials', 'Time & Materials'), ('milestone', 'Milestone-Based'), ('retainer', 'Retainer')], default='milestone', max_length=25)),
                ('billing_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_to_bill', 'Ready to Bill'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('invoiced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accounting_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_billing_records', to='accounting.invoice')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoices', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('sow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='projects.statementofwork')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('handoff_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='assigned', max_length=15)),
                ('deliverable_link', models.URLField(blank=True, help_text='External repository, design file, or deliverable URL')),
                ('scorecard_rating', models.PositiveSmallIntegerField(blank=True, help_text='Vendor deliverable rating on a 1–5 scale', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('performance_notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deficiency_notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_handoffs', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_handoffs', to='projects.projecttask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_vendor_handoffs', to='core.party')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('deliverable_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='draft', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Context and instructions for the client')),
                ('client_feedback', models.TextField(blank=True, help_text='Client annotations and comments')),
                ('signed_by_name', models.CharField(blank=True, max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assigned_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_approvals', to='core.party')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_approval_requests', to='core.document')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_approval_requests', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_approval_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_client_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'project'], name='cfb_tnt_project_idx'), models.Index(fields=['tenant', 'status'], name='cfb_tnt_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('can_view_progress', models.BooleanField(default=True)),
                ('can_view_milestones', models.BooleanField(default=True)),
                ('can_view_deliverables', models.BooleanField(default=True)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('can_submit_feedback', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_portal_accesses', to='core.party')),
                ('portal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_portal_accesses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_accesses', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'project'], name='cpa_tnt_project_idx'), models.Index(fields=['tenant', 'is_active'], name='cpa_tnt_active_idx')],
                'unique_together': {('tenant', 'number'), ('tenant', 'project', 'client_contact')},
            },
        ),
        migrations.AddIndex(
            model_name='statementofwork',
            index=models.Index(fields=['tenant', 'project'], name='sow_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='statementofwork',
            index=models.Index(fields=['tenant', 'status'], name='sow_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statementofwork',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='sowamendment',
            index=models.Index(fields=['tenant', 'sow'], name='swa_tnt_sow_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sowamendment',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectclientinvoice',
            index=models.Index(fields=['tenant', 'project'], name='pci_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectclientinvoice',
            index=models.Index(fields=['tenant', 'status'], name='pci_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectclientinvoice',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='vendorhandoff',
            index=models.Index(fields=['tenant', 'project'], name='vhd_tnt_project_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorhandoff',
            index=models.Index(fields=['tenant', 'status'], name='vhd_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorhandoff',
            unique_together={('tenant', 'number')},
        ),
    ]
