# Generated by Django 5.1.15 on 2026-09-18 18:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0021_statementofwork_sowamendment_projectclientinvoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('billing_type', models.CharField(choices=[('time_and_materials', 'Time & Materials'), ('fixed_fee', 'Fixed Fee'), ('milestone', 'Milestone-Based'), ('progress_percent', 'Progress Percentage'), ('retainer', 'Retainer')], default='time_and_materials', max_length=24)),
                ('run_date', models.DateField(default=django.utils.timezone.localdate)),
                ('cutoff_date', models.DateField(help_text='Unbilled hours and expenses up to this cutoff date are captured in this run.')),
                ('total_time_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('labor_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expense_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), help_text='Spot exchange rate to tenant functional currency at run date.', max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email Dispatch'), ('portal', 'Client Portal'), ('download', 'Manual Download')], default='email', max_length=12)),
                ('recipient_email', models.CharField(blank=True, max_length=255)),
                ('dispatched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accounting_invoice', models.ForeignKey(blank=True, help_text='Canonical invoice record in accounting AR ledger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_billing_runs', to='accounting.invoice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_billing_runs', to='core.party')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('dispatched_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_runs', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_runs', to='projects.project')),
                ('sow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_runs', to='projects.statementofwork')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.taxcode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('stage', models.CharField(choices=[('current', 'Current'), ('reminder_sent', 'Reminder Sent'), ('overdue', 'Overdue'), ('promise_to_pay', 'Promise to Pay'), ('in_dispute', 'In Dispute'), ('settled', 'Settled'), ('written_off', 'Written Off')], default='current', max_length=20)),
                ('dunning_level', models.CharField(choices=[('friendly_reminder', 'Friendly Reminder'), ('first_notice', 'First Formal Notice'), ('second_notice', 'Second Formal Notice'), ('final_demand', 'Final Demand'), ('legal', 'Legal Action')], default='friendly_reminder', max_length=20)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('promised_payment_date', models.DateField(blank=True, null=True)),
                ('promised_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dispute_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('accounting_invoice', models.ForeignKey(help_text='Canonical invoice being tracked for collection.', on_delete=django.db.models.deletion.CASCADE, related_name='project_collections', to='accounting.invoice')),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_collections', to=settings.AUTH_USER_MODEL)),
                ('billing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='projects.projectbillingrun')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_payment_records', to='core.party')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('role_name', models.CharField(max_length=100)),
                ('activity_code', models.CharField(blank=True, max_length=40)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expense_markup_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_rate_cards', to='core.party')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_cards', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRevenueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('recognition_date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('percent_complete', 'Percentage of Completion'), ('milestone', 'Milestone-Based'), ('as_billed', 'As Billed / Invoiced'), ('straight_line', 'Straight-Line Amortization'), ('manual', 'Manual Entry')], default='percent_complete', max_length=24)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total contractual revenue baseline under recognition.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('completion_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Project progress percentage driving revenue recognition.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('recognized_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue earned and recognized in this schedule.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deferred_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Invoiced revenue not yet earned (liability).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unbilled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Earned revenue not yet invoiced (WIP asset).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('recognized', 'Recognized'), ('locked', 'Locked'), ('void', 'Void')], default='draft', max_length=12)),
                ('recognized_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cost_center', models.ForeignKey(blank=True, help_text='Target cost center or division for profit/loss attribution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revenue_schedules', to='core.orgunit')),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revenue_schedules', to='accounting.fiscalperiod')),
                ('gl_account', models.ForeignKey(blank=True, help_text='Revenue account in the chart of accounts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_revenue_schedules', to='accounting.glaccount')),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, help_text='Canonical posted journal entry in accounting ledger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revenue_schedules', to='accounting.journalentry')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_schedules', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_schedules', to='projects.project')),
                ('recognized_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-recognition_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='projectbillingrun',
            index=models.Index(fields=['tenant', 'project'], name='pbr_tnt_prj_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbillingrun',
            index=models.Index(fields=['tenant', 'status'], name='pbr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbillingrun',
            index=models.Index(fields=['tenant', 'run_date'], name='pbr_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectbillingrun',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectpaymentrecord',
            index=models.Index(fields=['tenant', 'project'], name='ppr_tnt_prj_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpaymentrecord',
            index=models.Index(fields=['tenant', 'stage'], name='ppr_tnt_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpaymentrecord',
            index=models.Index(fields=['tenant', 'status'], name='ppr_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpaymentrecord',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectratecard',
            index=models.Index(fields=['tenant', 'project', 'is_active'], name='rtc_tnt_prj_act_idx'),
        ),
        migrations.AddIndex(
            model_name='projectratecard',
            index=models.Index(fields=['tenant', 'client', 'is_active'], name='rtc_tnt_cli_act_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectratecard',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectrevenueschedule',
            index=models.Index(fields=['tenant', 'project'], name='prs_tnt_prj_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrevenueschedule',
            index=models.Index(fields=['tenant', 'status'], name='prs_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrevenueschedule',
            index=models.Index(fields=['tenant', 'recognition_date'], name='prs_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrevenueschedule',
            unique_together={('tenant', 'number')},
        ),
    ]
