# Generated by Django 5.1.15 on 2026-09-19 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('projects', '0022_projectbillingrun_projectpaymentrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectpaymentrecord',
            index=models.Index(fields=['tenant', 'dunning_level'], name='ppr_tnt_dunning_idx'),
        ),
        migrations.AddIndex(
            model_name='projectratecard',
            index=models.Index(fields=['tenant', 'is_active'], name='rtc_tnt_act_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrevenueschedule',
            index=models.Index(fields=['tenant', 'method'], name='prs_tnt_method_idx'),
        ),
    ]
