# Generated by Django 5.1.15 on 2026-09-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_domain'),
        ('projects', '0024_projectdashboard_dashboardwidget_projectreport_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectwebhookdelivery',
            index=models.Index(fields=['tenant', '-attempted_at'], name='pwh_del_tnt_att_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwebhookdelivery',
            index=models.Index(fields=['tenant', 'status', '-attempted_at'], name='pwh_del_tnt_stat_att_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecutionlog',
            index=models.Index(fields=['tenant', '-fired_at'], name='pwf_log_tnt_fired_idx'),
        ),
    ]
