# Generated by Django 5.1.15 on 2026-09-20 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businesscalendar_customfielddefinition_and_more'),
        ('projects', '0025_projectwebhookdelivery_pwh_del_tnt_att_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('domain', models.CharField(choices=[('erp', 'ERP & Finance'), ('crm', 'CRM'), ('hris', 'HR & Talent'), ('devops', 'DevOps'), ('storage', 'File Storage'), ('custom', 'Custom / Other')], default='custom', max_length=12)),
                ('provider', models.CharField(blank=True, choices=[('sap', 'SAP'), ('oracle', 'Oracle'), ('netsuite', 'NetSuite'), ('dynamics', 'Microsoft Dynamics'), ('workday', 'Workday'), ('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('dynamics_sales', 'Dynamics Sales'), ('bamboohr', 'BambooHR'), ('adp', 'ADP'), ('jira', 'Jira'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('azure_devops', 'Azure DevOps'), ('ci_cd', 'CI/CD Pipeline'), ('sharepoint', 'SharePoint'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('box', 'Box'), ('custom', 'Custom / Other')], default='custom', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=14)),
                ('auth_method', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('basic', 'Basic Auth'), ('oauth2', 'OAuth 2.0'), ('pat', 'Personal Access Token')], default='api_key', max_length=10)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('remote_scope_ref', models.CharField(blank=True, max_length=200)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('event', 'Event-driven')], default='manual', max_length=10)),
                ('schedule_note', models.CharField(blank=True, max_length=200)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('sandbox', 'Sandbox')], default='sandbox', max_length=10)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled'), ('disconnected', 'Disconnected')], default='unverified', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('credential', models.CharField(blank=True, editable=False, help_text='Fernet ciphertext via apps.core.crypto; write-only via the form, never rendered.', max_length=512)),
                ('last_sync_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('notify_webhook', models.ForeignKey(blank=True, help_text='7.17 endpoint pinged on sync failure (7.17 owns delivery).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_connectors', to='projects.projectwebhookendpoint')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_project_connectors', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Null implies a workspace-wide connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_connectors', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_field', models.CharField(help_text='e.g. task.status, client.name, document.title, time_entry.hours', max_length=100)),
                ('remote_field', models.CharField(help_text='e.g. fields.status.name, Account.Name, path, timeSpentSeconds', max_length=100)),
                ('direction', models.CharField(choices=[('to_remote', 'Local → Remote'), ('from_remote', 'Remote → Local'), ('both', 'Bidirectional')], default='both', max_length=14)),
                ('transform', models.CharField(choices=[('none', 'None'), ('upper', 'Uppercase'), ('lower', 'Lowercase'), ('trim', 'Trim'), ('date_iso', 'ISO date'), ('number', 'Number'), ('bool', 'Boolean')], default='none', max_length=12)),
                ('value_map', models.JSONField(blank=True, default=dict, help_text='local value ⇒ remote value (or the reverse per direction)')),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('is_key', models.BooleanField(default=False, help_text='The match/identity key for de-dupe + idempotency.')),
                ('is_required', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='projects.projectintegrationconnector')),
            ],
            options={
                'ordering': ['connector__name', 'local_field', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('entity_scope', models.CharField(choices=[('tasks', 'Tasks'), ('issues', 'Issues'), ('risks', 'Risks'), ('milestones', 'Milestones'), ('time_entries', 'Time Entries'), ('resources', 'Resources'), ('documents', 'Documents'), ('folders', 'Folders'), ('budgets', 'Budgets'), ('cost_lines', 'Cost Lines'), ('journals', 'Journal Entries'), ('custom', 'Custom / Other')], default='custom', max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=14)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('event', 'Event-driven')], default='manual', max_length=10)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_note', models.CharField(blank=True, max_length=200)),
                ('filter_expression', models.TextField(blank=True, help_text='Recorded, never evaluated.')),
                ('conflict_policy', models.CharField(choices=[('local_wins', 'Local Wins'), ('remote_wins', 'Remote Wins'), ('newest_wins', 'Newest Wins'), ('manual', 'Manual')], default='manual', max_length=12)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('run_count', models.PositiveIntegerField(default=0, editable=False)),
                ('last_status', models.CharField(blank=True, editable=False, max_length=10)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.projectintegrationconnector')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('simulated', 'Simulated')], default='pending', max_length=10)),
                ('trigger_source', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('event', 'Event')], default='manual', max_length=10)),
                ('records_read', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('payload_excerpt', models.TextField(blank=True, help_text='Truncated; may contain partner PII.')),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0, editable=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='projects.projectsyncjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='projectintegrationconnector',
            index=models.Index(fields=['tenant', 'domain'], name='ixc_tnt_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='projectintegrationconnector',
            index=models.Index(fields=['tenant', 'status'], name='ixc_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectintegrationconnector',
            index=models.Index(fields=['tenant', 'project'], name='ixc_tnt_prj_idx'),
        ),
        migrations.AddIndex(
            model_name='projectintegrationconnector',
            index=models.Index(fields=['tenant', 'is_active'], name='ixc_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectintegrationconnector',
            unique_together={('tenant', 'number'), ('tenant', 'project', 'name')},
        ),
        migrations.AddIndex(
            model_name='connectorfieldmapping',
            index=models.Index(fields=['tenant', 'connector'], name='ixm_tnt_conn_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorfieldmapping',
            index=models.Index(fields=['tenant', 'connector', 'is_key'], name='ixm_tnt_conn_key_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectorfieldmapping',
            unique_together={('tenant', 'connector', 'local_field', 'direction')},
        ),
        migrations.AddIndex(
            model_name='projectsyncjob',
            index=models.Index(fields=['tenant', 'connector'], name='syj_tnt_conn_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsyncjob',
            index=models.Index(fields=['tenant', 'connector', 'is_active'], name='syj_tnt_conn_act_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsyncjob',
            index=models.Index(fields=['tenant', 'last_status'], name='syj_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsyncjob',
            unique_together={('tenant', 'connector', 'name'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='projectsyncrun',
            index=models.Index(fields=['tenant', 'job', 'status'], name='syr_tnt_job_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsyncrun',
            index=models.Index(fields=['tenant', 'status', 'started_at'], name='syr_tnt_stat_strt_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsyncrun',
            index=models.Index(fields=['tenant', 'job', 'started_at'], name='syr_tnt_job_strt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsyncrun',
            unique_together={('tenant', 'number')},
        ),
    ]
