# Generated by Django 5.1.15 on 2026-09-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_language_timezone_localeprofile_userlocalepreference_and_more'),
        ('projects', '0026_projectintegrationconnector_connectorfieldmapping_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectsyncjob',
            index=models.Index(fields=['tenant', 'is_active'], name='syj_tnt_active_idx'),
        ),
    ]
