# Generated by Django 5.1.15 on 2026-09-23 20:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        ('projects', '0027_projectsyncjob_syj_tnt_active_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text='Team name or pod designation.', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Short team code (e.g. POD-CORE-01).', max_length=50)),
                ('team_type', models.CharField(choices=[('dedicated', 'Dedicated Project Team'), ('matrix', 'Matrix Shared Team'), ('cross_functional', 'Cross-Functional Delivery'), ('agile_pod', 'Agile Pod / Scrum Team'), ('vendor_external', 'Vendor / Contractor Team')], default='cross_functional', help_text='Organizational structure and commitment model.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Remit, focus areas, and operational charter.')),
                ('location', models.CharField(blank=True, help_text='Geographic hub or primary office.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Active team available for staffing.')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Corporate organizational unit (department/branch/cost center) in company hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_teams', to='core.orgunit')),
                ('project', models.ForeignKey(blank=True, help_text='Optional dedicated project assignment (leave blank for shared enterprise resource pools).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='projects.project')),
                ('team_lead', models.ForeignKey(blank=True, help_text='Lead engineer, scrum master, or delivery lead accountable for this team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_project_teams', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('project_manager', 'Project Manager'), ('scrum_master', 'Scrum Master'), ('tech_lead', 'Technical Lead'), ('developer', 'Software Engineer / Developer'), ('designer', 'UI/UX Designer'), ('qa_engineer', 'QA / Test Engineer'), ('business_analyst', 'Business Analyst'), ('consultant', 'Functional Consultant'), ('stakeholder', 'Team Stakeholder')], default='developer', help_text='Functional role within this team.', max_length=30)),
                ('allocation_percentage', models.PositiveSmallIntegerField(default=100, help_text='Matrix allocation commitment percentage (1% to 100%).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary liaison contact for this team.')),
                ('joined_date', models.DateField(blank=True, help_text='Date member joined this team.', null=True)),
                ('left_date', models.DateField(blank=True, help_text='Date member departed or rotated out.', null=True)),
                ('team', models.ForeignKey(help_text='Parent project team.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.projectteam')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(help_text='Team member user account.', on_delete=django.db.models.deletion.CASCADE, related_name='project_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary_contact', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('methodology', models.CharField(choices=[('waterfall', 'Waterfall (Predictive)'), ('agile', 'Agile (Scrum / Iterative)'), ('hybrid', 'Hybrid (Stage-Gate + Agile)')], default='hybrid', help_text='Project execution and governance methodology.', max_length=20)),
                ('category', models.CharField(choices=[('software', 'Software & IT'), ('infrastructure', 'Infrastructure & Cloud'), ('consulting', 'Professional Services / Consulting'), ('r_and_d', 'R&D / Innovation'), ('marketing', 'Marketing / Creative'), ('operational', 'Operational / Internal'), ('internal', 'Internal Governance')], default='software', help_text='Industry or operational domain category.', max_length=30)),
                ('complexity', models.CharField(choices=[('small', 'Small / Quick-Turn'), ('medium', 'Medium Standard'), ('large', 'Large Multi-Phase'), ('enterprise', 'Enterprise Strategic')], default='medium', help_text='Project scale and governance rigor tier.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Scope and PM guidelines for this blueprint.')),
                ('estimated_duration_days', models.PositiveIntegerField(default=30, help_text='Estimated baseline delivery duration in business days.')),
                ('target_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Indicative baseline budget estimate.', max_digits=14)),
                ('default_roles', models.JSONField(blank=True, default=list, help_text='List of recommended standard team roles for this template.')),
                ('wbs_structure', models.JSONField(blank=True, default=list, help_text='Pre-built WBS phases, tasks, and milestone deliverables structure.')),
                ('workflow_config', models.JSONField(blank=True, default=dict, help_text='Pre-configured lifecycle stage gates and transition approvals.')),
                ('is_active', models.BooleanField(default=True, help_text='Available for project instantiation.')),
                ('is_default', models.BooleanField(default=False, help_text='Tenant default template for this methodology.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text='Administrative label for PMO governance.', max_length=255)),
                ('field_key', models.SlugField(help_text='Unique programmatic key (slug) for data storage.', max_length=60)),
                ('label', models.CharField(help_text='Human-facing label displayed on input forms.', max_length=200)),
                ('target_entity', models.CharField(choices=[('project', 'Project'), ('task', 'Project Task'), ('milestone', 'Project Milestone'), ('risk', 'Project Risk'), ('team', 'Project Team')], default='project', help_text='Project Management entity this custom field extends.', max_length=20)),
                ('field_type', models.CharField(choices=[('text', 'Text (Single Line)'), ('textarea', 'Text Area (Long)'), ('integer', 'Integer Number'), ('decimal', 'Decimal / Currency'), ('date', 'Date'), ('boolean', 'Yes / No (Boolean)'), ('select', 'Single Select Dropdown'), ('multiselect', 'Multi-Select Choices'), ('url', 'URL Web Link'), ('user_ref', 'Team Member Reference')], default='text', help_text='Underlying data type and widget format.', max_length=20)),
                ('form_section', models.CharField(choices=[('general', 'General Information'), ('governance', 'Governance & Compliance'), ('technical', 'Technical & Architecture'), ('financial', 'Financial & Commercial'), ('risk', 'Risk & Safety'), ('custom', 'Additional Attributes')], default='general', help_text='Form section layout grouping.', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Guidance or operational definition for users.')),
                ('placeholder', models.CharField(blank=True, help_text='UI placeholder text.', max_length=255)),
                ('default_value', models.CharField(blank=True, help_text='Default initial value.', max_length=255)),
                ('is_required', models.BooleanField(default=False, help_text='Mandatory field on form submission.')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed value for numeric types.', max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed value for numeric types.', max_digits=14, null=True)),
                ('regex_pattern', models.CharField(blank=True, help_text='Regex validation pattern.', max_length=255)),
                ('choices_list', models.JSONField(blank=True, default=list, help_text='Array of allowed string options for select and multiselect types.')),
                ('visibility_rule', models.JSONField(blank=True, default=dict, help_text="Conditional display rule dict (e.g. {'depends_on': 'methodology', 'equals': 'agile'}).")),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Visual sort order in form section.')),
                ('is_active', models.BooleanField(default=True, help_text='Active for data capture.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['target_entity', 'form_section', 'display_order', 'id'],
                'indexes': [models.Index(fields=['tenant', 'target_entity', 'is_active'], name='pcf_tnt_ent_act_idx')],
                'unique_together': {('tenant', 'target_entity', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLocaleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text='Profile title (e.g. UK Standard, Gulf Regional).', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Short profile identifier.', max_length=50)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD (ISO Standard)'), ('DD/MM/YYYY', 'DD/MM/YYYY (UK / EU / Commonwealth)'), ('MM/DD/YYYY', 'MM/DD/YYYY (US Standard)'), ('YYYY/MM/DD', 'YYYY/MM/DD (East Asia)')], default='YYYY-MM-DD', help_text='Display format for project schedule dates.', max_length=40)),
                ('time_format', models.CharField(choices=[('12h', '12-Hour (1:30 PM)'), ('24h', '24-Hour (13:30)')], default='24h', help_text='Time display format.', max_length=10)),
                ('first_day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday (ISO Standard)'), (6, 'Saturday (Middle East Standard)'), (7, 'Sunday (US / Global Standard)')], default=1, help_text='First day of the week for scheduling and Gantt views.')),
                ('number_format', models.CharField(choices=[('#,##0.00', '1,234.56 (Standard comma thousands, dot decimal)'), ('#.##0,00', '1.234,56 (European dot thousands, comma decimal)'), ('# ##0,00', '1 234,56 (French / SI space thousands)')], default='#,##0.00', help_text='Formatting notation for numbers and currencies.', max_length=40)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Standard business working hours per day.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('working_days_pattern', models.JSONField(blank=True, default=list, help_text='List of active working ISO weekday integers: 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat, 7=Sun.')),
                ('is_default', models.BooleanField(default=False, help_text='Workspace default profile for projects without custom override.')),
                ('is_active', models.BooleanField(default=True, help_text='Active profile.')),
                ('currency', models.ForeignKey(blank=True, help_text='Presentation currency for project financials.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currency')),
                ('language', models.ForeignKey(blank=True, help_text='Standard platform language pack.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.language')),
                ('project', models.ForeignKey(blank=True, help_text='Specific project override (leave blank for workspace default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locale_settings', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('time_zone', models.ForeignKey(blank=True, help_text='Standard IANA timezone for schedule calculations and milestone dates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.timezone')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['tenant', 'project'], name='pls_tnt_prj_idx'), models.Index(fields=['tenant', 'is_default'], name='pls_tnt_def_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projectteam',
            index=models.Index(fields=['tenant', 'team_type'], name='pte_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='projectteam',
            index=models.Index(fields=['tenant', 'org_unit'], name='pte_tnt_org_idx'),
        ),
        migrations.AddIndex(
            model_name='projectteam',
            index=models.Index(fields=['tenant', 'project'], name='pte_tnt_prj_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectteammember',
            unique_together={('team', 'user')},
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['tenant', 'methodology'], name='ptm_tnt_meth_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='ptm_tnt_active_idx'),
        ),
    ]
