# Generated by Django 5.1.15 on 2026-09-24 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        ('projects', '0028_projectteam_projectteammember_projecttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='estimated_duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Estimated baseline duration in business days when an operational calendar is configured; otherwise calendar days.'),
        ),
        migrations.AddIndex(
            model_name='projectteam',
            index=models.Index(fields=['tenant', '-created_at'], name='pte_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['tenant', '-created_at'], name='ptm_tnt_created_idx'),
        ),
    ]
