"""Procurement views package — one sub-package per NavERP sub-module, one module per entity.

Re-exports every view so the apps/procurement/urls/ package (``views.<name>``) resolves.
Imports inside the entity modules are ABSOLUTE.
"""
from .ApprovalWorkflowEngine import (
    approval_approve,
    approval_decide,
    approval_history,
    approval_mine,
    approval_queue,
    approval_reject,
    delegation_create,
    delegation_delete,
    delegation_detail,
    delegation_edit,
    delegation_list,
    escalation_queue,
    escalation_run,
    routingrule_create,
    routingrule_delete,
    routingrule_detail,
    routingrule_edit,
    routingrule_list,
)
from .DashboardPortal.ActivityFeed import activity_detail, activity_list
from .DashboardPortal.Overview import dashboard
from .DashboardPortal.ProcurementAlerts import (
    alert_acknowledge,
    alert_create,
    alert_delete,
    alert_detail,
    alert_edit,
    alert_list,
    alert_resolve,
)
from .DashboardPortal.QuickRequisitions import quickreq_create
from .DashboardPortal.SelfServiceReports import report_export, report_index
from .RequisitionManagement.Amendments import (
    amendment_approve,
    amendment_detail,
    amendment_list,
    amendment_reject,
    req_amendment_create,
)
from .RequisitionManagement.Requisitions import req_detail, req_list
from .ContractsManagement import (
    camendment_approve,
    camendment_create,
    camendment_detail,
    camendment_list,
    camendment_reject,
    clause_create,
    clause_delete,
    clause_detail,
    clause_edit,
    clause_list,
    contract_add_link,
    contract_add_signer,
    contract_create,
    contract_detail,
    contract_list,
    contract_remove_link,
    contract_remove_signer,
    contract_sign_page,
    milestone_complete,
    milestone_create,
    milestone_delete,
    milestone_edit,
    milestone_list,
    renewals_board,
    renewals_run,
)
from .EAuctionManagement import (
    eauc_award,
    eauc_bid,
    eauc_board,
    eauc_cancel,
    eauc_close,
    eauc_console,
    eauc_create,
    eauc_delete,
    eauc_detail,
    eauc_edit,
    eauc_floor,
    eauc_invite_add,
    eauc_invite_remove,
    eauc_list,
    eauc_publish,
    eauc_results,
    eauc_rules,
)
from .RfxManagement.Events import (
    rfx_cancel,
    rfx_clone,
    rfx_close,
    rfx_compare,
    rfx_create,
    rfx_delete,
    rfx_detail,
    rfx_edit,
    rfx_issue,
    rfx_library,
    rfx_list,
    rfx_question_move,
    rfx_scoring,
)
from .RfxManagement.Responses import (
    rfx_response_create,
    rfx_response_delete,
    rfx_response_detail,
    rfx_response_edit,
    rfx_response_list,
    rfx_response_set_status,
)
from .RequisitionManagement.Templates import (
    template_apply,
    template_create,
    template_delete,
    template_detail,
    template_edit,
    template_list,
)
from .SourcingTendering import (
    award_board,
    bid_create,
    bid_delete,
    bid_detail,
    bid_disqualify,
    bid_edit,
    bid_list,
    bid_shortlist,
    bid_submit,
    event_award,
    event_cancel,
    event_close,
    event_create,
    event_delete,
    event_detail,
    event_edit,
    event_list,
    event_open,
    sourcing_analytics,
)
from .VendorManagement import (
    vendor_invoice_new,
    vendor_portal_bid_edit,
    vendor_portal_bid_submit,
    vendor_portal_bids,
    vendor_portal_home,
    vis_accept,
    vis_delete,
    vis_detail,
    vis_list,
    vis_reject,
    vis_start_review,
    vpa_create,
    vpa_delete,
    vpa_detail,
    vpa_edit,
    vpa_list,
    vsu_approve,
    vsu_create,
    vsu_delete,
    vsu_detail,
    vsu_edit,
    vsu_lift,
    vsu_list,
    vsu_reject,
)
from .CatalogManagement.CatalogItems import (
    catalog_item_list,
    catalog_item_detail,
    catalog_item_create,
    catalog_item_edit,
    catalog_item_delete,
    catalog_item_submit,
    catalog_item_approve,
    catalog_item_reject,
    catalog_item_block,
)
from .CatalogManagement.Tiers import (
    catalog_tier_list,
    catalog_tier_detail,
    catalog_tier_create,
    catalog_tier_edit,
    catalog_tier_delete,
    catalog_tier_approve,
    catalog_tier_retire,
)
from .CatalogManagement.PunchOutEndpoints import (
    punchout_endpoint_list,
    punchout_endpoint_detail,
    punchout_endpoint_create,
    punchout_endpoint_edit,
    punchout_endpoint_delete,
    punchout_endpoint_test,
)
from .CatalogManagement.UploadBatches import (
    catalog_upload_list,
    catalog_upload_detail,
    catalog_upload_create,
    catalog_upload_edit,
    catalog_upload_delete,
    catalog_upload_validate,
    catalog_upload_publish,
    catalog_upload_reject,
)
from .OrderFulfillment import (
    asn_cancel,
    asn_confirm_delivery,
    asn_create,
    asn_delete,
    asn_detail,
    asn_edit,
    asn_list,
    asn_mark_in_transit,
    asn_submit,
    backorder_cancel,
    backorder_create,
    backorder_delete,
    backorder_detail,
    backorder_edit,
    backorder_fulfil,
    backorder_list,
    backorder_raise_alert,
    backorder_reschedule,
    delivery_confirmation,
    deliveryschedule_create,
    deliveryschedule_delete,
    deliveryschedule_detail,
    deliveryschedule_edit,
    deliveryschedule_list,
    deliveryschedule_split,
    inbound_tracking,
)
from .PurchaseOrderManagement import (
    poc_approve,
    poc_create,
    poc_detail,
    poc_list,
    poc_reject,
    po_generate,
    po_generation,
    po_line_tracking,
)
from .GoodsReceiptInspection import (
    discrepancy_cancel,
    discrepancy_create,
    discrepancy_delete,
    discrepancy_detail,
    discrepancy_edit,
    discrepancy_list,
    discrepancy_notify_vendor,
    discrepancy_resolve,
    receipt_audit,
    receiving_console,
    receiving_console_book,
    receiving_console_mint_lots,
    rtv_authorize,
    rtv_cancel,
    rtv_close,
    rtv_create,
    rtv_delete,
    rtv_detail,
    rtv_edit,
    rtv_list,
    rtv_ship,
    tolerance_exceptions,
    tolerancepolicy_create,
    tolerancepolicy_delete,
    tolerancepolicy_detail,
    tolerancepolicy_edit,
    tolerancepolicy_list,
)

__all__ = [
    "eauc_list", "eauc_detail", "eauc_create", "eauc_edit", "eauc_delete",
    "eauc_publish", "eauc_cancel", "eauc_close",
    "eauc_invite_add", "eauc_invite_remove",
    "eauc_floor", "eauc_rules", "eauc_console", "eauc_board",
    "eauc_bid", "eauc_results", "eauc_award",
    "routingrule_list", "routingrule_detail", "routingrule_create",
    "routingrule_edit", "routingrule_delete",
    "approval_queue", "approval_history", "approval_mine",
    "approval_approve", "approval_reject",
    "delegation_list", "delegation_detail", "delegation_create",
    "delegation_edit", "delegation_delete",
    "escalation_queue", "escalation_run",
    "activity_detail",
    "activity_list",
    "dashboard",
    "alert_acknowledge",
    "alert_create",
    "alert_delete",
    "alert_detail",
    "alert_edit",
    "alert_list",
    "alert_resolve",
    "quickreq_create",
    "report_export",
    "report_index",
    "amendment_approve",
    "amendment_detail",
    "amendment_list",
    "amendment_reject",
    "req_amendment_create",
    "req_detail",
    "req_list",
    "template_apply",
    "template_create",
    "template_delete",
    "template_detail",
    "template_edit",
    "template_list",
    "rfx_list",
    "rfx_detail",
    "rfx_create",
    "rfx_edit",
    "rfx_delete",
    "rfx_issue",
    "rfx_close",
    "rfx_cancel",
    "rfx_question_move",
    "rfx_compare",
    "rfx_library",
    "rfx_clone",
    "rfx_scoring",
    "rfx_response_list",
    "rfx_response_detail",
    "rfx_response_create",
    "rfx_response_edit",
    "rfx_response_delete",
    "rfx_response_set_status",
    "vpa_list",
    "vpa_detail",
    "vpa_create",
    "vpa_edit",
    "vpa_delete",
    "vsu_list",
    "vsu_detail",
    "vsu_create",
    "vsu_edit",
    "vsu_approve",
    "vsu_reject",
    "vsu_lift",
    "vsu_delete",
    "vis_list",
    "vis_detail",
    "vis_start_review",
    "vis_accept",
    "vis_reject",
    "vis_delete",
    "vendor_portal_home",
    "vendor_portal_bids",
    "vendor_portal_bid_edit",
    "vendor_portal_bid_submit",
    "vendor_invoice_new",
    "event_list",
    "event_detail",
    "event_create",
    "event_edit",
    "event_delete",
    "event_open",
    "event_close",
    "event_cancel",
    "event_award",
    "bid_list",
    "bid_detail",
    "bid_create",
    "bid_edit",
    "bid_delete",
    "bid_submit",
    "bid_shortlist",
    "bid_disqualify",
    "award_board",
    "sourcing_analytics",
    "clause_list", "clause_detail", "clause_create", "clause_edit", "clause_delete",
    "contract_list", "contract_detail", "contract_create",
    "contract_add_link", "contract_remove_link",
    "contract_add_signer", "contract_remove_signer",
    "contract_sign_page",
    "camendment_list", "camendment_detail", "camendment_create",
    "camendment_approve", "camendment_reject",
    "milestone_list", "milestone_create", "milestone_edit",
    "milestone_complete", "milestone_delete",
    "renewals_board", "renewals_run",
    "catalog_item_list", "catalog_item_detail", "catalog_item_create",
    "catalog_item_edit", "catalog_item_delete",
    "catalog_item_submit", "catalog_item_approve", "catalog_item_reject",
    "catalog_item_block",
    "catalog_tier_list", "catalog_tier_detail", "catalog_tier_create",
    "catalog_tier_edit", "catalog_tier_delete",
    "catalog_tier_approve", "catalog_tier_retire",
    "punchout_endpoint_list", "punchout_endpoint_detail", "punchout_endpoint_create",
    "punchout_endpoint_edit", "punchout_endpoint_delete", "punchout_endpoint_test",
    "catalog_upload_list", "catalog_upload_detail", "catalog_upload_create",
    "catalog_upload_edit", "catalog_upload_delete",
    "catalog_upload_validate", "catalog_upload_publish", "catalog_upload_reject",
    "asn_list", "asn_detail", "asn_create", "asn_edit", "asn_delete",
    "asn_submit", "asn_mark_in_transit", "asn_confirm_delivery", "asn_cancel",
    "deliveryschedule_list", "deliveryschedule_detail", "deliveryschedule_create",
    "deliveryschedule_edit", "deliveryschedule_delete", "deliveryschedule_split",
    "backorder_list", "backorder_detail", "backorder_create", "backorder_edit",
    "backorder_delete", "backorder_reschedule", "backorder_fulfil", "backorder_cancel",
    "backorder_raise_alert",
    "inbound_tracking", "delivery_confirmation",
    "poc_list", "poc_detail", "poc_create", "poc_approve", "poc_reject",
    "po_generation", "po_generate", "po_line_tracking",
    "tolerancepolicy_list", "tolerancepolicy_detail", "tolerancepolicy_create",
    "tolerancepolicy_edit", "tolerancepolicy_delete",
    "discrepancy_list", "discrepancy_detail", "discrepancy_create", "discrepancy_edit",
    "discrepancy_delete", "discrepancy_notify_vendor", "discrepancy_resolve",
    "discrepancy_cancel",
    "rtv_list", "rtv_detail", "rtv_create", "rtv_edit", "rtv_delete",
    "rtv_authorize", "rtv_ship", "rtv_close", "rtv_cancel",
    "receiving_console", "receiving_console_book", "receiving_console_mint_lots",
    "tolerance_exceptions", "receipt_audit",
]
