"""Procurement views package — one sub-package per NavERP sub-module, one module per entity.

Re-exports every view so the apps/procurement/urls/ package (``views.<name>``) resolves.
Imports inside the entity modules are ABSOLUTE.
"""
from .ApprovalWorkflowEngine import (
    approval_approve,
    approval_decide,
    approval_history,
    approval_mine,
    approval_queue,
    approval_reject,
    delegation_create,
    delegation_delete,
    delegation_detail,
    delegation_edit,
    delegation_list,
    escalation_queue,
    escalation_run,
    routingrule_create,
    routingrule_delete,
    routingrule_detail,
    routingrule_edit,
    routingrule_list,
)
from .DashboardPortal.ActivityFeed import activity_detail, activity_list
from .DashboardPortal.Overview import dashboard
from .DashboardPortal.ProcurementAlerts import (
    alert_acknowledge,
    alert_create,
    alert_delete,
    alert_detail,
    alert_edit,
    alert_list,
    alert_resolve,
)
from .DashboardPortal.QuickRequisitions import quickreq_create
from .DashboardPortal.SelfServiceReports import report_export, report_index
from .RequisitionManagement.Amendments import (
    amendment_approve,
    amendment_detail,
    amendment_list,
    amendment_reject,
    req_amendment_create,
)
from .RequisitionManagement.Requisitions import req_detail, req_list
from .ContractsManagement import (
    camendment_approve,
    camendment_create,
    camendment_detail,
    camendment_list,
    camendment_reject,
    clause_create,
    clause_delete,
    clause_detail,
    clause_edit,
    clause_list,
    contract_add_link,
    contract_add_signer,
    contract_create,
    contract_detail,
    contract_list,
    contract_remove_link,
    contract_remove_signer,
    contract_sign_page,
    milestone_complete,
    milestone_create,
    milestone_delete,
    milestone_edit,
    milestone_list,
    renewals_board,
    renewals_run,
)
from .EAuctionManagement import (
    eauc_award,
    eauc_bid,
    eauc_board,
    eauc_cancel,
    eauc_close,
    eauc_console,
    eauc_create,
    eauc_delete,
    eauc_detail,
    eauc_edit,
    eauc_floor,
    eauc_invite_add,
    eauc_invite_remove,
    eauc_list,
    eauc_publish,
    eauc_results,
    eauc_rules,
)
from .RfxManagement.Events import (
    rfx_cancel,
    rfx_clone,
    rfx_close,
    rfx_compare,
    rfx_create,
    rfx_delete,
    rfx_detail,
    rfx_edit,
    rfx_issue,
    rfx_library,
    rfx_list,
    rfx_question_move,
    rfx_scoring,
)
from .RfxManagement.Responses import (
    rfx_response_create,
    rfx_response_delete,
    rfx_response_detail,
    rfx_response_edit,
    rfx_response_list,
    rfx_response_set_status,
)
from .RequisitionManagement.Templates import (
    template_apply,
    template_create,
    template_delete,
    template_detail,
    template_edit,
    template_list,
)
from .SourcingTendering import (
    award_board,
    bid_create,
    bid_delete,
    bid_detail,
    bid_disqualify,
    bid_edit,
    bid_list,
    bid_shortlist,
    bid_submit,
    event_award,
    event_cancel,
    event_close,
    event_create,
    event_delete,
    event_detail,
    event_edit,
    event_list,
    event_open,
    sourcing_analytics,
)
from .VendorManagement import (
    vendor_invoice_new,
    vendor_portal_bid_edit,
    vendor_portal_bid_submit,
    vendor_portal_bids,
    vendor_portal_home,
    vis_accept,
    vis_delete,
    vis_detail,
    vis_list,
    vis_reject,
    vis_start_review,
    vpa_create,
    vpa_delete,
    vpa_detail,
    vpa_edit,
    vpa_list,
    vsu_approve,
    vsu_create,
    vsu_delete,
    vsu_detail,
    vsu_edit,
    vsu_lift,
    vsu_list,
    vsu_reject,
)
from .CatalogManagement.CatalogItems import (
    catalog_item_list,
    catalog_item_detail,
    catalog_item_create,
    catalog_item_edit,
    catalog_item_delete,
    catalog_item_submit,
    catalog_item_approve,
    catalog_item_reject,
    catalog_item_block,
)
from .CatalogManagement.Tiers import (
    catalog_tier_list,
    catalog_tier_detail,
    catalog_tier_create,
    catalog_tier_edit,
    catalog_tier_delete,
    catalog_tier_approve,
    catalog_tier_retire,
)
from .CatalogManagement.PunchOutEndpoints import (
    punchout_endpoint_list,
    punchout_endpoint_detail,
    punchout_endpoint_create,
    punchout_endpoint_edit,
    punchout_endpoint_delete,
    punchout_endpoint_test,
)
from .CatalogManagement.UploadBatches import (
    catalog_upload_list,
    catalog_upload_detail,
    catalog_upload_create,
    catalog_upload_edit,
    catalog_upload_delete,
    catalog_upload_validate,
    catalog_upload_publish,
    catalog_upload_reject,
)
from .OrderFulfillment import (
    asn_cancel,
    asn_confirm_delivery,
    asn_create,
    asn_delete,
    asn_detail,
    asn_edit,
    asn_list,
    asn_mark_in_transit,
    asn_submit,
    backorder_cancel,
    backorder_create,
    backorder_delete,
    backorder_detail,
    backorder_edit,
    backorder_fulfil,
    backorder_list,
    backorder_raise_alert,
    backorder_reschedule,
    delivery_confirmation,
    deliveryschedule_create,
    deliveryschedule_delete,
    deliveryschedule_detail,
    deliveryschedule_edit,
    deliveryschedule_list,
    deliveryschedule_split,
    inbound_tracking,
)
from .PurchaseOrderManagement import (
    poc_approve,
    poc_create,
    poc_detail,
    poc_list,
    poc_reject,
    po_generate,
    po_generation,
    po_line_tracking,
)
from .GoodsReceiptInspection import (
    discrepancy_cancel,
    discrepancy_create,
    discrepancy_delete,
    discrepancy_detail,
    discrepancy_edit,
    discrepancy_list,
    discrepancy_notify_vendor,
    discrepancy_resolve,
    receipt_audit,
    receiving_console,
    receiving_console_book,
    receiving_console_mint_lots,
    rtv_authorize,
    rtv_cancel,
    rtv_close,
    rtv_create,
    rtv_delete,
    rtv_detail,
    rtv_edit,
    rtv_list,
    rtv_ship,
    tolerance_exceptions,
    tolerancepolicy_create,
    tolerancepolicy_delete,
    tolerancepolicy_detail,
    tolerancepolicy_edit,
    tolerancepolicy_list,
)
# 6.13 Invoice & Voucher Management — from the entity MODULES, same reason as models/__init__.
from .InvoiceVoucherManagement.SupplierInvoices import (
    invoicevoucher_dashboard,
    supplierinvoice_approve,
    supplierinvoice_capture,
    supplierinvoice_create,
    supplierinvoice_delete,
    supplierinvoice_detail,
    supplierinvoice_duplicates,
    supplierinvoice_edit,
    supplierinvoice_list,
    supplierinvoice_mark_paid,
    supplierinvoice_match,
    supplierinvoice_override,
    supplierinvoice_revalidate,
    supplierinvoice_reverse,
    supplierinvoice_schedule,
    supplierinvoice_submit,
    supplierinvoice_void,
)
from .InvoiceVoucherManagement.SupplierInvoiceLines import (
    paymentschedule_list,
    supplierinvoiceline_create,
    supplierinvoiceline_delete,
    supplierinvoiceline_detail,
    supplierinvoiceline_edit,
    supplierinvoiceline_list,
)
from .InvoiceVoucherManagement.MatchVariances import (
    invoice_match_board,
    matchvariance_accept,
    matchvariance_detail,
    matchvariance_list,
)
from .InvoiceVoucherManagement.InvoiceDisputes import (
    invoicedispute_aging,
    invoicedispute_await_internal,
    invoicedispute_await_supplier,
    invoicedispute_close,
    invoicedispute_create,
    invoicedispute_delete,
    invoicedispute_detail,
    invoicedispute_edit,
    invoicedispute_escalate,
    invoicedispute_list,
    invoicedispute_resolve,
)

# 6.14 Spend Analytics & Reporting — from the entity MODULES, same reason as 6.13 above.
# EVERY view name, including the three computed-page lanes: a view that is imported by the
# URLconf as ``views.<name>`` but missing here is an AttributeError at URLconf import time,
# not at request time — the whole site fails to start, which is why this list is exhaustive
# rather than 'the ones with a sidebar link'.
from .SpendAnalyticsReporting.SpendClassificationRules import (
    spendrule_create,
    spendrule_delete,
    spendrule_detail,
    spendrule_edit,
    spendrule_list,
    spendrule_preview,
)
from .SpendAnalyticsReporting.MaverickFindings import (
    maverickfinding_create,
    maverickfinding_delete,
    maverickfinding_detail,
    maverickfinding_disposition,
    maverickfinding_edit,
    maverickfinding_list,
)
from .SpendAnalyticsReporting.MaverickDashboard import (
    maverick_dashboard,
    maverick_scan,
)
from .SpendAnalyticsReporting.ClassificationWorkbench import classification_workbench
from .SpendAnalyticsReporting.SpendReports import (
    spendreport_create,
    spendreport_delete,
    spendreport_detail,
    spendreport_edit,
    spendreport_export,
    spendreport_favorite,
    spendreport_list,
    spendreport_run,
    spendreport_snapshot,
    spendreportsnapshot_delete,
    spendreportsnapshot_detail,
    spendreportsnapshot_export,
)
from .SpendAnalyticsReporting.SpendDashboards import (
    category_spend,
    spend_dashboard,
    spend_export,
    spend_export_download,
)

# 6.15 Budget & Cost Management — from the entity MODULES, same reason as 6.14 above: a view
# the URLconf imports as ``views.<name>`` but is missing here fails the whole site at URLconf
# import time, so the list is exhaustive.
from .BudgetCostManagement.BudgetMappings import (
    budgetmapping_create,
    budgetmapping_delete,
    budgetmapping_detail,
    budgetmapping_edit,
    budgetmapping_list,
)
from .BudgetCostManagement.BudgetChecks import budget_availability
from .BudgetCostManagement.CommitmentRegister import commitment_register
from .BudgetCostManagement.VarianceReport import budget_variance, budget_variance_export
from .BudgetCostManagement.CostForecasts import (
    costforecast_create,
    costforecast_delete,
    costforecast_detail,
    costforecast_list,
)

# 6.19 Document & Knowledge Management - 32 views. Note pdocument_revision_upload: its ROUTE is
# declared in the Documents url module (url modules own segments, and it sits under documents/),
# but its VIEW lives in the Revisions module because the upload is what mints a revision. The
# URLconf resolves views.<name> off this package, so the split is invisible to it - but a name
# missing from the block below is an AttributeError at URLconf import, not a 404.
from .DocumentKnowledgeManagement.Documents import (
    pdocument_activate,
    pdocument_archive,
    pdocument_checkout,
    pdocument_create,
    pdocument_delete,
    pdocument_detail,
    pdocument_edit,
    pdocument_list,
    pdocument_reindex,
    pdocument_release,
    pdocument_run_reminders,
    pdocument_supersede,
)
from .DocumentKnowledgeManagement.Revisions import (
    pdocrevision_approve,
    pdocrevision_delete,
    pdocrevision_detail,
    pdocrevision_list,
    pdocument_revision_upload,
)
from .DocumentKnowledgeManagement.Policies import (
    ppolicy_archive,
    ppolicy_create,
    ppolicy_delete,
    ppolicy_detail,
    ppolicy_edit,
    ppolicy_list,
    ppolicy_publish,
)
from .DocumentKnowledgeManagement.KnowledgeResources import (
    knowledgeresource_archive,
    knowledgeresource_create,
    knowledgeresource_delete,
    knowledgeresource_detail,
    knowledgeresource_edit,
    knowledgeresource_list,
    knowledgeresource_publish,
    knowledgeresource_use,
)
# 6.16 Supplier Performance & Evaluation — 33 public views over five modules. The URLconf
# resolves ``views.<name>`` off THIS package, so a name missing from the block below is an
# AttributeError at URLconf import time, not a 404. Everything ``_``-prefixed in those modules
# is private helper surface and stays out.
from .SupplierPerformanceEvaluation.SupplierKpis import (
    supplierkpi_create,
    supplierkpi_delete,
    supplierkpi_detail,
    supplierkpi_edit,
    supplierkpi_list,
)
from .SupplierPerformanceEvaluation.ScorecardKpiScores import (
    supplierevaluation_detail,
    supplierevaluation_generate,
    supplierevaluation_list,
    supplierkpiscore_delete,
    supplierkpiscore_detail,
    supplierkpiscore_edit,
    supplierkpiscore_list,
)
from .SupplierPerformanceEvaluation.SupplierFeedback import (
    supplierfeedback_create,
    supplierfeedback_decline,
    supplierfeedback_delete,
    supplierfeedback_detail,
    supplierfeedback_edit,
    supplierfeedback_expire,
    supplierfeedback_list,
    supplierfeedback_submit,
)
from .SupplierPerformanceEvaluation.SupplierImprovementPlans import (
    improvementplan_acknowledge,
    improvementplan_activate,
    improvementplan_cancel,
    improvementplan_close,
    improvementplan_create,
    improvementplan_delete,
    improvementplan_detail,
    improvementplan_edit,
    improvementplan_list,
    improvementplan_monitor,
)
from .SupplierPerformanceEvaluation.PerformanceBoards import (
    supplier_benchmark_board,
    supplier_perception_gap,
    supplier_trend_board,
)
# 6.18 Inventory & Warehouse Integration — three CRUD entities plus three DERIVED pages that own
# no model at all (stock_position, receipt_bin_map, count_accuracy).
from .InventoryWarehouseIntegration.Policies import (
    replenishmentpolicy_list, replenishmentpolicy_detail, replenishmentpolicy_create,
    replenishmentpolicy_edit, replenishmentpolicy_delete,
)
from .InventoryWarehouseIntegration.Runs import (
    replenishmentrun_list, replenishmentrun_detail, replenishmentrun_create,
    replenishmentrun_edit, replenishmentrun_delete, replenishmentrun_generate,
    replenishmentrun_release, replenishmentrun_cancel, replenishmentsuggestion_decide,
)
from .InventoryWarehouseIntegration.MaterialIssues import (
    materialissue_list, materialissue_detail, materialissue_create, materialissue_edit,
    materialissue_delete, materialissue_submit, materialissue_post, materialissue_cancel,
    materialissueline_add, materialissueline_delete,
)
from .InventoryWarehouseIntegration.StockPosition import stock_position
from .InventoryWarehouseIntegration.ReceiptBinMap import receipt_bin_map
from .InventoryWarehouseIntegration.CountAccuracy import count_accuracy

__all__ = [
    "eauc_list", "eauc_detail", "eauc_create", "eauc_edit", "eauc_delete",
    "eauc_publish", "eauc_cancel", "eauc_close",
    "eauc_invite_add", "eauc_invite_remove",
    "eauc_floor", "eauc_rules", "eauc_console", "eauc_board",
    "eauc_bid", "eauc_results", "eauc_award",
    "routingrule_list", "routingrule_detail", "routingrule_create",
    "routingrule_edit", "routingrule_delete",
    "approval_queue", "approval_history", "approval_mine",
    "approval_approve", "approval_reject",
    "delegation_list", "delegation_detail", "delegation_create",
    "delegation_edit", "delegation_delete",
    "escalation_queue", "escalation_run",
    "activity_detail",
    "activity_list",
    "dashboard",
    "alert_acknowledge",
    "alert_create",
    "alert_delete",
    "alert_detail",
    "alert_edit",
    "alert_list",
    "alert_resolve",
    "quickreq_create",
    "report_export",
    "report_index",
    "amendment_approve",
    "amendment_detail",
    "amendment_list",
    "amendment_reject",
    "req_amendment_create",
    "req_detail",
    "req_list",
    "template_apply",
    "template_create",
    "template_delete",
    "template_detail",
    "template_edit",
    "template_list",
    "rfx_list",
    "rfx_detail",
    "rfx_create",
    "rfx_edit",
    "rfx_delete",
    "rfx_issue",
    "rfx_close",
    "rfx_cancel",
    "rfx_question_move",
    "rfx_compare",
    "rfx_library",
    "rfx_clone",
    "rfx_scoring",
    "rfx_response_list",
    "rfx_response_detail",
    "rfx_response_create",
    "rfx_response_edit",
    "rfx_response_delete",
    "rfx_response_set_status",
    "vpa_list",
    "vpa_detail",
    "vpa_create",
    "vpa_edit",
    "vpa_delete",
    "vsu_list",
    "vsu_detail",
    "vsu_create",
    "vsu_edit",
    "vsu_approve",
    "vsu_reject",
    "vsu_lift",
    "vsu_delete",
    "vis_list",
    "vis_detail",
    "vis_start_review",
    "vis_accept",
    "vis_reject",
    "vis_delete",
    "vendor_portal_home",
    "vendor_portal_bids",
    "vendor_portal_bid_edit",
    "vendor_portal_bid_submit",
    "vendor_invoice_new",
    "event_list",
    "event_detail",
    "event_create",
    "event_edit",
    "event_delete",
    "event_open",
    "event_close",
    "event_cancel",
    "event_award",
    "bid_list",
    "bid_detail",
    "bid_create",
    "bid_edit",
    "bid_delete",
    "bid_submit",
    "bid_shortlist",
    "bid_disqualify",
    "award_board",
    "sourcing_analytics",
    "clause_list", "clause_detail", "clause_create", "clause_edit", "clause_delete",
    "contract_list", "contract_detail", "contract_create",
    "contract_add_link", "contract_remove_link",
    "contract_add_signer", "contract_remove_signer",
    "contract_sign_page",
    "camendment_list", "camendment_detail", "camendment_create",
    "camendment_approve", "camendment_reject",
    "milestone_list", "milestone_create", "milestone_edit",
    "milestone_complete", "milestone_delete",
    "renewals_board", "renewals_run",
    "catalog_item_list", "catalog_item_detail", "catalog_item_create",
    "catalog_item_edit", "catalog_item_delete",
    "catalog_item_submit", "catalog_item_approve", "catalog_item_reject",
    "catalog_item_block",
    "catalog_tier_list", "catalog_tier_detail", "catalog_tier_create",
    "catalog_tier_edit", "catalog_tier_delete",
    "catalog_tier_approve", "catalog_tier_retire",
    "punchout_endpoint_list", "punchout_endpoint_detail", "punchout_endpoint_create",
    "punchout_endpoint_edit", "punchout_endpoint_delete", "punchout_endpoint_test",
    "catalog_upload_list", "catalog_upload_detail", "catalog_upload_create",
    "catalog_upload_edit", "catalog_upload_delete",
    "catalog_upload_validate", "catalog_upload_publish", "catalog_upload_reject",
    "asn_list", "asn_detail", "asn_create", "asn_edit", "asn_delete",
    "asn_submit", "asn_mark_in_transit", "asn_confirm_delivery", "asn_cancel",
    "deliveryschedule_list", "deliveryschedule_detail", "deliveryschedule_create",
    "deliveryschedule_edit", "deliveryschedule_delete", "deliveryschedule_split",
    "backorder_list", "backorder_detail", "backorder_create", "backorder_edit",
    "backorder_delete", "backorder_reschedule", "backorder_fulfil", "backorder_cancel",
    "backorder_raise_alert",
    "inbound_tracking", "delivery_confirmation",
    "poc_list", "poc_detail", "poc_create", "poc_approve", "poc_reject",
    "po_generation", "po_generate", "po_line_tracking",
    "tolerancepolicy_list", "tolerancepolicy_detail", "tolerancepolicy_create",
    "tolerancepolicy_edit", "tolerancepolicy_delete",
    "discrepancy_list", "discrepancy_detail", "discrepancy_create", "discrepancy_edit",
    "discrepancy_delete", "discrepancy_notify_vendor", "discrepancy_resolve",
    "discrepancy_cancel",
    "rtv_list", "rtv_detail", "rtv_create", "rtv_edit", "rtv_delete",
    "rtv_authorize", "rtv_ship", "rtv_close", "rtv_cancel",
    "receiving_console", "receiving_console_book", "receiving_console_mint_lots",
    "tolerance_exceptions", "receipt_audit",
    "supplierinvoice_list", "supplierinvoice_detail", "supplierinvoice_create",
    "supplierinvoice_edit", "supplierinvoice_delete",
    "supplierinvoice_capture", "supplierinvoice_duplicates", "supplierinvoice_match",
    "supplierinvoice_revalidate",
    "supplierinvoice_approve", "supplierinvoice_override", "supplierinvoice_void",
    "supplierinvoice_reverse", "supplierinvoice_schedule", "supplierinvoice_mark_paid",
    "supplierinvoice_submit",
    "invoicevoucher_dashboard",
    "supplierinvoiceline_list", "supplierinvoiceline_detail", "supplierinvoiceline_create",
    "supplierinvoiceline_edit", "supplierinvoiceline_delete", "paymentschedule_list",
    "matchvariance_list", "matchvariance_detail", "matchvariance_accept",
    "invoice_match_board",
    "invoicedispute_list", "invoicedispute_detail", "invoicedispute_create",
    "invoicedispute_edit", "invoicedispute_delete", "invoicedispute_resolve",
    "invoicedispute_escalate", "invoicedispute_await_supplier",
    "invoicedispute_await_internal", "invoicedispute_close", "invoicedispute_aging",
    "spendrule_list", "spendrule_detail", "spendrule_create", "spendrule_edit",
    "spendrule_delete", "spendrule_preview",
    "maverickfinding_list", "maverickfinding_detail", "maverickfinding_create",
    "maverickfinding_edit", "maverickfinding_delete", "maverickfinding_disposition",
    "maverick_dashboard", "maverick_scan", "classification_workbench",
    "spendreport_list", "spendreport_detail", "spendreport_create", "spendreport_edit",
    "spendreport_delete", "spendreport_run", "spendreport_snapshot", "spendreport_export",
    "spendreport_favorite",
    "spendreportsnapshot_detail", "spendreportsnapshot_export", "spendreportsnapshot_delete",
    "spend_dashboard", "category_spend", "spend_export", "spend_export_download",
    "budgetmapping_list", "budgetmapping_detail", "budgetmapping_create", "budgetmapping_edit",
    "budgetmapping_delete",
    "budget_availability", "commitment_register",
    "budget_variance", "budget_variance_export",
    "costforecast_list", "costforecast_detail", "costforecast_create", "costforecast_delete",
    "pdocument_list", "pdocument_detail", "pdocument_create", "pdocument_edit",
    "pdocument_delete", "pdocument_checkout", "pdocument_release", "pdocument_activate",
    "pdocument_supersede", "pdocument_archive", "pdocument_reindex", "pdocument_run_reminders",
    "pdocrevision_list", "pdocrevision_detail", "pdocument_revision_upload",
    "pdocrevision_approve", "pdocrevision_delete",
    "ppolicy_list", "ppolicy_detail", "ppolicy_create", "ppolicy_edit", "ppolicy_delete",
    "ppolicy_publish", "ppolicy_archive",
    "knowledgeresource_list", "knowledgeresource_detail", "knowledgeresource_create",
    "knowledgeresource_edit", "knowledgeresource_delete", "knowledgeresource_publish",
    "knowledgeresource_archive", "knowledgeresource_use",
    "supplierkpi_list", "supplierkpi_detail", "supplierkpi_create", "supplierkpi_edit",
    "supplierkpi_delete",
    "supplierevaluation_list", "supplierevaluation_detail", "supplierevaluation_generate",
    "supplierkpiscore_list", "supplierkpiscore_detail", "supplierkpiscore_edit",
    "supplierkpiscore_delete",
    "supplierfeedback_list", "supplierfeedback_detail", "supplierfeedback_create",
    "supplierfeedback_edit", "supplierfeedback_submit", "supplierfeedback_decline",
    "supplierfeedback_expire", "supplierfeedback_delete",
    "improvementplan_list", "improvementplan_detail", "improvementplan_create",
    "improvementplan_edit", "improvementplan_activate", "improvementplan_monitor",
    "improvementplan_acknowledge", "improvementplan_close", "improvementplan_cancel",
    "improvementplan_delete",
    "supplier_benchmark_board", "supplier_trend_board", "supplier_perception_gap",
    # 6.18 Inventory & Warehouse Integration
    "replenishmentpolicy_list", "replenishmentpolicy_detail", "replenishmentpolicy_create",
    "replenishmentpolicy_edit", "replenishmentpolicy_delete",
    "replenishmentrun_list", "replenishmentrun_detail", "replenishmentrun_create",
    "replenishmentrun_edit", "replenishmentrun_delete", "replenishmentrun_generate",
    "replenishmentrun_release", "replenishmentrun_cancel", "replenishmentsuggestion_decide",
    "materialissue_list", "materialissue_detail", "materialissue_create", "materialissue_edit",
    "materialissue_delete", "materialissue_submit", "materialissue_post", "materialissue_cancel",
    "materialissueline_add", "materialissueline_delete",
    "stock_position", "receipt_bin_map", "count_accuracy",
]
