# Generated by Django 5.1.15 on 2026-09-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accessreview_accessreviewitem_elevationgrant_and_more'),
        ('core', '0005_tenant_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enforced', models.BooleanField(default=False, help_text='Off by default — turning it on starts applying these rules.')),
                ('min_length', models.PositiveIntegerField(default=12)),
                ('require_upper', models.BooleanField(default=True)),
                ('require_lower', models.BooleanField(default=True)),
                ('require_digit', models.BooleanField(default=True)),
                ('require_symbol', models.BooleanField(default=False)),
                ('max_age_days', models.PositiveIntegerField(default=0, help_text='0 disables forced rotation.')),
                ('prevent_reuse_count', models.PositiveIntegerField(default=0, help_text='How many previous passwords to refuse. 0 disables the check.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_policy', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('risk_reasons', models.JSONField(blank=True, default=list)),
                ('mfa_challenged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='latt_tenant_created_idx'), models.Index(fields=['identifier', '-created_at'], name='latt_ident_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='MfaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('totp', 'Authenticator app (TOTP)')], default='totp', max_length=10)),
                ('name', models.CharField(blank=True, help_text="e.g. 'iPhone'.", max_length=120)),
                ('secret_encrypted', models.TextField(editable=False)),
                ('backup_code_hashes', models.JSONField(blank=True, default=list, editable=False)),
                ('last_counter', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'user', 'is_active'], name='mfa_tenant_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at'],
                'indexes': [models.Index(fields=['tenant', 'user', '-set_at'], name='pwdhist_tenant_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'user', '-last_seen_at'], name='usess_tenant_user_idx')],
            },
        ),
    ]
