# Generated by Django 5.1.15 on 2026-06-24 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='hrm.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('start_date', models.DateField(help_text="The new hire's first day — drives every task due date.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('welcome_message', models.TextField(blank=True)),
                ('welcome_video_url', models.URLField(blank=True)),
                ('first_day_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_for', to='hrm.employeeprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_programs', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='hrm.onboardingtemplate')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_category', models.CharField(choices=[('hr_admin', 'HR Admin'), ('it_setup', 'IT Setup'), ('manager_action', 'Manager Action'), ('buddy_action', 'Buddy Action'), ('new_hire_action', 'New Hire Action'), ('document_sign', 'Document Sign'), ('equipment_request', 'Equipment Request'), ('training', 'Training'), ('meet_greet', 'Meet & Greet'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('assignee_role', models.CharField(choices=[('hr', 'HR'), ('it', 'IT'), ('manager', 'Manager'), ('buddy', 'Buddy'), ('new_hire', 'New Hire')], default='hr', max_length=20)),
                ('due_offset_days', models.IntegerField(default=0, help_text='Days relative to start date (negative = before, 0 = first day, positive = after).')),
                ('phase', models.CharField(choices=[('preboarding', 'Preboarding'), ('week_1', 'Week 1'), ('month_1', 'Month 1'), ('month_2', 'Month 2'), ('month_3', 'Month 3'), ('ongoing', 'Ongoing')], default='week_1', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='hrm.onboardingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['template', 'phase', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrientationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('session_type', models.CharField(choices=[('orientation', 'Orientation'), ('training', 'Training'), ('meet_greet', 'Meet & Greet'), ('policy_review', 'Policy Review'), ('system_demo', 'System Demo'), ('department_intro', 'Department Intro'), ('social', 'Social / Team Lunch'), ('custom', 'Custom')], default='orientation', max_length=30)),
                ('facilitator_name', models.CharField(blank=True, help_text='Free-text fallback for an external trainer with no user account.', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('attendance_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_sessions', to='hrm.employeeprofile')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_orientation_sessions', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientation_sessions', to='hrm.onboardingprogram')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('employment_contract', 'Employment Contract'), ('nda', 'NDA'), ('offer_letter', 'Offer Letter'), ('id_proof', 'ID Proof'), ('tax_form', 'Tax Form'), ('bank_details', 'Bank Details'), ('policy_acknowledgment', 'Policy Acknowledgment'), ('background_check', 'Background Check'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='hrm/onboarding/docs/%Y/%m/')),
                ('esign_required', models.BooleanField(default=False)),
                ('esign_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined')], default='not_required', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('external_ref', models.CharField(blank=True, help_text='External e-sign envelope/reference id (future integration).', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrm.onboardingprogram')),
            ],
            options={
                'ordering': ['program', 'document_type', 'title'],
                'indexes': [models.Index(fields=['tenant', 'program'], name='hrm_ond_tenant_prog_idx'), models.Index(fields=['tenant', 'program', 'esign_status'], name='hrm_ond_tenant_prog_esign_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_category', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('phone', 'Phone'), ('id_card', 'ID Card'), ('access_card', 'Access Card'), ('uniform', 'Uniform'), ('vehicle', 'Vehicle'), ('sim', 'SIM Card'), ('other', 'Other')], default='other', max_length=30)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('return_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='hrm.employeeprofile')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_assets_issued', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hrm.onboardingprogram')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_ast_tenant_emp_idx'), models.Index(fields=['tenant', 'status'], name='hrm_ast_tenant_status_idx'), models.Index(fields=['tenant', 'program'], name='hrm_ast_tenant_prog_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_category', models.CharField(choices=[('hr_admin', 'HR Admin'), ('it_setup', 'IT Setup'), ('manager_action', 'Manager Action'), ('buddy_action', 'Buddy Action'), ('new_hire_action', 'New Hire Action'), ('document_sign', 'Document Sign'), ('equipment_request', 'Equipment Request'), ('training', 'Training'), ('meet_greet', 'Meet & Greet'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('assignee_role', models.CharField(choices=[('hr', 'HR'), ('it', 'IT'), ('manager', 'Manager'), ('buddy', 'Buddy'), ('new_hire', 'New Hire')], default='hr', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('preboarding', 'Preboarding'), ('week_1', 'Week 1'), ('month_1', 'Month 1'), ('month_2', 'Month 2'), ('month_3', 'Month 3'), ('ongoing', 'Ongoing')], default='week_1', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hrm.onboardingprogram')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['program', 'phase', 'order', 'due_date'],
                'indexes': [models.Index(fields=['tenant', 'program'], name='hrm_ont_tenant_prog_idx'), models.Index(fields=['tenant', 'program', 'status'], name='hrm_ont_tenant_prog_status_idx'), models.Index(fields=['tenant', 'program', 'phase'], name='hrm_ont_tenant_prog_phase_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_onbt_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['tenant', 'designation'], name='hrm_onbt_tenant_desig_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtemplate',
            unique_together={('tenant', 'name'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='onboardingprogram',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_onb_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingprogram',
            index=models.Index(fields=['tenant', 'status'], name='hrm_onb_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingprogram',
            index=models.Index(fields=['tenant', 'start_date'], name='hrm_onb_tenant_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingprogram',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='onboardingtemplatetask',
            index=models.Index(fields=['tenant', 'template'], name='hrm_ontt_tenant_tmpl_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplatetask',
            index=models.Index(fields=['tenant', 'template', 'phase'], name='hrm_ontt_tenant_tmpl_phase_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtemplatetask',
            unique_together={('tenant', 'template', 'title')},
        ),
        migrations.AddIndex(
            model_name='orientationsession',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_ors_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='orientationsession',
            index=models.Index(fields=['tenant', 'program'], name='hrm_ors_tenant_prog_idx'),
        ),
        migrations.AddIndex(
            model_name='orientationsession',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='hrm_ors_tenant_sched_idx'),
        ),
    ]
