# Generated by Django 5.1.15 on 2026-06-24 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0002_onboardingtemplate_onboardingprogram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orientationsession',
            index=models.Index(fields=['tenant', 'attendance_status'], name='hrm_ors_tenant_attst_idx'),
        ),
    ]
