# Generated by Django 5.1.15 on 2026-06-25 17:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0003_orientationsession_hrm_ors_tenant_attst_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('separation_type', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('layoff', 'Layoff'), ('retirement', 'Retirement'), ('contract_end', 'End of Contract'), ('deceased', 'Deceased')], default='resignation', max_length=20)),
                ('exit_reason', models.CharField(blank=True, choices=[('better_opportunity', 'Better Opportunity'), ('compensation', 'Compensation'), ('career_growth', 'Career Growth'), ('relocation', 'Relocation'), ('health', 'Health'), ('personal', 'Personal'), ('retirement', 'Retirement'), ('performance', 'Performance'), ('policy_violation', 'Policy Violation'), ('other', 'Other')], max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resignation_letter', models.FileField(blank=True, null=True, upload_to='hrm/offboarding/letters/%Y/%m/')),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('notice_start_date', models.DateField(blank=True, help_text='Day 1 of the notice period (usually the resignation date).', null=True)),
                ('expected_last_working_day', models.DateField(blank=True, editable=False, null=True)),
                ('actual_last_working_day', models.DateField(blank=True, help_text='HR-confirmed last working day.', null=True)),
                ('notice_buyout_type', models.CharField(choices=[('none', 'None'), ('pay_in_lieu', 'Pay in Lieu of Notice'), ('recover', 'Recover Shortfall')], default='none', max_length=20)),
                ('requires_kt', models.BooleanField(default=True, help_text='Adds a Knowledge-Transfer clearance line on approval.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_clearance', 'In Clearance'), ('cleared', 'Cleared'), ('settled', 'Settled'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', editable=False, max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('relieving_letter_generated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('experience_letter_generated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_approved_separations', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_cases', to='hrm.employeeprofile')),
                ('experience_letter_generated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_experience_letters_generated', to=settings.AUTH_USER_MODEL)),
                ('relieving_letter_generated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_relieving_letters_generated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('settlement_date', models.DateField(blank=True, help_text='Target payment date.', null=True)),
                ('prorata_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('leave_encashment_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('leave_encashment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gratuity_eligible', models.BooleanField(default=False)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notice_recovery_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recovery for unserved notice (or a negative value for an employer buyout payout).', max_digits=14)),
                ('loan_recovery', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('asset_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('advance_recovery', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('computed', 'Computed'), ('hr_approved', 'HR Approved'), ('finance_approved', 'Finance Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=20)),
                ('hr_approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finance_approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('paid_at', models.DateField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('gl_posted', models.BooleanField(default=False, editable=False, help_text='GL-posting stub — always False in v1 (posting deferred to accounting.PayrollRun).')),
                ('finance_approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_fnf_finance_approved', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_fnf_hr_approved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlements', to='hrm.separationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('conducted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('video', 'Video Call'), ('phone', 'Phone'), ('form', 'Self-Service Form')], default='in_person', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('no_show', 'No Show')], default='scheduled', editable=False, max_length=20)),
                ('rating_job_satisfaction', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_management', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_compensation', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_work_environment', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_growth_opportunities', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_work_life_balance', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_culture', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_overall', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('primary_reason', models.CharField(blank=True, choices=[('better_opportunity', 'Better Opportunity'), ('compensation', 'Compensation'), ('career_growth', 'Career Growth'), ('relocation', 'Relocation'), ('health', 'Health'), ('personal', 'Personal'), ('retirement', 'Retirement'), ('performance', 'Performance'), ('policy_violation', 'Policy Violation'), ('other', 'Other')], max_length=30)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('would_rejoin', models.BooleanField(blank=True, null=True)),
                ('what_went_well', models.TextField(blank=True)),
                ('what_to_improve', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_exit_interviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='hrm.separationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('it', 'IT'), ('finance', 'Finance'), ('hr', 'HR'), ('admin', 'Admin'), ('manager', 'Manager / KT'), ('legal', 'Legal'), ('security', 'Security'), ('library', 'Library'), ('custom', 'Custom')], default='hr', max_length=20)),
                ('department_label', models.CharField(blank=True, help_text='Free-text label when department is Custom.', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('cleared', 'Cleared'), ('not_applicable', 'Not Applicable'), ('rejected', 'Rejected')], default='pending', editable=False, max_length=20)),
                ('cleared_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset_allocation', models.ForeignKey(blank=True, help_text='Issued asset this line covers (returned when the line is cleared).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_items', to='hrm.assetallocation')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_clearance_items_assigned', to=settings.AUTH_USER_MODEL)),
                ('cleared_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_clearance_items_cleared', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_items', to='hrm.separationcase')),
            ],
            options={
                'ordering': ['case', 'department', 'description'],
            },
        ),
        migrations.AddIndex(
            model_name='separationcase',
            index=models.Index(fields=['tenant', 'status'], name='hrm_sep_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='separationcase',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_sep_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='separationcase',
            index=models.Index(fields=['tenant', 'separation_type'], name='hrm_sep_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='separationcase',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='finalsettlement',
            index=models.Index(fields=['tenant', 'status'], name='hrm_fnf_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='finalsettlement',
            index=models.Index(fields=['tenant', 'case'], name='hrm_fnf_tenant_case_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finalsettlement',
            unique_together={('tenant', 'case'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='exitinterview',
            index=models.Index(fields=['tenant', 'case'], name='hrm_ei_tenant_case_idx'),
        ),
        migrations.AddIndex(
            model_name='exitinterview',
            index=models.Index(fields=['tenant', 'status'], name='hrm_ei_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exitinterview',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='clearanceitem',
            index=models.Index(fields=['tenant', 'case'], name='hrm_ci_tenant_case_idx'),
        ),
        migrations.AddIndex(
            model_name='clearanceitem',
            index=models.Index(fields=['tenant', 'status'], name='hrm_ci_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clearanceitem',
            index=models.Index(fields=['tenant', 'case', 'status'], name='hrm_ci_tenant_case_st_idx'),
        ),
    ]
