# Generated by Django 5.1.15 on 2026-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_separationcase_finalsettlement_exitinterview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separationcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('in_clearance', 'In Clearance'), ('cleared', 'Cleared'), ('settled', 'Settled'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', editable=False, max_length=20),
        ),
    ]
