# Generated by Django 5.1.15 on 2026-06-25 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0005_alter_separationcase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clearanceitem',
            index=models.Index(fields=['tenant', 'department'], name='hrm_ci_tenant_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='exitinterview',
            index=models.Index(fields=['tenant', 'mode'], name='hrm_ei_tenant_mode_idx'),
        ),
    ]
