# Generated by Django 5.1.15 on 2026-06-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0006_clearanceitem_hrm_ci_tenant_dept_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='budgeted_headcount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='mid_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CostCenterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('budget_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_profile', to='core.orgunit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cost_centers', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['org_unit__name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_center', models.ForeignKey(blank=True, limit_choices_to={'kind': 'cost_center'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_cost_mappings', to='core.orgunit')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='hrm.employeeprofile')),
                ('org_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_profile', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['org_unit__name'],
            },
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('level_order', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['level_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='designation',
            name='job_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='hrm.jobgrade'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['tenant', 'job_grade'], name='hrm_desig_tenant_jg_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenterprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_cc_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenterprofile',
            index=models.Index(fields=['tenant', 'owner'], name='hrm_cc_tenant_owner_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenterprofile',
            unique_together={('tenant', 'org_unit')},
        ),
        migrations.AddIndex(
            model_name='departmentprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_dp_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentprofile',
            index=models.Index(fields=['tenant', 'head'], name='hrm_dp_tenant_head_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentprofile',
            unique_together={('tenant', 'org_unit')},
        ),
        migrations.AddIndex(
            model_name='jobgrade',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_jg_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='jobgrade',
            index=models.Index(fields=['tenant', 'level_order'], name='hrm_jg_tenant_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobgrade',
            unique_together={('tenant', 'name')},
        ),
    ]
