# Generated by Django 5.1.15 on 2026-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0007_designation_budgeted_headcount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='departmentprofile',
            index=models.Index(fields=['tenant', 'cost_center'], name='hrm_dp_tenant_cc_idx'),
        ),
    ]
