# Generated by Django 5.1.15 on 2026-06-25 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0008_departmentprofile_hrm_dp_tenant_cc_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_2_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_2_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='national_id_type',
            field=models.CharField(blank=True, help_text='e.g. Aadhaar, SSN, NRIC, PAN.', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notice_period_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Profile-default notice period; a SeparationCase can override it per departure.', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_email',
            field=models.EmailField(blank=True, help_text='Company email, distinct from personal_email.', max_length=254),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_location',
            field=models.CharField(blank=True, help_text='Office / site / remote assignment.', max_length=255),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID / Aadhaar / NRIC'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('address_proof', 'Address Proof'), ('visa', 'Visa'), ('work_permit', 'Work Permit'), ('degree_certificate', 'Degree / Diploma Certificate'), ('professional_cert', 'Professional Certification'), ('appointment_letter', 'Appointment Letter'), ('employment_contract', 'Employment Contract'), ('nda', 'Non-Disclosure Agreement'), ('non_compete', 'Non-Compete Agreement'), ('tax_form', 'Tax Form (W-4 / Form 16 / TDS)'), ('bank_proof', 'Bank Account Proof'), ('pf_nomination', 'PF / Pension Nomination'), ('medical_cert', 'Medical / Fitness Certificate'), ('background_check', 'Background Check Report'), ('experience_certificate', 'Previous Employment / Experience Letter'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, help_text='The alphanumeric ID on the document itself (passport no., PAN, licence no.).', max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, help_text='Leave blank for documents that do not expire.', null=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='HR-only visibility flag.')),
                ('file', models.FileField(blank=True, null=True, upload_to='hrm/employee_docs/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', editable=False, max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_edoc_tenant_emp_idx'), models.Index(fields=['tenant', 'document_type'], name='hrm_edoc_tenant_type_idx'), models.Index(fields=['tenant', 'verification_status'], name='hrm_edoc_tenant_vstat_idx'), models.Index(fields=['tenant', 'expires_on'], name='hrm_edoc_tenant_expiry_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('event_type', models.CharField(choices=[('hire', 'Hire'), ('confirmation', 'Confirmation (Probation End)'), ('transfer', 'Transfer'), ('promotion', 'Promotion'), ('demotion', 'Demotion'), ('salary_revision', 'Salary Revision'), ('re_designation', 'Re-designation'), ('location_change', 'Location Change'), ('reporting_change', 'Reporting Manager Change'), ('suspension', 'Suspension'), ('reinstatement', 'Reinstatement'), ('contract_renewal', 'Contract Renewal'), ('separation', 'Separation'), ('other', 'Other')], default='other', max_length=30)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('from_job_title', models.CharField(blank=True, max_length=255)),
                ('to_job_title', models.CharField(blank=True, max_length=255)),
                ('from_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('to_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('from_employee_type', models.CharField(blank=True, max_length=20)),
                ('to_employee_type', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='hrm.employeeprofile')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.orgunit')),
                ('from_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.designation')),
                ('from_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.employeeprofile')),
                ('initiated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_initiated_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.orgunit')),
                ('to_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.designation')),
                ('to_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.employeeprofile')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'effective_date'], name='hrm_elc_tenant_emp_date_idx'), models.Index(fields=['tenant', 'event_type'], name='hrm_elc_tenant_type_idx'), models.Index(fields=['tenant', 'employee', 'event_type'], name='hrm_elc_tenant_emp_type_idx'), models.Index(fields=['tenant', 'effective_date'], name='hrm_elc_tenant_effdate_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
