# Generated by Django 5.1.15 on 2026-06-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('hrm', '0009_employeeprofile_current_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('consultant', 'Consultant')], max_length=20)),
                ('jd_summary', models.TextField(blank=True)),
                ('jd_responsibilities', models.TextField(blank=True)),
                ('jd_requirements', models.TextField(blank=True)),
                ('jd_nice_to_have', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jd_templates', to='hrm.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('headcount', models.PositiveSmallIntegerField(default=1)),
                ('req_type', models.CharField(choices=[('standard', 'Standard'), ('backfill', 'Backfill'), ('replacement', 'Replacement'), ('evergreen', 'Evergreen / Pipeline')], default='standard', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('consultant', 'Consultant')], default='full_time', max_length=20)),
                ('reason_for_hire', models.CharField(choices=[('new_headcount', 'New Headcount'), ('backfill', 'Backfill Vacancy'), ('replacement', 'Replacement'), ('project', 'Project / Fixed Term'), ('contractor_to_perm', 'Contractor to Permanent')], default='new_headcount', max_length=30)),
                ('is_replacement_for', models.CharField(blank=True, help_text='Name of the departing employee (free text; FK upgrade deferred to 3.6).', max_length=255)),
                ('posting_type', models.CharField(choices=[('internal', 'Internal Only'), ('external', 'External Only'), ('both', 'Internal & External')], default='external', max_length=10)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('estimated_annual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Loaded annual cost (salary + benefits).', max_digits=14, null=True)),
                ('hiring_cost_budget', models.DecimalField(blank=True, decimal_places=2, help_text='One-time recruitment spend (agency/job-board).', max_digits=14, null=True)),
                ('jd_summary', models.TextField(blank=True)),
                ('jd_responsibilities', models.TextField(blank=True)),
                ('jd_requirements', models.TextField(blank=True)),
                ('jd_nice_to_have', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('on_hold', 'On Hold'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', editable=False, max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('filled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cost_center', models.ForeignKey(blank=True, limit_choices_to={'kind': 'cost_center'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_requisitions_cc', to='core.orgunit')),
                ('department', models.ForeignKey(blank=True, limit_choices_to={'kind': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_requisitions', to='core.orgunit')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='hrm.designation')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requisitions', to='hrm.employeeprofile')),
                ('job_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='hrm.jobgrade')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requisitions', to='hrm.employeeprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='hrm.jobdescriptiontemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveSmallIntegerField(default=1)),
                ('approver_role', models.CharField(choices=[('hiring_manager', 'Hiring Manager'), ('hr', 'HR'), ('finance', 'Finance'), ('executive', 'Executive'), ('custom', 'Custom')], default='hr', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision'), ('skipped', 'Skipped')], default='pending', editable=False, max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('comments', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_requisition_approvals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hrm.jobrequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddIndex(
            model_name='jobdescriptiontemplate',
            index=models.Index(fields=['tenant', 'designation'], name='hrm_jdtmpl_tenant_desig_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescriptiontemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_jdtmpl_tenant_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobdescriptiontemplate',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['tenant', 'status'], name='hrm_jr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['tenant', 'designation'], name='hrm_jr_tenant_desig_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['tenant', 'department'], name='hrm_jr_tenant_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['tenant', 'hiring_manager'], name='hrm_jr_tenant_hm_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['tenant', 'priority', 'status'], name='hrm_jr_tenant_prio_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrequisition',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='requisitionapproval',
            index=models.Index(fields=['requisition', 'status'], name='hrm_ra_req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionapproval',
            index=models.Index(fields=['approver', 'status'], name='hrm_ra_approver_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requisitionapproval',
            unique_together={('requisition', 'step_order')},
        ),
    ]
