# Generated by Django 5.1.15 on 2026-06-29 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0010_jobdescriptiontemplate_jobrequisition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='URL-safe token minted when the req is posted; powers the public careers portal.', max_length=64),
        ),
        migrations.CreateModel(
            name='CandidateEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('application_received', 'Application Received'), ('shortlisted', 'Application Shortlisted'), ('phone_screen_invite', 'Phone Screen Invitation'), ('interview_invite', 'Interview Invitation'), ('stage_advance', 'Advance to Next Stage'), ('assessment_invite', 'Assessment / Test Invitation'), ('rejection', 'Application Rejected'), ('on_hold', 'Application On Hold'), ('offer', 'Offer Communication'), ('general', 'General / Ad-hoc')], default='general', max_length=30)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField(help_text='Merge fields: {{candidate_name}}, {{job_title}}, {{company_name}}, {{recruiter_name}}, {{application_number}}.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_send', models.BooleanField(default=False, help_text='Auto-send when a JobApplication stage transition matches this template type.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Unique per tenant — the duplicate-detection anchor.', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin_url', models.URLField(blank=True)),
                ('current_job_title', models.CharField(blank=True, max_length=255)),
                ('current_employer', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('highest_qualification', models.CharField(blank=True, choices=[('high_school', 'High School / Secondary'), ('diploma', 'Diploma / Certificate'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD / Doctorate'), ('other', 'Other')], max_length=20)),
                ('skill_set', models.TextField(blank=True, help_text='Comma-delimited free-text skills. Structured skills live in CandidateSkill.')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='hrm/candidates/resumes/%Y/%m/')),
                ('resume_text', models.TextField(blank=True, help_text='Raw text extracted from the resume — powers keyword search (NLP parsing deferred).')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hrm/candidates/photos/%Y/%m/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hired', 'Hired'), ('blacklisted', 'Blacklisted'), ('do_not_contact', 'Do Not Contact')], default='active', editable=False, max_length=20)),
                ('source', models.CharField(blank=True, choices=[('careers_page', 'Company Careers Page'), ('referral', 'Employee Referral'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('job_board', 'Other Job Board'), ('agency', 'Recruitment Agency'), ('direct_approach', 'Direct / Sourced'), ('walk_in', 'Walk-in'), ('other', 'Other')], max_length=20)),
                ('do_not_contact', models.BooleanField(default=False, help_text='Suppresses all automated candidate emails.')),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('gdpr_consent_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('gdpr_consent_expires', models.DateField(blank=True, help_text='Data-retention window; after this date the record is eligible for anonymization.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='core.party')),
                ('sourced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_candidates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('source', models.CharField(choices=[('parsed', 'Resume Parsed'), ('manual', 'Manually Added'), ('self_reported', 'Self-Reported')], default='manual', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hrm.candidateprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color for the tag badge, e.g. #3B82F6.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, e.g. #3B82F6.')])),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='hrm.candidatetag'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('phone_screen', 'Phone Screen'), ('assessment', 'Assessment / Test'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='applied', editable=False, max_length=20)),
                ('source', models.CharField(choices=[('careers_page', 'Company Careers Page'), ('referral', 'Employee Referral'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('job_board', 'Other Job Board'), ('agency', 'Recruitment Agency'), ('direct_approach', 'Direct / Sourced'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='careers_page', max_length=20)),
                ('cover_letter_text', models.TextField(blank=True)),
                ('cover_letter_file', models.FileField(blank=True, null=True, upload_to='hrm/candidates/covers/%Y/%m/')),
                ('screening_answers', models.JSONField(blank=True, default=dict, help_text='Per-requisition screening questions and answers, stored as a {question: answer} map.')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Recruiter rating, 1–5.', null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('overqualified', 'Overqualified'), ('underqualified', 'Underqualified'), ('position_filled', 'Position Filled'), ('no_response', 'No Response / Unresponsive'), ('failed_screening', 'Failed Screening'), ('other', 'Other')], max_length=30)),
                ('rejection_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('stage_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('hired_on', models.DateField(blank=True, editable=False, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hrm.candidateprofile')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hrm.employeeprofile')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hrm.jobrequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=10)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_communications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='hrm.candidateemailtemplate')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='hrm.candidateprofile')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='hrm.jobapplication')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidateemailtemplate',
            index=models.Index(fields=['tenant', 'template_type', 'is_active'], name='hrm_cetmpl_type_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateemailtemplate',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['tenant', 'skill_name'], name='hrm_cskill_tenant_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together={('candidate', 'skill_name')},
        ),
        migrations.AddIndex(
            model_name='candidatetag',
            index=models.Index(fields=['tenant', 'name'], name='hrm_ctag_tenant_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatetag',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['tenant', 'status'], name='hrm_cand_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['tenant', 'source'], name='hrm_cand_tenant_source_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['tenant', 'do_not_contact'], name='hrm_cand_tenant_dnc_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='hrm_cand_tenant_email_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateprofile',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['tenant', 'stage'], name='hrm_app_tenant_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['tenant', 'source'], name='hrm_app_tenant_source_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['tenant', 'requisition'], name='hrm_app_tenant_req_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['tenant', 'candidate'], name='hrm_app_tenant_cand_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('candidate', 'requisition'), name='hrm_app_cand_req_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='candidatecommunication',
            index=models.Index(fields=['tenant', 'candidate'], name='hrm_cc_tenant_cand_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecommunication',
            index=models.Index(fields=['tenant', 'application'], name='hrm_cc_tenant_app_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecommunication',
            index=models.Index(fields=['tenant', 'delivery_status'], name='hrm_cc_tenant_dstatus_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatecommunication',
            unique_together={('tenant', 'number')},
        ),
    ]
