# Generated by Django 5.1.15 on 2026-06-29 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0012_jobrequisition_public_token_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['tenant', 'created_at'], name='hrm_cand_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['tenant', 'applied_at'], name='hrm_app_tenant_applied_idx'),
        ),
    ]
