# Generated by Django 5.1.15 on 2026-06-30 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0013_candidate_ordering_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateemailtemplate',
            name='template_type',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('shortlisted', 'Application Shortlisted'), ('phone_screen_invite', 'Phone Screen Invitation'), ('interview_invite', 'Interview Invitation'), ('interview_reminder', 'Interview Reminder'), ('stage_advance', 'Advance to Next Stage'), ('assessment_invite', 'Assessment / Test Invitation'), ('rejection', 'Application Rejected'), ('on_hold', 'Application On Hold'), ('offer', 'Offer Communication'), ('general', 'General / Ad-hoc')], default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(help_text='e.g. "Technical Round 2" or "HR Screen".', max_length=255)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video Call'), ('one_way_video', 'One-way Video')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', editable=False, max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('location', models.CharField(blank=True, help_text='Physical room / address for in-person rounds.', max_length=255)),
                ('video_provider', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google_meet', 'Google Meet'), ('other', 'Other')], max_length=20)),
                ('meeting_url', models.URLField(blank=True, help_text='Video meeting link (paste from Zoom/Teams/Meet — auto-generation is deferred).')),
                ('interviewer_instructions', models.TextField(blank=True, help_text='Briefing shown to the panel (focus areas, must-asks).')),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('feedback_reminder_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hrm.jobapplication')),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('overall_recommendation', models.CharField(choices=[('strong_no', 'Strong No'), ('no', 'No'), ('maybe', 'Maybe'), ('yes', 'Yes'), ('strong_yes', 'Strong Yes')], default='maybe', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Overall impression / key takeaways.')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='hrm.interview')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_feedback', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion_name', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (poor) – 5 (excellent).')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='hrm.interviewfeedback')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPanelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('lead', 'Lead Interviewer'), ('interviewer', 'Interviewer'), ('shadow', 'Shadow / Trainee'), ('observer', 'Observer')], default='interviewer', max_length=20)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('briefing_notes', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='hrm.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panels', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['role', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='panelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.interviewpanelist'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['tenant', 'status'], name='hrm_intv_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['tenant', 'mode'], name='hrm_intv_tenant_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['tenant', 'application'], name='hrm_intv_tenant_app_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='hrm_intv_tenant_sched_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='feedbackcriterion',
            index=models.Index(fields=['tenant', 'feedback'], name='hrm_fcrit_tenant_fb_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewpanelist',
            index=models.Index(fields=['tenant', 'interview'], name='hrm_ipan_tenant_intv_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewpanelist',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['tenant', 'interview'], name='hrm_ifb_tenant_intv_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['tenant', 'overall_recommendation'], name='hrm_ifb_tenant_reco_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['tenant', 'is_submitted'], name='hrm_ifb_tenant_sub_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewfeedback',
            unique_together={('tenant', 'number')},
        ),
    ]
