# Generated by Django 5.1.15 on 2026-06-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0014_interview_process'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewfeedback',
            unique_together={('interview', 'panelist'), ('tenant', 'number')},
        ),
    ]
