# Generated by Django 5.1.15 on 2026-07-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0015_alter_interviewfeedback_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('body_html', models.TextField(help_text='Merge fields: {{candidate_name}}, {{job_title}}, {{base_salary}}, {{currency}}, {{start_date}}, {{company_name}}, {{hiring_manager_name}}.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', help_text="Defaults from the requisition's salary_currency at creation.", max_length=3)),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bonus_terms', models.TextField(blank=True)),
                ('signing_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('equity_terms', models.TextField(blank=True, help_text="Grant description / vesting schedule — equity plans aren't a structured table yet.")),
                ('relocation_assistance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('benefits_summary', models.TextField(blank=True)),
                ('start_date', models.DateField(help_text='Proposed joining date.')),
                ('expires_on', models.DateField(blank=True, help_text='Offer response deadline.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('extended', 'Extended to Candidate'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rescinded', 'Rescinded'), ('expired', 'Expired')], default='draft', editable=False, max_length=20)),
                ('decline_reason', models.CharField(blank=True, choices=[('salary', 'Salary / Compensation'), ('competing_offer', 'Accepted a Competing Offer'), ('counteroffer', 'Counteroffer from Current Employer'), ('role_fit', 'Role / Responsibilities Fit'), ('culture_fit', 'Culture / Team Fit'), ('timing', 'Timing / Start Date'), ('other', 'Other')], max_length=30)),
                ('decline_notes', models.TextField(blank=True)),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='hrm/offers/signed/%Y/%m/')),
                ('signature_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent for Signature'), ('viewed', 'Viewed by Candidate'), ('signed', 'Signed'), ('declined', 'Declined to Sign')], default='not_sent', max_length=20)),
                ('extended_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('declined_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rescinded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hrm.jobapplication')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
                ('extended_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_offers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('offer_letter_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='hrm.offerlettertemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('tax_form', 'Tax Form'), ('bank_details', 'Bank / Direct-Deposit Details'), ('nda', 'NDA / Confidentiality Agreement'), ('education_certificate', 'Education Certificate'), ('background_check_consent', 'Background-Check Consent'), ('other', 'Other')], default='other', max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', editable=False, max_length=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='hrm/offers/preboarding/%Y/%m/')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preboarding_items', to='hrm.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_preboarding_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('vendor', models.CharField(blank=True, choices=[('checkr', 'Checkr'), ('hireright', 'HireRight'), ('sterling', 'Sterling'), ('other', 'Other / In-house')], max_length=30)),
                ('check_type', models.CharField(choices=[('criminal', 'Criminal Record'), ('employment', 'Employment History'), ('education', 'Education Verification'), ('professional_license', 'Professional License / Certification'), ('identity', 'Identity Verification'), ('credit', 'Credit Check')], default='employment', max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('consent_pending', 'Consent Pending'), ('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('action_needed', 'Action Needed'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed')], default='not_started', editable=False, max_length=20)),
                ('result', models.CharField(blank=True, choices=[('clear', 'Clear'), ('consider', 'Consider'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='hrm/offers/bgv_reports/%Y/%m/')),
                ('initiated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_bgv_checks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='hrm.offer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='hrm_bgv_tenant_status_idx'), models.Index(fields=['tenant', 'offer'], name='hrm_bgv_tenant_ofr_idx'), models.Index(fields=['tenant', 'check_type'], name='hrm_bgv_tenant_type_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OfferApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveSmallIntegerField(default=1)),
                ('approver_role', models.CharField(choices=[('hiring_manager', 'Hiring Manager'), ('hr', 'HR'), ('finance', 'Finance'), ('executive', 'Executive'), ('custom', 'Custom')], default='hr', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision'), ('skipped', 'Skipped')], default='pending', editable=False, max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('comments', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_offer_approvals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_offer_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hrm.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['step_order'],
                'indexes': [models.Index(fields=['offer', 'status'], name='hrm_oa_offer_status_idx'), models.Index(fields=['approver', 'status'], name='hrm_oa_approver_status_idx')],
                'unique_together': {('offer', 'step_order')},
            },
        ),
        migrations.AddIndex(
            model_name='offerlettertemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_oltmpl_tenant_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerlettertemplate',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['tenant', 'status'], name='hrm_ofr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['tenant', 'application'], name='hrm_ofr_tenant_app_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['tenant', 'created_at'], name='hrm_ofr_tenant_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='preboardingitem',
            index=models.Index(fields=['tenant', 'offer'], name='hrm_pbi_tenant_ofr_idx'),
        ),
        migrations.AddIndex(
            model_name='preboardingitem',
            index=models.Index(fields=['tenant', 'status'], name='hrm_pbi_tenant_status_idx'),
        ),
    ]
