# Generated by Django 5.1.15 on 2026-07-01 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0016_offer_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='backgroundverification',
            index=models.Index(fields=['tenant', 'created_at'], name='hrm_bgv_tenant_created_idx'),
        ),
    ]
