# Generated by Django 5.1.15 on 2026-07-02 18:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0017_backgroundverification_hrm_bgv_tenant_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('radius_m', models.PositiveIntegerField(default=100, help_text='Allowed radius from the centre point, in metres.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hrm.geofence'),
        ),
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('date', models.DateField()),
                ('reason_type', models.CharField(choices=[('missed_punch', 'Missed Punch'), ('forgot_checkin', 'Forgot Check-In'), ('forgot_checkout', 'Forgot Check-Out'), ('wrong_time', 'Wrong Time Recorded'), ('on_duty', 'On Official Duty'), ('work_from_home', 'Work From Home'), ('system_error', 'System / Device Error'), ('other', 'Other')], default='missed_punch', max_length=20)),
                ('requested_check_in', models.TimeField(blank=True, null=True)),
                ('requested_check_out', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_regularization_approvals', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularizations', to='hrm.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularizations', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'status'], name='hrm_reg_tenant_emp_status_idx'), models.Index(fields=['tenant', 'status'], name='hrm_reg_tenant_status_idx'), models.Index(fields=['tenant', 'date'], name='hrm_reg_tenant_date_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_geo_tenant_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geofence',
            unique_together={('tenant', 'name')},
        ),
    ]
