# Generated by Django 5.1.15 on 2026-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0018_attendancerecord_latitude_attendancerecord_longitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['tenant', 'geofence'], name='hrm_att_tenant_geofence_idx'),
        ),
    ]
