# Generated by Django 5.1.15 on 2026-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_leaveallocation_carried_forward_leaveencashment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveallocation',
            name='encashed_days',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
