# Generated by Django 5.1.15 on 2026-07-03 03:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0021_leaveallocation_encashed_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_timesheet_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('date', models.DateField()),
                ('hours_claimed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('payout_method', models.CharField(choices=[('pay', 'Pay'), ('comp_leave', 'Compensatory Leave')], default='pay', max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_overtime_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests', to='hrm.timesheet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('task_description', models.CharField(blank=True, max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_billable', models.BooleanField(default=True)),
                ('billable_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_timesheet_entries', to='accounting.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hrm.timesheet')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_ts_tenant_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'status'], name='hrm_ts_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'period_start'], name='hrm_ts_tenant_period_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('tenant', 'employee', 'period_start'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_ot_tenant_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['tenant', 'status'], name='hrm_ot_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['tenant', 'date'], name='hrm_ot_tenant_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='overtimerequest',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['tenant', 'timesheet'], name='hrm_tse_tenant_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['tenant', 'project'], name='hrm_tse_tenant_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['tenant', 'date'], name='hrm_tse_tenant_date_idx'),
        ),
    ]
