# Generated by Django 5.1.15 on 2026-07-03 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0022_timesheet_overtimerequest_timesheetentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='category',
            field=models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('company', 'Company'), ('observance', 'Observance')], default='national', max_length=20),
        ),
        migrations.CreateModel(
            name='HolidayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, help_text="Matched (case-insensitive contains) against an employee's work location. Blank = any.", max_length=255)),
                ('employee_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('consultant', 'Consultant')], help_text='Employment-type eligibility. Blank = any.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='The fallback policy applied when no more specific policy matches.')),
                ('floating_holiday_quota', models.PositiveSmallIntegerField(default=0, help_text='Maximum optional (floating) holidays an eligible employee may elect per year.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('designation', models.ForeignKey(blank=True, help_text='Designation/grade eligibility. Blank = any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_policies', to='hrm.designation')),
                ('holidays', models.ManyToManyField(blank=True, help_text='Optional — restrict the electable optional-holiday pool. Empty = all optional holidays.', related_name='policies', to='hrm.publicholiday')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Department/branch scope. Blank = any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_policies', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FloatingHolidayElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_on', models.DateField(default=django.utils.timezone.localdate)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_floating_holiday_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floating_holiday_elections', to='hrm.employeeprofile')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floating_elections', to='hrm.publicholiday')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('policy', models.ForeignKey(blank=True, help_text='The governing policy (auto-resolved from the employee if left blank).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='hrm.holidaypolicy')),
            ],
            options={
                'ordering': ['-requested_on'],
            },
        ),
        migrations.AddIndex(
            model_name='holidaypolicy',
            index=models.Index(fields=['tenant', 'is_default'], name='hrm_hpol_tenant_default_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaypolicy',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='floatingholidayelection',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_fhe_tenant_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='floatingholidayelection',
            index=models.Index(fields=['tenant', 'status'], name='hrm_fhe_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='floatingholidayelection',
            unique_together={('tenant', 'employee', 'holiday')},
        ),
    ]
