# Generated by Django 5.1.15 on 2026-07-04 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0023_publicholiday_category_holidaypolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='Optional short code, e.g. HRA, PF-EE.', max_length=20)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('statutory_deduction', 'Statutory Deduction'), ('voluntary_deduction', 'Voluntary Deduction'), ('reimbursement', 'Reimbursement'), ('variable', 'Variable')], default='earning', max_length=20)),
                ('variable_subtype', models.CharField(blank=True, help_text='Only for variable components — e.g. bonus, incentive, commission.', max_length=30)),
                ('calculation_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('pct_of_basic', '% of Basic'), ('pct_of_ctc', '% of CTC'), ('pct_of_gross', '% of Gross')], default='fixed_amount', max_length=20)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Org-wide default when the calculation is a fixed amount (a structure line can override).', max_digits=12, null=True)),
                ('default_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Org-wide default when the calculation is a percentage (a structure line can override).', max_digits=5, null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-Time')], default='monthly', max_length=20)),
                ('is_taxable', models.BooleanField(default=True)),
                ('include_in_ctc', models.BooleanField(default=True)),
                ('contribution_side', models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer'), ('both', 'Both')], default='employee', help_text='Which side pays this — mainly for statutory components (PF/ESI).', max_length=10)),
                ('annual_cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Annual cap, e.g. for a reimbursement like LTA/medical.', max_digits=12, null=True)),
                ('requires_bill', models.BooleanField(default=False, help_text='Reimbursement requires a submitted bill/receipt before payout.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('annual_ctc_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Target annual CTC — the base for %-of-CTC lines.', max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('job_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_structure_templates', to='hrm.jobgrade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_type', models.CharField(blank=True, choices=[('fixed_amount', 'Fixed Amount'), ('pct_of_basic', '% of Basic'), ('pct_of_ctc', '% of CTC'), ('pct_of_gross', '% of Gross')], help_text="Overrides the component's calculation type on this template; blank = use the component's.", max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('pay_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.paycomponent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrm.salarystructuretemplate')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('annual_ctc_amount', models.DecimalField(decimal_places=2, help_text="The employee's actual assigned annual CTC (may differ from the template default).", max_digits=14)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assignments', to='hrm.salarystructuretemplate')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='paycomponent',
            index=models.Index(fields=['tenant', 'component_type'], name='hrm_paycomp_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paycomponent',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='salarystructuretemplate',
            index=models.Index(fields=['tenant', 'job_grade'], name='hrm_sst_tenant_grade_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarystructuretemplate',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='salarystructureline',
            index=models.Index(fields=['tenant', 'template'], name='hrm_ssl_tenant_template_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarystructureline',
            unique_together={('tenant', 'template', 'pay_component')},
        ),
        migrations.AddIndex(
            model_name='employeesalarystructure',
            index=models.Index(fields=['tenant', 'employee', 'effective_from'], name='hrm_ess_tenant_emp_efrom_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalarystructure',
            index=models.Index(fields=['tenant', 'status'], name='hrm_ess_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalarystructure',
            unique_together={('tenant', 'number')},
        ),
    ]
