# Generated by Django 5.1.15 on 2026-07-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0024_paycomponent_salarystructuretemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField()),
                ('cycle_type', models.CharField(choices=[('regular', 'Regular'), ('off_cycle', 'Off-Cycle'), ('bonus', 'Bonus')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('accounting_payroll_run', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_cycles', to='accounting.payrollrun')),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_payroll_cycle_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_payroll_cycle_submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('days_in_period', models.PositiveSmallIntegerField(default=30)),
                ('days_worked', models.PositiveSmallIntegerField(default=30)),
                ('lop_days', models.DecimalField(decimal_places=2, default=0, help_text='Unpaid (loss-of-pay) days in the period.', max_digits=5)),
                ('lop_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('on_hold', models.BooleanField(default=False)),
                ('hold_reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hrm.payrollcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hrm.employeeprofile')),
                ('salary_structure', models.ForeignKey(blank=True, help_text='The structure this payslip was computed from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='hrm.employeesalarystructure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['cycle', 'employee__party__name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_name', models.CharField(max_length=150)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('statutory_deduction', 'Statutory Deduction'), ('voluntary_deduction', 'Voluntary Deduction'), ('reimbursement', 'Reimbursement'), ('variable', 'Variable'), ('arrears', 'Arrears'), ('bonus', 'Bonus'), ('lop', 'Loss of Pay')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contribution_side', models.CharField(blank=True, choices=[('employee', 'Employee'), ('employer', 'Employer'), ('both', 'Both')], default='', help_text="Snapshotted from the source component so the lock roll-up needn't re-join PayComponent.", max_length=10)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrm.payslip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollcycle',
            index=models.Index(fields=['tenant', 'status'], name='hrm_prc_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcycle',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'cycle'], name='hrm_psl_tenant_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_psl_tenant_emp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('tenant', 'cycle', 'employee')},
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['tenant', 'payslip'], name='hrm_psll_tenant_payslip_idx'),
        ),
    ]
