# Generated by Django 5.1.15 on 2026-07-04 16:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0025_payrollcycle_payslip_payslipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pf_establishment_code', models.CharField(blank=True, max_length=50)),
                ('pf_wage_ceiling', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), help_text='Monthly Basic+DA ceiling for PF (documentation; enforcement stays in payroll).', max_digits=12)),
                ('pf_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('pf_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('esi_employer_code', models.CharField(blank=True, max_length=50)),
                ('esi_wage_ceiling', models.DecimalField(decimal_places=2, default=Decimal('21000.00'), help_text='Monthly gross ceiling below which an employee is ESI-eligible.', max_digits=12)),
                ('esi_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=5)),
                ('esi_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('3.25'), max_digits=5)),
                ('pt_default_state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50)),
                ('tan_number', models.CharField(blank=True, help_text='Employer Tax Deduction Account Number — mandatory on Form 24Q/16 (distinct from PAN).', max_length=20)),
                ('tds_circle_address', models.TextField(blank=True, help_text='TDS circle/ward address printed on Form 16.')),
                ('pan_of_deductor', models.CharField(blank=True, help_text="The employer's own PAN (distinct from an employee's PAN in EmployeeProfile.national_id).", max_length=10)),
                ('is_lwf_applicable', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_statutory_config', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Statutory Configuration',
                'verbose_name_plural': 'Statutory Configuration',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatutoryIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uan_number', models.CharField(blank=True, help_text='PF Universal Account Number (lifelong, distinct from the establishment PF number).', max_length=20)),
                ('pf_number', models.CharField(blank=True, help_text='Establishment-specific PF account/member ID.', max_length=30)),
                ('esi_number', models.CharField(blank=True, help_text='ESI Insurance Number (blank if the employee is above the ESI ceiling / exempt).', max_length=20)),
                ('pt_state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], help_text='Resolves which PT/LWF StatutoryStateRule applies; falls back to the config default.', max_length=50)),
                ('is_pf_applicable', models.BooleanField(default=True)),
                ('is_esi_applicable', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_identifiers', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['employee__party__name'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_empstat_tenant_emp_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('scheme', models.CharField(choices=[('pf', 'Provident Fund'), ('esi', 'ESI'), ('pt', 'Professional Tax'), ('tds_24q', 'TDS — Form 24Q'), ('tds_form16', 'TDS — Form 16'), ('lwf', 'Labour Welfare Fund')], max_length=15)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual')], default='monthly', max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('employee_contribution_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('employer_contribution_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('headcount', models.PositiveIntegerField(default=0, editable=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filed', 'Filed'), ('paid', 'Paid'), ('late', 'Late')], default='pending', max_length=15)),
                ('filed_on', models.DateField(blank=True, editable=False, null=True)),
                ('paid_on', models.DateField(blank=True, editable=False, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('registration_number_used', models.CharField(blank=True, editable=False, help_text='Snapshot of the config/rule registration number at generation time.', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(blank=True, help_text='Set for the single-cycle monthly case; null for multi-cycle rollups (e.g. quarterly 24Q).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_returns', to='hrm.payrollcycle')),
                ('employee', models.ForeignKey(blank=True, help_text='Set only for per-employee Form 16; null for org-level returns.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_returns', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'scheme'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='hrm_scr_tenant_status_idx'), models.Index(fields=['tenant', 'due_date'], name='hrm_scr_tenant_duedate_idx'), models.Index(fields=['tenant', 'scheme'], name='hrm_scr_tenant_scheme_idx')],
                'unique_together': {('tenant', 'scheme', 'period_start', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='StatutoryStateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50)),
                ('scheme', models.CharField(choices=[('pt', 'Professional Tax'), ('lwf', 'Labour Welfare Fund')], default='pt', max_length=10)),
                ('income_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pt_monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pt_deduction_month', models.CharField(blank=True, help_text='Optional — some states deduct PT only in specific months (e.g. an annual lump sum).', max_length=20)),
                ('lwf_employee_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lwf_employer_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lwf_periodicity', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual')], max_length=20)),
                ('lwf_due_month_1', models.CharField(blank=True, help_text='e.g. July.', max_length=20)),
                ('lwf_due_month_2', models.CharField(blank=True, help_text='e.g. January (half-yearly states).', max_length=20)),
                ('registration_number', models.CharField(blank=True, help_text='State-specific PT/LWF employer registration number, where applicable.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['state', 'scheme', 'income_from'],
                'indexes': [models.Index(fields=['tenant', 'scheme'], name='hrm_ssr_tenant_scheme_idx'), models.Index(fields=['tenant', 'state'], name='hrm_ssr_tenant_state_idx')],
                'unique_together': {('tenant', 'state', 'scheme', 'income_from')},
            },
        ),
    ]
