# Generated by Django 5.1.15 on 2026-07-04 19:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0026_statutoryconfig_employeestatutoryidentifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('financial_year', models.CharField(help_text='Indian FY, e.g. "2025-26".', max_length=10)),
                ('regime_elected', models.CharField(choices=[('old', 'Old Regime'), ('new', 'New Regime')], default='new', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('locked', 'Locked')], default='draft', max_length=15)),
                ('declaration_window_open', models.DateField(blank=True, null=True)),
                ('declaration_window_close', models.DateField(blank=True, null=True)),
                ('proof_window_open', models.DateField(blank=True, null=True)),
                ('proof_window_close', models.DateField(blank=True, null=True)),
                ('previous_employer_income', models.DecimalField(decimal_places=2, default=0, help_text='Salary earned with a previous employer this FY (mid-year joiner projection input).', max_digits=14)),
                ('previous_employer_tds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_declarations', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-financial_year', 'employee__party__name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentDeclarationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_code', models.CharField(choices=[('80c', 'Section 80C'), ('80d', 'Section 80D — Self & Family'), ('80d_parents', 'Section 80D — Parents'), ('hra', 'HRA Exemption'), ('24b_home_loan_interest', 'Section 24(b) — Home Loan Interest'), ('80ccd_1b_nps', 'Section 80CCD(1B) — NPS'), ('lta', 'Leave Travel Allowance'), ('80e_education_loan', 'Section 80E — Education Loan Interest'), ('other_chapter_via', 'Other Chapter VI-A')], max_length=25)),
                ('declared_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Final amount used once proofs are checked — set by proof verification, never form-typed.', max_digits=12, null=True)),
                ('monthly_rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_metro_city', models.BooleanField(default=False, help_text='HRA: metro cities exempt up to 50% of basic, non-metro 40%.')),
                ('landlord_pan', models.CharField(blank=True, help_text='HRA: landlord PAN (mandatory when annual rent exceeds ₹1,00,000).', max_length=10)),
                ('lender_name', models.CharField(blank=True, help_text='Home-loan lender (Section 24b).', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrm.investmentdeclaration')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['declaration', 'section_code'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='hrm/investment_proofs/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text="The amount this proof substantiates (a line's verified_amount sums its verified proofs).", max_digits=12, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', editable=False, max_length=15)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('declaration_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='hrm.investmentdeclarationline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_verified_investment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('financial_year', models.CharField(help_text='Denormalized from the declaration for filtering.', max_length=10)),
                ('computation_type', models.CharField(choices=[('provisional', 'Provisional'), ('final', 'Final')], default='provisional', max_length=15)),
                ('manual_override_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the derived monthly TDS when set (edge cases the formula can't cover).", max_digits=12, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('remaining_pay_periods', models.PositiveSmallIntegerField(default=12, help_text='Pay periods left in the FY the projected tax is spread across.')),
                ('tax_payable', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('tax_paid_ytd', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('monthly_tds_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('computed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_computations', to='hrm.investmentdeclaration')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_computations', to='hrm.employeeprofile')),
                ('statutory_return', models.ForeignKey(blank=True, editable=False, help_text='The tds_form16 StatutoryReturn row this Part-B detail belongs to (set by link_form16).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_computations', to='hrm.statutoryreturn')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-financial_year', 'employee__party__name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRegimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(help_text='Indian FY, e.g. "2025-26".', max_length=10)),
                ('regime', models.CharField(choices=[('old', 'Old Regime'), ('new', 'New Regime')], default='new', max_length=10)),
                ('standard_deduction', models.DecimalField(decimal_places=2, default=Decimal('75000.00'), help_text='Flat salary deduction (new-regime default ₹75,000; old-regime ₹50,000).', max_digits=12)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Health & Education Cess applied on the computed tax (both regimes).', max_digits=5)),
                ('rebate_income_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Section 87A: taxable-income ceiling at/below which the rebate applies.', max_digits=12, null=True)),
                ('rebate_max_tax', models.DecimalField(blank=True, decimal_places=2, help_text='Section 87A: the maximum tax the rebate can zero out.', max_digits=12, null=True)),
                ('is_default_regime', models.BooleanField(default=False, help_text="The statutory default regime (new, since FY 2023-24) — drives a declaration's default election.")),
                ('tax_law_reference', models.CharField(blank=True, help_text='Free-text note (e.g. Finance Act / Income Tax Act 2025 renumbering caveat).', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-financial_year', 'regime'],
            },
        ),
        migrations.CreateModel(
            name='TaxSlabBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_to', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for the top (unbounded) band.', max_digits=12, null=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slab_bands', to='hrm.taxregimeconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['config', 'sequence', 'income_from'],
            },
        ),
        migrations.AddIndex(
            model_name='investmentdeclaration',
            index=models.Index(fields=['tenant', 'financial_year'], name='hrm_itd_tenant_fy_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentdeclaration',
            index=models.Index(fields=['tenant', 'status'], name='hrm_itd_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentdeclaration',
            unique_together={('tenant', 'employee', 'financial_year')},
        ),
        migrations.AddIndex(
            model_name='investmentdeclarationline',
            index=models.Index(fields=['tenant', 'declaration'], name='hrm_idl_tenant_decl_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentdeclarationline',
            unique_together={('tenant', 'declaration', 'section_code')},
        ),
        migrations.AddIndex(
            model_name='investmentproof',
            index=models.Index(fields=['tenant', 'declaration_line'], name='hrm_ivp_tenant_line_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentproof',
            index=models.Index(fields=['tenant', 'verification_status'], name='hrm_ivp_tenant_vstat_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcomputation',
            index=models.Index(fields=['tenant', 'financial_year'], name='hrm_txc_tenant_fy_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcomputation',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_txc_tenant_emp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxcomputation',
            unique_together={('tenant', 'employee', 'financial_year')},
        ),
        migrations.AddIndex(
            model_name='taxregimeconfig',
            index=models.Index(fields=['tenant', 'financial_year'], name='hrm_trc_tenant_fy_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxregimeconfig',
            unique_together={('tenant', 'financial_year', 'regime')},
        ),
        migrations.AddIndex(
            model_name='taxslabband',
            index=models.Index(fields=['tenant', 'config'], name='hrm_tsb_tenant_config_idx'),
        ),
    ]
