# Generated by Django 5.1.15 on 2026-07-05 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0027_investmentdeclaration_investmentdeclarationline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('partially_disbursed', 'Partially Disbursed'), ('reconciled', 'Reconciled')], default='draft', max_length=20)),
                ('bank_file_format', models.CharField(choices=[('neft', 'NEFT'), ('nach', 'NACH'), ('ach', 'ACH'), ('manual', 'Manual'), ('other', 'Other')], default='neft', max_length=15)),
                ('source_bank_name', models.CharField(blank=True, help_text='The disbursing (company) bank surfaced before initiating payment.', max_length=255)),
                ('source_account_last4', models.CharField(blank=True, help_text='Masked disbursing account — never the full number.', max_length=8)),
                ('generated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_payout_batch_approvals', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches', to='hrm.payrollcycle')),
                ('generated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_payout_batch_generations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-cycle__pay_date'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('statement_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('reconciled', 'Reconciled'), ('discrepancy', 'Discrepancy')], default='pending', max_length=15)),
                ('matched_count', models.PositiveIntegerField(default=0, editable=False)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('unmatched_count', models.PositiveIntegerField(default=0, editable=False)),
                ('unmatched_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('statement_reference', models.CharField(blank=True, max_length=100)),
                ('reconciled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_bank_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='hrm.payoutbatch')),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='PayoutPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Snapshot of Payslip.net_pay at generation time.', max_digits=14)),
                ('bank_name_snapshot', models.CharField(blank=True, editable=False, max_length=255)),
                ('bank_account_last4_snapshot', models.CharField(blank=True, editable=False, help_text='Masked last-4 of the destination account — never the full number.', max_length=8)),
                ('bank_routing_snapshot', models.CharField(blank=True, editable=False, max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('neft', 'NEFT'), ('nach', 'NACH'), ('ach', 'ACH'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('returned', 'Returned'), ('on_hold', 'On Hold')], default='pending', max_length=15)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank-assigned UTR / trace number — the reconciliation match key.', max_length=64)),
                ('initiated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('paid_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hrm.payoutbatch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_payments', to='hrm.employeeprofile')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_payments', to='hrm.payslip')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='hrm.payoutpayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['batch', 'employee__party__name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email'), ('portal', 'Portal'), ('print', 'Print')], default='portal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('sent_to_email', models.EmailField(blank=True, editable=False, help_text="Snapshot of the employee's email at send time.", max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('payslip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='hrm.payslip')),
                ('sent_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_payslip_distribution_sends', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-payslip__cycle__pay_date'],
            },
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['tenant', 'status'], name='hrm_pob_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payoutbatch',
            unique_together={('tenant', 'cycle')},
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['tenant', 'batch'], name='hrm_brc_tenant_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['tenant', 'status'], name='hrm_brc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutpayment',
            index=models.Index(fields=['tenant', 'batch'], name='hrm_pop_tenant_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutpayment',
            index=models.Index(fields=['tenant', 'status'], name='hrm_pop_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipdistribution',
            index=models.Index(fields=['tenant', 'status'], name='hrm_psd_tenant_status_idx'),
        ),
    ]
