# Generated by Django 5.1.15 on 2026-07-05 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0028_payoutbatch_bankreconciliation_payoutpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutbatch',
            name='source_account_last4',
            field=models.CharField(blank=True, help_text='Masked disbursing account — never the full number.', max_length=8, validators=[django.core.validators.RegexValidator('^(••••)?\\d{0,4}$', 'Enter only a masked last-4 (e.g. ••••4321), never the full account number.')]),
        ),
    ]
