# Generated by Django 5.1.15 on 2026-07-05 11:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0029_alter_payoutbatch_source_account_last4'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Q3 2026".', max_length=100)),
                ('period_type', models.CharField(choices=[('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual'), ('custom', 'Custom')], default='quarterly', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('metric_type', models.CharField(choices=[('numeric', 'Numeric'), ('percentage', 'Percentage'), ('currency', 'Currency'), ('boolean', 'Boolean'), ('milestone', 'Milestone')], default='numeric', max_length=15)),
                ('start_value', models.DecimalField(blank=True, decimal_places=2, help_text='Baseline value (nullable for boolean/milestone KRs).', max_digits=16, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Advanced by GoalCheckIn.save(); also directly editable on the KR form.', max_digits=16, null=True)),
                ('is_milestone_event', models.BooleanField(default=False, help_text='For milestone-type KRs: progress is driven by discrete check-in milestone events rather than a continuous value.')),
                ('unit', models.CharField(blank=True, help_text='Free text, e.g. "%", "$", "signups".', max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight among sibling KeyResults under the same Objective (equal-split by default, overridable).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=15)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['objective', '-weight', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GoalCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('checkin_date', models.DateField(default=django.utils.timezone.localdate)),
                ('value_at_checkin', models.DecimalField(blank=True, decimal_places=2, help_text='The KR value reported at this check-in (advances current_value).', max_digits=16, null=True)),
                ('confidence', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track')], default='on_track', help_text='Self-reported at check-in time (distinct from the derived KR health_status).', max_length=15)),
                ('is_milestone_event', models.BooleanField(default=False, help_text='Marks a discrete milestone-completion event (milestone-type KRs).')),
                ('comment', models.TextField(blank=True, help_text='Blockers / wins note.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Resolved from request.user in the view (allows manager overrides).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_checkins', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='hrm.keyresult')),
            ],
            options={
                'ordering': ['-checkin_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('company', 'Company'), ('department', 'Department'), ('team', 'Team'), ('individual', 'Individual')], default='individual', max_length=15)),
                ('target_type', models.CharField(choices=[('aspirational', 'Aspirational'), ('committed', 'Committed')], default='committed', help_text='Aspirational (50–70% is a win) vs. committed (100% expected).', max_length=15)),
                ('weight', models.DecimalField(decimal_places=2, default=100, help_text="Relative weight among SIBLING objectives under the same parent (for a parent's weighted-children view). NOT used to compute this objective's own progress_pct — that is strictly a KR-weighted rollup.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('at_risk', 'At Risk'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('start_date', models.DateField(blank=True, help_text="Defaults to the period's start; stored so an objective can start later.", null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department/team scope (a core.OrgUnit); blank for individual goals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='core.orgunit')),
                ('goal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectives', to='hrm.goalperiod')),
                ('owner', models.ForeignKey(help_text='The goal owner (an EmployeeProfile — never a raw Party/User).', on_delete=django.db.models.deletion.PROTECT, related_name='objectives', to='hrm.employeeprofile')),
                ('parent_objective', models.ForeignKey(blank=True, help_text='Aligns (rolls up into) a parent objective — the cascade link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_objectives', to='hrm.objective')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-goal_period__start_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='hrm.objective'),
        ),
        migrations.AddIndex(
            model_name='goalperiod',
            index=models.Index(fields=['tenant', 'status'], name='hrm_gp_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goalperiod',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='goalcheckin',
            index=models.Index(fields=['tenant', 'key_result'], name='hrm_gci_tenant_kr_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcheckin',
            index=models.Index(fields=['tenant', 'checkin_date'], name='hrm_gci_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['tenant', 'status'], name='hrm_obj_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['tenant', 'goal_period'], name='hrm_obj_tenant_period_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['tenant', 'owner'], name='hrm_obj_tenant_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['tenant', 'parent_objective'], name='hrm_obj_tenant_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='keyresult',
            index=models.Index(fields=['tenant', 'objective'], name='hrm_kr_tenant_objective_idx'),
        ),
        migrations.AddIndex(
            model_name='keyresult',
            index=models.Index(fields=['tenant', 'status'], name='hrm_kr_tenant_status_idx'),
        ),
    ]
