# Generated by Django 5.1.15 on 2026-07-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0030_goalperiod_keyresult_goalcheckin_objective_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalcheckin',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='keyresult',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='objective',
            unique_together={('tenant', 'number')},
        ),
    ]
