# Generated by Django 5.1.15 on 2026-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0031_alter_goalcheckin_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['tenant', 'department'], name='hrm_obj_tenant_department_idx'),
        ),
    ]
