# Generated by Django 5.1.15 on 2026-07-05 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0032_objective_hrm_obj_tenant_department_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "H1 2026 Performance Review".', max_length=100)),
                ('cycle_type', models.CharField(choices=[('annual', 'Annual'), ('half_yearly', 'Half-Yearly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='annual', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('self_assessment', 'Self-Assessment'), ('manager_review', 'Manager Review'), ('calibration', 'Calibration'), ('released', 'Results Released'), ('closed', 'Closed')], default='draft', help_text='Phase machine — gates which review actions are open. Advanced via the workflow action.', max_length=20)),
                ('self_review_start', models.DateField(blank=True, null=True)),
                ('self_review_end', models.DateField(blank=True, null=True)),
                ('manager_review_start', models.DateField(blank=True, null=True)),
                ('manager_review_end', models.DateField(blank=True, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('results_release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('goal_period', models.ForeignKey(blank=True, help_text='Aligns the review to a 3.18 OKR cycle (the goal-review section reads its Objectives).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_cycles', to='hrm.goalperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-self_review_start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('review_type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('peer', 'Peer'), ('upward', 'Upward'), ('skip_level', 'Skip-Level')], default='self', help_text='Denormalized from the template at creation for query convenience.', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('shared', 'Shared'), ('acknowledged', 'Acknowledged')], default='draft', max_length=15)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=2, help_text='As-submitted pre-calibration snapshot (manager reviews).', max_digits=4, null=True)),
                ('calibrated_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Post-calibration override; downstream comp/promotion reads this.', max_digits=4, null=True)),
                ('potential_rating', models.DecimalField(blank=True, decimal_places=2, help_text='9-box potential axis (visualization deferred).', max_digits=4, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True, help_text='Manager-only — NEVER rendered on the subject-facing view.')),
                ('calibration_notes', models.TextField(blank=True, help_text='Calibration adjustment rationale.')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Masks the reviewer on the subject-facing view (peer/upward).')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('shared_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_acknowledged', to='hrm.employeeprofile')),
                ('reviewer', models.ForeignKey(help_text='Who fills this instance (== subject for a self review).', on_delete=django.db.models.deletion.PROTECT, related_name='reviews_authored', to='hrm.employeeprofile')),
                ('subject', models.ForeignKey(help_text='The employee being reviewed.', on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='hrm.reviewcycle')),
            ],
            options={
                'ordering': ['-cycle__self_review_start', 'subject__party__name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('criterion_label', models.CharField(help_text='The competency/question text.', max_length=255)),
                ('criterion_category', models.CharField(choices=[('competency', 'Competency'), ('goal', 'Goal'), ('value', 'Company Value'), ('custom', 'Custom')], default='competency', max_length=15)),
                ('rating_value', models.DecimalField(decimal_places=2, help_text="Per-criterion score (within the template's rating scale).", max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight among sibling ratings under the same review (equal-split by default).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hrm.performancereview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['review', '-weight', 'criterion_label'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('review_type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('peer', 'Peer'), ('upward', 'Upward'), ('skip_level', 'Skip-Level')], default='self', max_length=15)),
                ('rating_scale_max', models.PositiveSmallIntegerField(default=5, help_text='Top of the rating scale (5-point is the de-facto standard).', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('include_goals', models.BooleanField(default=False, help_text="Pull the subject's 3.18 Objectives into a goal-review section.")),
                ('is_anonymous', models.BooleanField(default=False, help_text='Default anonymity (peer/360 commonly True); overridable per review.')),
                ('description', models.TextField(blank=True, help_text='Instructions shown to the reviewer.')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['review_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='performancereview',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='hrm.reviewtemplate'),
        ),
        migrations.AddIndex(
            model_name='reviewcycle',
            index=models.Index(fields=['tenant', 'status'], name='hrm_rc_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewcycle',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='reviewrating',
            index=models.Index(fields=['tenant', 'review'], name='hrm_rvr_tenant_review_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='reviewtemplate',
            index=models.Index(fields=['tenant', 'review_type'], name='hrm_rvt_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_rvt_tenant_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewtemplate',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['tenant', 'cycle'], name='hrm_rvw_tenant_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['tenant', 'subject'], name='hrm_rvw_tenant_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['tenant', 'reviewer'], name='hrm_rvw_tenant_reviewer_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['tenant', 'review_type'], name='hrm_rvw_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['tenant', 'status'], name='hrm_rvw_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('tenant', 'number')},
        ),
    ]
