# Generated by Django 5.1.15 on 2026-07-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0033_reviewcycle_performancereview_reviewrating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KudosBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name for the UI chip.', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex or Tailwind class for the chip.', max_length=20)),
                ('linked_value', models.CharField(blank=True, help_text="Free-text company value this badge celebrates (e.g. 'Customer First').", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('feedback_type', models.CharField(choices=[('kudos', 'Kudos'), ('appreciation', 'Appreciation'), ('constructive', 'Constructive'), ('request', 'Feedback Request')], default='kudos', max_length=15)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public')], default='private', help_text="private = giver/receiver/admin; team = receiver's org unit; public = the feed.", max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('given', 'Given'), ('acknowledged', 'Acknowledged')], default='given', help_text="A plain kudos is born 'given'; a pull request is born 'requested'.", max_length=15)),
                ('message', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Masks the giver on the receiver-facing view (admins still see it).')),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('giver', models.ForeignKey(blank=True, help_text='Who gave the feedback (masked on read when is_anonymous).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_given', to='hrm.employeeprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_received', to='hrm.employeeprofile')),
                ('related_objective', models.ForeignKey(blank=True, help_text='Optional 3.18 goal this feedback is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='hrm.objective')),
                ('related_review', models.ForeignKey(blank=True, help_text='Optional 3.19 review this feedback is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='hrm.performancereview')),
                ('requested_from', models.ForeignKey(blank=True, help_text="On a response row, points back at the 'requested' ask it answers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_responses', to='hrm.feedback')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='hrm.kudosbadge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneOnOneMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('agenda', models.TextField(blank=True, help_text='Shared talking points — editable by either party pre-meeting.')),
                ('shared_notes', models.TextField(blank=True, help_text='Visible to both the manager and the employee.')),
                ('manager_private_notes', models.TextField(blank=True, help_text='Manager-only — NEVER rendered on the employee-facing view.')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oneonones_as_employee', to='hrm.employeeprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oneonones_as_manager', to='hrm.employeeprofile')),
                ('related_objective', models.ForeignKey(blank=True, help_text='Optional 3.18 goal this 1:1 is anchored to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oneonones', to='hrm.objective')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_action_items', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='hrm.oneononemeeting')),
            ],
            options={
                'ordering': ['meeting', 'due_date', 'description'],
            },
        ),
        migrations.AddIndex(
            model_name='kudosbadge',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_kb_tenant_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kudosbadge',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tenant', 'receiver'], name='hrm_fbk_tenant_recv_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tenant', 'giver'], name='hrm_fbk_tenant_giver_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tenant', 'feedback_type'], name='hrm_fbk_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tenant', 'visibility'], name='hrm_fbk_tenant_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tenant', 'status'], name='hrm_fbk_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='oneononemeeting',
            index=models.Index(fields=['tenant', 'manager'], name='hrm_o2o_tenant_mgr_idx'),
        ),
        migrations.AddIndex(
            model_name='oneononemeeting',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_o2o_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='oneononemeeting',
            index=models.Index(fields=['tenant', 'status'], name='hrm_o2o_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='oneononemeeting',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='hrm_o2o_tenant_sched_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oneononemeeting',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['tenant', 'meeting'], name='hrm_mai_tenant_meeting_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['tenant', 'owner'], name='hrm_mai_tenant_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['tenant', 'status'], name='hrm_mai_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingactionitem',
            unique_together={('tenant', 'number')},
        ),
    ]
