# Generated by Django 5.1.15 on 2026-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0034_kudosbadge_feedback_oneononemeeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('given', 'Given'), ('acknowledged', 'Acknowledged'), ('responded', 'Responded')], default='given', help_text="A plain kudos is born 'given'; a pull request is born 'requested' and becomes 'responded' once answered.", max_length=15),
        ),
    ]
