# Generated by Django 5.1.15 on 2026-07-06 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0035_alter_feedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_hr_approval', 'Pending HR Approval'), ('active', 'Active'), ('closed', 'Closed')], default='draft', help_text='Workflow — HR approves a draft before it goes active; changed only via the workflow actions.', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('successful', 'Successful'), ('extended', 'Extended'), ('failed', 'Failed'), ('terminated', 'Terminated')], help_text='Set only when the plan is closed (via the close action), never on the form.', max_length=15)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('performance_issue', models.TextField(help_text='The specific performance gap (corrective, not vague criticism).')),
                ('expected_standards', models.TextField()),
                ('improvement_goals', models.TextField(help_text='The SMART expectations the employee must meet.')),
                ('support_provided', models.TextField(blank=True, help_text='Training/coaching/resources the org commits to.')),
                ('measurement_criteria', models.TextField(help_text='How success is judged.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('extended_end_date', models.DateField(blank=True, help_text='Set by the extend action.', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips_acknowledged', to='hrm.employeeprofile')),
                ('hr_approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips_hr_approved', to='hrm.employeeprofile')),
                ('manager', models.ForeignKey(help_text='Who owns/drives the plan (stored explicitly — may differ from the reporting line if escalated).', on_delete=django.db.models.deletion.PROTECT, related_name='pips_as_manager', to='hrm.employeeprofile')),
                ('subject', models.ForeignKey(help_text='The employee on the plan.', on_delete=django.db.models.deletion.PROTECT, related_name='pips_as_subject', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('triggering_review', models.ForeignKey(blank=True, help_text='Optional 3.19 review that prompted this plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_pips', to='hrm.performancereview')),
            ],
            options={
                'ordering': ['-start_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CoachingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('note_date', models.DateField(default=django.utils.timezone.localdate, help_text='When the coaching moment happened.')),
                ('category', models.CharField(choices=[('skill_development', 'Skill Development'), ('behavior', 'Behavior'), ('career_growth', 'Career Growth'), ('other', 'Other')], default='other', max_length=20)),
                ('content', models.TextField()),
                ('coach', models.ForeignKey(help_text='The author (manager/HRBP). Resolved server-side, not form-typed.', on_delete=django.db.models.deletion.PROTECT, related_name='coaching_notes_authored', to='hrm.employeeprofile')),
                ('employee', models.ForeignKey(help_text='The coached employee (who must NEVER see this note).', on_delete=django.db.models.deletion.PROTECT, related_name='coaching_notes_about', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('related_pip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_notes', to='hrm.performanceimprovementplan')),
            ],
            options={
                'ordering': ['-note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIPCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('checkin_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('progress_rating', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track')], default='on_track', max_length=10)),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='hrm.performanceimprovementplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['pip', 'checkin_date'],
            },
        ),
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('level', models.CharField(choices=[('verbal', 'Verbal Warning'), ('written', 'Written Warning'), ('final', 'Final Written Warning'), ('suspension', 'Suspension')], default='verbal', max_length=15)),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('conduct', 'Conduct'), ('performance', 'Performance'), ('policy_violation', 'Policy Violation')], default='conduct', max_length=20)),
                ('incident_date', models.DateField()),
                ('description', models.TextField(help_text='Specific behaviours/actions (not vague criticism).')),
                ('policy_reference', models.CharField(blank=True, help_text='Which policy/handbook section was violated.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('expired', 'Expired')], default='draft', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('employee_response', models.TextField(blank=True, help_text="The recipient's optional written response/rebuttal.")),
                ('expiry_date', models.DateField(blank=True, help_text='When this warning goes stale (per company policy).', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings_acknowledged', to='hrm.employeeprofile')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings_issued', to='hrm.employeeprofile')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings_received', to='hrm.employeeprofile')),
                ('related_pip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_letters', to='hrm.performanceimprovementplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-incident_date', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='performanceimprovementplan',
            index=models.Index(fields=['tenant', 'status'], name='hrm_pip_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceimprovementplan',
            index=models.Index(fields=['tenant', 'subject'], name='hrm_pip_tenant_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceimprovementplan',
            index=models.Index(fields=['tenant', 'manager'], name='hrm_pip_tenant_manager_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceimprovementplan',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='coachingnote',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_cn_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingnote',
            index=models.Index(fields=['tenant', 'coach'], name='hrm_cn_tenant_coach_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coachingnote',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='pipcheckin',
            index=models.Index(fields=['tenant', 'pip'], name='hrm_pci_tenant_pip_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipcheckin',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='warningletter',
            index=models.Index(fields=['tenant', 'issued_to'], name='hrm_wrn_tenant_to_idx'),
        ),
        migrations.AddIndex(
            model_name='warningletter',
            index=models.Index(fields=['tenant', 'level'], name='hrm_wrn_tenant_level_idx'),
        ),
        migrations.AddIndex(
            model_name='warningletter',
            index=models.Index(fields=['tenant', 'status'], name='hrm_wrn_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warningletter',
            unique_together={('tenant', 'number')},
        ),
    ]
