# Generated by Django 5.1.15 on 2026-07-07 19:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0036_performanceimprovementplan_coachingnote_pipcheckin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('compliance', 'Compliance'), ('leadership', 'Leadership'), ('soft_skills', 'Soft Skills'), ('safety', 'Safety'), ('onboarding', 'Onboarding'), ('product', 'Product'), ('other', 'Other')], default='technical', max_length=20)),
                ('delivery_mode', models.CharField(choices=[('classroom', 'Classroom'), ('virtual', 'Virtual'), ('external', 'External'), ('blended', 'Blended')], default='classroom', help_text="The course's typical mode; each session sets its own actual mode.", max_length=15)),
                ('provider_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', help_text='Run in-house (internal) or sourced from an external provider.', max_length=10)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_certification', models.BooleanField(default=False, help_text='This course grants (or represents) a certification.')),
                ('certification_name', models.CharField(blank=True, max_length=255)),
                ('certification_validity_months', models.PositiveIntegerField(blank=True, help_text='How long the certification stays valid.', null=True)),
                ('default_capacity', models.PositiveIntegerField(blank=True, help_text='Default seat limit new sessions inherit.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prerequisite_course', models.ForeignKey(blank=True, help_text='A course that must be completed first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='hrm.trainingcourse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('delivery_mode', models.CharField(choices=[('classroom', 'Classroom'), ('virtual', 'Virtual'), ('external', 'External')], default='classroom', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=15)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', help_text='IANA/display timezone the times are quoted in.', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('waitlist_enabled', models.BooleanField(default=False, help_text='Allow a waitlist once full (the queue itself is 3.24 Nomination).')),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('meeting_platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('webex', 'Webex'), ('google_meet', 'Google Meet'), ('gotomeeting', 'GoToMeeting'), ('other', 'Other')], max_length=15)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('external_instructor_name', models.CharField(blank=True, max_length=255)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(help_text='The catalog course this session delivers.', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='hrm.trainingcourse')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='accounting.currency')),
                ('external_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions_as_vendor', to='core.party')),
                ('instructor_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions_instructed', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_datetime', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['tenant', 'category'], name='hrm_trc_tenant_category_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_trc_tenant_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingcourse',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'status'], name='hrm_trs_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'course'], name='hrm_trs_tenant_course_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'delivery_mode'], name='hrm_trs_tenant_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'start_datetime'], name='hrm_trs_tenant_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together={('tenant', 'number')},
        ),
    ]
