# Generated by Django 5.1.15 on 2026-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0037_trainingcourse_trainingsession_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['tenant', 'delivery_mode'], name='hrm_trc_tenant_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'instructor_employee'], name='hrm_trs_tenant_instr_idx'),
        ),
    ]
