# Generated by Django 5.1.15 on 2026-07-08 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0038_trainingcourse_hrm_trc_tenant_mode_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Compliance path (vs. optional development).')),
                ('is_active', models.BooleanField(default=True)),
                ('target_department', models.ForeignKey(blank=True, help_text='Department this path is aimed at (optional).', limit_choices_to={'kind': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='core.orgunit')),
                ('target_designation', models.ForeignKey(blank=True, help_text='Role this path is aimed at (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='hrm.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Ordered completion position in the path.')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='path_items', to='hrm.trainingcourse')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hrm.learningpath')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['path', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='not_started', max_length=15)),
                ('percent_complete', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Gamification points (leaderboard is derived).')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_progress', to='hrm.trainingcourse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='hrm.employeeprofile')),
                ('learning_path', models.ForeignKey(blank=True, help_text='Enrolled via this path (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='hrm.learningpath')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('scorm', 'SCORM Package'), ('external_link', 'External Link'), ('text', 'Text / Article'), ('assessment', 'Assessment')], default='video', max_length=15)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Ordered lesson position within the course.')),
                ('is_required', models.BooleanField(default=True, help_text='Required for course completion (vs. supplemental).')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True)),
                ('document_file', models.FileField(blank=True, upload_to='hrm/lms/documents/%Y/%m/')),
                ('scorm_package', models.FileField(blank=True, upload_to='hrm/lms/scorm/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('pass_threshold_percent', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_attempts', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='hrm.trainingcourse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['course', 'sequence'],
                'indexes': [models.Index(fields=['tenant', 'course'], name='hrm_lci_tenant_course_idx'), models.Index(fields=['tenant', 'content_type'], name='hrm_lci_tenant_ctype_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_lnp_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['tenant', 'is_mandatory'], name='hrm_lnp_tenant_mand_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='learningpathitem',
            index=models.Index(fields=['tenant', 'path'], name='hrm_lpi_tenant_path_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathitem',
            index=models.Index(fields=['tenant', 'course'], name='hrm_lpi_tenant_course_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathitem',
            unique_together={('tenant', 'path', 'course')},
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_lprog_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['tenant', 'course'], name='hrm_lprog_tenant_course_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['tenant', 'status'], name='hrm_lprog_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('tenant', 'employee', 'course')},
        ),
    ]
