# Generated by Django 5.1.15 on 2026-07-09 18:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0039_learningpath_learningpathitem_learningprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('nomination_type', models.CharField(choices=[('self', 'Self-Nominated'), ('manager', 'Manager-Nominated'), ('hr', 'HR-Assigned')], default='self', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], default='pending', help_text='Workflow — set by the approve/reject/waitlist/cancel/withdraw actions.', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True, help_text='Why this nomination (free text).')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('approver', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_approved', to='hrm.employeeprofile')),
                ('employee', models.ForeignKey(help_text='The nominee.', on_delete=django.db.models.deletion.PROTECT, related_name='training_nominations', to='hrm.employeeprofile')),
                ('nominated_by', models.ForeignKey(blank=True, help_text='Who nominated (null = self).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_made', to='hrm.employeeprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='hrm.trainingsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('present', 'Present'), ('absent', 'Absent'), ('partial', 'Partial'), ('walk_in', 'Walk-in')], default='registered', max_length=10)),
                ('completion_status', models.CharField(choices=[('not_completed', 'Not Completed'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_completed', max_length=15)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_attendance', to='hrm.employeeprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='hrm.trainingsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('nomination', models.ForeignKey(blank=True, help_text='Links back when nominated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hrm.trainingnomination')),
            ],
            options={
                'ordering': ['-session__start_datetime', 'employee__party__name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(blank=True, help_text="Defaults from the course's certification name.", max_length=255)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, editable=False, help_text="Computed once from issued_on + the course's validity months.", null=True)),
                ('verification_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='issued', max_length=10)),
                ('revoked_reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='hrm.trainingcourse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_certificates', to='hrm.employeeprofile')),
                ('source_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to='hrm.trainingattendance')),
                ('source_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to='hrm.learningprogress')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-issued_on'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_cert_tenant_emp_idx'), models.Index(fields=['tenant', 'course'], name='hrm_cert_tenant_course_idx'), models.Index(fields=['tenant', 'status'], name='hrm_cert_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TrainingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('trainer_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text="Hide the attendee's identity on read (non-admins).")),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='hrm.trainingattendance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'attendance')},
            },
        ),
        migrations.AddIndex(
            model_name='trainingnomination',
            index=models.Index(fields=['tenant', 'session'], name='hrm_nom_tenant_session_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingnomination',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_nom_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingnomination',
            index=models.Index(fields=['tenant', 'status'], name='hrm_nom_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingnomination',
            unique_together={('tenant', 'session', 'employee')},
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['tenant', 'session'], name='hrm_tatt_tenant_session_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_tatt_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['tenant', 'attendance_status'], name='hrm_tatt_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together={('tenant', 'session', 'employee')},
        ),
    ]
