# Generated by Django 5.1.15 on 2026-07-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0040_trainingnomination_trainingattendance_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['tenant', 'completion_status'], name='hrm_tatt_tenant_comp_idx'),
        ),
    ]
