# Generated by Django 5.1.15 on 2026-07-11 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0041_trainingattendance_hrm_tatt_tenant_comp_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, help_text='e.g. Spouse, Parent, Sibling, Friend.', max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('alt_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Which contact to call first.')),
                ('priority_order', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['employee', 'priority_order', '-is_primary'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_ec_tenant_emp_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=64)),
                ('routing_number', models.CharField(blank=True, help_text='IFSC / ABA / sort code.', max_length=20)),
                ('account_type', models.CharField(choices=[('checking', 'Checking / Current'), ('savings', 'Savings'), ('other', 'Other')], default='checking', max_length=10)),
                ('is_salary_account', models.BooleanField(default=False, help_text='The account salary is paid into (one per employee).')),
                ('split_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Split-deposit intent (Gusto-style); stored only, not wired to payroll disbursement yet.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', editable=False, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['employee', '-is_salary_account', 'bank_name'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_eba_tenant_emp_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfoChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('profile_field', 'Profile Field'), ('bank', 'Bank Account'), ('family', 'Family Member')], default='profile_field', max_length=15)),
                ('field_changes', models.JSONField(default=dict, help_text='{"field": {"old": ..., "new": ...}, ...}')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', editable=False, max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_change_requests', to='hrm.employeeprofile')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_icr_tenant_emp_idx'), models.Index(fields=['tenant', 'status'], name='hrm_icr_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('other', 'Other')], default='spouse', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_dependent', models.BooleanField(default=False, help_text='Eligible dependent for benefits/insurance.')),
                ('is_minor', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100)),
                ('is_nominee', models.BooleanField(default=False)),
                ('nominee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['employee', 'name'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_fam_tenant_emp_idx')],
            },
        ),
    ]
