# Generated by Django 5.1.15 on 2026-07-11 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0042_emergencycontact_employeebankaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('asset_category', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('phone', 'Phone'), ('id_card', 'ID Card'), ('access_card', 'Access Card'), ('uniform', 'Uniform'), ('vehicle', 'Vehicle'), ('sim', 'SIM Card'), ('other', 'Other')], default='other', max_length=30)),
                ('asset_name', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('allocation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='hrm.assetallocation')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_assetrequest_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_astreq_tenant_emp_idx'), models.Index(fields=['tenant', 'status'], name='hrm_astreq_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('document_type', models.CharField(choices=[('experience_letter', 'Experience Letter'), ('salary_certificate', 'Salary Certificate'), ('address_proof', 'Address Proof'), ('employment_verification', 'Employment Verification'), ('noc', 'No-Objection Certificate'), ('relieving_letter_copy', 'Relieving Letter Copy'), ('other', 'Other')], default='experience_letter', max_length=30)),
                ('purpose', models.TextField(help_text='Why the document is needed (e.g. visa, bank loan, higher education).')),
                ('addressed_to', models.CharField(blank=True, help_text='e.g. "To Whom It May Concern" or a named recipient.', max_length=255)),
                ('copies', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_method', models.CharField(choices=[('soft_copy', 'Soft Copy'), ('hard_copy', 'Hard Copy'), ('both', 'Both')], default='soft_copy', max_length=15)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('output_file', models.FileField(blank=True, upload_to='hrm/requests/documents/%Y/%m/')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_documentrequest_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_docreq_tenant_emp_idx'), models.Index(fields=['tenant', 'status'], name='hrm_docreq_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='IdCardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('request_type', models.CharField(choices=[('new', 'New'), ('replacement', 'Replacement'), ('correction', 'Correction'), ('renewal', 'Renewal')], default='new', max_length=15)),
                ('reason_type', models.CharField(choices=[('lost', 'Lost'), ('damaged', 'Damaged'), ('stolen', 'Stolen'), ('expired', 'Expired'), ('name_change', 'Name Change'), ('designation_change', 'Designation Change'), ('first_issue', 'First Issue'), ('other', 'Other')], default='first_issue', max_length=20)),
                ('reason', models.TextField()),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('card_number', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_idcardrequest_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcard_requests', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_idreq_tenant_emp_idx'), models.Index(fields=['tenant', 'status'], name='hrm_idreq_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
