# Generated by Django 5.1.15 on 2026-07-11 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0043_assetrequest_documentrequest_idcardrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetrequest',
            name='hrm_astreq_tenant_emp_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentrequest',
            name='hrm_docreq_tenant_emp_idx',
        ),
        migrations.RemoveIndex(
            model_name='idcardrequest',
            name='hrm_idreq_tenant_emp_idx',
        ),
        migrations.AddIndex(
            model_name='assetrequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_astreq_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_docreq_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardrequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_idreq_emp_status_idx'),
        ),
    ]
