# Generated by Django 5.1.15 on 2026-07-12 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0044_remove_assetrequest_hrm_astreq_tenant_emp_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list, help_text='List of {"text": str, "type": "rating"|"text"|"single_choice", "options": [...]}.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('opens_at', models.DateField(blank=True, null=True)),
                ('closes_at', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_survey_authored', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='hrm.employeeprofile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hrm.survey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('news', 'News'), ('policy', 'Policy'), ('event', 'Event'), ('it', 'IT'), ('hr', 'HR'), ('benefits', 'Benefits')], default='general', max_length=15)),
                ('audience_type', models.CharField(choices=[('all', 'All Employees'), ('department', 'A Department'), ('designation', 'A Designation')], default='all', max_length=15)),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_announcement_authored', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, limit_choices_to={'kind': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.orgunit')),
                ('target_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='hrm.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='hrm_ann_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('process', 'Process Improvement'), ('workplace', 'Workplace / Facilities'), ('product', 'Product / Service'), ('cost_saving', 'Cost Saving'), ('wellbeing', 'Wellbeing / Culture'), ('other', 'Other')], default='other', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('implemented', 'Implemented')], default='draft', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('implementation_note', models.TextField(blank=True)),
                ('implemented_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_suggestion_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'status'], name='hrm_sug_emp_status_idx'), models.Index(fields=['tenant', 'status'], name='hrm_sug_tenant_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['tenant', 'status'], name='hrm_survey_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['tenant', 'survey'], name='hrm_survresp_tenant_surv_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_survresp_tenant_emp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('survey', 'employee')},
        ),
    ]
