# Generated by Django 5.1.15 on 2026-07-12 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0045_survey_surveyresponse_announcement_suggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('layout', models.CharField(choices=[('one', 'Single column'), ('two', 'Two columns'), ('three', 'Three columns')], default='two', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_dashboards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HRDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('metric', models.CharField(choices=[('kpi_headcount', 'KPI - Active Headcount (#)'), ('kpi_attrition_rate', 'KPI - Attrition Rate (%, annualized)'), ('kpi_avg_tenure', 'KPI - Avg Tenure (yrs)'), ('kpi_gross_payroll', 'KPI - Payroll Cost ($)'), ('kpi_absenteeism_rate', 'KPI - Absenteeism Rate (%)'), ('kpi_open_reqs', 'KPI - Open Requisitions (#)'), ('kpi_pending_leave', 'KPI - Pending Leave Requests (#)'), ('kpi_gender_diversity', 'KPI - Gender Diversity (% female)'), ('kpi_avg_attrition_risk', 'KPI - Avg Attrition Risk Score (0-100)'), ('headcount_trend', 'Chart - Headcount Trend (12mo)'), ('attrition_by_department', 'Chart - Attrition by Department (#)'), ('gender_split', 'Chart - Gender Split (#)'), ('leave_by_type', 'Chart - Leave Days by Type'), ('hiring_funnel', 'Chart - Hiring Funnel (applications by stage)'), ('payroll_cost_by_department', 'Chart - Payroll Cost by Department ($)'), ('top_attrition_risk_employees', 'Table - Top Attrition-Risk Employees')], default='kpi_headcount', max_length=40)),
                ('chart_type', models.CharField(choices=[('kpi', 'KPI Card'), ('gauge', 'Gauge'), ('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('table', 'Table')], default='kpi', max_length=10)),
                ('date_range', models.CharField(choices=[('last_30', 'Last 30 days'), ('last_90', 'Last 90 days'), ('last_180', 'Last 180 days'), ('last_365', 'Last 12 months'), ('ytd', 'Year to date'), ('all', 'All time')], default='last_90', max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small (quarter width)'), ('medium', 'Medium (half width)'), ('large', 'Large (three-quarter width)'), ('full', 'Full width')], default='medium', max_length=10)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='hrm.hrdashboard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='hrdashboard',
            index=models.Index(fields=['tenant', 'owner'], name='hrm_hrdash_tnt_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdashboard',
            index=models.Index(fields=['tenant', 'is_shared'], name='hrm_hrdash_tnt_shared_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hrdashboard',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='hrdashboardwidget',
            index=models.Index(fields=['tenant', 'dashboard'], name='hrm_hrwidget_tnt_dash_idx'),
        ),
    ]
