# Generated by Django 5.1.15 on 2026-07-12 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0046_hrdashboard_hrdashboardwidget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='separationcase',
            index=models.Index(fields=['tenant', 'actual_last_working_day'], name='hrm_sep_tenant_lwd_idx'),
        ),
    ]
