# Generated by Django 5.1.15 on 2026-07-12 20:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0047_separationcase_hrm_sep_tenant_lwd_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('asset_tag', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('phone', 'Phone'), ('id_card', 'ID Card'), ('access_card', 'Access Card'), ('uniform', 'Uniform'), ('vehicle', 'Vehicle'), ('sim', 'SIM Card'), ('other', 'Other')], default='other', max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='in_stock', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('depreciation_method', models.CharField(choices=[('none', 'No Depreciation'), ('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance (20%/yr)')], default='none', max_length=20)),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_assets', to='accounting.currency')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_held', to='hrm.employeeprofile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_assets', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='hrm.asset'),
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('repair', 'Repair'), ('amc', 'AMC (Annual Maintenance Contract)'), ('warranty_claim', 'Warranty Claim'), ('inspection', 'Inspection')], default='preventive', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='hrm.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'status'], name='hrm_asset_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'category'], name='hrm_asset_tnt_category_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'current_holder'], name='hrm_asset_tnt_holder_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['tenant', 'asset'], name='hrm_astmnt_tnt_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['tenant', 'status'], name='hrm_astmnt_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetmaintenance',
            unique_together={('tenant', 'number')},
        ),
    ]
