# Generated by Django 5.1.15 on 2026-07-12 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0048_asset_assetallocation_asset_assetmaintenance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('per_claim_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max amount for a single expense line in this category. Blank = no limit.', max_digits=12, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max total per employee per month. Not enforced automatically this pass.', max_digits=12, null=True)),
                ('requires_receipt_above', models.DecimalField(blank=True, decimal_places=2, help_text='A line above this amount must have a receipt attached. Blank = never required.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gl_account_hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_expense_category_hints', to='accounting.glaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True, help_text='Why this expense was incurred (trip name, project, etc).')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('approved', 'Approved (Finance)'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('payroll', 'Payroll'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_expense_claims', to='accounting.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='hrm.employeeprofile')),
                ('finance_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_expenseclaim_finance_approvals', to=settings.AUTH_USER_MODEL)),
                ('manager_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_expenseclaim_manager_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='hrm/expense_receipts/%Y/%m/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='hrm.expensecategory')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrm.expenseclaim')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['expense_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_expcat_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_expclaim_tnt_emp_st_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['tenant', 'status'], name='hrm_expclaim_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expenseclaim',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='expenseclaimline',
            index=models.Index(fields=['tenant', 'claim'], name='hrm_expline_tnt_claim_idx'),
        ),
    ]
