# Generated by Django 5.1.15 on 2026-07-13 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0049_expensecategory_expenseclaim_expenseclaimline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('trip_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International'), ('both', 'Both')], default='both', max_length=15)),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20)),
                ('daily_allowance_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Per-diem cap. A static number this pass — not an auto-calc engine.', max_digits=12, null=True)),
                ('hotel_limit_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_percent_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max advance as a percent of estimated cost, e.g. 80.00 = max 80%.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_grade', models.ForeignKey(blank=True, help_text='Blank = applies to all grades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_policies', to='hrm.jobgrade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('trip_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=15)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('advance_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_paid_at', models.DateTimeField(blank=True, null=True)),
                ('advance_reference', models.CharField(blank=True, max_length=100)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_travelrequest_approvals', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_travel_requests', to='accounting.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='hrm.employeeprofile')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_requests', to='hrm.travelpolicy')),
                ('settlement_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_settlements', to='hrm.expenseclaim')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('cab', 'Cab'), ('rail', 'Rail'), ('other', 'Other')], default='flight', max_length=10)),
                ('vendor', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, help_text='PNR / confirmation number.', max_length=100)),
                ('depart_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, help_text='Check-out / drop-off date.', null=True)),
                ('travel_class', models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First')], max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='hrm/travel_docs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hrm.travelrequest')),
            ],
            options={
                'ordering': ['depart_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='travelpolicy',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_travelpol_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='travelpolicy',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_travelreq_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['tenant', 'status'], name='hrm_travelreq_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='travelrequest',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='travelbooking',
            index=models.Index(fields=['tenant', 'travel_request'], name='hrm_travelbk_tnt_req_idx'),
        ),
    ]
