# Generated by Django 5.1.15 on 2026-07-13 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0050_travelpolicy_travelrequest_travelbooking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpdeskSLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('urgent_response_hours', models.PositiveIntegerField(default=1)),
                ('urgent_resolution_hours', models.PositiveIntegerField(default=4)),
                ('high_response_hours', models.PositiveIntegerField(default=4)),
                ('high_resolution_hours', models.PositiveIntegerField(default=24)),
                ('medium_response_hours', models.PositiveIntegerField(default=8)),
                ('medium_resolution_hours', models.PositiveIntegerField(default=48)),
                ('low_response_hours', models.PositiveIntegerField(default=24)),
                ('low_resolution_hours', models.PositiveIntegerField(default=96)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('hr', 'Human Resources'), ('it', 'IT'), ('admin', 'Administration'), ('facilities', 'Facilities'), ('finance', 'Finance'), ('other', 'Other')], default='hr', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_helpdesk_categories', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('default_sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='hrm.helpdeskslapolicy')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Requester'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=15)),
                ('first_response_due', models.DateTimeField(blank=True, null=True)),
                ('resolution_due', models.DateTimeField(blank=True, null=True)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('satisfaction_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('satisfaction_comment', models.TextField(blank=True)),
                ('satisfaction_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_helpdesk_assigned', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='hrm.helpdeskcategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_tickets', to='hrm.employeeprofile')),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='hrm.helpdeskslapolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords for search.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='hrm.helpdeskcategory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_kb_articles', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='helpdeskslapolicy',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_hsla_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskslapolicy',
            index=models.Index(fields=['tenant', 'is_default'], name='hrm_hsla_tnt_default_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helpdeskslapolicy',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='helpdeskcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_hdcat_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskcategory',
            index=models.Index(fields=['tenant', 'department'], name='hrm_hdcat_tnt_dept_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helpdeskcategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'status'], name='hrm_tkt_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_tkt_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'assignee'], name='hrm_tkt_tnt_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'category'], name='hrm_tkt_tnt_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helpdeskticket',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tenant', 'status'], name='hrm_kba_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tenant', 'category'], name='hrm_kba_tnt_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgearticle',
            unique_together={('tenant', 'number')},
        ),
    ]
