# Generated by Django 5.1.15 on 2026-07-13 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0051_helpdeskslapolicy_helpdeskcategory_helpdeskticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', '-created_at'], name='hrm_tkt_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'priority'], name='hrm_tkt_tnt_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'sla_policy'], name='hrm_tkt_tnt_slapolicy_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tenant', '-updated_at'], name='hrm_kba_tnt_updated_idx'),
        ),
    ]
