# Generated by Django 5.1.15 on 2026-07-13 19:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0052_helpdeskticket_hrm_tkt_tnt_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('plan_type', models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life Insurance'), ('disability', 'Disability'), ('retirement', 'Retirement / Pension'), ('wellness', 'Wellness'), ('other', 'Other')], default='medical', max_length=15)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('is_flex_credit_eligible', models.BooleanField(default=False)),
                ('flex_credit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flex-credit value this plan carries when flex-eligible.', max_digits=12, null=True)),
                ('employer_cost_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('employee_cost_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('coverage_tier_options', models.CharField(blank=True, default='employee_only', help_text='Comma-separated coverage tiers.', max_length=255)),
                ('enrollment_window_start', models.DateField(blank=True, null=True)),
                ('enrollment_window_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_benefit_plans', to='accounting.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['plan_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('election_choice', models.CharField(choices=[('opt_in', 'Opt In'), ('opt_out', 'Opt Out'), ('waived', 'Waived')], default='opt_in', max_length=10)),
                ('coverage_tier', models.CharField(blank=True, max_length=50)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('employee_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employer_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('waived', 'Waived'), ('terminated', 'Terminated')], default='pending', max_length=12)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_benefit_decisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='hrm.employeeprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='hrm.benefitplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('grant_type', models.CharField(choices=[('iso', 'ISO (Incentive Stock Option)'), ('nso', 'NSO (Non-qualified Stock Option)'), ('rsu', 'RSU (Restricted Stock Unit)'), ('espp', 'ESPP (Employee Stock Purchase Plan)'), ('phantom', 'Phantom Stock')], default='rsu', max_length=10)),
                ('grant_date', models.DateField()),
                ('shares_granted', models.PositiveIntegerField(default=0)),
                ('exercise_price', models.DecimalField(blank=True, decimal_places=4, help_text='Strike price per share (options); blank for RSUs.', max_digits=12, null=True)),
                ('fair_market_value_at_grant', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vesting_start_date', models.DateField()),
                ('cliff_months', models.PositiveSmallIntegerField(default=12)),
                ('vesting_duration_months', models.PositiveSmallIntegerField(default=48)),
                ('vesting_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('exercised_shares', models.PositiveIntegerField(default=0)),
                ('last_exercised_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fully_vested', 'Fully Vested'), ('exercised', 'Exercised'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_equity_grants', to='accounting.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-grant_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('internal', 'Internal Survey'), ('payscale', 'Payscale'), ('mercer', 'Mercer'), ('radford', 'Radford'), ('other', 'Other')], default='internal', max_length=20)),
                ('region', models.CharField(blank=True, help_text='e.g. US-National, APAC, EMEA.', max_length=100)),
                ('percentile_25', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percentile_50', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percentile_75', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percentile_90', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_salary_benchmarks', to='accounting.currency')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_benchmarks', to='hrm.designation')),
                ('job_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_benchmarks', to='hrm.jobgrade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-survey_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='benefitplan',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_bplan_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='benefitplan',
            index=models.Index(fields=['tenant', 'plan_type'], name='hrm_bplan_tnt_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='benefitplan',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='employeebenefitenrollment',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_ben_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebenefitenrollment',
            index=models.Index(fields=['tenant', 'status'], name='hrm_ben_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebenefitenrollment',
            index=models.Index(fields=['tenant', 'plan'], name='hrm_ben_tnt_plan_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeebenefitenrollment',
            unique_together={('tenant', 'employee', 'plan', 'effective_from'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='equitygrant',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_esop_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equitygrant',
            index=models.Index(fields=['tenant', 'status'], name='hrm_esop_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equitygrant',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='salarybenchmark',
            index=models.Index(fields=['tenant', 'job_grade'], name='hrm_sbm_tnt_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='salarybenchmark',
            index=models.Index(fields=['tenant', 'designation'], name='hrm_sbm_tnt_desig_idx'),
        ),
    ]
