# Generated by Django 5.1.15 on 2026-07-13 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0053_benefitplan_employeebenefitenrollment_equitygrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeebenefitenrollment',
            index=models.Index(fields=['tenant', '-created_at'], name='hrm_ben_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='equitygrant',
            index=models.Index(fields=['tenant', '-grant_date'], name='hrm_esop_tnt_grant_idx'),
        ),
    ]
