# Generated by Django 5.1.15 on 2026-07-14 20:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0054_employeebenefitenrollment_hrm_ben_tnt_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('vacancy_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('critical_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='succession_plans', to='hrm.designation')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_succession_plans', to='core.orgunit')),
                ('incumbent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_plans_held', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('readiness', models.CharField(choices=[('ready_now', 'Ready Now'), ('ready_1_2y', 'Ready in 1-2 Years'), ('ready_3_5y', 'Ready in 3-5 Years'), ('development_needed', 'Development Needed')], default='development_needed', max_length=20)),
                ('rank_order', models.PositiveSmallIntegerField(default=1)),
                ('development_notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_candidacies', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hrm.successionplan')),
            ],
            options={
                'ordering': ['rank_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('pool_type', models.CharField(choices=[('hipo', 'High Potential'), ('successor', 'Successor Bench'), ('critical_skill', 'Critical Skill'), ('leadership', 'Leadership Pipeline'), ('other', 'Other')], default='hipo', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_talent_pools', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['pool_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TalentPoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('promoted', 'Promoted')], default='active', max_length=10)),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the linked review's effective rating (1-5).", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('potential_rating', models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the linked review's potential rating (1-5).", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('flight_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('retention_action_plan', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_memberships', to='hrm.employeeprofile')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hrm.talentpool')),
                ('review', models.ForeignKey(blank=True, help_text='Source review for the 9-box ratings (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_memberships', to='hrm.performancereview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['tenant', 'status'], name='hrm_spl_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['tenant', 'vacancy_risk'], name='hrm_spl_tnt_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['tenant', 'critical_role'], name='hrm_spl_tnt_role_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='successionplan',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='successioncandidate',
            index=models.Index(fields=['tenant', 'plan'], name='hrm_sc_tnt_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='successioncandidate',
            index=models.Index(fields=['tenant', 'readiness'], name='hrm_sc_tnt_readiness_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='successioncandidate',
            unique_together={('tenant', 'plan', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='talentpool',
            index=models.Index(fields=['tenant', 'is_active'], name='hrm_tpool_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='talentpool',
            index=models.Index(fields=['tenant', 'pool_type'], name='hrm_tpool_tnt_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='talentpool',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='talentpoolmembership',
            index=models.Index(fields=['tenant', 'pool'], name='hrm_tpm_tnt_pool_idx'),
        ),
        migrations.AddIndex(
            model_name='talentpoolmembership',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_tpm_tnt_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='talentpoolmembership',
            index=models.Index(fields=['tenant', 'flight_risk'], name='hrm_tpm_tnt_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='talentpoolmembership',
            index=models.Index(fields=['tenant', 'status'], name='hrm_tpm_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='talentpoolmembership',
            unique_together={('tenant', 'pool', 'employee')},
        ),
    ]
