# Generated by Django 5.1.15 on 2026-07-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0055_successionplan_successioncandidate_talentpool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('code_of_conduct', 'Code of Conduct'), ('leave', 'Leave'), ('attendance', 'Attendance'), ('it_security', 'IT & Security'), ('harassment', 'Anti-Harassment'), ('health_safety', 'Health & Safety'), ('travel', 'Travel & Expense'), ('other', 'Other')], default='other', max_length=20)),
                ('version_number', models.CharField(default='1.0', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='hrm/policies/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('requires_acknowledgment', models.BooleanField(default=True)),
                ('applicable_org_unit', models.ForeignKey(blank=True, help_text='Blank = applies to the whole organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_policies', to='core.orgunit')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='hrm.hrpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Mask the complainant from everyone except HR admins.')),
                ('category', models.CharField(choices=[('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('safety', 'Workplace Safety'), ('compensation', 'Compensation'), ('management', 'Management / Supervision'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], default='open', max_length=15)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('assigned_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances_investigating', to='hrm.employeeprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances_filed', to='hrm.employeeprofile')),
                ('related_warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='hrm.warningletter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('related_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='hrm.hrpolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged')], default='pending', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='hrm.employeeprofile')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='hrm.hrpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('register_type', models.CharField(choices=[('labor_law_requirement', 'Labour Law Requirement'), ('muster_roll', 'Muster Roll'), ('wage_register', 'Wage Register'), ('inspection_report', 'Inspection Report'), ('license_permit', 'Licence / Permit'), ('other', 'Other')], default='labor_law_requirement', max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(blank=True, help_text='e.g. Karnataka, India / Federal.', max_length=150)),
                ('authority', models.CharField(blank=True, help_text='The issuing/inspecting authority.', max_length=150)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('filed', 'Filed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=15)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('inspector_name', models.CharField(blank=True, max_length=150)),
                ('findings', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='hrm/compliance/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'register_type'], name='hrm_cmp_tnt_type_idx'), models.Index(fields=['tenant', 'status'], name='hrm_cmp_tnt_status_idx'), models.Index(fields=['tenant', 'due_date'], name='hrm_cmp_tnt_due_idx'), models.Index(fields=['tenant', '-created_at'], name='hrm_cmp_tnt_created_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('probation', 'Probation'), ('consultant', 'Consultant'), ('intern', 'Intern'), ('part_time', 'Part Time')], default='permanent', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank for an open-ended contract.', null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=12)),
                ('document', models.FileField(blank=True, null=True, upload_to='hrm/contracts/%Y/%m/')),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='hrm.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hrm.employeeprofile')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='hrm.employmentcontract')),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='hrm.employeesalarystructure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'status'], name='hrm_ctr_emp_status_idx'), models.Index(fields=['tenant', 'status'], name='hrm_ctr_tnt_status_idx'), models.Index(fields=['tenant', 'end_date'], name='hrm_ctr_tnt_end_idx'), models.Index(fields=['tenant', '-created_at'], name='hrm_ctr_tnt_created_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='hrpolicy',
            index=models.Index(fields=['tenant', 'status'], name='hrm_pol_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpolicy',
            index=models.Index(fields=['tenant', 'category'], name='hrm_pol_tnt_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpolicy',
            index=models.Index(fields=['tenant', '-created_at'], name='hrm_pol_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hrpolicy',
            unique_together={('tenant', 'number'), ('tenant', 'title', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['tenant', 'status'], name='hrm_grv_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_grv_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['tenant', 'severity'], name='hrm_grv_tnt_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['tenant', '-created_at'], name='hrm_grv_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grievance',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['tenant', 'policy'], name='hrm_pack_tnt_policy_idx'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='hrm_pack_emp_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyacknowledgment',
            unique_together={('tenant', 'policy', 'employee')},
        ),
    ]
