# Generated by Django 5.1.15 on 2026-07-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0056_hrpolicy_grievance_policyacknowledgment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['tenant', '-created_at'], name='hrm_pack_tnt_created_idx'),
        ),
    ]
