# Generated by Django 5.1.15 on 2026-07-14 22:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0057_policyacknowledgment_hrm_pack_tnt_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforcePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('plan_type', models.CharField(choices=[('annual', 'Annual'), ('project', 'Project'), ('restructuring', 'Restructuring'), ('custom', 'Custom')], default='annual', max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('growth_assumption_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Business-growth assumption driving the demand forecast, e.g. 12.50 = +12.5%.', max_digits=6, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_workforce_plans', to='accounting.currency')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Blank = the whole organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_workforce_plans', to='core.orgunit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_plans_owned', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkforcePlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_headcount', models.PositiveSmallIntegerField(default=0)),
                ('planned_headcount', models.PositiveSmallIntegerField(default=0)),
                ('hiring_type', models.CharField(choices=[('new_growth', 'New Growth'), ('replacement', 'Replacement'), ('attrition_backfill', 'Attrition Backfill'), ('reduction', 'Reduction')], default='new_growth', max_length=20)),
                ('avg_annual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Fully-loaded average annual cost per head.', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('designation', models.ForeignKey(blank=True, help_text='Blank = a whole-department aggregate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_plan_lines', to='hrm.designation')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_workforce_plan_lines', to='core.orgunit')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrm.workforceplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('scenario_type', models.CharField(choices=[('growth', 'Growth'), ('freeze', 'Hiring Freeze'), ('restructuring', 'Restructuring'), ('attrition', 'Attrition'), ('cost_reduction', 'Cost Reduction'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('headcount_delta', models.SmallIntegerField(default=0, help_text='Signed: negative = a reduction.')),
                ('cost_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Signed: negative = a saving.', max_digits=14)),
                ('is_baseline', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('affected_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_workforce_scenarios', to='core.orgunit')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='hrm.workforceplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=120)),
                ('skill_category', models.CharField(choices=[('technical', 'Technical'), ('functional', 'Functional'), ('leadership', 'Leadership'), ('soft_skill', 'Soft Skill'), ('certification', 'Certification')], default='technical', max_length=15)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=15)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('certification_name', models.CharField(blank=True, max_length=150)),
                ('last_assessed_date', models.DateField(blank=True, null=True)),
                ('is_critical_skill', models.BooleanField(default=False, help_text='Flags a skill critical to future workforce needs.')),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['skill_name', 'id'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hrm_eskill_tnt_emp_idx'), models.Index(fields=['tenant', 'skill_category'], name='hrm_eskill_tnt_cat_idx'), models.Index(fields=['tenant', 'is_critical_skill'], name='hrm_eskill_tnt_crit_idx')],
                'unique_together': {('tenant', 'employee', 'skill_name')},
            },
        ),
        migrations.AddIndex(
            model_name='workforceplan',
            index=models.Index(fields=['tenant', 'status'], name='hrm_wfp_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceplan',
            index=models.Index(fields=['tenant', 'plan_type'], name='hrm_wfp_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceplan',
            index=models.Index(fields=['tenant', '-created_at'], name='hrm_wfp_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workforceplan',
            unique_together={('tenant', 'name'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='workforceplanline',
            index=models.Index(fields=['tenant', 'plan'], name='hrm_wfpl_tnt_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceplanline',
            index=models.Index(fields=['tenant', 'org_unit'], name='hrm_wfpl_tnt_org_idx'),
        ),
        migrations.AddIndex(
            model_name='workforcescenario',
            index=models.Index(fields=['tenant', 'plan'], name='hrm_wfs_tnt_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='workforcescenario',
            index=models.Index(fields=['tenant', 'status'], name='hrm_wfs_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workforcescenario',
            index=models.Index(fields=['tenant', '-created_at'], name='hrm_wfs_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workforcescenario',
            unique_together={('tenant', 'number'), ('tenant', 'plan', 'name')},
        ),
    ]
