# Generated by Django 5.1.15 on 2026-07-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0058_workforceplan_workforceplanline_workforcescenario_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['tenant', 'proficiency_level'], name='hrm_eskill_tnt_prof_idx'),
        ),
        migrations.AddIndex(
            model_name='workforcescenario',
            index=models.Index(fields=['tenant', 'scenario_type'], name='hrm_wfs_tnt_type_idx'),
        ),
    ]
