# Generated by Django 5.1.15 on 2026-07-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0059_workforce_scenario_type_and_proficiency_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellbeingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('program_type', models.CharField(choices=[('wellness_challenge', 'Wellness Challenge'), ('mental_health_resource', 'Mental Health Resource'), ('eap_counseling', 'EAP / Counseling'), ('culture_assessment', 'Culture Assessment'), ('team_event', 'Team Event'), ('interest_group', 'Interest Group'), ('volunteering', 'Volunteering'), ('work_life_policy', 'Work-Life Policy')], default='wellness_challenge', max_length=25)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Blank for an ongoing resource (e.g. an EAP hotline).', null=True)),
                ('points_value', models.PositiveIntegerField(blank=True, help_text='Gamification points a participant earns.', null=True)),
                ('external_resource_url', models.URLField(blank=True, help_text='Link out to the provider portal / sign-up page.')),
                ('is_confidential', models.BooleanField(default=False, help_text='EAP/counseling is ALWAYS confidential (forced on save); its roster is aggregate-only.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_wellbeingprogram_owned', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, help_text='Blank = company-wide.', limit_choices_to={'kind': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_programs', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WellbeingParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('completed', 'Completed'), ('no_show', 'No Show'), ('withdrawn', 'Withdrawn')], default='registered', max_length=12)),
                ('points_earned', models.PositiveIntegerField(blank=True, help_text='Admin-awarded — not self-settable by employees.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, help_text='Scheduling/status notes only — never clinical or counseling content.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wellbeing_participations', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='hrm.wellbeingprogram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlexibleWorkArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('arrangement_type', models.CharField(choices=[('remote', 'Fully Remote'), ('hybrid', 'Hybrid'), ('compressed_week', 'Compressed Week'), ('flextime', 'Flexible Hours'), ('part_time', 'Part Time')], default='remote', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank = open-ended / permanent.', null=True)),
                ('days_per_week_remote', models.PositiveSmallIntegerField(blank=True, help_text='Only for Remote/Hybrid — days worked remotely per week (1–5).', null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrm_fwa_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_work_arrangements', to='hrm.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'status'], name='hrm_fwa_emp_status_idx'), models.Index(fields=['tenant', 'status'], name='hrm_fwa_tnt_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SurveyActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('focus_area', models.CharField(help_text='The low-scoring driver/theme this plan addresses.', max_length=255)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('department', models.ForeignKey(blank=True, limit_choices_to={'kind': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_action_plans', to='core.orgunit')),
                ('owner', models.ForeignKey(help_text='The accountable owner — may be a manager, not necessarily an admin.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_action_plans', to='hrm.employeeprofile')),
                ('related_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_action_plans', to='hrm.objective')),
                ('survey', models.ForeignKey(help_text='The survey this plan responds to (typically a closed one).', on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='hrm.survey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-target_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='hrm_actp_tenant_status_idx'), models.Index(fields=['tenant', 'survey'], name='hrm_actp_tenant_survey_idx'), models.Index(fields=['tenant', 'owner'], name='hrm_actp_tenant_owner_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='wellbeingprogram',
            index=models.Index(fields=['tenant', 'program_type'], name='hrm_wbp_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='wellbeingprogram',
            index=models.Index(fields=['tenant', 'status'], name='hrm_wbp_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wellbeingprogram',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='wellbeingparticipation',
            index=models.Index(fields=['tenant', 'program'], name='hrm_wbpart_tnt_program_idx'),
        ),
        migrations.AddIndex(
            model_name='wellbeingparticipation',
            index=models.Index(fields=['tenant', 'employee'], name='hrm_wbpart_tnt_employee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wellbeingparticipation',
            unique_together={('tenant', 'program', 'employee')},
        ),
    ]
