# Generated by Django 5.1.15 on 2026-07-15 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('hrm', '0060_wellbeingprogram_wellbeingparticipation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wellbeingparticipation',
            name='hrm_wbpart_tnt_program_idx',
        ),
        migrations.AddIndex(
            model_name='flexibleworkarrangement',
            index=models.Index(fields=['tenant', 'arrangement_type'], name='hrm_fwa_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyactionplan',
            index=models.Index(fields=['tenant', 'department'], name='hrm_actp_tenant_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='wellbeingprogram',
            index=models.Index(fields=['tenant', 'target_department'], name='hrm_wbp_tenant_dept_idx'),
        ),
    ]
