# Generated by Django 5.1.15 on 2026-08-21 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('deadline', 'Deadline'), ('approval', 'Approval'), ('delivery', 'Delivery'), ('task', 'Task')], default='task', max_length=12)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=14)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, help_text='What needs doing / what happened')),
                ('link_url', models.CharField(blank=True, help_text='Optional internal link, e.g. /scm/requisitions/5/', max_length=255)),
                ('due_at', models.DateTimeField(blank=True, help_text='When the deadline hits / the alert becomes late', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution_note', models.TextField(blank=True, help_text='How it was closed out')),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Who owns this alert — blank raises it to the team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_alerts_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='prc_alr_tnt_status_idx'), models.Index(fields=['tenant', 'kind'], name='prc_alr_tnt_kind_idx'), models.Index(fields=['tenant', 'assigned_to'], name='prc_alr_tnt_assign_idx')],
            },
        ),
        migrations.CreateModel(
            name='WidgetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget_key', models.CharField(max_length=40)),
                ('is_visible', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_widget_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'id'],
                'unique_together': {('tenant', 'user', 'widget_key')},
            },
        ),
    ]
