# Generated by Django 5.1.15 on 2026-08-21 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='procurementalert',
            index=models.Index(fields=['tenant', 'severity'], name='prc_alr_tnt_sev_idx'),
        ),
    ]
