# Generated by Django 5.1.15 on 2026-08-22 07:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0002_procurementalert_prc_alr_tnt_sev_idx'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('amendment_type', models.CharField(choices=[('amend', 'Amend details'), ('cancel', 'Cancel requisition')], default='amend', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('reason', models.TextField(help_text='Why this change / cancellation is needed')),
                ('new_required_by', models.DateField(blank=True, help_text='Proposed new required-by date', null=True)),
                ('new_justification', models.TextField(blank=True, help_text='Proposed new justification text')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True, editable=False)),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_amendments_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_amendments_requested', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(help_text='The requisition this amendment proposes to change', on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='scm.purchaserequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionAmendmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add line'), ('update', 'Update line'), ('remove', 'Remove line')], default='update', max_length=6)),
                ('item_description', models.CharField(blank=True, help_text='Required when adding a line', max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('uom_hint', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Blank on update = keep the current quantity', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Blank on update = keep the current price', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.requisitionamendment')),
                ('target_line', models.ForeignKey(blank=True, help_text='Which existing line this changes (blank = a new line)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment_lines', to='scm.purchaserequisitionline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text="What this recurring order is, e.g. 'Monthly office supplies'", max_length=120)),
                ('description', models.TextField(blank=True, help_text='When/how this template is meant to be used')),
                ('default_lead_days', models.PositiveIntegerField(blank=True, help_text='Applied requisitions fall due this many days ahead (blank = no date)', null=True)),
                ('justification', models.TextField(blank=True, help_text="Pre-filled 'why this purchase is needed'")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden from the apply action but kept for history')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requisition_templates', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requisition_templates', to='accounting.currency')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Pre-filled requesting department / cost centre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requisition_templates', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(help_text='What is being requested', max_length=255)),
                ('sku_hint', models.CharField(blank=True, help_text='Vendor/catalog code, if known (free-text until core.Item exists)', max_length=64)),
                ('uom_hint', models.CharField(blank=True, help_text='Unit of measure, e.g. each / box / kg', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gl_account', models.ForeignKey(blank=True, help_text='Expense account to charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_template_lines', to='accounting.glaccount')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.requisitiontemplate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='requisitionamendment',
            index=models.Index(fields=['tenant', 'status'], name='prc_ram_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionamendment',
            index=models.Index(fields=['tenant', 'amendment_type'], name='prc_ram_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requisitiontemplate',
            unique_together={('tenant', 'number')},
        ),
    ]
