# Generated by Django 5.1.15 on 2026-08-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0003_requisitionamendment_requisitionamendmentline_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requisitionamendment',
            unique_together={('tenant', 'number')},
        ),
    ]
