# Generated by Django 5.1.15 on 2026-08-25 18:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0004_alter_requisitionamendment_unique_together'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(help_text='Last day the grant holds — authority reverts automatically after')),
                ('reason', models.CharField(blank=True, help_text='e.g. annual leave cover', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('delegate', models.ForeignKey(blank=True, help_text='The approver covering for them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_doa_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(blank=True, help_text='The approver stepping aside', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_doa_given', to=settings.AUTH_USER_MODEL)),
                ('scope_org_unit', models.ForeignKey(blank=True, help_text='Restrict the grant to one department; blank covers them all', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_delegations', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.CharField(blank=True, help_text="Keyword matched against line descriptions/SKUs (e.g. 'safety'); blank = any commodity", max_length=64)),
                ('min_total', models.DecimalField(blank=True, decimal_places=2, help_text='Band floor (inclusive); blank = no lower bound', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_total', models.DecimalField(blank=True, decimal_places=2, help_text='Band ceiling (EXCLUSIVE); blank = no upper bound', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('required_tiers', models.PositiveSmallIntegerField(default=1, help_text='Sequential sign-offs this spend needs before final approval', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('escalation_hours', models.PositiveIntegerField(blank=True, help_text="Idle hours after which this rule's queue escalates; blank = the tenant policy's window", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('org_unit', models.ForeignKey(blank=True, help_text='Department this rule routes; blank = any department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_routing_rules', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idle_hours', models.PositiveIntegerField(default=48, help_text='A pending approval idle longer than this escalates; a routing rule may override per queue')),
                ('is_active', models.BooleanField(default=True)),
                ('escalate_to', models.ForeignKey(blank=True, help_text='Backup approver escalation alerts are assigned to; blank = raised to the team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_escalations_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('tier', models.PositiveSmallIntegerField(help_text='Which sign-off in the chain (1-based)')),
                ('tier_count', models.PositiveSmallIntegerField(help_text='Chain length as resolved when this decision was made — a snapshot, so a later rule change never rewrites what this approver thought they were signing')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=8)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(help_text='The requisition this signature belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_approvals', to='scm.purchaserequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('via_delegation', models.ForeignKey(blank=True, help_text='Set when the signer held authority through an active DOA grant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='procurement.approvaldelegation')),
            ],
            options={
                'ordering': ['requisition_id', 'tier', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='approvaldelegation',
            index=models.Index(fields=['tenant', 'is_active'], name='prc_del_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalroutingrule',
            index=models.Index(fields=['tenant', 'is_active'], name='prc_arr_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionapproval',
            index=models.Index(fields=['tenant', 'decision'], name='prc_rqa_tnt_decision_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requisitionapproval',
            unique_together={('tenant', 'requisition', 'tier')},
        ),
    ]
