# Generated by Django 5.1.15 on 2026-08-25 19:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0006_escalationpolicy_unique_tenant'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escalationpolicy',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='VendorInvoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('invoice_ref', models.CharField(help_text="The supplier's own invoice number", max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Header total as the supplier states it', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.TextField(blank=True, help_text="The supplier's message to procurement")),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='The PO this invoices against, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_invoice_submissions', to='scm.purchaseorder')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_vis_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, help_text='The portal login that filed it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_vis_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='The supplier who filed this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_invoice_submissions', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='prc_vis_tnt_status_idx'), models.Index(fields=['tenant', 'supplier'], name='prc_vis_tnt_supp_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VendorPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Switch off instead of delete')),
                ('note', models.TextField(blank=True)),
                ('invited_by', models.ForeignKey(blank=True, editable=False, help_text='Which staff member issued this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_vendor_invitations', to=settings.AUTH_USER_MODEL)),
                ('portal_user', models.OneToOneField(blank=True, help_text='The ONE login bound to this supplier identity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_vendor_portal_access', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='The company whose POs/invoices this login may see', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_portal_accesses', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='prc_vpa_tnt_active_idx'), models.Index(fields=['tenant', 'supplier'], name='prc_vpa_tnt_supp_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VendorSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('kind', models.CharField(choices=[('suspension', 'Suspension'), ('blacklist', 'Blacklist')], default='suspension', help_text='Blacklists are normally open-ended; suspensions carry an end date', max_length=16)),
                ('reason_category', models.CharField(choices=[('quality', 'Quality failure'), ('delivery', 'Delivery failure'), ('compliance', 'Compliance breach'), ('financial', 'Financial risk'), ('other', 'Other')], default='other', max_length=16)),
                ('reason', models.TextField(help_text='The documented case for the block')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, help_text='Suspensions expire automatically after; blank = until lifted (blacklists normally open-ended)', null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'In force'), ('rejected', 'Rejected'), ('lifted', 'Lifted')], default='requested', max_length=16)),
                ('decision_note', models.TextField(blank=True, help_text='Approve/reject note')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lifted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lift_note', models.TextField(blank=True, help_text='Why the block was lifted')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_suspensions_decided', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_suspensions_lifted', to=settings.AUTH_USER_MODEL)),
                ('po_reference', models.ForeignKey(blank=True, help_text='Optional evidence link — the order that triggered it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_suspensions', to='scm.purchaseorder')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_suspensions_requested', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='The vendor being blocked', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_suspensions', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='prc_vsu_tnt_status_idx'), models.Index(fields=['tenant', 'supplier'], name='prc_vsu_tnt_supp_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
