# Generated by Django 5.1.15 on 2026-08-25 19:50
# NOTE: this migration intentionally contains ONLY the 6.6 RFx Management models. The concurrent
# 6.5 Sourcing & Tendering build had its unmigrated models autodetected into the first draft of
# this file; those ops were removed here so 6.5 can ship its own migration (L43 - one owner per
# migration).

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0007_alter_escalationpolicy_unique_together_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RfxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('rfx_type', models.CharField(choices=[('rfi', 'RFI — Request for Information'), ('rfp', 'RFP — Request for Proposal'), ('rfq', 'RFQ — Request for Quotation')], default='rfp', help_text='Information (RFI), proposal (RFP) or quotation (RFQ)', max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions shown to suppliers alongside the questions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('response_due', models.DateTimeField(blank=True, help_text='Deadline for supplier responses', null=True)),
                ('issued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_template', models.BooleanField(default=False, help_text='Template-library row: a reusable questionnaire kept in draft and cloned into real events via Use')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_rfx_events', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, help_text='Sourcing this event supports (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_events', to='scm.purchaserequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RfxQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, help_text="Optional grouping, e.g. 'Technical' / 'Commercial'", max_length=120)),
                ('prompt', models.TextField(help_text='The question asked of every supplier')),
                ('help_text', models.CharField(blank=True, help_text='Clarification rendered under the prompt', max_length=255)),
                ('answer_type', models.CharField(choices=[('text', 'Short text'), ('longtext', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('choice', 'Choice (single select)')], default='text', max_length=10)),
                ('options', models.TextField(blank=True, help_text='For choice questions: one option per line')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Scoring weight — 0 excludes from the score, higher moves the ranking more', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_scored', models.BooleanField(default=True, help_text='Unscored questions collect answers but never affect totals')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display position (builder reorders)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='procurement.rfxevent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RfxResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('scored', 'Scored'), ('disqualified', 'Disqualified')], default='draft', max_length=14)),
                ('notes', models.TextField(blank=True, help_text="Cover note / summary of the supplier's submission")),
                ('attachment', models.FileField(blank=True, help_text="The supplier's proposal document. Serve with Content-Disposition: attachment and keep MEDIA_ROOT outside any executable path.", null=True, upload_to='procurement/rfx/%Y/%m/')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='procurement.rfxevent')),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, help_text='Staff member who recorded this response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='The responding supplier (a Party with the supplier role)', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_rfx_responses', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RfxAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text="The supplier's answer (choice answers store the chosen option verbatim)")),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Evaluator rating, 0–10', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='procurement.rfxquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='procurement.rfxresponse')),
            ],
            options={
                'ordering': ['question__order', 'question__id'],
            },
        ),
        migrations.AddIndex(
            model_name='rfxevent',
            index=models.Index(fields=['tenant', 'status'], name='prc_rfx_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rfxevent',
            index=models.Index(fields=['tenant', 'is_template'], name='prc_rfx_tnt_tmpl_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfxevent',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='rfxresponse',
            index=models.Index(fields=['tenant', 'status'], name='prc_rxr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rfxresponse',
            index=models.Index(fields=['tenant', 'event'], name='prc_rxr_tnt_event_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfxresponse',
            unique_together={('event', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='rfxanswer',
            unique_together={('response', 'question')},
        ),
    ]
