# Generated by Django 5.1.15 on 2026-08-25 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0008_rfx_management'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Scope of the requirement suppliers are bidding on')),
                ('event_type', models.CharField(choices=[('tender', 'Open Tender'), ('rfp', 'RFP'), ('rfq', 'Restricted RFQ')], default='tender', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('budget_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Internal expectation for this spend — blank when genuinely unknown', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('opens_at', models.DateTimeField(blank=True, help_text='When suppliers may start submitting bids', null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Submission deadline — the evaluation window opens', null=True)),
                ('rules', models.TextField(blank=True, help_text='Rules sent to suppliers: terms, compliance requirements, how bids will be evaluated')),
                ('opened_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_sourcing_events_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_sourcing_events', to='accounting.currency')),
                ('requisition', models.ForeignKey(blank=True, help_text='Requisition that triggered this event (traceability only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_events', to='scm.purchaserequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourcingBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('disqualified', 'Disqualified'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Whole-package price quoted for the event scope', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Quoted delivery lead time, in days', null=True)),
                ('is_compliant', models.BooleanField(default=True, help_text="Supplier meets the event's stated compliance requirements")),
                ('compliance_note', models.CharField(blank=True, help_text='What is missing when not compliant', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Proposal abstract / exceptions taken')),
                ('contact_ref', models.CharField(blank=True, help_text='Reference or reply-to captured with the submission', max_length=120)),
                ('decision_note', models.TextField(blank=True, help_text='Evaluator notes — e.g. why a bid was disqualified')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_sourcing_bids_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Who bid (a Party carrying the supplier or vendor role)', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_sourcing_bids', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='procurement.sourcingevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Total cost', 'Delivery lead time', 'Compliance & certifications'", max_length=120)),
                ('weight_pct', models.DecimalField(decimal_places=2, default=0, help_text='Share of the overall score, 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('max_score', models.PositiveIntegerField(default=10, help_text='Scale an evaluator scores this criterion on, e.g. 1-10', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='procurement.sourcingevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BidScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='procurement.eventcriterion')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='procurement.sourcingbid')),
            ],
            options={
                'ordering': ['criterion_id', 'id'],
                'unique_together': {('bid', 'criterion')},
            },
        ),
        migrations.AddIndex(
            model_name='sourcingevent',
            index=models.Index(fields=['tenant', 'status'], name='prc_sev_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcingevent',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='sourcingbid',
            index=models.Index(fields=['tenant', 'event'], name='prc_bid_tnt_event_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcingbid',
            index=models.Index(fields=['tenant', 'status'], name='prc_bid_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcingbid',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='eventcriterion',
            unique_together={('event', 'name')},
        ),
    ]
