# Generated by Django 5.1.15 on 2026-08-25 21:51
# NOTE: this migration intentionally contains ONLY the 6.7 E-Auction models. The concurrent
# 6.8 Contracts build had its unmigrated models autodetected into the first draft of this file
# (ContractClause/ContractClauseLink/ContractMilestone/ContractSigner/ContractAmendment); those
# ops were removed so 6.8 can ship its own migration (L43 - one owner per migration).

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0009_sourcing_management'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eauction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Scope and rules shown to invited suppliers')),
                ('auction_type', models.CharField(choices=[('reverse', 'Reverse auction (price falls)')], default='reverse', max_length=8)),
                ('start_price', models.DecimalField(decimal_places=2, help_text='Opening ceiling for the first bid (reverse auction)', max_digits=14)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, help_text='Internal target — results flag winning bids that land below it', max_digits=14, null=True)),
                ('min_decrement', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text="Each supplier's next bid must undercut their own previous bid by at least this much", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('extension_trigger_seconds', models.PositiveIntegerField(default=60, help_text='A bid inside this many seconds of the close extends the auction')),
                ('extension_seconds', models.PositiveIntegerField(default=120, help_text='How long each automatic extension adds to closes_at')),
                ('max_extensions', models.PositiveIntegerField(default=3, help_text='Hard cap so an auction cannot extend forever')),
                ('extensions_used', models.PositiveIntegerField(default=0, editable=False)),
                ('opens_at', models.DateTimeField(help_text='When bidding may begin')),
                ('closes_at', models.DateTimeField(help_text='When bidding ends (extensions push this later)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('awarded_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('award_note', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('awarded_supplier', models.ForeignKey(blank=True, help_text='Set once, when the auction is awarded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_eauc_wins', to='core.party')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_eauc_auctions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_eauc_auctions', to='accounting.currency')),
                ('requisition', models.ForeignKey(blank=True, help_text='Sourcing this auction supports (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eauctions', to='scm.purchaserequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EaucInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_note', models.CharField(blank=True, max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_eauc_invites', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='procurement.eauction')),
            ],
            options={
                'ordering': ['supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='EaucBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, help_text='Optional remark carried with the bid', max_length=255)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('placed_by', models.ForeignKey(blank=True, editable=False, help_text='Staff recorder, or the vendor-portal user themselves', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_eauc_bids', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='procurement.eauction')),
            ],
            options={
                'ordering': ['placed_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='eauction',
            index=models.Index(fields=['tenant', 'status'], name='prc_eauc_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eauction',
            index=models.Index(fields=['tenant', 'opens_at'], name='prc_eauc_tnt_open_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eauction',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='eaucinvite',
            unique_together={('auction', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='eaucbid',
            index=models.Index(fields=['tenant', 'auction'], name='prc_ebid_tnt_auction_idx'),
        ),
        migrations.AddIndex(
            model_name='eaucbid',
            index=models.Index(fields=['auction', 'amount'], name='prc_ebid_auc_amount_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eaucbid',
            unique_together={('tenant', 'number')},
        ),
    ]
