# Generated by Django 5.1.15 on 2026-08-25 22:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0010_eauction_management'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('legal', 'Legal & Liability'), ('payment', 'Payment Terms'), ('delivery', 'Delivery & Acceptance'), ('confidentiality', 'Confidentiality'), ('termination', 'Termination'), ('compliance', 'Compliance'), ('other', 'Other')], default='other', max_length=20)),
                ('body', models.TextField(help_text='The standard wording inserted into drafted contracts')),
                ('version', models.CharField(blank=True, help_text="Legal revision tag, e.g. 'v2.1' — informational only", max_length=20)),
                ('is_pre_approved', models.BooleanField(default=True, help_text='Signed off by legal; unapproved clauses render flagged on the contract page')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['category', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractClauseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.PositiveSmallIntegerField(default=1, help_text='Position of this clause within the drafted document')),
                ('custom_text', models.TextField(blank=True, help_text='Negotiated wording replacing the standard body for THIS agreement')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_clause_links', to='procurement.contractclause')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_clause_links', to='scm.suppliercontract')),
            ],
            options={
                'ordering': ['section_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('kind', models.CharField(choices=[('deliverable', 'Deliverable'), ('payment', 'Payment milestone'), ('penalty', 'Penalty')], default='deliverable', max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment value or penalty cap — blank for pure deliverables', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('waived', 'Waived')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('completed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_milestones_completed', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_milestones', to='scm.suppliercontract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('internal', 'Internal stakeholder'), ('supplier', 'Supplier representative')], default='internal', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('signed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('declined_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_signers', to='scm.suppliercontract')),
                ('signer_party', models.ForeignKey(blank=True, help_text='The supplier identity signing (blank for internal staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_contract_signers', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reason', models.TextField(help_text='The documented case for this change')),
                ('proposed_end_date', models.DateField(blank=True, help_text='Blank = leave the current end date standing', null=True)),
                ('proposed_value', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = leave the current contract value standing', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('proposed_auto_renew', models.BooleanField(blank=True, help_text='Blank = leave the current auto-renewal setting', null=True)),
                ('proposed_notice_days', models.PositiveSmallIntegerField(blank=True, help_text='Blank = leave the current renewal-notice window', null=True)),
                ('proposed_summary', models.TextField(blank=True, help_text='Digest of clause-level changes riding along')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_amendments', to='scm.suppliercontract')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_contract_amendments_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_contract_amendments_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='contractclause',
            index=models.Index(fields=['tenant', 'is_active'], name='prc_ccl_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractclauselink',
            unique_together={('contract', 'clause')},
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['tenant', 'status'], name='prc_cmi_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractmilestone',
            unique_together={('tenant', 'number')},
        ),
    ]
