# Generated by Django 5.1.15 on 2026-08-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_contractclause_contractclauselink_contractmilestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementalert',
            name='kind',
            field=models.CharField(choices=[('deadline', 'Deadline'), ('approval', 'Approval'), ('delivery', 'Delivery'), ('task', 'Task'), ('contract', 'Contract')], default='task', max_length=12),
        ),
    ]
