# Generated by Django 5.1.15 on 2026-08-26 05:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0012_alter_procurementalert_kind'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('source_type', models.CharField(choices=[('internal', 'Internal stock item'), ('supplier_product', 'Supplier product')], default='internal', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('supplier_part_no', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='List price the tiers discount from', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred source when requisitions match this entry')),
                ('is_active', models.BooleanField(default=True)),
                ('category_text', models.CharField(blank=True, help_text="Free-text category for filtering, e.g. 'Safety wear'", max_length=120)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_items_approved', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, help_text='Agreement this catalogue entry prices against (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_contract_catalog_items', to='scm.suppliercontract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_items_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, help_text='Price currency (global ISO master)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_item_currencies', to='accounting.currency')),
                ('item', models.ForeignKey(blank=True, help_text='Stock item mirrored into the catalogue (internal entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_items', to='scm.item')),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_items_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier offering this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_supplier_items', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_item_uoms', to='scm.uom')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Quantity from which this price applies', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Used when no discount percentage is given', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, help_text="Percent off the item's base price — leave blank to price at unit_price (capped at 100)", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valid_from', models.DateField(blank=True, help_text='Optional start of the validity window', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Open-ended when left blank', null=True)),
                ('status', models.CharField(choices=[('draft', 'Proposed'), ('active', 'Active'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_price_tiers_approved', to=settings.AUTH_USER_MODEL)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='procurement.catalogitem')),
                ('contract', models.ForeignKey(blank=True, help_text='Supplier agreement this break honours (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_contract_price_tiers', to='scm.suppliercontract')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_price_tiers_submitted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['catalog_item_id', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='CatalogUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='procurement/catalog_uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected')], default='received', max_length=12)),
                ('validated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rows_parsed', models.PositiveIntegerField(default=0, editable=False)),
                ('rows_accepted', models.PositiveIntegerField(default=0, editable=False)),
                ('rows_rejected', models.PositiveIntegerField(default=0, editable=False)),
                ('error_log', models.TextField(blank=True, editable=False, help_text='Line-numbered "row N: reason" rejects from validation')),
                ('notes', models.TextField(blank=True)),
                ('party', models.ForeignKey(blank=True, help_text='Supplier whose catalog this file carries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_upload_batches', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_upload_batches_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PunchOutEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('protocol', models.CharField(choices=[('cxml', 'cXML'), ('oci', 'SAP OCI'), ('manual_link', 'Manual link')], default='cxml', max_length=20)),
                ('punchout_url', models.URLField(help_text="Entry URL of the supplier's punch-out site")),
                ('username', models.CharField(blank=True, max_length=120)),
                ('shared_secret', models.CharField(blank=True, help_text='Write-only: left blank on edit, stored for this workspace only.', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Disabled endpoints stay on file but leave the buyer launch lists')),
                ('last_session_at', models.DateTimeField(blank=True, editable=False, help_text='When a punch-out session was last recorded against this endpoint', null=True)),
                ('notes', models.TextField(blank=True)),
                ('party', models.ForeignKey(help_text='Supplier this punch-out connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='punchout_endpoints', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['tenant', 'status'], name='prc_catitem_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['tenant', 'item'], name='prc_catitem_tnt_item_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='catalogpricetier',
            index=models.Index(fields=['tenant', 'status'], name='prc_cattier_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogpricetier',
            unique_together={('tenant', 'catalog_item', 'min_quantity', 'valid_from')},
        ),
        migrations.AddIndex(
            model_name='cataloguploadbatch',
            index=models.Index(fields=['tenant', 'status'], name='prc_catupload_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cataloguploadbatch',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='punchoutendpoint',
            index=models.Index(fields=['tenant', 'enabled'], name='prc_poe_tnt_enabled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='punchoutendpoint',
            unique_together={('tenant', 'number')},
        ),
    ]
