# Generated by Django 5.1.15 on 2026-08-26 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0013_catalogitem_catalogpricetier_cataloguploadbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataloguploadbatch',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Supplier whose catalog this file carries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_catalog_upload_batches', to='core.party'),
        ),
        migrations.AlterField(
            model_name='punchoutendpoint',
            name='party',
            field=models.ForeignKey(help_text='Supplier this punch-out connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='procurement_punchout_endpoints', to='core.party'),
        ),
    ]
