# Generated by Django 5.1.15 on 2026-08-27 15:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0014_alter_cataloguploadbatch_party_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('change_type', models.CharField(choices=[('amend', 'Change details'), ('cancel', 'Cancel order')], default='amend', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('reason', models.TextField(help_text='Why this change / cancellation is needed')),
                ('new_expected_date', models.DateField(blank=True, help_text='Proposed new expected delivery date', null=True)),
                ('new_notes', models.TextField(blank=True, help_text='Proposed replacement notes text')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True, editable=False)),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_po_changes_decided', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(help_text='The purchase order this change proposes to alter', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_changes', to='scm.purchaseorder')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_po_changes_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderChangeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add line'), ('update', 'Update line'), ('remove', 'Remove line')], default='update', max_length=6)),
                ('item_description', models.CharField(blank=True, help_text='Required when adding a line', max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('uom_hint', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Blank on update = keep the current quantity', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Blank on update = keep the current price', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Blank on update = keep the current tax rate', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorderchange')),
                ('target_line', models.ForeignKey(blank=True, help_text='Which existing line this changes (blank = a new line)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_lines', to='scm.purchaseorderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorderchange',
            index=models.Index(fields=['tenant', 'status'], name='prc_pco_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderchange',
            index=models.Index(fields=['tenant', 'change_type'], name='prc_pco_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderchange',
            unique_together={('tenant', 'number')},
        ),
    ]
