# Generated by Django 5.1.15 on 2026-08-29 12:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0015_purchaseorderchange_purchaseorderchangeline_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedShipmentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('supplier_reference', models.CharField(blank=True, help_text="Vendor's own ASN / delivery-note number", max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=12)),
                ('source', models.CharField(choices=[('portal', 'Supplier Portal'), ('email', 'Email'), ('edi', 'EDI 856'), ('manual', 'Manual Entry')], default='manual', max_length=8)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('carrier_name', models.CharField(blank=True, help_text="Supplier's own courier when there is no TMS profile", max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('bill_of_lading_ref', models.CharField(blank=True, max_length=64, verbose_name='Bill of lading ref')),
                ('container_ref', models.CharField(blank=True, max_length=64)),
                ('freight_terms', models.CharField(blank=True, choices=[('prepaid', 'Prepaid'), ('collect', 'Collect'), ('third_party', 'Third Party'), ('prepaid_and_charged', 'Prepaid & Charged')], max_length=20)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pallet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume (CBM)')),
                ('arrival_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('partial', 'Partial'), ('refused', 'Refused')], editable=False, max_length=10)),
                ('pod_reference', models.CharField(blank=True, editable=False, max_length=64, verbose_name='POD reference')),
                ('received_signature_name', models.CharField(blank=True, editable=False, max_length=120)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(blank=True, help_text='TMS carrier profile, when the freight rides on one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_asns', to='scm.carrier')),
                ('confirmed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_asns_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_asns_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(help_text='The order this shipment is declared against', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_asns', to='scm.purchaseorder')),
                ('shipment', models.ForeignKey(blank=True, help_text='Inbound SCM 4.6 shipment whose tracking projections this ASN reads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_asns', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AsnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, help_text="Blank copies the PO line's description", max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('uom_hint', models.CharField(blank=True, max_length=32, verbose_name='UOM hint')),
                ('quantity_shipped', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('package_ref', models.CharField(blank=True, help_text='Carton / pallet / LPN reference', max_length=64)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.advancedshipmentnotice')),
                ('po_line', models.ForeignKey(help_text='Which ordered line this declares against', on_delete=django.db.models.deletion.PROTECT, related_name='asn_lines', to='scm.purchaseorderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Instalment number within the line (1, 2, 3 …)')),
                ('scheduled_quantity', models.DecimalField(decimal_places=4, help_text='How much of the line arrives in this instalment', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('need_by_date', models.DateField(help_text='When the business needs this instalment')),
                ('promised_quantity', models.DecimalField(blank=True, decimal_places=4, help_text="Supplier's counter-offer quantity, if different", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('promised_date', models.DateField(blank=True, help_text="Supplier's committed date, if different from need-by", null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('delivery_mode', models.CharField(blank=True, choices=[('standard', 'Standard'), ('express', 'Express'), ('courier', 'Courier'), ('freight', 'Freight'), ('collection', 'Collection'), ('dropship', 'Dropship')], max_length=16)),
                ('change_reason', models.CharField(blank=True, help_text="Why this instalment's quantity or date moved", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('asn', models.ForeignKey(blank=True, help_text='The advance shipping notice covering this instalment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='procurement.advancedshipmentnotice')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_delivery_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('po_line', models.ForeignKey(help_text='The ordered line this instalment delivers part of', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_delivery_schedules', to='scm.purchaseorderline')),
                ('ship_to', models.ForeignKey(blank=True, help_text='Site / unit this instalment is delivered to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_delivery_schedules', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['po_line_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Backorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('quantity_backordered', models.DecimalField(decimal_places=4, help_text='How much of the ordered quantity is still outstanding', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('reason', models.CharField(choices=[('out_of_stock', 'Out of Stock'), ('production_delay', 'Production Delay'), ('allocation', 'Allocation Shortfall'), ('material_shortage', 'Material Shortage'), ('supplier_capacity', 'Supplier Capacity'), ('logistics', 'Logistics'), ('other', 'Other')], default='out_of_stock', max_length=20)),
                ('reason_note', models.CharField(blank=True, help_text="Required when the reason is 'Other'; also carries the latest reschedule note", max_length=255)),
                ('original_promise_date', models.DateField(blank=True, help_text='The date first committed to — kept so slippage stays visible after a reschedule', null=True)),
                ('revised_promise_date', models.DateField(blank=True, help_text='The date the supplier is committing to now', null=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('rescheduled', 'Rescheduled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', editable=False, max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closure_note', models.CharField(blank=True, editable=False, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('alert', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.procurementalert')),
                ('asn', models.ForeignKey(blank=True, help_text='The shipment whose declared quantity revealed the shortfall', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='procurement.advancedshipmentnotice')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_backorders_created', to=settings.AUTH_USER_MODEL)),
                ('po_line', models.ForeignKey(help_text='The ordered line whose quantity is short', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_backorders', to='scm.purchaseorderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('delivery_schedule', models.ForeignKey(blank=True, help_text='The split-delivery instalment that fell short, when there is one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='procurement.deliveryschedule')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='advancedshipmentnotice',
            index=models.Index(fields=['tenant', 'status'], name='prc_asn_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedshipmentnotice',
            index=models.Index(fields=['tenant', 'expected_delivery_date'], name='prc_asn_tnt_expdate_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedshipmentnotice',
            index=models.Index(fields=['tenant', 'purchase_order'], name='prc_asn_tnt_po_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='advancedshipmentnotice',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='asnline',
            unique_together={('asn', 'po_line')},
        ),
        migrations.AddIndex(
            model_name='deliveryschedule',
            index=models.Index(fields=['tenant', 'status'], name='prc_dsc_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedule',
            index=models.Index(fields=['tenant', 'need_by_date'], name='prc_dsc_tnt_needby_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryschedule',
            unique_together={('tenant', 'number'), ('tenant', 'po_line', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['tenant', 'status'], name='prc_bko_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['tenant', 'reason'], name='prc_bko_tnt_reason_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['tenant', 'revised_promise_date'], name='prc_bko_tnt_revdate_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backorder',
            unique_together={('tenant', 'number')},
        ),
    ]
