# Generated by Django 5.1.15 on 2026-08-29 21:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0028_uomconversion'),
        ('procurement', '0016_advancedshipmentnotice_asnline_deliveryschedule_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('kind', models.CharField(choices=[('over_shipment', 'Over-shipment'), ('short_shipment', 'Short shipment'), ('damaged', 'Damaged'), ('wrong_item', 'Wrong item'), ('quality_failure', 'Quality failure'), ('documentation', 'Documentation'), ('late_delivery', 'Late delivery')], max_length=16)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=8)),
                ('quantity_affected', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('item_description', models.CharField(blank=True, help_text="Blank copies the receipt line's description", max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text="What was found, in the buyer's own words")),
                ('evidence', models.FileField(blank=True, null=True, upload_to='procurement/receipt_evidence/%Y/%m/')),
                ('evidence_url', models.URLField(blank=True, help_text='Link to evidence held elsewhere (used when no file is uploaded)')),
                ('remedy', models.CharField(choices=[('pending', 'Pending decision'), ('replacement', 'Replacement'), ('credit', 'Credit'), ('rtv', 'Return to vendor'), ('accept_as_is', 'Accept as is'), ('scrap', 'Scrap')], default='pending', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('vendor_notified', 'Vendor notified'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', editable=False, max_length=15)),
                ('vendor_notified_on', models.DateField(blank=True, editable=False, null=True)),
                ('vendor_reference', models.CharField(blank=True, help_text="The supplier's own claim / case number, once they give us one", max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution_notes', models.TextField(blank=True, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_discrepancies_created', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(help_text='The receipt this finding was raised against', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_discrepancies', to='scm.goodsreceiptnote')),
                ('goods_receipt_line', models.ForeignKey(blank=True, help_text='Leave blank for a header-level finding (e.g. missing paperwork)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_discrepancies', to='scm.goodsreceiptline')),
                ('nonconformance', models.ForeignKey(blank=True, help_text='SCM 4.9 quality record this finding was escalated into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_discrepancies', to='scm.nonconformance')),
                ('quarantine_order', models.ForeignKey(blank=True, help_text='Inventory 5.15 segregation raised for the suspect stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_discrepancies', to='inventory.quarantineorder')),
                ('resolved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_discrepancies_resolved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'receipt discrepancy',
                'verbose_name_plural': 'receipt discrepancies',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnToVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('defective', 'Defective'), ('wrong_item', 'Wrong item'), ('over_shipment', 'Over-shipment'), ('expired', 'Expired'), ('not_to_spec', 'Not to spec'), ('other', 'Other')], max_length=14)),
                ('reason_note', models.CharField(blank=True, help_text="Required when the reason is 'Other'", max_length=255)),
                ('remedy', models.CharField(choices=[('credit', 'Credit'), ('replacement', 'Replacement'), ('repair', 'Repair'), ('none', 'No remedy')], default='credit', max_length=11)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Authorized'), ('shipped', 'Shipped'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=10)),
                ('supplier_rma_number', models.CharField(blank=True, help_text="The supplier's return authorization number", max_length=64, verbose_name='Supplier RMA number')),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('shipped_on', models.DateField(blank=True, editable=False, null=True)),
                ('expected_return_date', models.DateField(blank=True, help_text='When the replacement / credit is expected back', null=True)),
                ('credit_note_ref', models.CharField(blank=True, help_text='Reference only — the AP credit is blocked on the accounting.Bill.kind gap (L29); this posts NOTHING to the ledger.', max_length=64)),
                ('authorized_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_rtvs_authorized', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_rtvs_created', to=settings.AUTH_USER_MODEL)),
                ('discrepancy', models.ForeignKey(blank=True, help_text='The receiving finding this return answers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtvs', to='procurement.receiptdiscrepancy')),
                ('goods_receipt', models.ForeignKey(blank=True, help_text='The receipt these goods arrived on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_rtvs', to='scm.goodsreceiptnote')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_rtvs', to='scm.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(help_text='The supplier the goods go back to', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_rtvs', to='core.party')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='receiptdiscrepancy',
            name='return_to_vendor',
            field=models.ForeignKey(blank=True, help_text='The RTV raised to send the goods back', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_discrepancies', to='procurement.returntovendor'),
        ),
        migrations.CreateModel(
            name='ReturnToVendorLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, help_text="Blank copies the source line's description", max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('uom_hint', models.CharField(blank=True, max_length=32, verbose_name='UOM hint')),
                ('quantity_returned', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('condition_note', models.CharField(blank=True, help_text='What is wrong with this specific quantity', max_length=255)),
                ('goods_receipt_line', models.ForeignKey(blank=True, help_text='The received line these goods came in on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_rtv_lines', to='scm.goodsreceiptline')),
                ('po_line', models.ForeignKey(blank=True, help_text='Sizes the expected credit through its unit price', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_rtv_lines', to='scm.purchaseorderline')),
                ('return_to_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.returntovendor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTolerancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'ACME 5% over-receipt', 'Spares strict'", max_length=100)),
                ('over_receipt_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percent of the ordered quantity that may be over-delivered', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('under_receipt_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percent short a delivery may fall and still close the line', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('over_receipt_qty', models.DecimalField(blank=True, decimal_places=4, help_text='Absolute alternative to the percentage — when BOTH are set the MORE RESTRICTIVE wins', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allow_unlimited_over_receipt', models.BooleanField(default=False, help_text='SAP escape flag — when on, over_receipt_pct and over_receipt_qty are IGNORED')),
                ('early_receipt_days', models.PositiveIntegerField(blank=True, help_text='Days a receipt may arrive BEFORE the expected date', null=True)),
                ('late_receipt_days', models.PositiveIntegerField(blank=True, help_text='Days a receipt may arrive AFTER the expected date', null=True)),
                ('action', models.CharField(choices=[('none', 'No Action'), ('warn', 'Warn'), ('block_flag', 'Flag as Blocking')], default='warn', help_text='block_flag FLAGS the line — it never blocks scm:goodsreceipt_receive', max_length=11)),
                ('price_variance_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Advisory mirror of GoodsReceiptNote.PRICE_TOLERANCE_PCT (2%). Wiring it into recompute_match() is an SCM write, parked for 6.13.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('priority', models.PositiveIntegerField(default=10, help_text='Tie-breaker — lower numbers win')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Item category this rule applies to (blank if item-pinned or workspace-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_receipt_tolerances', to='scm.itemcategory')),
                ('item', models.ForeignKey(blank=True, help_text='Specific product (blank for a category or workspace-wide rule)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_receipt_tolerances', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, help_text='Only receipts from this supplier match; blank = any vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_receipt_tolerances', to='core.party')),
            ],
            options={
                'verbose_name': 'Receipt Tolerance Policy',
                'verbose_name_plural': 'Receipt Tolerance Policies',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'priority'], name='prc_rtp_tnt_act_pri_idx'), models.Index(fields=['tenant', 'action'], name='prc_rtp_tnt_action_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='returntovendor',
            index=models.Index(fields=['tenant', 'status'], name='prc_rtv_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returntovendor',
            index=models.Index(fields=['tenant', 'vendor'], name='prc_rtv_tnt_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='returntovendor',
            index=models.Index(fields=['tenant', 'reason'], name='prc_rtv_tnt_reason_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returntovendor',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='receiptdiscrepancy',
            index=models.Index(fields=['tenant', 'status'], name='prc_rds_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdiscrepancy',
            index=models.Index(fields=['tenant', 'kind'], name='prc_rds_tnt_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdiscrepancy',
            index=models.Index(fields=['tenant', 'goods_receipt'], name='prc_rds_tnt_grn_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptdiscrepancy',
            unique_together={('tenant', 'number')},
        ),
    ]
