# Generated by Django 5.1.15 on 2026-08-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0017_receiptdiscrepancy_returntovendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipttolerancepolicy',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Only receipts from this supplier match; blank = any vendor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_receipt_tolerances', to='core.party'),
        ),
    ]
