# Generated by Django 5.1.15 on 2026-08-29 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0018_alter_receipttolerancepolicy_vendor'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='returntovendor',
            index=models.Index(fields=['tenant', 'supplier_rma_number'], name='prc_rtv_tnt_rma_idx'),
        ),
    ]
