# Generated by Django 5.1.15 on 2026-08-30 11:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0019_returntovendor_prc_rtv_tnt_rma_idx'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('invoice_type', models.CharField(choices=[('standard', 'Standard Invoice'), ('credit_memo', 'Credit Memo'), ('debit_memo', 'Debit Memo'), ('prepayment', 'Prepayment / Down-payment Request'), ('service', 'Service Invoice (PO-less)')], default='standard', max_length=20)),
                ('invoice_number', models.CharField(help_text="The supplier's own invoice number", max_length=64)),
                ('invoice_number_norm', models.CharField(db_index=True, editable=False, max_length=64)),
                ('external_ref', models.CharField(blank=True, max_length=64)),
                ('invoice_date', models.DateField()),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, editable=False, null=True)),
                ('discount_date', models.DateField(blank=True, editable=False, null=True)),
                ('discount_expiry_date', models.DateField(blank=True, editable=False, null=True)),
                ('discount_base', models.CharField(choices=[('net_of_tax', 'Net of Tax'), ('gross', 'Gross (Incl. Tax)')], default='net_of_tax', max_length=10)),
                ('discount_grace_days', models.PositiveSmallIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('match_basis', models.CharField(choices=[('quantity', 'Quantity'), ('amount', 'Amount'), ('none', 'No Match')], default='none', max_length=10)),
                ('match_status', models.CharField(choices=[('not_run', 'Not Run'), ('matched', 'Matched'), ('within_tolerance', 'Matched Within Tolerance'), ('price_variance', 'Price Variance'), ('quantity_variance', 'Quantity Variance'), ('total_variance', 'Total Amount Variance'), ('fx_variance', 'FX / Conversion-Rate Variance'), ('no_receipt', 'No Receipt Posted'), ('over_invoiced', 'Over-Invoiced'), ('duplicate_suspect', 'Duplicate Suspect')], default='not_run', editable=False, max_length=20)),
                ('match_notes', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('parked', 'Parked'), ('captured', 'Captured'), ('blocked', 'Blocked'), ('disputed', 'Disputed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('paid', 'Paid'), ('void', 'Void'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Keying'), ('pdf_text_layer', 'PDF Text-Layer Extraction'), ('e_invoice_xml', 'Structured E-Invoice (XML)'), ('vis', 'Vendor Portal Submission'), ('ocr', 'OCR Engine')], default='manual', max_length=20)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('extraction_raw_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices_approved', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='accounting.bill')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='accounting.currency')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='core.document')),
                ('duplicate_of', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='procurement.supplierinvoice')),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='scm.goodsreceiptnote')),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='accounting.journalentry')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='accounting.paymentterm')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='scm.purchaseorder')),
                ('source_submission', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='procurement.vendorinvoicesubmission')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplier_invoices', to='accounting.taxcode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_supplier_invoices', to='core.party')),
            ],
            options={
                'verbose_name': 'supplier invoice',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('reason_code', models.CharField(choices=[('price', 'Price Dispute'), ('quantity', 'Quantity Dispute'), ('goods_not_received', 'Missing Goods'), ('damaged', 'Damaged / Quality'), ('duplicate', 'Duplicate Invoice'), ('credit_not_processed', 'Credit Not Processed'), ('tax', 'Tax / VAT Error'), ('freight', 'Unapproved Freight or Charges'), ('admin', 'Administrative Error'), ('other', 'Other')], max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_supplier', 'Awaiting Supplier'), ('awaiting_internal', 'Awaiting Internal Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', editable=False, max_length=20)),
                ('disputed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField()),
                ('supplier_contact', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('credit_memo', 'Supplier Credit Memo'), ('debit_memo', 'Debit Memo Raised'), ('reinvoice', 'Supplier Re-Invoice'), ('short_pay', 'Short Payment Accepted'), ('withdrawn', 'Dispute Withdrawn')], max_length=16)),
                ('resolution_note', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_invoice_disputes_assigned', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_invoice_disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_invoice_disputes', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('credit_memo_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to='procurement.supplierinvoice')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='procurement.supplierinvoice')),
            ],
            options={
                'verbose_name': 'invoice dispute',
                'ordering': ['-raised_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('uom_hint', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('matched_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=14)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_invoice_lines', to='accounting.glaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.supplierinvoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_invoice_lines', to='scm.item')),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_invoice_lines', to='scm.purchaseorderline')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_invoice_lines', to='scm.goodsreceiptline')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_invoice_lines', to='accounting.taxcode')),
            ],
            options={
                'verbose_name': 'supplier invoice line',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceMatchVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variance_type', models.CharField(choices=[('price', 'Unit Price'), ('quantity', 'Quantity vs Receipt'), ('quantity_no_receipt', 'Quantity vs Order (No Receipt)'), ('over_invoice', 'Cumulative Over-Invoicing'), ('total_amount', 'Header Total'), ('fx_rate', 'FX / Conversion Rate'), ('tax', 'Tax Amount'), ('duplicate', 'Duplicate Invoice'), ('missing_po', 'No PO Reference'), ('missing_receipt', 'No Goods Receipt')], max_length=20)),
                ('basis', models.CharField(choices=[('po', 'Purchase Order'), ('receipt', 'Goods Receipt'), ('header', 'Invoice Header')], default='po', max_length=20)),
                ('expected_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('actual_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('variance_abs', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=18)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=9, null=True)),
                ('tolerance_abs_applied', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('tolerance_pct_applied', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('outcome', models.CharField(choices=[('auto_accept', 'Auto-Accepted (Within Tolerance)'), ('warn', 'Accepted With Warning'), ('block', 'Blocked — Outside Tolerance')], default='auto_accept', max_length=12)),
                ('resolution', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted by AP'), ('disputed', 'Disputed With Supplier'), ('credit_memo', 'Resolved by Credit Memo'), ('debit_memo', 'Resolved by Debit Memo'), ('short_paid', 'Resolved by Short Payment'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variances', to='procurement.invoicedispute')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='procurement.supplierinvoice')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='procurement.supplierinvoiceline')),
            ],
            options={
                'verbose_name': 'invoice match variance',
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoicedispute',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='procurement.supplierinvoiceline'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'status'], name='prc_siv_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'match_status'], name='prc_siv_tnt_match_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'vendor', 'invoice_number_norm'], name='prc_siv_tnt_dup_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'discount_date'], name='prc_siv_tnt_disc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'due_date'], name='prc_siv_tnt_due_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceline',
            index=models.Index(fields=['invoice'], name='prc_sivl_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceline',
            index=models.Index(fields=['po_line'], name='prc_sivl_poline_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicematchvariance',
            index=models.Index(fields=['tenant', 'outcome', 'resolution'], name='prc_imv_tnt_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicematchvariance',
            index=models.Index(fields=['tenant', 'variance_type'], name='prc_imv_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicematchvariance',
            index=models.Index(fields=['invoice'], name='prc_imv_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicedispute',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='prc_dsp_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicedispute',
            index=models.Index(fields=['tenant', 'supplier'], name='prc_dsp_tnt_supplier_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicedispute',
            unique_together={('tenant', 'number')},
        ),
    ]
