# Generated by Django 5.1.15 on 2026-08-31 21:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0020_supplierinvoice_invoicedispute_supplierinvoiceline_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('basis', models.CharField(choices=[('invoiced', 'Invoiced (recognised) spend'), ('committed', 'Committed (PO) spend')], default='invoiced', max_length=12)),
                ('measure', models.CharField(choices=[('net_spend', 'Net spend'), ('transaction_count', 'Transactions'), ('avg_transaction', 'Average transaction value'), ('supplier_count', 'Distinct suppliers'), ('maverick_spend', 'Maverick spend'), ('maverick_pct', 'Maverick spend %'), ('classified_pct', 'Classified spend %'), ('leakage', 'Contract leakage value')], default='net_spend', max_length=20)),
                ('dimension_1', models.CharField(choices=[('supplier', 'Supplier'), ('category', 'Category'), ('department', 'Department / cost centre'), ('gl_account', 'GL account'), ('currency', 'Currency'), ('month', 'Month'), ('quarter', 'Quarter'), ('invoice_type', 'Invoice type'), ('none', '- none -')], default='supplier', max_length=16)),
                ('dimension_2', models.CharField(choices=[('supplier', 'Supplier'), ('category', 'Category'), ('department', 'Department / cost centre'), ('gl_account', 'GL account'), ('currency', 'Currency'), ('month', 'Month'), ('quarter', 'Quarter'), ('invoice_type', 'Invoice type'), ('none', '- none -')], default='none', max_length=16)),
                ('date_range', models.CharField(choices=[('last_30', 'Last 30 days'), ('last_90', 'Last 90 days'), ('quarter', 'This quarter'), ('year', 'This year'), ('all', 'All time'), ('custom', 'Custom range')], default='last_90', max_length=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('table', 'Table only')], default='bar', max_length=10)),
                ('top_n', models.PositiveSmallIntegerField(default=20, help_text='How many grouped rows to keep (1–100); the rest fall into the tail.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_reports', to='scm.itemcategory')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_reports', to='accounting.glaccount')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_reports', to='core.orgunit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_reports', to='core.party')),
            ],
            options={
                'ordering': ['-is_favorite', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpendReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_report_snapshots', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='procurement.spendreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaverickSpendFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('reason', models.CharField(choices=[('no_contract', 'No active contract'), ('po_less_invoice', 'Invoice with no purchase order'), ('no_requisition', 'PO raised with no requisition'), ('off_catalog', 'Item not on an approved catalogue'), ('non_preferred_vendor', 'Bought from a non-preferred supplier'), ('price_above_contract', 'Price above the contracted/catalogue price'), ('suspended_vendor', 'Supplier was blocked or suspended'), ('split_purchase', 'Orders split below an approval threshold')], max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('document_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('benchmark_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('leakage_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('is_addressable', models.BooleanField(default=True)),
                ('dedupe_key', models.CharField(editable=False, max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('justified', 'Justified - accepted'), ('remediated', 'Remediated'), ('dismissed', 'Dismissed - false positive')], default='open', editable=False, max_length=16)),
                ('resolution_note', models.TextField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maverick_findings', to='procurement.catalogitem')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_maverick_findings', to='scm.itemcategory')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_maverick_findings', to='scm.suppliercontract')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maverick_findings', to='procurement.supplierinvoiceline')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_maverick_findings', to='core.orgunit')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_maverick_findings', to='scm.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_maverick_findings_resolved', to=settings.AUTH_USER_MODEL)),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maverick_findings', to='procurement.supplierinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_maverick_findings', to='core.party')),
            ],
            options={
                'verbose_name': 'maverick spend finding',
                'ordering': ['-document_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='prc_msf_tnt_status_idx'), models.Index(fields=['tenant', 'reason'], name='prc_msf_tnt_reason_idx'), models.Index(fields=['tenant', 'document_date'], name='prc_msf_tnt_docdate_idx'), models.Index(fields=['tenant', 'vendor'], name='prc_msf_tnt_vendor_idx')],
                'unique_together': {('tenant', 'dedupe_key'), ('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SpendClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="What this rule is for, e.g. 'ACME → Facilities' or 'GL 6120 → Travel'", max_length=120)),
                ('match_type', models.CharField(choices=[('vendor', 'Supplier'), ('gl_account', 'GL Account'), ('keyword', 'Description / SKU keyword'), ('invoice_type', 'Invoice Type'), ('org_unit', 'Department / Cost Centre')], default='vendor', help_text='Which attribute of a spend line this rule reads', max_length=20)),
                ('keyword', models.CharField(blank=True, help_text='Case-insensitive fragment matched against the line description and SKU hint', max_length=120)),
                ('invoice_type', models.CharField(blank=True, help_text='Supplier-invoice type (standard, credit memo, service …). Invoiced basis only — a purchase order has no invoice type.', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text="Lower numbers win. Ties break on the rule's id.")),
                ('applies_to', models.CharField(choices=[('both', 'Invoiced + Committed'), ('invoiced', 'Invoiced only'), ('committed', 'Committed (PO) only')], default='both', help_text='Which spend basis this rule governs', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('match_count', models.PositiveIntegerField(default=0, editable=False, help_text='Lines matched by the most recent preview run — a usage counter, not a balance')),
                ('last_matched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(help_text='Category every matching line is classified into', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_spend_rules', to='scm.itemcategory')),
                ('gl_account', models.ForeignKey(blank=True, help_text='GL account coded on the line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_rules', to='accounting.glaccount')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Requesting department / cost centre behind the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_rules', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, help_text='Supplier whose spend this rule classifies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_spend_rules', to='core.party')),
            ],
            options={
                'verbose_name': 'Spend Classification Rule',
                'verbose_name_plural': 'Spend Classification Rules',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='prc_scr_tnt_active_idx'), models.Index(fields=['tenant', 'match_type'], name='prc_scr_tnt_mtype_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='spendreport',
            index=models.Index(fields=['tenant', 'measure'], name='prc_spr_tnt_measure_idx'),
        ),
        migrations.AddIndex(
            model_name='spendreport',
            index=models.Index(fields=['tenant', 'is_favorite'], name='prc_spr_tnt_fav_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spendreport',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='spendreportsnapshot',
            index=models.Index(fields=['tenant', 'report'], name='prc_sprsnap_tnt_rpt_idx'),
        ),
    ]
