# Generated by Django 5.1.15 on 2026-09-01 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0021_spendreport_spendreportsnapshot_maverickspendfinding_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoicematchvariance',
            index=models.Index(fields=['tenant', '-detected_at'], name='prc_imv_tnt_detected_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', '-invoice_date'], name='prc_siv_tnt_invdate_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'status', 'invoice_date'], name='prc_siv_tnt_status_dt_idx'),
        ),
    ]
