# Generated by Django 5.1.15 on 2026-09-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_invoicematchvariance_prc_imv_tnt_detected_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendreportsnapshot',
            options={'ordering': ['-generated_at', '-id']},
        ),
    ]
