# Generated by Django 5.1.15 on 2026-09-01 14:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0023_alter_spendreportsnapshot_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text="Lower numbers win. Ties break on the mapping's id.")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('budget', models.ForeignKey(help_text='The accounting budget this mapping governs spend against', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_budget_mappings', to='accounting.budget')),
                ('default_gl_account', models.ForeignKey(blank=True, help_text='GL account to pre-fill when raising requisitions under this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_budget_mappings', to='accounting.glaccount')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Department / cost centre this mapping applies to (blank = any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_budget_mappings', to='core.orgunit')),
                ('project', models.ForeignKey(blank=True, help_text='Project this mapping applies to (blank = any). Project mappings are more specific than department ones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_budget_mappings', to='accounting.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Budget Mapping',
                'verbose_name_plural': 'Budget Mappings',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='prc_bmap_tnt_active_idx'), models.Index(fields=['tenant', 'budget'], name='prc_bmap_tnt_budget_idx')],
            },
        ),
        migrations.CreateModel(
            name='CostForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text="What this forecast is for, e.g. 'Q3 ops spend projection'", max_length=120)),
                ('method', models.CharField(choices=[('open_pos', 'Open POs'), ('run_rate', 'Run rate (historical)'), ('blended', 'Blended')], default='blended', help_text='How the projection is arrived at — arithmetic only, never a model', max_length=10)),
                ('horizon_months', models.PositiveSmallIntegerField(default=3, help_text='Months ahead to project (and the history window for run rate), 1-24', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('as_of', models.DateField(default=django.utils.timezone.localdate, help_text='The date the figures are computed as at')),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Open purchase-order commitment at the as-of date', max_digits=18)),
                ('historical_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Recognised invoices over the horizon window before the as-of date', max_digits=18)),
                ('forecast_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='The projection itself, per the chosen method', max_digits=18)),
                ('assumptions', models.TextField(blank=True, help_text='What the reader should know: scope, exclusions, why this method')),
                ('budget', models.ForeignKey(blank=True, help_text='Budget whose GL accounts scope this forecast (blank = whole workspace)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_cost_forecasts', to='accounting.budget')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_cost_forecasts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, help_text='Display currency label — sums are at face value, nothing is converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_cost_forecasts', to='accounting.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cost Forecast',
                'verbose_name_plural': 'Cost Forecasts',
                'ordering': ['-as_of', '-id'],
                'indexes': [models.Index(fields=['tenant', 'as_of'], name='prc_fcst_tnt_asof_idx'), models.Index(fields=['tenant', 'budget'], name='prc_fcst_tnt_budget_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
