# Generated by Django 5.1.15 on 2026-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0024_budgetmapping_costforecast'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='budgetmapping',
            name='prc_bmap_tnt_active_idx',
        ),
        migrations.AddIndex(
            model_name='budgetmapping',
            index=models.Index(fields=['tenant', 'is_active', 'priority', 'id'], name='prc_bmap_tnt_active_idx'),
        ),
    ]
