# Generated by Django 5.1.15 on 2026-09-05 09:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0028_uomconversion'),
        ('procurement', '0026_procurementdocument_knowledgeresource_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('movement_type', models.CharField(choices=[('issue', 'Issue'), ('return', 'Return to stock')], default='issue', help_text='Issue takes stock out of the location; Return puts unused material back in. Returning goods to a SUPPLIER is a different document — 6.12 Return to Vendor.', max_length=8)),
                ('purpose', models.CharField(choices=[('cost_centre', 'Cost centre'), ('project', 'Project'), ('work_order', 'Work order'), ('maintenance', 'Maintenance'), ('sample', 'Sample'), ('other', 'Other')], default='cost_centre', help_text="What consumed the material. 'Other' requires a note — a consumption nobody can categorise is exactly the one that needs explaining.", max_length=12)),
                ('reference', models.CharField(blank=True, help_text="Free text: the project, job or work-order number this was drawn for, e.g. JOB-0042. Deliberately NOT a foreign key to scm.WorkOrder — that is module 4.8's manufacturing object and a procurement issue is not a production draw (which is why StockMove carries separate 'consumption' and 'maintenance' move types). Anything a store issues against, including a purely external job number, can be keyed here.", max_length=64)),
                ('issue_date', models.DateField(help_text="The date the material actually left (or came back to) the shelf. The minted stock adjustment carries this same date, not today's.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(blank=True, editable=False, help_text='The DRAFT scm.StockAdjustment this issue minted when it was posted. Stock does not move until SCM posts THAT document. The CycleCountTask.adjustment provenance precedent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issues', to='scm.stockadjustment')),
                ('gl_account', models.ForeignKey(blank=True, help_text='Default expense account for the document. A line may override it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issues', to='accounting.glaccount')),
                ('issued_by', models.ForeignKey(blank=True, editable=False, help_text='Who posted the document (system-stamped at post).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issues_issued', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='The location material is issued FROM, or returned TO. PROTECTed because a posted issue is the evidence for a stock movement — deleting the location out from under it would leave a movement nothing explains.', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_material_issues', to='scm.location')),
                ('org_unit', models.ForeignKey(blank=True, help_text='The cost centre / department the consumption belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issues', to='core.orgunit')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Who asked for the material. Not necessarily who handed it over.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issues_requested', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, help_text="Optional: the soft lock this issue consumes (SAP's MB21 reservation feeding the MB1A issue). Linked out to, never re-declared here — 5.6 owns reservations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issues', to='inventory.inventoryreservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Material Issue',
                'verbose_name_plural': 'Material Issues',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text="Always POSITIVE. Direction comes from the document's movement type, which is what becomes the sign on the stock adjustment line.", max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, editable=False, help_text="Snapshot of the item's moving-average cost when the line was added.", max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('gl_account', models.ForeignKey(blank=True, help_text="Per-line override of the document's expense account.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issue_lines', to='accounting.glaccount')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.materialissue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_material_issue_lines', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Optional lot/batch or serial for a tracked item. It rides through to the minted stock adjustment line, so the ledger records which lot actually moved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_material_issue_lines', to='scm.lotserial')),
            ],
            options={
                'verbose_name': 'Material Issue Line',
                'verbose_name_plural': 'Material Issue Lines',
                'ordering': ['item__sku', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_method', models.CharField(choices=[('buy', 'Buy'), ('transfer', 'Transfer'), ('manufacture', 'Manufacture')], default='buy', help_text="How the shortfall is covered. Only 'Buy' raises a requisition; 'Transfer' and 'Manufacture' are recorded and reported but never purchased automatically.", max_length=12)),
                ('trigger_mode', models.CharField(choices=[('review', 'Review then release'), ('auto', 'Automatic')], default='review', help_text="'Review then release' proposes and waits for a person. 'Automatic' marks the policy as one a scheduled run may propose for — releasing the money is still a human action either way.", max_length=8)),
                ('target_level', models.DecimalField(blank=True, decimal_places=2, help_text="Order-up-to level. Blank falls back to the reorder rule's reorder point plus safety stock — this is an OVERRIDE, never a copy of the rule.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('order_multiple', models.DecimalField(blank=True, decimal_places=2, help_text='Round the suggested quantity UP to a multiple of this (case or pallet size)', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Vendor minimum order quantity — a smaller shortfall is raised to this', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_order_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Hard ceiling on one suggested line. Applied LAST, so it wins over the multiple.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('include_on_order', models.BooleanField(default=True, help_text='Net open purchase-order quantity off the shortfall before proposing. The scm reorder alert tests on-hand alone, which is why it keeps re-proposing what has already been ordered.')),
                ('include_open_requisitions', models.BooleanField(default=True, help_text='Also net off quantity already sitting on un-converted requisitions')),
                ('lead_time_days_override', models.PositiveIntegerField(blank=True, help_text="Replenishment lead time in days. Blank falls back to the reorder rule's own lead time — this is an OVERRIDE, never a copy.", null=True, validators=[django.core.validators.MaxValueValidator(3650)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive policies are never resolved. Prefer deactivating over deleting when an item is phased out — the history stays readable.')),
                ('notes', models.TextField(blank=True)),
                ('default_budget', models.ForeignKey(blank=True, help_text='Budget to stamp on the generated requisition (the amounts stay in accounting)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_policies', to='accounting.budget')),
                ('default_gl_account', models.ForeignKey(blank=True, help_text='Expense account to pre-fill on the generated requisition line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_policies', to='accounting.glaccount')),
                ('default_org_unit', models.ForeignKey(blank=True, help_text='Department / cost centre to stamp on the generated requisition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_policies', to='core.orgunit')),
                ('item', models.ForeignKey(help_text='The item this policy replenishes', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_replenishment_policies', to='scm.item')),
                ('location', models.ForeignKey(blank=True, help_text='Location this policy applies to. Blank = any location — the catch-all that a location-specific policy overrides.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_policies', to='scm.location')),
                ('preferred_vendor', models.ForeignKey(blank=True, help_text='Vendor the generated requisition is grouped under (blank = decided at release)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_policies', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Replenishment Policy',
                'verbose_name_plural': 'Replenishment Policies',
                'ordering': ['item__sku', 'location__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('run_date', models.DateField(help_text="The date this proposal is for. Requisition due dates are counted forward from it using each line's lead time.")),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', help_text="How this run was started. 'Scheduled' records that a timetable asked for it — the column ships, the cron does not, exactly as CountProgram.is_due() does.", max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('abc_class_filter', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='Plan only this ABC class. GOTCHA: this filters scm.ReorderRule.abc_class, which is the UPPERCASE revenue rank A/B/C — NOT scm.Location.abc_class, which is the lowercase bin-velocity attribute a/b/c. They are different things.', max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('generated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last generated the proposal (system-stamped)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_runs', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Location to plan for. Blank = the whole network, which is also the only scope where the network-wide on-order figure is a rough netting rather than exact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_runs', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Replenishment Run',
                'verbose_name_plural': 'Replenishment Runs',
                'ordering': ['-run_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16)),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Sales-order allocations plus inventory reservations', max_digits=16)),
                ('on_order_qty', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Outstanding on receivable purchase orders, network-wide (PO lines carry no location)', max_digits=16)),
                ('open_requisition_qty', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16)),
                ('available_qty', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='on hand − claims − non-sellable. Recorded for the reader; the trigger is on-hand plus supply.', max_digits=16)),
                ('reorder_point_snapshot', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16)),
                ('target_level_snapshot', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16)),
                ('raw_suggested_qty', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='The shortfall before rounding — kept so the rounding is auditable, not just its result', max_digits=16)),
                ('suggested_qty', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('lead_time_days', models.PositiveIntegerField(default=0, editable=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('snooze_until', models.DateField(blank=True, help_text='Required when snoozing, and it has to be in the future — a snooze that has already expired is a dismissal wearing a different label.', null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_replenishment_suggestions', to='scm.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_replenishment_suggestions', to='scm.location')),
                ('policy', models.ForeignKey(blank=True, help_text='The policy that shaped this line. Null means the item had none and the run used plain defaults — which is worth seeing, not worth hiding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='procurement.replenishmentpolicy')),
                ('reorder_rule', models.ForeignKey(blank=True, help_text='The rule this line was computed from. SET_NULL — deleting a rule must not delete the record of a decision that was taken while it existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_suggestions', to='scm.reorderrule')),
                ('requisition', models.ForeignKey(blank=True, editable=False, help_text='The requisition this line was released into (system-stamped)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_suggestions', to='scm.purchaserequisition')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.replenishmentrun')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor this line is grouped under at release. Defaulted from the policy and overridable per line.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_replenishment_suggestions', to='core.party')),
            ],
            options={
                'verbose_name': 'Replenishment Suggestion',
                'verbose_name_plural': 'Replenishment Suggestions',
                'ordering': ['item__sku', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['tenant', 'status'], name='prc_mis_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['tenant', 'issue_date'], name='prc_mis_tnt_date_idx'),
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['tenant', 'movement_type'], name='prc_mis_tnt_mvt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialissue',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='replenishmentpolicy',
            index=models.Index(fields=['tenant', 'is_active', 'item'], name='prc_rpol_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentpolicy',
            index=models.Index(fields=['tenant', 'item', 'location'], name='prc_rpol_tnt_item_loc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='replenishmentpolicy',
            unique_together={('tenant', 'item', 'location')},
        ),
        migrations.AddIndex(
            model_name='replenishmentrun',
            index=models.Index(fields=['tenant', 'status'], name='prc_rpl_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrun',
            index=models.Index(fields=['tenant', 'run_date'], name='prc_rpl_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='replenishmentrun',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='replenishmentsuggestion',
            index=models.Index(fields=['run', 'decision'], name='prc_rsg_run_dec_idx'),
        ),
    ]
