# Generated by Django 5.1.15 on 2026-09-05 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0028_compliancescreening_fraudalert_policyattestation_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='procurementdocumentrevision',
            name='prc_pdrev_tnt_doc_idx',
        ),
        migrations.AddIndex(
            model_name='procurementdocument',
            index=models.Index(fields=['tenant', 'review_on'], name='prc_pdoc_tnt_review_idx'),
        ),
    ]
