# Generated by Django 5.1.15 on 2026-09-05 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('procurement', '0029_remove_procurementdocumentrevision_prc_pdrev_tnt_doc_idx_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditseal',
            name='prc_asl_tnt_sealed_idx',
        ),
        migrations.RemoveIndex(
            model_name='policyattestation',
            name='prc_patt_tnt_policy_idx',
        ),
        migrations.AddField(
            model_name='auditseal',
            name='last_verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_audit_seal_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='document_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='procurementalert',
            name='kind',
            field=models.CharField(choices=[('deadline', 'Deadline'), ('approval', 'Approval'), ('delivery', 'Delivery'), ('task', 'Task'), ('contract', 'Contract'), ('risk', 'Risk')], default='task', max_length=12),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['tenant', 'assigned_to'], name='prc_frd_tnt_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierfeedback',
            index=models.Index(fields=['tenant', '-period_end', '-id'], name='prc_sfb_tnt_period_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierimprovementplan',
            index=models.Index(fields=['tenant', '-start_date', '-id'], name='prc_sip_tnt_start_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierkpiscore',
            index=models.Index(fields=['tenant', 'kpi_category', 'kpi_name', 'id'], name='prc_sks_tnt_cat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierrisksignal',
            index=models.Index(fields=['tenant', 'observed_on'], name='prc_srs_tnt_obs_idx'),
        ),
    ]
