# Generated by Django 5.1.15 on 2026-06-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_activity_tenant_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['tenant', 'status'], name='core_emp_tenant_status_idx'),
        ),
    ]
