# Generated by Django 5.1.15 on 2026-06-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrole',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('lead', 'Lead'), ('candidate', 'Candidate'), ('contact', 'Contact'), ('partner', 'Partner')], max_length=20),
        ),
    ]
