# Generated by Django 5.1.15 on 2026-09-19 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text='Custom domain for this workspace, e.g. acme.example.com.', max_length=253, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(?=.{1,253}$)(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$', 'Enter a valid domain, e.g. acme.example.com.')]),
        ),
    ]
