# Generated by Django 5.1.15 on 2026-09-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordpolicy_loginattempt_mfadevice_and_more'),
        ('core', '0005_tenant_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.CharField(max_length=4)),
                ('module_slug', models.CharField(max_length=40)),
                ('module_title', models.CharField(max_length=150)),
                ('is_enabled', models.BooleanField(default=True, help_text="Off hides the module's data from members of this workspace.")),
                ('data_scope', models.CharField(choices=[('all', 'All records'), ('team', 'Team / department only'), ('own', 'Own records only')], default='all', max_length=10)),
                ('requires_approval', models.BooleanField(default=False, help_text='Adjustments in this module need an approval before they take effect.')),
                ('mask_sensitive', models.BooleanField(default=False, help_text='Apply the field masks configured below.')),
                ('period_lock_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_scopes', to='core.tenant')),
            ],
            options={
                'ordering': ['module_number', 'module_slug'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveFieldMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='The model field to mask, e.g. bank_account.', max_length=64)),
                ('mask_style', models.CharField(choices=[('full', 'Fully hidden'), ('partial', 'Keep first and last character'), ('last4', 'Keep the last 4 characters'), ('email', 'Email style (first letter + domain)')], default='partial', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exempt_roles', models.ManyToManyField(blank=True, related_name='+', to='accounts.role')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='core.moduleaccessscope')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_field_masks', to='core.tenant')),
            ],
            options={
                'ordering': ['scope', 'field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='moduleaccessscope',
            index=models.Index(fields=['tenant', 'module_slug'], name='modscope_tenant_slug_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleaccessscope',
            unique_together={('tenant', 'module_slug')},
        ),
        migrations.AlterUniqueTogether(
            name='sensitivefieldmask',
            unique_together={('scope', 'field_name')},
        ),
    ]
