# Generated by Django 5.1.15 on 2026-09-19 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_moduleaccessscope_sensitivefieldmask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=60)),
                ('lawful_basis', models.CharField(choices=[('consent', 'Consent'), ('contract', 'Contract'), ('legal_obligation', 'Legal obligation'), ('vital_interest', 'Vital interest'), ('public_task', 'Public task'), ('legitimate_interest', 'Legitimate interest')], default='consent', max_length=24)),
                ('is_optional', models.BooleanField(default=True, help_text='Only meaningful when the lawful basis is Consent.')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_purposes', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn')], default='granted', max_length=12)),
                ('source', models.CharField(choices=[('web_form', 'Web form'), ('email', 'Email'), ('phone', 'Phone'), ('in_person', 'In person'), ('imported', 'Imported'), ('api', 'API')], default='web_form', max_length=20)),
                ('evidence', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='core.party')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.consentpurpose')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('access', 'Access (copy of data)'), ('rectification', 'Rectification'), ('erasure', 'Erasure / right to be forgotten'), ('portability', 'Portability (machine-readable export)'), ('restriction', 'Restriction of processing'), ('objection', 'Objection to processing')], max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verifying', 'Verifying identity'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('refused', 'Refused'), ('withdrawn', 'Withdrawn by the subject')], default='received', max_length=20)),
                ('detail', models.TextField(help_text='What the subject asked for, in their own words.')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('identity_verified', models.BooleanField(default=False)),
                ('verification_note', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('refusal_reason', models.TextField(blank=True)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_dsars', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subject_requests', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subject_requests', to='core.tenant')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PiiClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=120)),
                ('field_name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('identifier', 'Identifier (name, email, phone)'), ('financial', 'Financial'), ('health', 'Health'), ('biometric', 'Biometric'), ('location', 'Location'), ('online', 'Online identifier'), ('special', 'Special category'), ('unknown', 'Unclassified')], default='unknown', max_length=20)),
                ('sensitivity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('confirmation', models.CharField(choices=[('suggested', 'Suggested by scan'), ('confirmed', 'Confirmed by a human'), ('dismissed', 'Dismissed — not PII')], default='suggested', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_classifications', to='core.tenant')),
            ],
            options={
                'ordering': ['model_label', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('gdpr', 'GDPR (EU)'), ('ccpa', 'CCPA / CPRA (California)'), ('hipaa', 'HIPAA (US health)'), ('lgpd', 'LGPD (Brazil)'), ('pipeda', 'PIPEDA (Canada)'), ('other', 'Other / local')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('is_enabled', models.BooleanField(default=False)),
                ('dsar_window_days', models.PositiveIntegerField(default=30, help_text='Statutory window to answer a data-subject request, in days.')),
                ('data_residency_region', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_frameworks', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data_category', models.CharField(max_length=120)),
                ('model_label', models.CharField(blank=True, max_length=120)),
                ('retention_months', models.PositiveIntegerField(default=12, help_text='How long the data is kept from its creation.')),
                ('action', models.CharField(choices=[('review', 'Flag for review'), ('delete', 'Delete'), ('anonymize', 'Anonymize'), ('archive', 'Archive')], default='review', max_length=12)),
                ('basis', models.CharField(choices=[('legal', 'Legal requirement'), ('contract', 'Contractual'), ('consent', 'Consent'), ('legitimate_interest', 'Legitimate interest'), ('operational', 'Operational need')], default='legal', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(blank=True, max_length=120)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(choices=[('deleted', 'Deleted from the database'), ('anonymized', 'Anonymized in place'), ('archived', 'Moved to archive'), ('destroyed_media', 'Destroyed with the media'), ('other', 'Other')], default='deleted', max_length=20)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_records', to='core.tenant')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals', to='core.retentionpolicy')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='consentpurpose',
            index=models.Index(fields=['tenant', 'is_active'], name='cpurp_tenant_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consentpurpose',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant', 'party', '-occurred_at'], name='crec_tenant_party_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant', 'purpose', 'action'], name='crec_tenant_purpose_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['tenant', 'status'], name='dsar_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['tenant', 'due_at'], name='dsar_tenant_due_idx'),
        ),
        migrations.AddIndex(
            model_name='piiclassification',
            index=models.Index(fields=['tenant', 'confirmation'], name='pii_tenant_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='piiclassification',
            index=models.Index(fields=['tenant', 'sensitivity'], name='pii_tenant_sens_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='piiclassification',
            unique_together={('tenant', 'model_label', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='regulatoryframework',
            index=models.Index(fields=['tenant', 'is_enabled'], name='regfw_tenant_enabled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regulatoryframework',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='retentionpolicy',
            index=models.Index(fields=['tenant', 'is_active'], name='retpol_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrecord',
            index=models.Index(fields=['tenant', '-performed_at'], name='disp_tenant_at_idx'),
        ),
    ]
