# Generated by Django 5.1.15 on 2026-09-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordpolicy_loginattempt_mfadevice_and_more'),
        ('core', '0007_consentpurpose_consentrecord_datasubjectrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('timezone_name', models.CharField(blank=True, help_text="IANA name, e.g. 'Europe/London'.", max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_calendar', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(max_length=40)),
                ('entity_label', models.CharField(help_text="e.g. 'crm.Lead' — the entity the field extends.", max_length=120)),
                ('field_key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Yes / No'), ('date', 'Date'), ('choice', 'Choice')], default='text', max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('validation_regex', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='core.tenant')),
            ],
            options={
                'ordering': ['module_slug', 'entity_label', 'display_order', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_label', models.CharField(max_length=120)),
                ('object_id', models.BigIntegerField()),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.customfielddefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity_label', 'object_id', 'definition__display_order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable identifier, e.g. 'projects.gantt'.", max_length=120)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('applies_to_plan', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exempt_roles', models.ManyToManyField(blank=True, related_name='feature_flags', to='accounts.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='core.tenant')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False, help_text="Repeats on the same month/day every year (e.g. New Year's Day).")),
                ('region', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.tenant')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(help_text="e.g. 'Purchase Order'.", max_length=150)),
                ('prefix', models.CharField(help_text="e.g. 'PO' — matches TenantNumbered.NUMBER_PREFIX.", max_length=20)),
                ('padding_width', models.PositiveIntegerField(default=5)),
                ('reset_rule', models.CharField(choices=[('never', 'Never resets'), ('yearly', 'Resets each year'), ('monthly', 'Resets each month')], default='never', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_schemes', to='core.tenant')),
            ],
            options={
                'ordering': ['document_kind'],
            },
        ),
        migrations.CreateModel(
            name='SettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable identifier, e.g. 'accounting.default_payment_terms'.", max_length=120, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('module_slug', models.CharField(blank=True, help_text='Which module owns it; blank means platform-wide.', max_length=40)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('choice', 'Choice')], default='text', max_length=10)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('help_text', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked settings show in the register but cannot be overridden.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module_slug', 'key'],
                'indexes': [models.Index(fields=['module_slug', 'key'], name='setdef_module_key_idx')],
            },
        ),
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.settingdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_values', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['definition__module_slug', 'definition__key'],
            },
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['tenant', 'entity_label'], name='cfdef_tenant_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['tenant', 'module_slug'], name='cfdef_tenant_module_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfielddefinition',
            unique_together={('tenant', 'entity_label', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['tenant', 'entity_label', 'object_id'], name='cfval_tenant_entity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('definition', 'entity_label', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['tenant', 'key'], name='flag_tenant_key_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureflag',
            unique_together={('tenant', 'key')},
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'date'], name='holiday_tenant_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('tenant', 'date', 'name')},
        ),
        migrations.AddIndex(
            model_name='numberingscheme',
            index=models.Index(fields=['tenant', 'prefix'], name='numscheme_tenant_prefix_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='numberingscheme',
            unique_together={('tenant', 'prefix')},
        ),
        migrations.AddIndex(
            model_name='settingvalue',
            index=models.Index(fields=['tenant', 'definition'], name='setval_tenant_def_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='settingvalue',
            unique_together={('tenant', 'definition')},
        ),
    ]
