# Generated by Django 5.1.15 on 2026-09-21 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordpolicy_loginattempt_mfadevice_and_more'),
        ('core', '0008_businesscalendar_customfielddefinition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module_slug', models.CharField(max_length=40)),
                ('trigger', models.CharField(choices=[('on_create', 'On create'), ('on_update', 'On update'), ('on_status_change', 'On status change'), ('on_approval', 'On approval decision'), ('on_evaluation', 'On manual evaluation')], default='on_create', max_length=20)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('flag', 'Flag for attention'), ('require_approval', 'Require an approval'), ('notify_role', 'Notify a role'), ('block', 'Block the operation'), ('set_field', 'Set a field')], default='flag', max_length=20)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(max_length=40)),
                ('trigger', models.CharField(max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('matched', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.businessrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_rule_logs', to='core.tenant')),
            ],
            options={
                'ordering': ['-evaluated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SlaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module_slug', models.CharField(max_length=40)),
                ('engine_label', models.CharField(blank=True, help_text='Optional: restrict the rule to one engine.', max_length=120)),
                ('hours', models.PositiveIntegerField(help_text='Hours after which the rule fires.')),
                ('action', models.CharField(choices=[('remind', 'Remind the approver'), ('escalate', 'Escalate to the next tier'), ('auto_approve', 'Auto-approve on timeout'), ('auto_reject', 'Auto-reject on timeout')], default='remind', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalate_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_rules', to='accounts.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['module_slug', 'hours'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module_slug', models.CharField(max_length=40)),
                ('engine_label', models.CharField(blank=True, help_text='The model holding the decision rows, e.g. procurement.RequisitionApproval.', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_hours', models.PositiveIntegerField(default=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_role', models.ForeignKey(blank=True, help_text='Who owns this process, not who approves in it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workflows', to='accounts.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='core.tenant')),
            ],
            options={
                'ordering': ['module_slug', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('is_parallel', models.BooleanField(default=False)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='accounts.role')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workflowdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='core.tenant')),
            ],
            options={
                'ordering': ['definition', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(max_length=40)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Above this, the approval must escalate.', max_digits=14)),
                ('currency_code', models.CharField(blank=True, default='USD', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_limits', to='accounts.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_limits', to='core.tenant')),
            ],
            options={
                'ordering': ['module_slug', 'role__name'],
                'indexes': [models.Index(fields=['tenant', 'module_slug'], name='aplimit_tenant_module_idx')],
                'unique_together': {('tenant', 'module_slug', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['tenant', 'module_slug', 'trigger'], name='brule_tenant_mod_trig_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessrule',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='businessrulelog',
            index=models.Index(fields=['tenant', '-evaluated_at'], name='brlog_tenant_at_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrulelog',
            index=models.Index(fields=['tenant', 'module_slug'], name='brlog_tenant_module_idx'),
        ),
        migrations.AddIndex(
            model_name='slarule',
            index=models.Index(fields=['tenant', 'module_slug'], name='slarule_tenant_module_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['tenant', 'module_slug'], name='wfdef_tenant_module_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['tenant', 'definition'], name='wfstep_tenant_def_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('definition', 'sequence', 'name')},
        ),
    ]
