# Generated by Django 5.1.15 on 2026-09-21 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordpolicy_loginattempt_mfadevice_and_more'),
        ('core', '0009_businessrule_businessrulelog_slarule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('chat', 'Chat (Slack / Teams)')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('is_enabled', models.BooleanField(default=False, help_text='Off by default: enabling a channel without a provider behind it sends nothing.')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='core.tenant')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=120)),
                ('channel_kind', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('chat', 'Chat (Slack / Teams)')], max_length=10)),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck to opt out of this event on this channel.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'event', 'channel_kind'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable identifier, e.g. 'invoice_overdue'.", max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('channel_kind', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('chat', 'Chat (Slack / Teams)')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('locale', models.CharField(blank=True, default='en', help_text="e.g. 'en', 'fr-CA'. Blank means the workspace default.", max_length=10)),
                ('module_slug', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['module_slug', 'code', 'locale'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event', models.CharField(help_text="The event key, e.g. 'invoice.overdue'.", max_length=120)),
                ('module_slug', models.CharField(blank=True, max_length=40)),
                ('audience_kind', models.CharField(choices=[('role', 'Everyone holding a role'), ('user', 'One named user'), ('party', 'The related party (customer / vendor)'), ('all', 'Everyone in the workspace')], default='role', max_length=10)),
                ('digest', models.CharField(choices=[('immediate', 'Send immediately'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest')], default='immediate', max_length=10)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audience_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='accounts.role')),
                ('audience_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.notificationchannel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='core.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='core.notificationtemplate')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_kind', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('chat', 'Chat (Slack / Teams)')], max_length=10)),
                ('label', models.CharField(max_length=150)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('api_endpoint', models.CharField(blank=True, max_length=255)),
                ('credential_env_var', models.CharField(blank=True, help_text='Name of the environment variable holding the secret. Never the secret itself.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='core.tenant')),
            ],
            options={
                'ordering': ['channel_kind', 'priority'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['tenant', 'is_enabled'], name='nchan_tenant_enabled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationchannel',
            unique_together={('tenant', 'kind')},
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['tenant', 'user'], name='npref_tenant_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'event', 'channel_kind')},
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'code'], name='ntmpl_tenant_code_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('tenant', 'code', 'locale')},
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['tenant', 'event', 'is_active'], name='nrule_tenant_event_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationrule',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='providerconfig',
            index=models.Index(fields=['tenant', 'channel_kind'], name='nprov_tenant_kind_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerconfig',
            unique_together={('tenant', 'channel_kind', 'label')},
        ),
    ]
