# Generated by Django 5.1.15 on 2026-09-21 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notificationchannel_notificationpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('api_key', 'API key'), ('oauth_client', 'OAuth client'), ('service_account', 'Service account token')], default='api_key', max_length=20)),
                ('prefix', models.CharField(editable=False, max_length=16)),
                ('key_hash', models.CharField(editable=False, max_length=64)),
                ('scopes', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_api_credentials', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('erp', 'ERP'), ('crm', 'CRM'), ('accounting', 'Accounting'), ('logistics', 'Logistics'), ('payments', 'Payments'), ('messaging', 'Messaging'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('engine_label', models.CharField(blank=True, help_text="The model holding this connector's config, e.g. projects.ProjectIntegrationConnector.", max_length=120)),
                ('is_installed', models.BooleanField(default=False, help_text='Off until the connector is actually configured — a catalogue entry is not an install.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_definitions', to='core.tenant')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('source_format', models.CharField(blank=True, help_text="e.g. 'X12 850', 'CSV', 'JSON'.", max_length=40)),
                ('target_label', models.CharField(blank=True, help_text="The entity this maps onto, e.g. 'scm.PurchaseOrder'.", max_length=120)),
                ('mappings', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['direction', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('max_requests', models.PositiveIntegerField(default=1000)),
                ('window', models.CharField(choices=[('minute', 'Per minute'), ('hour', 'Per hour'), ('day', 'Per day')], default='hour', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='core.apicredential')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_policies', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('transport', models.CharField(choices=[('api', 'REST API'), ('sftp', 'SFTP'), ('file', 'File drop'), ('edi', 'EDI'), ('webhook', 'Webhook')], default='api', max_length=10)),
                ('frequency', models.CharField(choices=[('manual', 'Manual only'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=10)),
                ('entity_label', models.CharField(blank=True, help_text="What is exchanged, e.g. 'inventory.Item'.", max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.connectordefinition')),
                ('mapping_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.mappingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedules', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='apicredential',
            index=models.Index(fields=['tenant', 'is_active'], name='apicred_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='apicredential',
            index=models.Index(fields=['key_hash'], name='apicred_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='connectordefinition',
            index=models.Index(fields=['tenant', 'category'], name='connector_tenant_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectordefinition',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='mappingtemplate',
            index=models.Index(fields=['tenant', 'direction'], name='mapping_tenant_dir_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mappingtemplate',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='ratelimitpolicy',
            index=models.Index(fields=['tenant', 'is_active'], name='ratelimit_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='syncschedule',
            index=models.Index(fields=['tenant', 'frequency'], name='syncsched_tenant_freq_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncschedule',
            unique_together={('tenant', 'name')},
        ),
    ]
