# Generated by Django 5.1.15 on 2026-09-21 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0011_apicredential_connectordefinition_mappingtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="ISO 639-1 code, e.g. 'en', 'fr', 'ar'.", max_length=8, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('native_name', models.CharField(blank=True, help_text="The language's own name, e.g. 'العربية'.", max_length=60)),
                ('is_rtl', models.BooleanField(default=False, help_text='Rendered right-to-left.')),
                ('is_default', models.BooleanField(default=False, help_text='The platform fallback language.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="IANA name, e.g. 'Europe/London'.", max_length=64, unique=True)),
                ('label', models.CharField(help_text="Human label, e.g. 'London (GMT/BST)'.", max_length=100)),
                ('utc_offset_minutes', models.IntegerField(default=0)),
                ('observes_dst', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['utc_offset_minutes', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocaleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(default='dd/MM/yyyy', max_length=40)),
                ('time_format', models.CharField(default='HH:mm', max_length=40)),
                ('number_format', models.CharField(default='#,##0.00', max_length=40)),
                ('address_format', models.TextField(blank=True, help_text='Multi-line address template.')),
                ('first_day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currency')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.language')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locale_profile', to='core.tenant')),
                ('time_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.timezone')),
            ],
            options={
                'ordering': ['tenant__name'],
            },
        ),
        migrations.CreateModel(
            name='UserLocalePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.language')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locale_preferences', to='core.tenant')),
                ('time_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.timezone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locale_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('jurisdiction', models.CharField(blank=True, max_length=120)),
                ('e_invoicing_required', models.BooleanField(default=False)),
                ('e_invoicing_scheme', models.CharField(choices=[('none', 'Not required'), ('peppol', 'PEPPOL / EU'), ('sdi', 'Italy SDI'), ('cfdi', 'Mexico CFDI'), ('gst_irn', 'India GST IRN'), ('other', 'Other')], default='none', max_length=12)),
                ('statutory_report', models.CharField(blank=True, help_text="e.g. 'VAT Return (MTD)'.", max_length=150)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_rules', to='accounting.taxcode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['jurisdiction', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='statrule_tenant_active_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
