# Generated by Django 5.1.15 on 2026-09-23 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_backup_recovery_data_lifecycle'),
        ('tenants', '0004_usagerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dataarchive',
            index=models.Index(fields=['tenant', '-archived_at'], name='darch_tenant_at_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentinstance',
            index=models.Index(fields=['tenant', 'name'], name='envinst_tenant_name_idx'),
        ),
        migrations.AddIndex(
            model_name='legalhold',
            index=models.Index(fields=['tenant', '-issued_at'], name='lghold_tenant_at_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverydrill',
            index=models.Index(fields=['tenant', '-performed_at'], name='drill_tenant_perf_idx'),
        ),
    ]
