# Generated by Django 5.1.15 on 2026-09-26 11:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordpolicy_loginattempt_mfadevice_and_more'),
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('module_slug', models.CharField(blank=True, max_length=40)),
                ('metric_key', models.CharField(choices=[('uptime_pct', 'Uptime %'), ('storage_mb', 'Storage (MB)'), ('latency_p95_ms', 'Latency p95 (ms)'), ('throughput_rps', 'Throughput (requests/sec)'), ('error_rate_pct', 'Error rate %'), ('slow_query_ms', 'Slow query (ms)'), ('cpu_pct', 'CPU utilisation %'), ('memory_pct', 'Memory utilisation %'), ('disk_usage_pct', 'Disk usage %'), ('db_connection_pct', 'DB connection pool %'), ('queue_depth', 'Queue depth (items)'), ('job_failures', 'Job failures (count)')], default='uptime_pct', max_length=24)),
                ('comparator', models.CharField(choices=[('eq', 'Eq'), ('ne', 'Ne'), ('gt', 'Gt'), ('gte', 'Gte'), ('lt', 'Lt'), ('lte', 'Lte'), ('in', 'In'), ('not_in', 'Not In'), ('contains', 'Contains'), ('is_set', 'Is Set'), ('is_empty', 'Is Empty')], default='gte', max_length=10)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('must_persist_seconds', models.PositiveIntegerField(default=0)),
                ('frequency', models.CharField(choices=[('manual', 'Manual only'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', help_text='A recorded intention. Nothing in NavERP runs it.', max_length=10)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('category', models.CharField(choices=[('availability', 'Availability'), ('error', 'Error'), ('performance', 'Performance'), ('capacity', 'Capacity'), ('security', 'Security')], default='availability', max_length=16)),
                ('no_data_action', models.CharField(choices=[('fire', 'Fire on no data'), ('ignore', 'Ignore no data'), ('ok', 'Treat no data as OK')], default='ignore', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.notificationrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_label', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(choices=[('firing', 'Firing'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('expired', 'Expired'), ('no_data', 'No data')], default='firing', max_length=12)),
                ('severity_at_fire', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('observed_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('threshold_at_fire', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('message', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='core.tenant')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.alertrule')),
            ],
            options={
                'ordering': ['-fired_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('web_service', 'Web service'), ('api', 'API'), ('database', 'Database'), ('background_job', 'Background job'), ('queue', 'Queue'), ('integration', 'Integration'), ('storage', 'Storage'), ('external_dependency', 'External dependency'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], default='web_service', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('current_status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('partial_outage', 'Partial outage'), ('major_outage', 'Major outage'), ('unknown', 'Unknown')], default='unknown', help_text='A hand-set claim. Nothing in NavERP probes this component.', max_length=20)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_service_components', to='accounts.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_components', to='core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('incident', 'Incident'), ('scheduled_maintenance', 'Scheduled maintenance'), ('postmortem', 'Postmortem (reserved — 0.21)')], default='incident', max_length=24)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('investigating', 'Investigating'), ('identified', 'Identified'), ('in_progress', 'In progress'), ('monitoring', 'Monitoring'), ('verifying', 'Verifying'), ('resolved', 'Resolved'), ('completed', 'Completed')], default='investigating', max_length=16)),
                ('impact', models.CharField(choices=[('none', 'No impact'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=12)),
                ('public_note', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('progress_pct', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('scheduled_until', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.alertevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.tenant')),
                ('affected_services', models.ManyToManyField(blank=True, related_name='affected_incidents', to='core.servicecomponent')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_incidents', to='core.servicecomponent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.servicecomponent'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='core.servicecomponent'),
        ),
        migrations.AddIndex(
            model_name='servicecomponent',
            index=models.Index(fields=['tenant', 'current_status'], name='svccomp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomponent',
            index=models.Index(fields=['tenant', 'is_public'], name='svccomp_tenant_public_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', '-created_at'], name='incident_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'status'], name='incident_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'impact'], name='incident_tenant_impact_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['tenant', 'category'], name='alertrule_tenant_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['tenant', 'severity'], name='alertrule_tenant_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['tenant', 'name'], name='alertrule_tenant_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertrule',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['tenant', '-fired_at'], name='alertevent_tenant_fired_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['tenant', 'state'], name='alertevent_tenant_state_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['tenant', 'service', '-fired_at'], name='alertevent_tenant_svc_idx'),
        ),
    ]
