# Generated by Django 5.1.15 on 2026-09-27 08:08

import apps.core.models.Security
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alertrule_alertevent_servicecomponent_incident_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='An address or CIDR block, e.g. 203.0.113.7 or 203.0.113.0/24.', max_length=43, validators=[apps.core.models.Security.validate_ip_or_cidr])),
                ('direction', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=5)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('challenge', 'Challenge'), ('managed_challenge', 'Managed challenge'), ('non_interactive_challenge', 'Non-interactive challenge'), ('interactive_challenge', 'Interactive challenge'), ('log', 'Log only')], default='log', max_length=28)),
                ('scope', models.CharField(choices=[('workspace', 'Whole workspace'), ('service', 'One service'), ('credential', 'One API credential')], default='workspace', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Entered by hand'), ('threat', 'From a recorded threat'), ('rate_limit', 'From a rate-limit finding'), ('import', 'Imported from elsewhere')], default='manual', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. An allow-list entry with a real expiry is a temporary one.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by_label', models.CharField(blank=True, editable=False, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.apicredential')),
                ('rate_limit_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_access_rules', to='core.ratelimitpolicy')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.servicecomponent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_access_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_label', models.CharField(blank=True, editable=False, max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('threat_type', models.CharField(choices=[('brute_force', 'Brute force'), ('credential_stuffing', 'Credential stuffing'), ('anomalous_login', 'Anomalous login'), ('privilege_escalation', 'Privilege escalation'), ('suspicious_api_activity', 'Suspicious API activity'), ('data_exfiltration', 'Data exfiltration attempt'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('waf_rule_match', 'WAF rule match'), ('rate_limit_exceeded', 'Rate limit exceeded'), ('bot_abuse', 'Bot or automated abuse'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('mitre_technique', models.CharField(blank=True, max_length=20)),
                ('mitre_tactic', models.CharField(blank=True, max_length=50)),
                ('rule_reference', models.CharField(blank=True, max_length=120)),
                ('waf_action', models.CharField(blank=True, choices=[('none', 'None'), ('log', 'Log'), ('block', 'Block'), ('challenge', 'Challenge'), ('managed_challenge', 'Managed challenge'), ('interactive_challenge', 'Interactive challenge')], default='', max_length=30)),
                ('defense_mode', models.CharField(blank=True, choices=[('none', 'None'), ('captcha', 'CAPTCHA'), ('challenge', 'Challenge'), ('rate_limit', 'Rate limit'), ('block', 'Block'), ('waf', 'WAF')], default='', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrence_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('summary', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('false_positive', 'False positive'), ('ignored', 'Ignored')], default='new', max_length=14)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.alertevent')),
                ('mitigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigated_threats', to='core.ipaccessrule')),
                ('rate_limit_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_threats', to='core.ratelimitpolicy')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.servicecomponent')),
                ('target_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.apicredential')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_threats', to='core.tenant')),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('incident_class', models.CharField(choices=[('security_incident', 'Security incident'), ('data_breach', 'Personal data breach'), ('unauthorized_access', 'Unauthorised access'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('insider_threat', 'Insider threat'), ('policy_violation', 'Policy violation'), ('denial_of_service', 'Denial of service'), ('other', 'Other')], default='security_incident', max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('triage', 'Triage'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('eradicated', 'Eradicated'), ('recovered', 'Recovered'), ('closed', 'Closed'), ('false_positive', 'False positive')], default='detected', max_length=14)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('eradicated_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_notifiable', models.BooleanField(blank=True, null=True)),
                ('notifiable_reason', models.TextField(blank=True)),
                ('authority_notified_at', models.DateTimeField(blank=True, null=True)),
                ('authority_reference', models.CharField(blank=True, max_length=150)),
                ('subjects_notified', models.BooleanField(blank=True, null=True)),
                ('subjects_notified_at', models.DateTimeField(blank=True, null=True)),
                ('subject_exemption', models.CharField(choices=[('none', 'No exemption claimed'), ('technical_measures', 'Technical measures protect the rights of data subjects'), ('subsequent_measures', 'Subsequent measures undo the adverse consequences'), ('disproportionate_effort', 'Disproportionate effort')], default='none', max_length=28)),
                ('data_subjects_affected', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('records_affected', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dpo_contact', models.CharField(blank=True, max_length=200)),
                ('likely_consequences', models.TextField(blank=True)),
                ('measures_taken', models.TextField(blank=True)),
                ('measures_proposed', models.TextField(blank=True)),
                ('forensic_log', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('owner_label', models.CharField(blank=True, editable=False, max_length=150)),
                ('evidence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_services', models.ManyToManyField(blank=True, related_name='security_incidents', to='core.servicecomponent')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='core.incident')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='core.tenant')),
                ('primary_threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='core.securitythreat')),
            ],
            options={
                'ordering': ['-discovered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('advisory_id', models.CharField(db_index=True, max_length=40)),
                ('finding_source', models.CharField(choices=[('dependency', 'Software dependency'), ('operating_system', 'Operating system'), ('application', 'Application'), ('configuration', 'Configuration'), ('third_party', 'Third-party service'), ('misconfiguration', 'Misconfiguration')], max_length=20)),
                ('package_name', models.CharField(blank=True, max_length=150)),
                ('installed_version', models.CharField(blank=True, max_length=60)),
                ('severity', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=8)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('epss_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('fix_available', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial')], default=None, max_length=8, null=True)),
                ('fixed_in_version', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'Remediation in progress'), ('fixed', 'Fixed'), ('risk_accepted', 'Risk accepted'), ('false_positive', 'False positive'), ('not_applicable', 'Not applicable')], default='open', max_length=20)),
                ('accepted_reason', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('remediation_note', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('scan_frequency', models.CharField(choices=[('manual', 'Manual only'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.servicecomponent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_findings', to='core.tenant')),
            ],
            options={
                'ordering': ['-first_seen_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='ipaccessrule',
            index=models.Index(fields=['tenant', '-created_at'], name='iprule_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaccessrule',
            index=models.Index(fields=['tenant', 'direction'], name='iprule_tenant_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaccessrule',
            index=models.Index(fields=['tenant', 'expires_at'], name='iprule_tenant_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipaccessrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'cidr', 'direction'), name='core_iprule_tenant_cidr_dir_uniq'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['tenant', '-detected_at'], name='secthreat_tenant_detected_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['tenant', 'status'], name='secthreat_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['tenant', 'threat_type'], name='secthreat_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['tenant', 'source_ip'], name='secthreat_tenant_source_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['tenant', '-discovered_at'], name='secinc_tenant_discovered_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['tenant', 'status'], name='secinc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['tenant', 'incident_class'], name='secinc_tenant_class_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['tenant', 'is_notifiable'], name='secinc_tenant_notifiable_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['tenant', 'status'], name='vulfind_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['tenant', 'severity'], name='vulfind_tenant_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['tenant', 'advisory_id'], name='vulfind_tenant_advisory_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['tenant', '-first_seen_at'], name='vulfind_tenant_firstseen_idx'),
        ),
    ]
