# Generated by Django 5.1.15 on 2026-09-27 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_security_threat_protection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('change_type', models.CharField(choices=[('standard', 'Standard'), ('normal', 'Normal'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('impact_level', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major')], default='minor', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rolled_back', 'Rolled back'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_reason', models.TextField(blank=True)),
                ('rollback_at', models.DateTimeField(blank=True, null=True)),
                ('post_review', models.TextField(blank=True)),
                ('downtime_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='core.environmentinstance')),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureRollout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('internal', 'Internal only'), ('pilot', 'Pilot'), ('partial', 'Partial'), ('general', 'General availability')], default='internal', max_length=10)),
                ('percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('cohort_label', models.CharField(blank=True, max_length=120)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('rolled_back', 'Rolled back')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollouts', to='core.changerequest')),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollouts', to='core.featureflag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_rollouts', to='core.tenant')),
            ],
            options={
                'ordering': ['stage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('module_slug', models.CharField(max_length=60)),
                ('job_type', models.CharField(choices=[('scheduled_task', 'Scheduled task'), ('integration_sync', 'Integration sync'), ('bulk_operation', 'Bulk operation'), ('report', 'Report'), ('cleanup', 'Cleanup'), ('maintenance', 'Maintenance')], default='scheduled_task', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('schedule_kind', models.CharField(choices=[('manual', 'Manual only'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=10)),
                ('cron_expression', models.CharField(blank=True, max_length=60)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
                ('handler_path', models.CharField(help_text='Declared target, e.g. apps.core.tasks.send_expiry_notices. RECORDED ONLY - nothing in this repository imports or calls it.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=100)),
                ('timeout_seconds', models.IntegerField(blank=True, null=True)),
                ('max_active_runs', models.SmallIntegerField(default=1)),
                ('pool_name', models.CharField(blank=True, help_text='Recorded pool name. No worker pool exists; nothing reserves a slot.', max_length=60)),
                ('pool_slots', models.SmallIntegerField(default=1)),
                ('max_consecutive_failures', models.SmallIntegerField(default=3)),
                ('auto_pause_after', models.SmallIntegerField(default=10)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_job_definitions', to='core.environmentinstance')),
                ('sync_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_definitions', to='core.syncschedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_definitions', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_kind', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('backfill', 'Backfill'), ('api', 'API')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='queued', max_length=10)),
                ('is_dry_run', models.BooleanField(default=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('records_processed', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.jobdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_runs', to='core.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=10)),
                ('timezone_label', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended_early', 'Ended early'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('suppresses_jobs', models.BooleanField(default=False, help_text='Recorded intent. No scheduler exists to suppress anything.')),
                ('blocks_admin_writes', models.BooleanField(default=False, help_text='Recorded intent. No permission check consults this flag.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_services', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='core.servicecomponent')),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows', to='core.changerequest')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows', to='core.environmentinstance')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.incident')),
                ('suppressed_alert_rules', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='core.alertrule')),
                ('suppressed_notification_rules', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='core.notificationrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='core.tenant')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['tenant', 'status'], name='chgreq_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['tenant', 'risk_level'], name='chgreq_tenant_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerollout',
            index=models.Index(fields=['tenant', 'status'], name='rollout_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerollout',
            index=models.Index(fields=['change', 'stage'], name='rollout_change_stage_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featurerollout',
            unique_together={('change', 'feature_flag')},
        ),
        migrations.AddIndex(
            model_name='jobdefinition',
            index=models.Index(fields=['tenant', 'is_active'], name='jobdef_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdefinition',
            index=models.Index(fields=['tenant', 'module_slug'], name='jobdef_tenant_module_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrun',
            index=models.Index(fields=['tenant', 'status'], name='jobrun_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrun',
            index=models.Index(fields=['job', '-triggered_at'], name='jobrun_job_time_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancewindow',
            index=models.Index(fields=['tenant', 'status'], name='mntwin_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancewindow',
            index=models.Index(fields=['tenant', 'starts_at'], name='mntwin_tenant_starts_idx'),
        ),
    ]
