# Generated by Django 5.1.15 on 2026-09-27 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_changerequest_featurerollout_jobdefinition_jobrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('effective', 'Effective'), ('not_applicable', 'Not applicable')], default='not_started', max_length=16)),
                ('frequency', models.CharField(blank=True, max_length=20)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('next_review_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_controls', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ControlFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('framework_type', models.CharField(choices=[('attestation', 'Attestation / certification'), ('regulatory', 'Regulatory regime'), ('industry', 'Industry standard'), ('internal', 'Internal standard')], default='attestation', max_length=20)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('authority', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adopted_on', models.DateField(blank=True, null=True)),
                ('review_due_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_frameworks', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'control frameworks',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ControlFrameworkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_reference', models.CharField(blank=True, max_length=40)),
                ('coverage', models.CharField(choices=[('not_started', 'Not started'), ('partial', 'Partial'), ('covered', 'Covered'), ('not_applicable', 'Not applicable')], default='not_started', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.compliancecontrol')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.controlframework')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_framework_mappings', to='core.tenant')),
            ],
            options={
                'ordering': ['framework__code', 'control__code'],
            },
        ),
        migrations.CreateModel(
            name='CorporatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('policy_type', models.CharField(choices=[('security', 'Security'), ('acceptable_use', 'Acceptable use'), ('access_control', 'Access control'), ('data_handling', 'Data handling'), ('incident_response', 'Incident response'), ('business_continuity', 'Business continuity'), ('code_of_conduct', 'Code of conduct')], default='security', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('review_due_on', models.DateField(blank=True, null=True)),
                ('requires_acknowledgement', models.BooleanField(default=True)),
                ('body', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_policies', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'corporate policies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(editable=False, max_length=20)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='core.corporatepolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('risk_statement', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('likelihood', models.CharField(choices=[('rare', 'Rare'), ('unlikely', 'Unlikely'), ('possible', 'Possible'), ('likely', 'Likely'), ('almost_certain', 'Almost certain')], default='possible', max_length=14)),
                ('impact', models.CharField(choices=[('negligible', 'Negligible'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('severe', 'Severe')], default='minor', max_length=12)),
                ('inherent_score', models.PositiveSmallIntegerField(default=0)),
                ('residual_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('treatment', models.CharField(choices=[('accept', 'Accept'), ('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('avoid', 'Avoid')], default='mitigate', max_length=10)),
                ('treatment_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessing', 'Assessing'), ('treating', 'Treating'), ('monitoring', 'Monitoring'), ('closed', 'Closed')], default='identified', max_length=12)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('next_review_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_register', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'risk register',
                'ordering': ['-inherent_score', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['tenant', 'status'], name='ctl_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['tenant', 'category'], name='ctl_tenant_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecontrol',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='controlframework',
            index=models.Index(fields=['tenant', 'is_active'], name='cfw_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='controlframework',
            index=models.Index(fields=['tenant', 'framework_type'], name='cfw_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlframework',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='controlframeworkmapping',
            index=models.Index(fields=['framework', 'coverage'], name='cfmap_fw_cov_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlframeworkmapping',
            unique_together={('framework', 'control')},
        ),
        migrations.AddIndex(
            model_name='corporatepolicy',
            index=models.Index(fields=['tenant', 'status'], name='cpol_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatepolicy',
            index=models.Index(fields=['tenant', 'policy_type'], name='cpol_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporatepolicy',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='policyacknowledgement',
            index=models.Index(fields=['policy', 'acknowledged_at'], name='ack_pol_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyacknowledgement',
            unique_together={('policy', 'user', 'policy_version')},
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['tenant', 'status'], name='grc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['tenant', '-inherent_score'], name='grc_tenant_score_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['tenant', 'category'], name='grc_tenant_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskregister',
            unique_together={('tenant', 'code')},
        ),
    ]
