# Generated by Django 5.1.15 on 2026-09-28 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_compliancecontrol_controlframework_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('audit_type', models.CharField(choices=[('certification', 'External certification'), ('internal', 'Internal audit'), ('customer', 'Customer-driven audit'), ('regulatory', 'Regulatory examination')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('fieldwork', 'Fieldwork in progress'), ('findings_issued', 'Findings issued'), ('closed', 'Closed')], default='planned', max_length=20)),
                ('auditor_name', models.CharField(blank=True, max_length=120)),
                ('auditor_email', models.EmailField(blank=True, max_length=254)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='core.controlframework')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audits', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'compliance audits',
                'ordering': ['-started_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('observation', 'Observation')], default='minor', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('remediation', 'Remediation in progress'), ('resolved', 'Resolved'), ('risk_accepted', 'Risk accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('remediation', models.TextField(blank=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.compliancecontrol')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='core.tenant')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.complianceaudit')),
            ],
            options={
                'verbose_name_plural': 'audit findings',
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('evidence_type', models.CharField(choices=[('document', 'Document (in the document register)'), ('screenshot', 'Screenshot'), ('log_export', 'Log / data export'), ('attestation', 'Written attestation'), ('observation', 'Auditor observation')], default='observation', max_length=20)),
                ('collected_on', models.DateField(blank=True, null=True)),
                ('period_covered', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.compliancecontrol')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_evidence', to='core.tenant')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.complianceaudit')),
            ],
            options={
                'verbose_name_plural': 'audit evidence',
                'ordering': ['-collected_on', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['tenant', 'status'], name='cad_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['tenant', '-started_on'], name='cad_tenant_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceaudit',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['tenant', 'status'], name='fnd_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['tenant', 'severity'], name='fnd_tenant_sev_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditfinding',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='auditevidence',
            index=models.Index(fields=['tenant', 'audit'], name='evd_tenant_audit_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidence',
            index=models.Index(fields=['tenant', 'evidence_type'], name='evd_tenant_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditevidence',
            unique_together={('tenant', 'code')},
        ),
    ]
