# Generated by Django 5.1.15 on 2026-06-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_budget_budgetline_fixedasset_assetdisposal_and_more'),
        ('core', '0002_activity_activity_tenant_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetdisposal',
            index=models.Index(fields=['tenant', 'status'], name='acc_disp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='costallocation',
            index=models.Index(fields=['tenant', 'status'], name='acc_calloc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['tenant', 'status'], name='acc_ict_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['tenant', 'eliminated'], name='acc_ict_tenant_elim_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcostentry',
            index=models.Index(fields=['tenant', 'status'], name='acc_jce_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcostentry',
            index=models.Index(fields=['tenant', 'project'], name='acc_jce_tenant_project_idx'),
        ),
    ]
