# Generated by Django 5.1.15 on 2026-06-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_recurringinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recurring_invoice',
            field=models.ForeignKey(blank=True, editable=False, help_text='The schedule that generated this invoice, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='accounting.recurringinvoice'),
        ),
    ]
