# Generated by Django 5.1.15 on 2026-06-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandingsetting',
            options={'ordering': ['-updated_at']},
        ),
    ]
