# Generated by Django 5.1.15 on 2026-06-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_activity_tenant_status_idx_and_more'),
        ('tenants', '0002_alter_brandingsetting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='healthmetric',
            index=models.Index(fields=['tenant', 'metric', '-created_at'], name='health_tenant_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['tenant', 'status'], name='subinv_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['stripe_invoice_id'], name='subinv_stripe_inv_idx'),
        ),
    ]
