# Generated by Django 5.1.15 on 2026-09-19 12:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_domain'),
        ('tenants', '0003_alter_subscription_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('api_calls', 'API Calls'), ('storage_mb', 'Storage (MB)'), ('active_users', 'Active Users'), ('transactions', 'Transactions')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_billed', models.BooleanField(default=False, editable=False)),
                ('billed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='tenants.subscription')),
                ('subscription_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='tenants.subscriptioninvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', '-id'],
                'indexes': [models.Index(fields=['tenant', 'metric', '-period_start'], name='usage_tenant_metric_idx'), models.Index(fields=['tenant', 'is_billed'], name='usage_tenant_billed_idx')],
            },
        ),
    ]
