# Generated by Django 5.1.15 on 2026-09-27 14:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_security_threat_protection'),
        ('tenants', '0004_usagerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EntitlementFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('privilege_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('select', 'Select')], default='boolean', max_length=12)),
                ('select_options', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_add_on', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_features', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('module_slug', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reclaimed', 'Reclaimed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=12)),
                ('assignment_source', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('rule', 'Rule')], default='direct', max_length=10)),
                ('assigned_from', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('reclaimed_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reclaim_reason', models.CharField(blank=True, editable=False, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_assignments', to='tenants.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('privilege_value', models.CharField(blank=True, max_length=120)),
                ('is_add_on', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='tenants.entitlementfeature')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_overrides', to='tenants.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='core.tenant')),
            ],
            options={
                'ordering': ['plan', 'feature__code', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('metric', models.CharField(choices=[('api_calls', 'API Calls'), ('storage_mb', 'Storage (MB)'), ('active_users', 'Active Users'), ('transactions', 'Transactions')], max_length=20)),
                ('quota_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('warn_at_pct', models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('action_on_breach', models.CharField(choices=[('alert', 'Alert'), ('charge', 'Charge'), ('block', 'Block')], default='alert', max_length=10)),
                ('is_fair_use', models.BooleanField(default=False)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('breached_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to='tenants.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to='core.tenant')),
            ],
            options={
                'ordering': ['subscription', 'metric', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='entitlementfeature',
            index=models.Index(fields=['tenant', 'status'], name='entfeat_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementfeature',
            index=models.Index(fields=['tenant', 'code'], name='entfeat_tenant_code_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitlementfeature',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['tenant', 'status'], name='licassign_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['tenant', 'user'], name='licassign_user_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['tenant', 'subscription'], name='licassign_sub_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='licenseassignment',
            unique_together={('tenant', 'user', 'module_slug')},
        ),
        migrations.AddIndex(
            model_name='planentitlement',
            index=models.Index(fields=['tenant', 'plan'], name='planent_tenant_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='planentitlement',
            index=models.Index(fields=['tenant', 'feature'], name='planent_tenant_feature_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planentitlement',
            unique_together={('tenant', 'plan', 'feature', 'subscription')},
        ),
        migrations.AddIndex(
            model_name='usagequota',
            index=models.Index(fields=['tenant', 'subscription'], name='uquota_tenant_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='usagequota',
            index=models.Index(fields=['subscription', 'metric'], name='uquota_sub_metric_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagequota',
            unique_together={('tenant', 'subscription', 'metric', 'period')},
        ),
    ]
