# Generated by Django 5.1.15 on 2026-09-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscription_auto_renew_subscription_grace_ends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
