# Generated by Django 5.1.15 on 2026-08-21 13:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Color", "Size", "Voltage"', max_length=60)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, help_text='Optional unit shown after the value, e.g. "mm", "kg", "V"', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Spec-sheet display order')),
                ('item', models.ForeignKey(help_text='The product this attribute describes', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_attributes', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item_id', 'sequence', 'name'],
                'indexes': [models.Index(fields=['tenant', 'item'], name='inv_ita_tnt_item_idx')],
                'unique_together': {('tenant', 'item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('promotional', 'Promotional'), ('clearance', 'Clearance')], default='retail', max_length=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Price-break threshold; 1 = the base price', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Open-ended when blank', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('currency', models.ForeignKey(blank=True, help_text='Blank = the workspace default currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currency')),
                ('item', models.ForeignKey(help_text='The product being priced', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_prices', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item_id', 'price_type', 'min_quantity'],
                'indexes': [models.Index(fields=['tenant', 'item'], name='inv_prp_tnt_item_idx'), models.Index(fields=['tenant', 'price_type'], name='inv_prp_tnt_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('safety_sheet', 'Safety Sheet'), ('manual', 'Manual'), ('datasheet', 'Datasheet'), ('certificate', 'Certificate'), ('other', 'Other')], default='photo', max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='inventory/products/%Y/%m/')),
                ('url', models.URLField(blank=True, help_text='External link — used when no file is uploaded')),
                ('is_primary', models.BooleanField(default=False, help_text="The product's cover image; saving a new primary demotes the previous one")),
                ('item', models.ForeignKey(help_text='The product this file or link documents', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_files', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item_id', '-is_primary', 'kind', 'title'],
                'indexes': [models.Index(fields=['tenant', 'item'], name='inv_pfl_tnt_item_idx')],
            },
        ),
    ]
