# Generated by Django 5.1.15 on 2026-08-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0001_initial'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productfile',
            index=models.Index(fields=['tenant', 'kind'], name='inv_pfl_tnt_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='productfile',
            index=models.Index(fields=['tenant', 'created_at'], name='inv_pfl_tnt_created_idx'),
        ),
    ]
