# Generated by Django 5.1.15 on 2026-08-21 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0002_productfile_inv_pfl_tnt_kind_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('site_visit', 'Site Visit'), ('note', 'Note')], default='email', max_length=12)),
                ('direction', models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the interaction actually happened')),
                ('follow_up_on', models.DateField(blank=True, help_text='Optional next-action date; drives the due/overdue filters', null=True)),
                ('party', models.ForeignKey(help_text='The vendor this interaction belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_vendor_communications', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'party'], name='inv_vc_tnt_party_idx'), models.Index(fields=['tenant', 'channel'], name='inv_vc_tnt_channel_idx'), models.Index(fields=['tenant', 'follow_up_on'], name='inv_vc_tnt_followup_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
