# Generated by Django 5.1.15 on 2026-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0003_vendorcommunication'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendorcommunication',
            index=models.Index(fields=['tenant', 'occurred_at'], name='inv_vc_tnt_occur_idx'),
        ),
    ]
