# Generated by Django 5.1.15 on 2026-08-22 09:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0004_vendorcommunication_inv_vc_tnt_occur_idx'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Band lower bound, inclusive', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Band upper bound, EXCLUSIVE — blank means open-ended above min_amount', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tier_count', models.PositiveIntegerField(default=1, help_text='Sequential approval sign-offs a matching order must clear', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('org_unit', models.ForeignKey(blank=True, help_text='Restrict this rule to one department/site — blank matches every order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_po_approval_rules', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-min_amount', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('tier', models.PositiveIntegerField(help_text='1-based position in the approval sequence', validators=[django.core.validators.MinValueValidator(1)])),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_po_tier_decisions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_approvals', to='scm.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='inventory.purchaseorderapprovalrule')),
            ],
            options={
                'ordering': ['purchase_order_id', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('edi', 'EDI'), ('print', 'Print / PDF')], default='email', max_length=10)),
                ('recipient', models.CharField(help_text='Vendor email address, or EDI mailbox/partner ID', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Message-ID or interchange control number from the transport', max_length=255)),
                ('dispatched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_dispatches', to='scm.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorderapprovalrule',
            index=models.Index(fields=['tenant', 'is_active'], name='inv_par_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderapprovalrule',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderapproval',
            index=models.Index(fields=['tenant', 'purchase_order'], name='inv_pa_tnt_po_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderapproval',
            unique_together={('tenant', 'purchase_order', 'tier')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderdispatch',
            index=models.Index(fields=['tenant', 'purchase_order'], name='inv_pd_tnt_po_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderdispatch',
            index=models.Index(fields=['tenant', 'dispatched_at'], name='inv_pd_tnt_sent_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderdispatch',
            unique_together={('tenant', 'number')},
        ),
    ]
