# Generated by Django 5.1.15 on 2026-08-22 13:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0005_purchaseorderapprovalrule_purchaseorderapproval_and_more'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum gross weight the bin may hold, kg (blank = not limited)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_volume_m3', models.DecimalField(blank=True, decimal_places=3, help_text='Maximum volume the bin may hold, m³ (blank = not limited)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum units the bin may hold (blank = not limited)', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(help_text='The bin (or dock/staging area) these limits apply to', on_delete=django.db.models.deletion.PROTECT, related_name='bin_capacity', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['location__code'],
                'unique_together': {('tenant', 'location')},
            },
        ),
        migrations.CreateModel(
            name='CrossDockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Inbound cost per unit — becomes the receipt's cost layer", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('scheduled_date', models.DateField(help_text='Planned dock date')),
                ('inbound_reference', models.CharField(blank=True, help_text='Where the goods come from, e.g. GRN-00012 / PO-00007', max_length=40)),
                ('outbound_reference', models.CharField(blank=True, help_text='Where the goods go, e.g. SO-00031 / SHP-00004', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received at Dock'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('received_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dock_location', models.ForeignKey(help_text='The dock/staging area the goods land on and leave from — no bin in between', on_delete=django.db.models.deletion.PROTECT, related_name='crossdock_orders', to='scm.location')),
                ('item', models.ForeignKey(help_text='The product flowing dock-to-dock', on_delete=django.db.models.deletion.PROTECT, related_name='crossdock_orders', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Optional lot/serial for tracked items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossdock_orders', to='scm.lotserial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_xd_tnt_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
