# Generated by Django 5.1.15 on 2026-08-22 14:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0006_bincapacity_crossdockorder'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('purpose', models.CharField(choices=[('sales_order', 'Sales Order'), ('job', 'Job / Work Order'), ('project', 'Project'), ('other', 'Other')], default='sales_order', max_length=12)),
                ('reference', models.CharField(blank=True, help_text='The document the stock is locked for, e.g. SO-00031 / JOB-0042', max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released to Floor'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled')], default='reserved', editable=False, max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('item', models.ForeignKey(help_text='The item whose stock is being locked', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='scm.item')),
                ('location', models.ForeignKey(help_text='The spot the reserved units are held at', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='scm.location')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Optional lot/serial for tracked items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='scm.lotserial')),
                ('reserved_by', models.ForeignKey(blank=True, help_text='Who raised the lock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_rsv_tnt_status_idx'), models.Index(fields=['tenant', 'item', 'location'], name='inv_rsv_tnt_item_loc_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('on_hold', 'On Hold')], default='damaged', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='How many of the units at this spot the claim covers', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('reason', models.CharField(blank=True, help_text="Why the units carry this status, e.g. 'fork puncture case 3'", max_length=255)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the classification was observed')),
                ('item', models.ForeignKey(help_text='The item whose stock is being classified', on_delete=django.db.models.deletion.PROTECT, related_name='stock_statuses', to='scm.item')),
                ('location', models.ForeignKey(help_text='Where the classified units sit', on_delete=django.db.models.deletion.PROTECT, related_name='stock_statuses', to='scm.location')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Optional lot/serial — expiry usually belongs to a specific batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_statuses', to='scm.lotserial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item__sku', 'location__code', '-effective_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_ss_tnt_status_idx')],
            },
        ),
    ]
