# Generated by Django 5.1.15 on 2026-08-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0007_inventoryreservation_stockstatus'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderapproval',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PutawayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category match (middle tier); ignored when an item is pinned', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_putaway_rules', to='scm.itemcategory')),
                ('destination', models.ForeignKey(help_text='Destination bin or zone', on_delete=django.db.models.deletion.PROTECT, related_name='putaway_rules_to', to='scm.location')),
                ('item', models.ForeignKey(blank=True, help_text='Exact-item match (most specific tier); leave blank for broader rules', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_putaway_rules', to='scm.item')),
                ('source_location', models.ForeignKey(blank=True, help_text='Applies when goods arrive in this staging/dock; blank = any arrival point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_rules_from', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='inv_pwr_tnt_active_idx')],
            },
        ),
    ]
