# Generated by Django 5.1.15 on 2026-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0008_alter_purchaseorderapproval_unique_together_and_more'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crossdockorder',
            index=models.Index(fields=['tenant', 'scheduled_date', 'id'], name='inv_xd_tnt_sched_idx'),
        ),
    ]
