# Generated by Django 5.1.15 on 2026-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0009_crossdockorder_inv_xd_tnt_sched_idx'),
        ('scm', '0034_remove_integrationmessage_scm_msg_tnt_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockstatus',
            index=models.Index(fields=['tenant', 'item', 'location'], name='inv_ss_tnt_item_loc_idx'),
        ),
    ]
