# Generated by Django 5.1.15 on 2026-08-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockstatus_inv_ss_tnt_item_loc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdispatch',
            name='recipient',
            field=models.CharField(blank=True, help_text='Vendor email address, or EDI mailbox/partner ID', max_length=255),
        ),
    ]
