# Generated by Django 5.1.15 on 2026-08-23 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0012_transferroute_transferapprovalrule_transferapproval'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfLifePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelf_life_days', models.PositiveSmallIntegerField(blank=True, help_text='Total expected shelf life in days — informational context for the board', null=True)),
                ('min_remaining_days', models.PositiveSmallIntegerField(default=0, help_text='Outbound gate: lots with less remaining life than this are flagged do-not-ship')),
                ('warning_days', models.PositiveSmallIntegerField(default=30, help_text='Amber window: lots expiring within this many days are flagged for first-out picking')),
                ('fefo_enforced', models.BooleanField(default=True, help_text='Pick strictly earliest-expiry-first for this item')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.OneToOneField(help_text='One shelf-life regime per tracked SKU', on_delete=django.db.models.deletion.CASCADE, related_name='shelf_life_policy', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item__sku'],
            },
        ),
        migrations.CreateModel(
            name='LotNumberRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('lot', 'Lot / Batch'), ('serial', 'Serial')], default='lot', help_text='What kind of tracked number this rule mints', max_length=8)),
                ('prefix', models.CharField(default='LOT', help_text='Literal stem of the number, upper-cased on save, e.g. LOT / BATCH-A', max_length=12)),
                ('include_date', models.BooleanField(default=True, help_text='Append a YYMMDD date component after the prefix')),
                ('sequence_padding', models.PositiveSmallIntegerField(default=5, help_text='Zero-padded width of the running sequence, e.g. 5 → 00001', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(blank=True, help_text='Leave empty for the tenant-wide default; an item rule overrides it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_number_rules', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item__sku', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='inv_lnr_tnt_active_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
