# Generated by Django 5.1.15 on 2026-08-23 09:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0013_shelflifepolicy_lotnumberrule'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='planned', editable=False, max_length=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ship_method', models.CharField(blank=True, choices=[('economy', 'Economy'), ('standard', 'Standard'), ('expedited', 'Expedited')], default='', max_length=12)),
                ('planned_ship_date', models.DateField(blank=True, null=True)),
                ('cutoff_at', models.DateTimeField(blank=True, help_text='Orders must be picked by this moment to make the truck', null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('criteria_text', models.TextField(blank=True, help_text="What qualifies an order for this wave, in the planner's words")),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(blank=True, help_text='Carrier tendered for the whole wave (4.6 TCS master)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_waves', to='scm.carrier')),
                ('location', models.ForeignKey(blank=True, help_text='Warehouse the wave ships from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_waves', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentWaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Who put the order into the wave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(help_text='The customer order travelling with this wave', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_wave_orders', to='scm.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_wave_orders', to='core.tenant')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.fulfillmentwave')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity of units inspected', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the inspection took place')),
                ('packaging_condition', models.CharField(choices=[('intact', 'Original & Intact'), ('opened', 'Opened / Minor Wear'), ('damaged', 'Heavily Damaged'), ('missing', 'Missing / No Packaging')], default='opened', help_text='Condition of packaging upon warehouse receipt', max_length=20)),
                ('completeness', models.CharField(choices=[('complete', 'Complete (All Parts/Accessories)'), ('missing_accessories', 'Missing Cables/Accessories'), ('missing_parts', 'Missing Major Components'), ('missing_manual', 'Missing Manual/Docs Only')], default='complete', help_text='Completeness of product accessories, manuals, and parts', max_length=20)),
                ('functional_status', models.CharField(choices=[('pass', 'Fully Functional'), ('partial', 'Partially Functional / Minor Defect'), ('fail', 'Non-Functional / Defective'), ('untested', 'Untested / Not Applicable')], default='pass', help_text='Operational testing verdict', max_length=20)),
                ('cosmetic_condition', models.CharField(choices=[('new', 'Like New / Pristine'), ('minor_wear', 'Minor Scratches / Light Wear'), ('heavy_wear', 'Heavy Wear / Dents'), ('broken', 'Broken / Cracked')], default='new', help_text='Visual cosmetic evaluation', max_length=20)),
                ('condition_grade', models.CharField(choices=[('a', 'Grade A — Like New'), ('b', 'Grade B — Minor Wear / Refurbishable'), ('c', 'Grade C — Heavy Wear / Secondary'), ('d', 'Grade D — Defective / Unsellable')], default='a', help_text='Assigned condition grade: Grade A (new) to Grade D (defective)', max_length=1)),
                ('serial_verified', models.BooleanField(default=True, help_text='Whether serial number matches the RMA authorization record')),
                ('is_restock_eligible', models.BooleanField(default=True, help_text='Whether goods are fit to be restocked into sellable inventory')),
                ('suggested_restock_fee_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recommended restocking fee percentage based on condition findings', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('findings', models.TextField(blank=True, help_text='Detailed defect notes, missing parts, or inspector comments')),
                ('status', models.CharField(choices=[('pending', 'Pending Inspection'), ('in_progress', 'In Progress'), ('passed', 'Passed Inspection'), ('failed', 'Failed Inspection'), ('quarantined', 'Quarantined')], default='passed', help_text='Overall status of this warehouse inspection', max_length=16)),
                ('inspected_by', models.ForeignKey(blank=True, help_text='Staff/Inspector party who performed the inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_inspections_conducted', to='core.party')),
                ('item', models.ForeignKey(help_text='The item SKU inspected', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_return_inspections', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Specific lot or serial number inspected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.lotserial')),
                ('return_authorization', models.ForeignKey(help_text='The parent Return Authorization (RMA) ticket', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inspections', to='scm.returnauthorization')),
                ('return_disposition', models.ForeignKey(blank=True, help_text='Receiving bench disposition row (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_inspections', to='scm.returndisposition')),
                ('return_line', models.ForeignKey(blank=True, help_text='Specific return line on the RMA (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_inspections', to='scm.returnline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-inspected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnInspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpoint', models.CharField(help_text="Checkpoint label (e.g. 'Power-on test', 'Packaging integrity', 'Factory reset')", max_length=120)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], default='pass', max_length=10)),
                ('notes', models.CharField(blank=True, help_text='Specific note on this checkpoint', max_length=255)),
                ('inspection', models.ForeignKey(help_text='The parent inspection record', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='inventory.returninspection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DispositionRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Descriptive rule name (e.g. 'Grade A Electronics Restock', 'Defective Audio Scrap')", max_length=100)),
                ('condition_grade', models.CharField(choices=[('all', 'All Condition Grades'), ('a', 'Grade A — Like New'), ('b', 'Grade B — Minor Wear / Refurbishable'), ('c', 'Grade C — Heavy Wear / Secondary'), ('d', 'Grade D — Defective / Unsellable')], default='all', help_text='Condition grade condition matching this rule', max_length=4)),
                ('suggested_disposition', models.CharField(choices=[('restock', 'Restock into Sellable Inventory'), ('refurbish', 'Route to Refurbishment / Testing'), ('scrap', 'Route to Scrap / Disposal'), ('donate', 'Route to Donation'), ('recycle', 'Route to Recycling'), ('liquidate', 'Route to Liquidation Channel'), ('return_to_vendor', 'Return to Vendor (RTV / Warranty Claim)'), ('quarantine', 'Quarantine Hold')], default='restock', help_text='Recommended disposition action', max_length=20)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Evaluation order — lower numbers fire first')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active in the routing engine')),
                ('requires_supervisor_approval', models.BooleanField(default=False, help_text='Flag requiring supervisor sign-off before executing this disposition')),
                ('notes', models.CharField(blank=True, help_text='Internal routing guidelines or instructions for warehouse operators', max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Item category this rule applies to (blank if item-pinned or workspace-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_disposition_rules', to='scm.itemcategory')),
                ('destination_location', models.ForeignKey(blank=True, help_text='Suggested destination warehouse/zone/bin location for the routed items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_disposition_rules', to='scm.location')),
                ('item', models.ForeignKey(blank=True, help_text='Specific item SKU (blank for category or workspace-wide rule)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_disposition_rules', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'priority'], name='inv_drr_tnt_act_pri_idx'), models.Index(fields=['tenant', 'condition_grade'], name='inv_drr_tnt_grd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fulfillmentwave',
            index=models.Index(fields=['tenant', 'status'], name='inv_wav_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fulfillmentwave',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='fulfillmentwaveorder',
            unique_together={('wave', 'sales_order')},
        ),
        migrations.AddIndex(
            model_name='returninspection',
            index=models.Index(fields=['tenant', 'status'], name='inv_rmi_tnt_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='returninspection',
            index=models.Index(fields=['tenant', 'inspected_at'], name='inv_rmi_tnt_insp_idx'),
        ),
        migrations.AddIndex(
            model_name='returninspection',
            index=models.Index(fields=['tenant', 'condition_grade'], name='inv_rmi_tnt_grd_idx'),
        ),
        migrations.AddIndex(
            model_name='returninspectionchecklist',
            index=models.Index(fields=['tenant', 'inspection'], name='inv_rmick_tnt_insp_idx'),
        ),
    ]
