# Generated by Django 5.1.15 on 2026-08-23 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0014_fulfillmentwave_fulfillmentwaveorder_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('abc_class', models.CharField(blank=True, choices=[('', 'Any class'), ('a', 'A only'), ('b', 'B only'), ('c', 'C only')], help_text='Restrict to one ABC class, or any', max_length=1)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=8)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Weekly: which day (0=Monday)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Monthly: which day (1-28; months without it roll up to the 28th)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('count_method', models.CharField(choices=[('zone', 'Zone'), ('abc', 'ABC Class'), ('full', 'Full Count')], default='zone', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateField(blank=True, editable=False, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('location', models.ForeignKey(blank=True, help_text='The zone/bin/warehouse section counted on this cadence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='count_programs', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='inv_ctp_tnt_active_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PhysicalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('counting', 'Counting'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=12)),
                ('is_frozen', models.BooleanField(default=False, editable=False)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_physical_inventories', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('warehouse', models.ForeignKey(help_text='The warehouse being frozen for a full count', on_delete=django.db.models.deletion.PROTECT, related_name='physical_inventories', to='scm.location')),
            ],
            options={
                'ordering': ['-scheduled_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_phy_tnt_status_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
