# Generated by Django 5.1.15 on 2026-08-23 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0015_countprogram_physicalinventory'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='physicalinventory',
            index=models.Index(fields=['tenant', '-scheduled_date'], name='inv_phy_tnt_sched_idx'),
        ),
    ]
