# Generated by Django 5.1.15 on 2026-08-23 22:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0016_physicalinventory_inv_phy_tnt_sched_idx'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('base_target_qty', models.DecimalField(decimal_places=2, help_text='Unadjusted stock target for index-neutral periods', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Floor below which the plan flags the item understocked', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Ceiling above which the plan flags excess stock', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', editable=False, max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(help_text='The SKU being planned', on_delete=django.db.models.deletion.PROTECT, related_name='stock_level_plans', to='scm.item')),
                ('location', models.ForeignKey(blank=True, help_text='Empty = network-wide plan row for this SKU', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_level_plans', to='scm.location')),
                ('seasonal_profile', models.ForeignKey(blank=True, help_text='Optional SCM index curve applied on top of the base target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_level_plans', to='scm.seasonalityprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item__sku', '-effective_from', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_slp_tnt_status_idx'), models.Index(fields=['tenant', 'item'], name='inv_slp_tnt_item_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
