# Generated by Django 5.1.15 on 2026-08-23 23:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0017_stocklevelplan'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('device_label', models.CharField(help_text="Rugged handheld or wedge scanner name (e.g. 'Zebra TC22 - Dock 3')", max_length=80)),
                ('mode', models.CharField(choices=[('single', 'Single Scan'), ('batch', 'Batch / Paste-many')], default='single', help_text='Single Scan accepts one code per submit; Batch / Paste-many takes a pasted list', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Open sessions accept scans; closing freezes the session for audit', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When scanning began')),
                ('ended_at', models.DateTimeField(blank=True, editable=False, help_text='When the session was closed', null=True)),
                ('notes', models.CharField(blank=True, help_text='Free-text context for this session (shift, dock, campaign…)', max_length=255)),
                ('operator', models.ForeignKey(blank=True, editable=False, help_text='Operator party, stamped by seeding/integrations — NavERP has NO User→Party link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_code', models.CharField(help_text='The raw scanned/pasted string exactly as the device delivered it', max_length=120)),
                ('resolved_kind', models.CharField(choices=[('item', 'Item'), ('location', 'Location'), ('lot', 'Lot / Serial'), ('rfid', 'RFID Tag'), ('unknown', 'Unknown')], default='unknown', help_text='Which spine entity the code matched at scan time', max_length=10)),
                ('resolved_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the matched row, snapshotted at scan time', null=True)),
                ('resolved_label', models.CharField(blank=True, help_text='Human-readable snapshot of the match at scan time', max_length=120)),
                ('ok', models.BooleanField(default=False, help_text='Whether the code resolved to any known record')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Capture timestamp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('session', models.ForeignKey(help_text='The parent scan session that captured this code', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.scansession')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('target_type', models.CharField(choices=[('item', 'Item SKU'), ('location', 'Location / Bin'), ('lot', 'Lot / Serial'), ('free', 'Free-form')], default='item', help_text='Which L36 master this label points at', max_length=16)),
                ('target_ref', models.CharField(blank=True, help_text='Raw code for free-form targets', max_length=64)),
                ('pallet_ref', models.CharField(blank=True, help_text='License-plate / pallet reference — free-text stand-in: no pallet/HU master exists yet (L28)', max_length=64)),
                ('label_kind', models.CharField(choices=[('product', 'Product Label'), ('bin', 'Bin Label'), ('pallet', 'Pallet License Plate'), ('generic', 'Generic')], default='product', help_text='Physical role this label plays on the floor', max_length=16)),
                ('symbology', models.CharField(choices=[('code39', 'Code 39'), ('code128', 'Code 128'), ('ean13', 'EAN-13'), ('qr', 'QR Code')], default='code128', help_text='Barcode symbology used to render the payload', max_length=12)),
                ('payload', models.CharField(help_text='Exact string encoded into the barcode', max_length=120)),
                ('copies', models.PositiveIntegerField(default=1, help_text='Number of physical labels one print run produces', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('printed', 'Printed'), ('void', 'Voided')], default='draft', help_text='Lifecycle of this label registration', max_length=12)),
                ('printed_at', models.DateTimeField(blank=True, editable=False, help_text='When the label was last printed (refreshed on reprint)', null=True)),
                ('notes', models.CharField(blank=True, help_text='Internal operator notes', max_length=255)),
                ('item', models.ForeignKey(blank=True, help_text="The labelled item SKU (for target_type='item')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_labels', to='scm.item')),
                ('location', models.ForeignKey(blank=True, help_text="The labelled location / bin (for target_type='location')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_labels', to='scm.location')),
                ('lot_serial', models.ForeignKey(blank=True, help_text="The labelled lot or serial number (for target_type='lot')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_labels', to='scm.lotserial')),
                ('printed_by', models.ForeignKey(blank=True, editable=False, help_text='Stamped by print()/integrations — there is NO User→Party link in NavERP, never guess one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_barcode_labels', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_lbl_tnt_stat_idx'), models.Index(fields=['tenant', 'target_type'], name='inv_lbl_tnt_tgt_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('node_type', models.CharField(choices=[('company', 'Company'), ('region', 'Region'), ('dc', 'Distribution Center'), ('store', 'Store / Site')], default='store', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Org-tier parent (blank = a top-level root of the network tree)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.locationnetwork')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Stocked site this node maps to; blank = pure grouping. Attachable at ANY tier, not leaves only — a stocking DC node IS its warehouse (leaf-rule ruling). Warehouse-typed scm locations only: a bin is not a store.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_nodes', to='scm.location')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['tenant', 'node_type'], name='inv_lnw_tnt_type_idx')],
                'unique_together': {('tenant', 'code'), ('tenant', 'number'), ('tenant', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='RfidTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epc', models.CharField(help_text='Electronic Product Code — uppercase hex, hyphens allowed; unique per workspace', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9A-F\\-]{8,64}$', message='EPC must be 8-64 hex characters (hyphens allowed).')])),
                ('kind', models.CharField(choices=[('passive', 'Passive (UHF)'), ('active', 'Active / Powered')], default='passive', help_text='Passive UHF label or battery-powered active tag', max_length=10)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('active', 'Active'), ('retired', 'Retired'), ('lost', 'Lost')], default='unassigned', help_text='Lifecycle state — moved only by the activate/retire/mark-lost actions', max_length=12)),
                ('target_ref', models.CharField(blank=True, help_text='Free-text reference for targets without a master record', max_length=64)),
                ('pallet_ref', models.CharField(blank=True, help_text='Pallet/HU reference — free text; no pallet master exists in NavERP yet', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp of the most recent reader sweep that reported this EPC', null=True)),
                ('notes', models.CharField(blank=True, help_text='Free-form notes', max_length=255)),
                ('item', models.ForeignKey(blank=True, help_text='Item this tag is attached to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_tags', to='scm.item')),
                ('last_seen_location', models.ForeignKey(blank=True, editable=False, help_text='Read point of the most recent reader sweep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_last_seen_reads', to='scm.location')),
                ('location', models.ForeignKey(blank=True, help_text='Bin/location the tag is assigned to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_tags', to='scm.location')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Specific lot or serial the tag identifies (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_tags', to='scm.lotserial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['epc'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_tag_tnt_stat_idx')],
                'unique_together': {('tenant', 'epc')},
            },
        ),
        migrations.AddIndex(
            model_name='scansession',
            index=models.Index(fields=['tenant', 'status'], name='inv_ssn_tnt_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['tenant', 'session'], name='inv_scnev_tnt_sess_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['tenant', 'resolved_kind'], name='inv_scnev_tnt_kind_idx'),
        ),
    ]
