# Generated by Django 5.1.15 on 2026-08-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0018_scansession_scanevent_barcodelabel_locationnetwork_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanevent',
            options={'ordering': ['-scanned_at', '-id']},
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['tenant', 'scanned_at'], name='inv_scnev_tnt_scan_idx'),
        ),
    ]
