# Generated by Django 5.1.15 on 2026-08-24 19:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0019_scanevent_tenant_scanned_at_idx'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidtag',
            name='epc',
            field=models.CharField(help_text='Electronic Product Code — uppercase hex, hyphens allowed; unique per workspace', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9A-Fa-f\\-]{8,64}$', message='EPC must be 8-64 hex characters (hyphens allowed).')]),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text='Human-readable rule name', max_length=120)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('overstock', 'Overstock'), ('expiry', 'Expiry'), ('po_approval_pending', 'PO Awaiting Approval'), ('shipment_delayed', 'Delayed Shipment')], help_text='Which watch condition the engine evaluates', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', help_text='Stamped onto every alert this rule raises', max_length=10)),
                ('expiry_days', models.PositiveIntegerField(default=30, help_text='Expiry rules: flag lots expiring within this many days (0 = expired only)', validators=[django.core.validators.MaxValueValidator(3650)])),
                ('overstock_pct', models.DecimalField(decimal_places=2, default=100, help_text='Overstock rules: raise when bin utilisation exceeds this % of max_quantity', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))])),
                ('notify_inapp', models.BooleanField(default=True, help_text='Raise in the in-app alert inbox')),
                ('notify_email', models.BooleanField(default=False, help_text='Queue an email delivery per recipient')),
                ('notify_sms', models.BooleanField(default=False, help_text='Queue an SMS delivery')),
                ('notify_push', models.BooleanField(default=False, help_text='Queue a push notification')),
                ('email_recipients', models.CharField(blank=True, help_text='Comma-separated email addresses for the email channel', max_length=255)),
                ('cooldown_days', models.PositiveIntegerField(default=7, help_text='Do not re-raise the same condition within this many days', validators=[django.core.validators.MaxValueValidator(365)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, help_text='Watch only this item (blank = all items; ignored for PO/shipment types)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='scm.item')),
                ('location', models.ForeignKey(blank=True, help_text='Watch only this location (blank = all locations; lots carry no location)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('overstock', 'Overstock'), ('expiry', 'Expiry'), ('po_approval_pending', 'PO Awaiting Approval'), ('shipment_delayed', 'Delayed Shipment')], editable=False, help_text="Snapshot of the rule's type at raise time", max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], editable=False, help_text="Snapshot of the rule's severity at raise time", max_length=10)),
                ('dedup_key', models.CharField(editable=False, help_text='Condition identity used to suppress duplicates while one is still open', max_length=180)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Observed figure at raise time: qty on hand, % utilisation or days to expiry', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts', to='scm.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts', to='scm.location')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts', to='scm.lotserial')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts', to='scm.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, help_text='Rule that raised this alert (kept after the rule is deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='inventory.alertrule')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=8)),
                ('recipient', models.CharField(help_text="Email address, number or token; '(broadcast)' for inbox-wide channels", max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=8)),
                ('detail', models.CharField(blank=True, help_text='Gateway note — e.g. why a delivery is still queued', max_length=255)),
                ('alert', models.ForeignKey(help_text='The alert this dispatch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.inventoryalert')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['tenant', 'alert_type', 'is_active'], name='inv_alr_tnt_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertrule',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['tenant', 'status'], name='inv_alt_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['tenant', 'alert_type'], name='inv_alt_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['tenant', 'channel', 'status'], name='inv_ndl_tnt_chan_idx'),
        ),
    ]
