# Generated by Django 5.1.15 on 2026-08-24 20:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0022_inventoryreportsnapshot'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Electronics dock inspection', 'ACME incoming check'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, help_text='Pin to one product — blank for category-wide/vendor-wide/workspace-wide use', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_qc_checklists', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, help_text='Pin to one supplier — receipts from them run this checklist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_qc_checklists', to='core.party')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QcChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="e.g. 'Carton seal intact', 'Power-on test'", max_length=255)),
                ('kind', models.CharField(choices=[('visual', 'Visual Check'), ('functional', 'Functional Test'), ('documentation', 'Documentation / Labels'), ('quantity', 'Quantity Verification'), ('instruction', 'Instruction (no verdict)')], default='visual', max_length=13)),
                ('expected_result', models.CharField(blank=True, help_text="What 'pass' looks like, e.g. 'Seal unbroken' — informational", max_length=120)),
                ('is_mandatory', models.BooleanField(default=True, help_text='A failed mandatory checkpoint blocks acceptance; advisory ones only warn')),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Execution order — lower runs first')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='inventory.qcchecklist')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['checklist_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QcRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'ACME electronics inspect', 'Spare parts bypass'", max_length=100)),
                ('verdict', models.CharField(choices=[('inspect', 'Route via QC Zone'), ('bypass', 'Straight to Storage')], default='inspect', help_text='Whether matching receipts detour through the QC zone', max_length=7)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Tie-breaker — lower numbers win')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Item category this rule applies to (blank if item-pinned or workspace-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_qc_routing_rules', to='scm.itemcategory')),
                ('item', models.ForeignKey(blank=True, help_text='Specific product (blank for category or workspace-wide rule)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_qc_routing_rules', to='scm.item')),
                ('qc_location', models.ForeignKey(blank=True, help_text='The restricted QC zone matching receipts wait in (required when verdict is inspect)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_qc_routing_rules', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, help_text='Only receipts from this supplier match; blank = any vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_qc_routing_rules', to='core.party')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('reason', models.CharField(choices=[('suspected_defect', 'Suspected Defect'), ('damage_found', 'Damage Found in Stock'), ('customer_return', 'Customer Return Pending Inspection'), ('qc_hold', 'QC Hold — Awaiting Inspection'), ('compliance_hold', 'Compliance / Regulatory Hold'), ('other', 'Other')], default='qc_hold', max_length=18)),
                ('reference', models.CharField(blank=True, help_text='Source document number, e.g. GRN-00012 / RMA-00004 / NCR-00002', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quarantined', 'Quarantined'), ('released', 'Released'), ('scrapped', 'Scrapped'), ('cancelled', 'Cancelled')], default='draft', max_length=11)),
                ('quarantined_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, help_text='Release / scrap / cancel moment', null=True)),
                ('item', models.ForeignKey(help_text='The suspect product', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_quarantine_orders', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Optional lot/serial for tracked items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_quarantine_orders', to='scm.lotserial')),
                ('quarantine_location', models.ForeignKey(help_text='The restricted QC zone they are segregated INTO', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_quarantine_orders', to='scm.location')),
                ('source_location', models.ForeignKey(help_text='Where the goods sit NOW — the outbound half of the hold pair', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_quarantine_sources', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='How many units are affected', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('defect_type', models.CharField(choices=[('dimensional', 'Dimensional'), ('visual_cosmetic', 'Visual / Cosmetic'), ('functional', 'Functional'), ('material', 'Material'), ('packaging', 'Packaging'), ('labelling', 'Labelling'), ('contamination', 'Contamination'), ('other', 'Other')], default='other', max_length=18)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=8)),
                ('discovered_during', models.CharField(choices=[('receiving', 'Receiving'), ('putaway', 'Putaway'), ('picking', 'Picking'), ('packing', 'Packing'), ('cycle_count', 'Cycle Count'), ('other', 'Other')], default='receiving', max_length=11)),
                ('description', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='inventory/defects/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, help_text='External link — used when no file is uploaded')),
                ('reported_on', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('open', 'Open'), ('written_off', 'Written Off'), ('closed', 'Closed — No Write-off')], default='open', editable=False, max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_defect_reports', to='scm.item')),
                ('location', models.ForeignKey(help_text='Where the defective units sit — the write-off draws from here', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_defect_reports', to='scm.location')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='Optional lot/serial for tracked items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_defect_reports', to='scm.lotserial')),
                ('ncr', models.ForeignKey(blank=True, help_text='Set when escalated to the quality-engineering register (SCM owns that flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_defect_reports', to='scm.nonconformance')),
                ('reported_by', models.ForeignKey(blank=True, help_text='An employee party — who found it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_defect_reports', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-reported_on', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_def_tnt_status_idx'), models.Index(fields=['tenant', 'item'], name='inv_def_tnt_item_idx'), models.Index(fields=['tenant', 'reported_on'], name='inv_def_tnt_date_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='qcchecklist',
            index=models.Index(fields=['tenant', 'is_active'], name='inv_qcc_tnt_act_idx'),
        ),
        migrations.AddIndex(
            model_name='qcchecklist',
            index=models.Index(fields=['tenant', 'item'], name='inv_qcc_tnt_item_idx'),
        ),
        migrations.AddIndex(
            model_name='qcchecklist',
            index=models.Index(fields=['tenant', 'vendor'], name='inv_qcc_tnt_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='qcchecklistitem',
            index=models.Index(fields=['tenant', 'checklist'], name='inv_qci_tnt_chk_idx'),
        ),
        migrations.AddIndex(
            model_name='qcroutingrule',
            index=models.Index(fields=['tenant', 'is_active', 'priority'], name='inv_qcr_tnt_act_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='qcroutingrule',
            index=models.Index(fields=['tenant', 'verdict'], name='inv_qcr_tnt_verdict_idx'),
        ),
        migrations.AddIndex(
            model_name='quarantineorder',
            index=models.Index(fields=['tenant', 'status'], name='inv_qro_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quarantineorder',
            index=models.Index(fields=['tenant', 'item'], name='inv_qro_tnt_item_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quarantineorder',
            unique_together={('tenant', 'number')},
        ),
    ]
