# Generated by Django 5.1.15 on 2026-08-24 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0023_qcchecklist_qcchecklistitem_qcroutingrule_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GLPostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('adjustment', 'Inventory Adjustment'), ('cogs', 'Cost of Goods Sold')], help_text='One mapping per event type — a second would make runs ambiguous', max_length=12)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('inventory_account', models.ForeignKey(help_text='The stock asset account (e.g. 1500 Inventory)', on_delete=django.db.models.deletion.PROTECT, related_name='gl_post_rules_as_inventory', to='accounting.glaccount')),
                ('offset_account', models.ForeignKey(help_text='Adjustments: the gain/write-off account · COGS: the COGS expense (e.g. 5000 Cost of Goods Sold)', on_delete=django.db.models.deletion.PROTECT, related_name='gl_post_rules_as_offset', to='accounting.glaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['event_type'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='inv_gpr_tnt_active_idx')],
                'unique_together': {('tenant', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='JournalSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('source_kind', models.CharField(choices=[('adjustment', 'Stock Adjustment'), ('cogs_batch', 'COGS Batch')], max_length=12)),
                ('date_from', models.DateField(blank=True, help_text='COGS batch window start', null=True)),
                ('date_to', models.DateField(blank=True, help_text='COGS batch window end', null=True)),
                ('moves_count', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sync_logs', to='accounting.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_adjustment', models.ForeignKey(blank=True, help_text='Set on adjustment postings', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_sync_logs', to='scm.stockadjustment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'source_kind'], name='inv_jsy_tnt_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(blank=True, help_text='Billing country this rule covers — blank = any geography', max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Tie-break between equally specific rules — lower wins')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Applies to every item in this category (when no SKU rule matches)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='scm.itemcategory')),
                ('item', models.ForeignKey(blank=True, help_text='Pin to one SKU (highest specificity)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='scm.item')),
                ('tax_code', models.ForeignKey(help_text='The rate applied when this rule wins', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tax_rules', to='accounting.taxcode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='inv_taxrule_active_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
