# Generated by Django 5.1.15 on 2026-08-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_glpostrule_journalsynclog_taxrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantineorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('quarantined', 'Quarantined'), ('released', 'Released'), ('scrapped', 'Scrapped'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=11),
        ),
    ]
