# Generated by Django 5.1.15 on 2026-08-24 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0025_alter_quarantineorder_status'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('ecommerce', 'E-commerce'), ('erp', 'ERP'), ('accounting', 'Accounting'), ('custom', 'Custom')], default='custom', help_text='Which family of external system this connection points at', max_length=12)),
                ('platform', models.CharField(blank=True, choices=[('shopify', 'Shopify'), ('amazon_sp_api', 'Amazon SP-API'), ('woocommerce', 'WooCommerce'), ('ebay', 'eBay'), ('walmart', 'Walmart'), ('magento', 'Magento'), ('bigcommerce', 'BigCommerce'), ('sap', 'SAP'), ('oracle_erp', 'Oracle ERP'), ('netsuite', 'NetSuite'), ('dynamics', 'Microsoft Dynamics'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero'), ('sage', 'Sage'), ('custom', 'Custom')], default='custom', help_text='Named commercial platform the connector targets', max_length=20)),
                ('direction', models.CharField(choices=[('push_stock', 'Push Stock'), ('pull_orders', 'Pull Orders'), ('bidirectional', 'Bidirectional')], default='bidirectional', help_text='Which way stock data flows across this connection (intent)', max_length=14)),
                ('auth_method', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('basic', 'Basic Auth'), ('oauth2', 'OAuth 2.0'), ('signature', 'Signature')], default='api_key', help_text='Auth intent only — OAuth2 records intent and stores nothing', max_length=10)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('external_account_ref', models.CharField(blank=True, help_text='Shop domain / seller id / realm / company id at the platform', max_length=120)),
                ('api_key_prefix', models.CharField(blank=True, editable=False, max_length=12)),
                ('api_key_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='disconnected', help_text='ON the form deliberately — a human-maintained marker; no transport observes anything (scm endpoint.status ruling)', max_length=14)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook')], default='manual', help_text='Sync-firing intent only — no scheduler exists in this build', max_length=10)),
                ('schedule_note', models.CharField(blank=True, max_length=200)),
                ('rate_limit_note', models.CharField(blank=True, help_text='Prose humans read, never enforced — e.g. "QBO: 429 w/ Retry-After, ~10 concurrent"', max_length=120)),
                ('last_sync_at', models.DateTimeField(blank=True, editable=False, help_text='Home for the future transport pass — NOTHING in this build writes it', null=True)),
                ('last_run_status', models.CharField(blank=True, editable=False, help_text='Written ONLY by the sync verb — honestly reflects the latest recorded run', max_length=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('default_location', models.ForeignKey(blank=True, help_text="WHICH stocking location backs this channel's availability", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelListingMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_product_id', models.CharField(blank=True, help_text='Shopify product gid / Amazon ASIN / Woo product id', max_length=80)),
                ('external_variant_id', models.CharField(blank=True, help_text='Shopify variant gid / Amazon ASIN-SKU / Woo variation id', max_length=80)),
                ('external_sku', models.CharField(blank=True, help_text='The SKU as the platform knows it, when it differs from ours', max_length=80)),
                ('sync_enabled', models.BooleanField(default=True, help_text='Paused rows are left out of stock pushes')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Channel-specific selling price, overriding the catalogue price', max_digits=18, null=True)),
                ('last_pushed_qty', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Derived display copy of the quantity last pushed — NEVER the on-hand source', max_digits=18, null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, editable=False, help_text='When the last push for this listing completed', null=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, help_text='Blank = a channel-wide row (availability rule rather than one SKU)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_listings', to='scm.item')),
                ('location', models.ForeignKey(blank=True, help_text='Blank = every location backs this listing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('channel', models.ForeignKey(help_text="The connection this mapping belongs to (the sub-module's one cascade)", on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='inventory.integrationchannel')),
            ],
            options={
                'ordering': ['channel__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('direction', models.CharField(choices=[('outbound_push', 'Outbound Push'), ('inbound_pull', 'Inbound Pull')], max_length=14)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('webhook_inbound', 'Webhook Inbound')], default='manual', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('exhausted', 'Exhausted'), ('simulated', 'Simulated')], default='pending', max_length=10)),
                ('records_total', models.PositiveIntegerField(default=0)),
                ('records_ok', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('payload_excerpt', models.TextField(blank=True, help_text='TRUNCATED excerpt only. May contain buyer PII. A full body is NEVER stored.')),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='inventory.integrationchannel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('scopes', models.CharField(blank=True, help_text='Comma-separated scope list, e.g. "stock:read,moves:read" — RECORDED intent only; no enforcement middleware exists in this pass.', max_length=255)),
                ('protocol', models.CharField(choices=[('rest', 'REST'), ('graphql', 'GraphQL')], default='rest', max_length=8)),
                ('api_token_prefix', models.CharField(blank=True, editable=False, max_length=12)),
                ('api_token_hash', models.CharField(blank=True, editable=False, help_text='Prefix + SHA-256 marker; plaintext NEVER persisted, shown exactly once on issue/rotate.', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', help_text='Moves ONLY via the revoke POST verb — never a form field.', max_length=8)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('allowed_ips', models.CharField(blank=True, help_text='Comma-separated allow-list, e.g. 203.0.113.7,198.51.100.0/24 — RECORDED intent, NOT enforced by any gateway in this pass.', max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, help_text='Home for the future gateway pass to stamp; NOTHING in this build writes it.', null=True)),
                ('rate_limit_note', models.CharField(blank=True, help_text='Our budget promise to the consumer, e.g. "60 req/min sustained" — prose, never a throttle.', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inv_apc_tnt_status_idx')],
                'unique_together': {('tenant', 'name'), ('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='integrationchannel',
            index=models.Index(fields=['tenant', 'kind'], name='inv_int_tnt_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationchannel',
            index=models.Index(fields=['tenant', 'status'], name='inv_int_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationchannel',
            index=models.Index(fields=['tenant', 'is_active'], name='inv_int_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationchannel',
            unique_together={('tenant', 'name'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='channellistingmap',
            index=models.Index(fields=['tenant', 'item'], name='inv_clm_tnt_item_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channellistingmap',
            unique_together={('tenant', 'channel', 'external_variant_id')},
        ),
        migrations.AddIndex(
            model_name='stocksyncrun',
            index=models.Index(fields=['tenant', 'channel'], name='inv_syn_tnt_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksyncrun',
            index=models.Index(fields=['tenant', 'status', 'started_at'], name='inv_syn_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksyncrun',
            unique_together={('tenant', 'number')},
        ),
    ]
