# Generated by Django 5.1.15 on 2026-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0026_integrationchannel_channellistingmap_stocksyncrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channellistingmap',
            name='external_variant_id',
            field=models.CharField(blank=True, help_text='Shopify variant gid / Amazon ASIN-SKU / Woo variation id', max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='stocksyncrun',
            index=models.Index(fields=['tenant', 'started_at'], name='inv_syn_tnt_started_idx'),
        ),
    ]
