# Generated by Django 5.1.15 on 2026-08-25 15:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('inventory', '0027_alter_channellistingmap_external_variant_id_and_more'),
        ('scm', '0035_stocktransfer_route_and_governed_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UomConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=4, help_text='How many TO-units one FROM-unit holds — 12 means 1 Case = 12 Units', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('from_uom', models.ForeignKey(help_text='Unit being converted FROM (e.g. Case)', on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='scm.uom')),
                ('item', models.ForeignKey(blank=True, help_text='Exact-item rule (most specific); blank = tenant-wide default', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uom_conversions', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('to_uom', models.ForeignKey(help_text='Unit being converted INTO (e.g. Unit)', on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='scm.uom')),
            ],
            options={
                'ordering': ['from_uom__code', 'to_uom__code', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='inv_uom_tnt_active_idx')],
                'unique_together': {('tenant', 'item', 'from_uom', 'to_uom')},
            },
        ),
    ]
