# Generated by Django 5.1.15 on 2026-06-20 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_activity_tenant_status_idx_and_more'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_campaign_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_case_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crmtask',
            index=models.Index(fields=['tenant', 'due_date', 'created_at'], name='crm_task_tnt_due_created_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_kb_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_lead_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_opp_tenant_created_idx'),
        ),
    ]
