# Generated by Django 5.1.15 on 2026-06-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_activity_tenant_status_idx_and_more'),
        ('crm', '0002_campaign_crm_campaign_tnt_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('energy', 'Energy & Utilities'), ('media', 'Media & Entertainment'), ('professional_services', 'Professional Services'), ('construction', 'Construction'), ('transportation', 'Transportation & Logistics'), ('hospitality', 'Hospitality'), ('nonprofit', 'Non-Profit'), ('government', 'Government'), ('other', 'Other')], max_length=40)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('annual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=120)),
                ('address_state', models.CharField(blank=True, max_length=120)),
                ('address_postal', models.CharField(blank=True, max_length=20)),
                ('address_country', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, choices=[('web', 'Web Form'), ('referral', 'Referral'), ('event', 'Event'), ('cold_call', 'Cold Call'), ('email_campaign', 'Email Campaign'), ('social', 'Social Media'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_account_profiles', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_child_account_profiles', to='core.party')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_account_profile', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['party__name'],
            },
        ),
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=120)),
                ('address_state', models.CharField(blank=True, max_length=120)),
                ('address_postal', models.CharField(blank=True, max_length=20)),
                ('address_country', models.CharField(blank=True, max_length=120)),
                ('linkedin', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, choices=[('web', 'Web Form'), ('referral', 'Referral'), ('event', 'Event'), ('cold_call', 'Cold Call'), ('email_campaign', 'Email Campaign'), ('social', 'Social Media'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_account_contacts', to='core.party')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contact_profiles', to=settings.AUTH_USER_MODEL)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contact_profile', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['party__name'],
            },
        ),
    ]
