# Generated by Django 5.1.15 on 2026-06-20 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_activity_tenant_status_idx_and_more'),
        ('crm', '0003_accountprofile_contactprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountprofile',
            index=models.Index(fields=['tenant', 'industry'], name='crm_accp_tnt_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='accountprofile',
            index=models.Index(fields=['tenant', 'source'], name='crm_accp_tnt_source_idx'),
        ),
        migrations.AddIndex(
            model_name='accountprofile',
            index=models.Index(fields=['tenant', 'parent_account'], name='crm_accp_tnt_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['tenant', 'source'], name='crm_conp_tnt_source_idx'),
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['tenant', 'account'], name='crm_conp_tnt_account_idx'),
        ),
    ]
