# Generated by Django 5.1.15 on 2026-06-20 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_activity_tenant_status_idx_and_more'),
        ('crm', '0004_accountprofile_crm_accp_tnt_industry_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_projects', to='core.party')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_projects', to=settings.AUTH_USER_MODEL)),
                ('source_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_projects', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('milestone', 'Milestone'), ('task', 'Task')], default='task', max_length=12)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_milestones', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='crm.crmmilestone')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='crm.crmproject')),
            ],
            options={
                'ordering': ['order', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('nda', 'NDA'), ('proposal', 'Proposal'), ('contract', 'Contract'), ('quote', 'Quote'), ('receipt', 'Receipt')], default='contract', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_doc_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('current_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('body_snapshot', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contracts', to='core.party')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='crm.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contracts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='crm.doctemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('meals', 'Meals'), ('software', 'Software'), ('accommodation', 'Accommodation'), ('other', 'Other')], default='travel', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='crm/receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='crm.opportunity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='crm.crmproject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_submitted_expenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('tier', models.CharField(choices=[('green', 'Green — Healthy'), ('yellow', 'Yellow — At Risk'), ('red', 'Red — Critical')], default='green', max_length=10)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_health_scores', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_tickets', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('weight_nps', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('weight_tasks', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('weight_engagement', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('red_threshold', models.PositiveSmallIntegerField(default=40)),
                ('yellow_threshold', models.PositiveSmallIntegerField(default=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_health_config', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_onboarding_plans', to='core.party')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_onboarding_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_onboarding_steps', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.onboardingplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_level', models.CharField(choices=[('read_only', 'Read Only'), ('lead_register', 'Lead Registration'), ('full', 'Full Access')], default='read_only', max_length=20)),
                ('can_view_stock', models.BooleanField(default=False)),
                ('can_register_leads', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partner_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_portal_accesses', to='core.party')),
                ('portal_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_portal_access', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('on_hand_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_purchase_orders', to='core.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='crm.productstock')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SignerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='crm.contractdocument')),
                ('signer_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_signer_records', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_type', models.CharField(choices=[('nps', 'NPS'), ('csat', 'CSAT'), ('ces', 'CES')], default='nps', max_length=10)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('post_close', 'Post Close Won'), ('post_ticket', 'Post Ticket Close'), ('scheduled', 'Scheduled')], default='manual', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('feedback_text', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, choices=[('promoter', 'Promoter'), ('passive', 'Passive'), ('detractor', 'Detractor')], max_length=10)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_surveys', to='core.party')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_survey_contacts', to='core.party')),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_surveys', to='crm.case')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_timesheets', to='core.party')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_timesheets', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='crm.crmmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='crm.crmproject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_entity', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('case', 'Case'), ('expense', 'Expense'), ('contract', 'Contract'), ('health_score', 'Health Score')], default='opportunity', max_length=20)),
                ('trigger_event', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('field_value', 'Field Value Matches'), ('date_reached', 'Date Reached')], default='created', max_length=20)),
                ('trigger_field', models.CharField(blank=True, max_length=100)),
                ('trigger_value', models.CharField(blank=True, max_length=255)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('delay_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delay_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_workflow_rules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_label', models.CharField(max_length=255)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=10)),
                ('error_msg', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='crm.workflowrule')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('record_label', models.CharField(blank=True, max_length=255)),
                ('threshold_field', models.CharField(blank=True, max_length=100)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_approvals_to_action', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='crm.workflowrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crmproject',
            index=models.Index(fields=['tenant', 'status'], name='crm_prj_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crmproject',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_prj_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crmproject',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='crmmilestone',
            index=models.Index(fields=['tenant', 'project', 'status'], name='crm_ms_tnt_prj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crmmilestone',
            index=models.Index(fields=['tenant', 'due_date'], name='crm_ms_tnt_due_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crmmilestone',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='doctemplate',
            index=models.Index(fields=['tenant', 'template_type'], name='crm_tpl_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='doctemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_tpl_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctemplate',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['tenant', 'status'], name='crm_ctr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['tenant', 'opportunity'], name='crm_ctr_tnt_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_ctr_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractdocument',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'status'], name='crm_exp_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'expense_date'], name='crm_exp_tnt_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'opportunity'], name='crm_exp_tnt_opp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='healthscore',
            index=models.Index(fields=['tenant', 'tier'], name='crm_hs_tnt_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='healthscore',
            index=models.Index(fields=['tenant', 'computed_at'], name='crm_hs_tnt_computed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='healthscore',
            unique_together={('tenant', 'account'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='onboardingplan',
            index=models.Index(fields=['tenant', 'account'], name='crm_obp_tnt_account_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingplan',
            index=models.Index(fields=['tenant', 'status'], name='crm_obp_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingplan',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='partnerportalaccess',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_prt_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerportalaccess',
            index=models.Index(fields=['tenant', 'partner_party'], name='crm_prt_tnt_partner_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerportalaccess',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_stk_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['tenant', 'name'], name='crm_stk_tnt_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'status'], name='crm_po_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_po_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['tenant', 'survey_type'], name='crm_nps_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['tenant', 'account'], name='crm_nps_tnt_account_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['tenant', 'sent_at'], name='crm_nps_tnt_sent_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'project', 'date'], name='crm_ts_tnt_prj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'employee', 'date'], name='crm_ts_tnt_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'status'], name='crm_ts_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_wfr_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['tenant', 'trigger_entity'], name='crm_wfr_tnt_entity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowrule',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='workflowlog',
            index=models.Index(fields=['tenant', 'status'], name='crm_wfl_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowlog',
            index=models.Index(fields=['tenant', 'fired_at'], name='crm_wfl_tnt_fired_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'status'], name='crm_apr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'approver'], name='crm_apr_tnt_approver_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_apr_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalrequest',
            unique_together={('tenant', 'number')},
        ),
    ]
