# Generated by Django 5.1.15 on 2026-06-26 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0005_crmproject_crmmilestone_doctemplate_contractdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('awareness', 'Brand Awareness'), ('lead_gen', 'Lead Generation'), ('nurture', 'Nurture / Engagement'), ('conversion', 'Conversion / Sales'), ('event', 'Event Promotion'), ('retention', 'Retention / Loyalty')], default='lead_gen', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parent_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_campaigns', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='campaign',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='campaign',
            name='utm_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('newsletter', 'Newsletter'), ('promotional', 'Promotional'), ('transactional', 'Transactional'), ('drip', 'Drip / Nurture'), ('announcement', 'Announcement'), ('other', 'Other')], default='promotional', max_length=15)),
                ('subject', models.CharField(max_length=255)),
                ('preheader', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_email_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_ab_test', models.BooleanField(default=False)),
                ('send_type', models.CharField(choices=[('one_time', 'One-time Blast'), ('drip', 'Drip / Automated'), ('ab_test', 'A/B Test')], default='one_time', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('bounced_count', models.PositiveIntegerField(default=0)),
                ('unsubscribed_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='crm.campaign')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='crm.emailtemplate')),
                ('variant_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('public_token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('capture_phone', models.BooleanField(default=True)),
                ('capture_company', models.BooleanField(default=True)),
                ('capture_message', models.BooleanField(default=False)),
                ('cta_label', models.CharField(default='Submit', max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('lead_source', models.CharField(choices=[('web', 'Web Form'), ('referral', 'Referral'), ('event', 'Event'), ('cold_call', 'Cold Call'), ('email_campaign', 'Email Campaign'), ('social', 'Social Media'), ('other', 'Other')], default='web', max_length=20)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='crm.campaign')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_landing_pages', to=settings.AUTH_USER_MODEL)),
                ('routing_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_routed_landing_pages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('routed', 'Routed'), ('converted', 'Converted'), ('spam', 'Spam')], default='new', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_form_submissions', to='crm.lead')),
                ('routed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_routed_submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='crm.landingpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('member_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('targeted', 'Targeted'), ('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('responded', 'Responded'), ('converted', 'Converted'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='targeted', max_length=15)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.campaign')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_campaign_members', to='crm.lead')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_campaign_members', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='crm_cmem_tnt_status_idx'), models.Index(fields=['tenant', 'campaign'], name='crm_cmem_tnt_camp_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['tenant', 'category'], name='crm_etpl_tnt_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_etpl_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['tenant', 'status'], name='crm_blast_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_blast_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailcampaign',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['tenant', 'status'], name='crm_lp_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_lp_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='landingpage',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['tenant', 'status'], name='crm_fsub_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['tenant', 'landing_page'], name='crm_fsub_tnt_lp_idx'),
        ),
    ]
