# Generated by Django 5.1.15 on 2026-06-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0006_campaign_objective_campaign_parent_campaign_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_cmem_tnt_created_idx'),
        ),
    ]
