# Generated by Django 5.1.15 on 2026-06-26 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0007_campaignmember_crm_cmem_tnt_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='competitor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='forecast_category',
            field=models.CharField(choices=[('omitted', 'Omitted'), ('pipeline', 'Pipeline'), ('best_case', 'Best Case'), ('commit', 'Commit'), ('closed', 'Closed')], default='pipeline', max_length=12),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='loss_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OpportunitySplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_type', models.CharField(choices=[('revenue', 'Revenue'), ('overlay', 'Overlay / Credit')], default='revenue', max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='crm.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_opportunity_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['split_type', '-percentage'],
            },
        ),
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('tier', models.CharField(blank=True, max_length=120)),
                ('price_adjustment_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('product_type', models.CharField(choices=[('good', 'Good'), ('service', 'Service'), ('subscription', 'Subscription')], default='good', max_length=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_quotes', to='core.party')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_quotes', to=settings.AUTH_USER_MODEL)),
                ('price_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm.pricebook')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='crm.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.quote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('segment', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_territories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_territories', to='crm.territory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Annual')], default='quarter', max_length=10)),
                ('period_year', models.PositiveSmallIntegerField(default=2026)),
                ('period_number', models.PositiveSmallIntegerField(default=1)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_sales_quotas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotas', to='crm.territory')),
            ],
            options={
                'ordering': ['-period_year', 'period_number'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.territory'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'forecast_category'], name='crm_opp_tnt_fcast_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitysplit',
            index=models.Index(fields=['tenant', 'opportunity'], name='crm_osplit_tnt_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebook',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_pb_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebook',
            index=models.Index(fields=['tenant', 'is_default'], name='crm_pb_tnt_default_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricebook',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'product_type'], name='crm_prd_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_prd_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant', 'status'], name='crm_quo_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_quo_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['tenant', 'quote'], name='crm_qline_tnt_quote_idx'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_ter_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_ter_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='territory',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='salesquota',
            index=models.Index(fields=['tenant', 'period_year'], name='crm_qta_tnt_year_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesquota',
            unique_together={('tenant', 'number'), ('tenant', 'owner', 'period_type', 'period_year', 'period_number')},
        ),
    ]
