# Generated by Django 5.1.15 on 2026-06-26 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0008_opportunity_competitor_opportunity_forecast_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesquota',
            unique_together={('tenant', 'number'), ('tenant', 'owner', 'territory', 'period_type', 'period_year', 'period_number')},
        ),
    ]
