# Generated by Django 5.1.15 on 2026-06-26 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0009_alter_salesquota_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesquota',
            index=models.Index(fields=['tenant', 'territory'], name='crm_qta_tnt_terr_idx'),
        ),
    ]
