# Generated by Django 5.1.15 on 2026-06-26 17:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0011_alter_opportunitysplit_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('response_low', models.PositiveSmallIntegerField(default=48)),
                ('response_medium', models.PositiveSmallIntegerField(default=24)),
                ('response_high', models.PositiveSmallIntegerField(default=8)),
                ('response_critical', models.PositiveSmallIntegerField(default=2)),
                ('resolution_low', models.PositiveSmallIntegerField(default=240)),
                ('resolution_medium', models.PositiveSmallIntegerField(default=120)),
                ('resolution_high', models.PositiveSmallIntegerField(default=48)),
                ('resolution_critical', models.PositiveSmallIntegerField(default=8)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='first_response_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='resolution_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='satisfaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='satisfaction_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='satisfaction_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_case_comments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.case')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_submit_cases', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customer_portal_accesses', to='core.party')),
                ('portal_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customer_portal_access', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='crm.kbcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='kb_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='crm.kbcategory'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tenant', 'kb_category'], name='crm_kb_tnt_category_idx'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='case',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='crm.slapolicy'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['tenant', 'priority'], name='crm_case_tnt_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='casecomment',
            index=models.Index(fields=['tenant', 'case'], name='crm_ccmt_tnt_case_idx'),
        ),
        migrations.AddIndex(
            model_name='customerportalaccess',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_csp_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customerportalaccess',
            index=models.Index(fields=['tenant', 'customer_party'], name='crm_csp_tnt_party_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerportalaccess',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='kbcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_kbc_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kbcategory',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_sla_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['tenant', 'is_default'], name='crm_sla_tnt_default_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slapolicy',
            unique_together={('tenant', 'number')},
        ),
    ]
