# Generated by Django 5.1.15 on 2026-06-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_crmtask_recurrence_crmtask_recurrence_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
