# Generated by Django 5.1.15 on 2026-06-27 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0014_alter_calendarevent_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('layout', models.CharField(choices=[('one', 'Single column'), ('two', 'Two columns'), ('three', 'Three columns')], default='two', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_dashboards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('sales_activity', 'Sales Activity'), ('sales_performance', 'Sales Performance (Top Performers)'), ('funnel', 'Funnel Analysis (Drop-off)'), ('service', 'Service (Resolution Time & CSAT)')], default='sales_activity', max_length=20)),
                ('date_range', models.CharField(choices=[('last_7', 'Last 7 days'), ('last_30', 'Last 30 days'), ('last_90', 'Last 90 days'), ('quarter', 'This quarter'), ('year', 'This year'), ('all', 'All time')], default='last_90', max_length=10)),
                ('group_by', models.CharField(choices=[('month', 'By Month'), ('week', 'By Week'), ('owner', 'By Owner'), ('priority', 'By Priority'), ('stage', 'By Stage')], default='month', max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_favorite', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('metric', models.CharField(choices=[('kpi_open_pipeline', 'KPI · Open Pipeline ($)'), ('kpi_weighted_forecast', 'KPI · Weighted Forecast ($)'), ('kpi_win_rate', 'KPI · Win Rate (%)'), ('kpi_revenue_won', 'KPI · Revenue Won ($)'), ('kpi_new_leads', 'KPI · New Leads (#)'), ('kpi_open_cases', 'KPI · Open Cases (#)'), ('kpi_avg_csat', 'KPI · Avg CSAT (1-5)'), ('kpi_open_tasks', 'KPI · Open Tasks (#)'), ('pipeline_by_stage', 'Chart · Pipeline by Stage (#)'), ('pipeline_value_by_stage', 'Chart · Pipeline Value by Stage ($)'), ('win_loss', 'Chart · Won vs Lost (#)'), ('revenue_won_by_month', 'Chart · Revenue Won by Month ($)'), ('leads_by_rating', 'Chart · Leads by Rating'), ('leads_by_status', 'Chart · Leads by Status'), ('leads_by_source', 'Chart · Leads by Source'), ('cases_by_status', 'Chart · Cases by Status'), ('cases_by_priority', 'Chart · Cases by Priority'), ('tasks_by_type', 'Chart · Tasks by Type'), ('top_performers', 'Table · Top Performers'), ('campaign_roi', 'Table · Campaign ROI')], default='kpi_open_pipeline', max_length=40)),
                ('chart_type', models.CharField(choices=[('kpi', 'KPI Card'), ('gauge', 'Gauge'), ('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('table', 'Table')], default='kpi', max_length=10)),
                ('date_range', models.CharField(choices=[('last_7', 'Last 7 days'), ('last_30', 'Last 30 days'), ('last_90', 'Last 90 days'), ('quarter', 'This quarter'), ('year', 'This year'), ('all', 'All time')], default='last_30', max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small (quarter width)'), ('medium', 'Medium (half width)'), ('large', 'Large (three-quarter width)'), ('full', 'Full width')], default='medium', max_length=10)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='crm.analyticsdashboard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_report_snapshots', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='crm.analyticsreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['tenant', 'owner'], name='crm_dash_tnt_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['tenant', 'is_shared'], name='crm_dash_tnt_shared_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsdashboard',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['tenant', 'report_type'], name='crm_rpt_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['tenant', 'is_favorite'], name='crm_rpt_tnt_fav_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsreport',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['tenant', 'dashboard'], name='crm_widget_tnt_dash_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['tenant', 'report'], name='crm_snap_tnt_report_idx'),
        ),
    ]
