# Generated by Django 5.1.15 on 2026-06-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0015_analyticsdashboard_analyticsreport_dashboardwidget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_billable',
            field=models.BooleanField(default=False, help_text="Billable costs are re-billed to the client, so they are excluded from the deal's true margin."),
        ),
        migrations.CreateModel(
            name='DealInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deal_invoices', to='core.party')),
                ('invoice', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deal_invoices', to='accounting.invoice')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_invoices', to='crm.opportunity')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_invoices', to='crm.quote')),
                ('recurring_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deal_invoices', to='accounting.recurringinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_date', models.DateField()),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('check', 'Check'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('ach', 'ACH'), ('wire', 'Wire Transfer'), ('other', 'Other')], default='bank_transfer', max_length=16)),
                ('gateway', models.CharField(choices=[('manual', 'Manual / Offline'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay')], default='manual', max_length=12)),
                ('gateway_txn_id', models.CharField(blank=True, help_text='External gateway charge / transaction id.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('deal_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='crm.dealinvoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_receipts', to='accounting.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='dealinvoice',
            index=models.Index(fields=['tenant', 'opportunity'], name='crm_dinv_tnt_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='dealinvoice',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_dinv_tnt_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealinvoice',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['tenant', 'received_date'], name='crm_rcpt_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentreceipt',
            unique_together={('tenant', 'number')},
        ),
    ]
