# Generated by Django 5.1.15 on 2026-06-27 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0017_resourceallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'status'], name='crm_ra_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'start_date'], name='crm_ra_tnt_start_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['tenant', 'end_date'], name='crm_ra_tnt_end_idx'),
        ),
    ]
