# Generated by Django 5.1.15 on 2026-06-27 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0018_resourceallocation_crm_ra_tnt_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveSmallIntegerField(default=1)),
                ('body_snapshot', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='crm/contracts/%Y/%m/')),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='crm.contractdocument')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_doc_versions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-version_no'],
                'indexes': [models.Index(fields=['tenant', 'contract'], name='crm_dv_tnt_contract_idx')],
                'unique_together': {('tenant', 'contract', 'version_no')},
            },
        ),
    ]
