# Generated by Django 5.1.15 on 2026-06-27 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0019_documentversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['tenant', 'account'], name='crm_ctr_tnt_account_idx'),
        ),
    ]
