# Generated by Django 5.1.15 on 2026-06-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0020_contractdocument_crm_ctr_tnt_account_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target_url', models.URLField(max_length=500)),
                ('trigger_entity', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('case', 'Case'), ('expense', 'Expense'), ('contract', 'Contract'), ('health_score', 'Health Score')], default='opportunity', max_length=20)),
                ('trigger_event', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('field_value', 'Field Value Matches'), ('date_reached', 'Date Reached')], default='created', max_length=20)),
                ('secret', models.CharField(blank=True, help_text='HMAC signing key — write-only (never shown after saving).', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('payload', models.TextField(blank=True)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('simulated', 'Simulated')], default='pending', max_length=10)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='crm.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_wh_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['tenant', 'trigger_entity'], name='crm_wh_tnt_entity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['tenant', 'webhook'], name='crm_whd_tnt_webhook_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['tenant', 'status'], name='crm_whd_tnt_status_idx'),
        ),
    ]
