# Generated by Django 5.1.15 on 2026-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0021_webhook_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowlog',
            index=models.Index(fields=['tenant', 'rule', '-fired_at'], name='crm_wfl_tnt_rule_fired_idx'),
        ),
    ]
