# Generated by Django 5.1.15 on 2026-06-27 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0022_workflowlog_crm_wfl_tnt_rule_fired_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='classification',
            field=models.CharField(blank=True, choices=[('promoter', 'Promoter'), ('passive', 'Passive'), ('detractor', 'Detractor'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('dissatisfied', 'Dissatisfied'), ('easy', 'Low Effort'), ('hard', 'High Effort')], max_length=12),
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('offset_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.onboardingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('tier', models.CharField(choices=[('green', 'Green — Healthy'), ('yellow', 'Yellow — At Risk'), ('red', 'Red — Critical')], default='green', max_length=10)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_health_history', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['tenant', 'account', '-computed_at'], name='crm_hsh_tnt_acct_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_otpl_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtemplate',
            unique_together={('tenant', 'number')},
        ),
    ]
