# Generated by Django 5.1.15 on 2026-06-27 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employment_core_emp_tenant_status_idx'),
        ('crm', '0023_alter_survey_classification_onboardingtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crmtask',
            index=models.Index(fields=['tenant', 'party'], name='crm_task_tnt_party_idx'),
        ),
    ]
