# Generated by Django 5.1.15 on 2026-08-17 19:29
#
# Widens crm.Webhook.secret and encrypts what is already in it. The column held the HMAC
# signing key in PLAINTEXT, so any database dump, backup, replica or logged row disclosed
# every tenant's webhook key. The form-layer mitigation (PasswordInput/render_value=False)
# only ever stopped disclosure through the edit page.
#
# The key is NOT hashed, unlike tenants.EncryptionKey / accounting.IntegrationConfig: HMAC
# needs the real bytes back at signing time, so this is reversible encryption with the key
# material held outside the database. See apps/core/crypto.py.

from django.db import migrations, models

from apps.core.crypto import PREFIX, decrypt, encrypt


def _encrypt_existing_secrets(apps, schema_editor):
    """Wrap every pre-existing plaintext key.

    Deliberately NOT tenant-scoped: a migration runs once across the whole table, and a
    row left behind would keep a plaintext key on disk. Idempotent via the marker, so a
    re-run (or a row written by newer code mid-deploy) is skipped rather than double-wrapped.
    """
    Webhook = apps.get_model("crm", "Webhook")
    batch = []
    qs = Webhook.objects.exclude(secret="").exclude(secret__startswith=PREFIX).only("pk", "secret")
    for webhook in qs.iterator(chunk_size=500):
        webhook.secret = encrypt(webhook.secret)
        batch.append(webhook)
        if len(batch) >= 500:
            Webhook.objects.bulk_update(batch, ["secret"])
            batch = []
    if batch:
        Webhook.objects.bulk_update(batch, ["secret"])


def _decrypt_existing_secrets(apps, schema_editor):
    """Unwrap on rollback.

    WARNING: this restores the plaintext-at-rest weakness by design — it exists so the
    migration is reversible and so the column still fits when it narrows back to 128. Only
    run it as part of an actual rollback, and rotate the keys afterwards if the database
    was dumped while unwrapped.
    """
    Webhook = apps.get_model("crm", "Webhook")
    batch = []
    qs = Webhook.objects.filter(secret__startswith=PREFIX).only("pk", "secret")
    for webhook in qs.iterator(chunk_size=500):
        webhook.secret = decrypt(webhook.secret)
        batch.append(webhook)
        if len(batch) >= 500:
            Webhook.objects.bulk_update(batch, ["secret"])
            batch = []
    if batch:
        Webhook.objects.bulk_update(batch, ["secret"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_crmtask_crm_task_tnt_party_idx'),
    ]

    operations = [
        # Widen BEFORE encrypting — ciphertext is ~2x the plaintext and would not fit in 128.
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, help_text='HMAC signing key — write-only (never shown after saving), encrypted at rest.', max_length=512),
        ),
        migrations.RunPython(_encrypt_existing_secrets, _decrypt_existing_secrets),
    ]
