# Generated by Django 5.1.15 on 2026-09-25 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0014_dataarchive_darch_tenant_at_idx_and_more'),
        ('crm', '0025_alter_webhook_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunities', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_step_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'next_step_due_date'], name='crm_opp_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'currency'], name='crm_opp_tenant_curr_idx'),
        ),
    ]
