# Generated by Django 5.1.15 on 2026-07-17 11:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('amendment_reason', models.TextField(blank=True, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acknowledgement_note', models.CharField(blank=True, editable=False, max_length=255)),
                ('promised_ship_date', models.DateField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_purchase_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_purchase_orders', to='accounting.currency')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_purchase_orders', to='accounting.paymentterm')),
                ('ship_to', models.ForeignKey(blank=True, help_text='Delivering to which site/unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_purchase_orders', to='core.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scm_purchase_orders', to='core.party')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('delivery_note_ref', models.CharField(blank=True, help_text="The vendor's delivery-note number", max_length=64)),
                ('match_status', models.CharField(choices=[('not_matched', 'Not Matched'), ('matched', 'Matched'), ('price_variance', 'Price Variance'), ('quantity_variance', 'Quantity Variance'), ('over_received', 'Over Received')], default='not_matched', editable=False, max_length=20)),
                ('match_notes', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(blank=True, help_text='The vendor bill this receipt is matched against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_goods_receipts', to='accounting.bill')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='scm.purchaseorder')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('uom_hint', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_purchase_order_lines', to='accounting.glaccount')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=4, default=0, help_text='Quantity accepted into stock', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_rejected', models.DecimalField(decimal_places=4, default=0, help_text='Quantity refused (damaged / out of spec)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.goodsreceiptnote')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='scm.purchaseorderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('justification', models.TextField(blank=True, help_text='Why this purchase is needed')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True, editable=False, help_text="Approver's rejection reason / approval note")),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_requisitions_approved', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(blank=True, help_text='Budget this spend is checked against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_requisitions', to='accounting.budget')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_requisitions', to='accounting.currency')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Requesting department / cost centre — the budget dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_requisitions', to='core.orgunit')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_requisitions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='scm.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(help_text='What is being requested', max_length=255)),
                ('sku_hint', models.CharField(blank=True, help_text='Vendor/catalog code, if known (free-text until core.Item exists)', max_length=64)),
                ('uom_hint', models.CharField(blank=True, help_text='Unit of measure, e.g. each / box / kg', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('gl_account', models.ForeignKey(blank=True, help_text='Expense account to charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_requisition_lines', to='accounting.glaccount')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.purchaserequisition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('response_due', models.DateField(blank=True, help_text='Deadline for supplier responses', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('terms', models.TextField(blank=True, help_text='Terms & conditions sent to suppliers')),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_rfqs', to='accounting.currency')),
                ('requisition', models.ForeignKey(blank=True, help_text='Requisition this RFQ sources', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='scm.purchaserequisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('sku_hint', models.CharField(blank=True, max_length=64)),
                ('uom_hint', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('specification', models.TextField(blank=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.rfq')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RFQQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('vendor_reference', models.CharField(blank=True, help_text="The supplier's own quote number", max_length=64)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Quoted delivery lead time, in days', null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('shortlisted', 'Shortlisted'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], default='received', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scm_quotes', to='core.party')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_quotes', to='accounting.paymentterm')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='scm.rfq')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['total', 'id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quote',
            field=models.ForeignKey(blank=True, help_text='Awarded quote this PO came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='scm.rfqquote'),
        ),
        migrations.CreateModel(
            name='RFQQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.rfqquote')),
                ('rfq_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='scm.rfqline')),
            ],
            options={
                'ordering': ['rfq_line_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RFQVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('contact_note', models.CharField(blank=True, max_length=255)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scm_rfq_invites', to='core.party')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_vendors', to='scm.rfq')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['party__name'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceiptnote',
            index=models.Index(fields=['tenant', 'status'], name='scm_grn_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptnote',
            index=models.Index(fields=['tenant', 'match_status'], name='scm_grn_tenant_match_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceiptnote',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['tenant', 'status'], name='scm_pr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['tenant', 'required_by'], name='scm_pr_tenant_reqby_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaserequisition',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['tenant', 'status'], name='scm_rfq_tenant_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfq',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='rfqquote',
            index=models.Index(fields=['tenant', 'status'], name='scm_quote_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfqquote',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'status'], name='scm_po_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'order_date'], name='scm_po_tenant_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='rfqquoteline',
            unique_together={('quote', 'rfq_line')},
        ),
        migrations.AlterUniqueTogether(
            name='rfqvendor',
            unique_together={('rfq', 'party')},
        ),
    ]
