# Generated by Django 5.1.15 on 2026-07-17 17:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_catalogs', to='accounting.currency')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scm_catalogs', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, help_text="Supplier's catalog code", max_length=64)),
                ('uom', models.CharField(blank=True, help_text='Unit of measure', max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scm.suppliercatalog')),
            ],
            options={
                'ordering': ['item_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('master', 'Master Agreement'), ('purchase', 'Purchase Contract'), ('service', 'Service Agreement'), ('nda', 'NDA'), ('sla', 'SLA'), ('framework', 'Framework')], default='purchase', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expiring', 'Expiring Soon'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_notice_days', models.PositiveIntegerField(default=30, help_text='Alert this many days before expiry')),
                ('terms_summary', models.TextField(blank=True, help_text='Key terms & conditions')),
                ('terminated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('termination_reason', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_supplier_contracts', to='accounting.currency')),
                ('document', models.ForeignKey(blank=True, help_text='Signed contract file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_supplier_contracts', to='core.document')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scm_supplier_contracts', to='core.party')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_supplier_contracts', to='accounting.paymentterm')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_status', models.CharField(choices=[('draft', 'Draft'), ('qualification', 'Qualification'), ('due_diligence', 'Due Diligence'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=16)),
                ('tier', models.CharField(choices=[('strategic', 'Strategic'), ('preferred', 'Preferred'), ('approved', 'Approved'), ('transactional', 'Transactional')], default='transactional', max_length=16)),
                ('category', models.CharField(blank=True, help_text='What this supplier provides', max_length=120)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_registration', models.CharField(blank=True, max_length=64)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('dd_financials_verified', models.BooleanField(default=False, verbose_name='Financials verified')),
                ('dd_compliance_verified', models.BooleanField(default=False, verbose_name='Compliance / sanctions checked')),
                ('dd_insurance_verified', models.BooleanField(default=False, verbose_name='Insurance verified')),
                ('dd_quality_cert_verified', models.BooleanField(default=False, verbose_name='Quality certification verified')),
                ('dd_references_checked', models.BooleanField(default=False, verbose_name='References checked')),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.TextField(blank=True, editable=False)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_supplier_approvals', to=settings.AUTH_USER_MODEL)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scm_supplier_profile', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['party__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('assessment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('financial_score', models.PositiveSmallIntegerField(choices=[(1, '1 — Low'), (2, '2 — Guarded'), (3, '3 — Elevated'), (4, '4 — High'), (5, '5 — Critical')], default=1)),
                ('geopolitical_score', models.PositiveSmallIntegerField(choices=[(1, '1 — Low'), (2, '2 — Guarded'), (3, '3 — Elevated'), (4, '4 — High'), (5, '5 — Critical')], default=1)),
                ('compliance_score', models.PositiveSmallIntegerField(choices=[(1, '1 — Low'), (2, '2 — Guarded'), (3, '3 — Elevated'), (4, '4 — High'), (5, '5 — Critical')], default=1)),
                ('operational_score', models.PositiveSmallIntegerField(choices=[(1, '1 — Low'), (2, '2 — Guarded'), (3, '3 — Elevated'), (4, '4 — High'), (5, '5 — Critical')], default=1)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', editable=False, max_length=8)),
                ('risk_index', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Averaged factor score, 1.00-5.00', max_digits=4)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scm_risk_assessments', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-assessment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('delivery_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('responsiveness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, editable=False, max_length=2)),
                ('manual_override', models.BooleanField(default=False)),
                ('signal_summary', models.TextField(blank=True, editable=False, help_text='How each derived score was calculated')),
                ('notes', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scm_scorecards', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='suppliercatalog',
            index=models.Index(fields=['tenant', 'status'], name='scm_cat_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercatalog',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='suppliercontract',
            index=models.Index(fields=['tenant', 'status'], name='scm_sc_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercontract',
            index=models.Index(fields=['tenant', 'end_date'], name='scm_sc_tnt_enddate_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercontract',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['tenant', 'onboarding_status'], name='scm_supp_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['tenant', 'tier'], name='scm_supp_tnt_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierriskassessment',
            index=models.Index(fields=['tenant', 'status'], name='scm_sra_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierriskassessment',
            index=models.Index(fields=['tenant', 'risk_level'], name='scm_sra_tnt_level_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierriskassessment',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='supplierscorecard',
            index=models.Index(fields=['tenant', 'status'], name='scm_scr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierscorecard',
            index=models.Index(fields=['tenant', 'party'], name='scm_scr_tnt_party_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierscorecard',
            unique_together={('tenant', 'number')},
        ),
    ]
