# Generated by Django 5.1.15 on 2026-07-17 19:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0003_alter_supplierscorecard_delivery_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scm.itemcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('stock', 'Stock'), ('consumable', 'Consumable'), ('service', 'Service')], default='stock', max_length=12)),
                ('tracking', models.CharField(choices=[('none', 'None'), ('lot', 'Lot / Batch'), ('serial', 'Serial')], default='none', max_length=8)),
                ('costing_method', models.CharField(choices=[('weighted_avg', 'Weighted Average'), ('fifo', 'FIFO'), ('lifo', 'LIFO')], default='weighted_avg', max_length=12)),
                ('standard_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, help_text='Item-wide default; a ReorderRule can override per location', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='scm.itemcategory')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('zone', 'Zone'), ('bin', 'Bin'), ('staging', 'Staging'), ('transit', 'In Transit')], default='warehouse', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LotSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('lot', 'Lot / Batch'), ('serial', 'Serial')], default='lot', max_length=8)),
                ('number', models.CharField(help_text='Lot/batch code or serial number', max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('quarantine', 'Quarantine'), ('expired', 'Expired'), ('consumed', 'Consumed')], default='available', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_serials', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item__sku', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, help_text='Reorder when on-hand falls to/below this', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Suggested quantity to reorder', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='scm.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['item__sku'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('reason', models.CharField(choices=[('cycle_count', 'Cycle Count Correction'), ('write_off', 'Write-Off'), ('damage', 'Damage'), ('found', 'Found Stock'), ('revaluation', 'Revaluation'), ('other', 'Other')], default='cycle_count', max_length=16)),
                ('adjustment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=4, help_text='Signed: positive adds stock, negative removes it', max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.stockadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_lines', to='scm.lotserial')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('move_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=12)),
                ('reference', models.CharField(blank=True, help_text='Source document number, e.g. TRF-00001 / ADJ-00001 / GRN-00001', max_length=40)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('moved_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='scm.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='scm.location')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='scm.lotserial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='scm.location')),
            ],
            options={
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_lines', to='scm.lotserial')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.stocktransfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=60)),
                ('factor', models.DecimalField(decimal_places=4, default=1, help_text='Units of the base UOM per one of this UOM', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'UOM',
                'verbose_name_plural': 'UOMs',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='scm.uom'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_itemcat_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'location_type'], name='scm_loc_tnt_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='lotserial',
            index=models.Index(fields=['tenant', 'status'], name='scm_lot_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lotserial',
            unique_together={('tenant', 'item', 'number')},
        ),
        migrations.AddIndex(
            model_name='reorderrule',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_reorder_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reorderrule',
            unique_together={('tenant', 'item', 'location')},
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['tenant', 'status'], name='scm_adj_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockadjustment',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['tenant', 'item', 'location'], name='scm_move_tnt_item_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['tenant', 'moved_at'], name='scm_move_tnt_movedat_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['tenant', 'reference'], name='scm_move_tnt_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['tenant', 'status'], name='scm_trf_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktransfer',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='uom',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_item_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'category'], name='scm_item_tnt_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'sku')},
        ),
    ]
