# Generated by Django 5.1.15 on 2026-07-18 06:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0004_itemcategory_item_location_lotserial_reorderrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.9999'))]),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['tenant', 'location', 'item'], name='scm_move_tnt_loc_item_idx'),
        ),
    ]
