# Generated by Django 5.1.15 on 2026-07-18 09:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0005_alter_stockadjustmentline_unit_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Receiving / staging location the goods land in', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='scm.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='abc_class',
            field=models.CharField(blank=True, choices=[('a', 'A — fast moving'), ('b', 'B — medium'), ('c', 'C — slow moving')], help_text='Velocity class used for slotting and count frequency', max_length=1),
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Storage capacity in the bin's own units (blank = unlimited)", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='location',
            name='is_pickable',
            field=models.BooleanField(default=True, help_text='Whether stock here can be picked from'),
        ),
        migrations.AddField(
            model_name='location',
            name='pick_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Walk order for picking; lower is picked first', null=True),
        ),
        migrations.CreateModel(
            name='CycleCountTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('scheduled_date', models.DateField()),
                ('count_method', models.CharField(choices=[('full', 'Full Count'), ('abc', 'ABC Class'), ('random', 'Random Sample'), ('zone', 'Zone')], default='full', max_length=8)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('counted', 'Counted'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('counted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts', to='scm.stockadjustment')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_cycle_counts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='The section being counted', on_delete=django.db.models.deletion.PROTECT, related_name='cycle_counts', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountTaskLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.cyclecounttask')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_lines', to='scm.lotserial')),
            ],
            options={
                'ordering': ['item__sku', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('strategy', models.CharField(choices=[('single', 'Single Order'), ('wave', 'Wave'), ('batch', 'Batch'), ('zone', 'Zone')], default='single', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('picking', 'Picking'), ('picked', 'Picked'), ('packed', 'Packed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('wave_ref', models.CharField(blank=True, help_text='Groups tasks released together as one wave', max_length=40)),
                ('ship_to', models.CharField(blank=True, help_text='Free-text destination for now', max_length=255)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tracking_ref', models.CharField(blank=True, help_text='Carrier tracking reference (recorded, not generated)', max_length=64)),
                ('picked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('packed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_pick_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('zone', models.ForeignKey(blank=True, help_text='Zone this pick is confined to (zone picking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_tasks', to='scm.location')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PickTaskLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('quantity_picked', models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('from_location', models.ForeignKey(help_text='Bin to pick from', on_delete=django.db.models.deletion.PROTECT, related_name='pick_lines', to='scm.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_lines', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lines', to='scm.lotserial')),
                ('pick_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.picktask')),
            ],
            options={
                'ordering': ['from_location__pick_sequence', 'from_location__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PutawayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('strategy', models.CharField(choices=[('directed', 'Directed'), ('fixed', 'Fixed Location'), ('random', 'Random'), ('cross_dock', 'Cross-Dock')], default='directed', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_putaway_tasks', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(help_text='Staging / receiving location holding the stock', on_delete=django.db.models.deletion.PROTECT, related_name='putaways_out', to='scm.location')),
                ('goods_receipt', models.ForeignKey(blank=True, help_text='The receipt these goods arrived on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='scm.goodsreceiptnote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='putaway_tasks', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='scm.lotserial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('to_location', models.ForeignKey(help_text='Destination bin', on_delete=django.db.models.deletion.PROTECT, related_name='putaways_in', to='scm.location')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='YardVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('carrier_name', models.CharField(help_text='Haulier (free text until 4.6 TMS)', max_length=255)),
                ('vehicle_ref', models.CharField(blank=True, help_text='Truck / tractor registration', max_length=64)),
                ('trailer_ref', models.CharField(blank=True, max_length=64)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=8)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('arrived', 'Arrived'), ('at_dock', 'At Dock'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('docked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('departed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dock_door', models.ForeignKey(blank=True, help_text='Dock door assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yard_visits', to='scm.location')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Inbound load this vehicle is delivering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yard_visits', to='scm.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-scheduled_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cyclecounttask',
            index=models.Index(fields=['tenant', 'status'], name='scm_cc_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecounttask',
            index=models.Index(fields=['tenant', 'scheduled_date'], name='scm_cc_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cyclecounttask',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='picktask',
            index=models.Index(fields=['tenant', 'status'], name='scm_pik_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='picktask',
            index=models.Index(fields=['tenant', 'wave_ref'], name='scm_pik_tnt_wave_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='picktask',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='putawaytask',
            index=models.Index(fields=['tenant', 'status'], name='scm_put_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='putawaytask',
            index=models.Index(fields=['tenant', 'to_location'], name='scm_put_tnt_toloc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='putawaytask',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='yardvisit',
            index=models.Index(fields=['tenant', 'status'], name='scm_yrd_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='yardvisit',
            index=models.Index(fields=['tenant', 'direction'], name='scm_yrd_tnt_dir_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yardvisit',
            unique_together={('tenant', 'number')},
        ),
    ]
