# Generated by Django 5.1.15 on 2026-07-18 16:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('crm', '0024_crmtask_crm_task_tnt_party_idx'),
        ('scm', '0006_goodsreceiptnote_location_location_abc_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('source_channel', models.CharField(choices=[('manual', 'Manual'), ('web', 'Web'), ('marketplace', 'Marketplace'), ('edi', 'EDI'), ('api', 'API'), ('phone', 'Phone')], default='manual', help_text='Where the order came in from', max_length=12)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('requested_date', models.DateField(blank=True, help_text='The date the customer asked for', null=True)),
                ('promised_date', models.DateField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('on_hold', 'On Hold'), ('allocated', 'Allocated'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', editable=False, max_length=20)),
                ('credit_hold', models.BooleanField(default=False, editable=False)),
                ('fraud_flag', models.BooleanField(default=False, editable=False)),
                ('hold_reason', models.TextField(blank=True, editable=False)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('shipped_notification_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('delivered_notification_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_sales_orders', to='accounting.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='core.party')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='accounting.invoice')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_sales_orders', to='accounting.paymentterm')),
                ('ship_to_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_shipped', to='core.address')),
                ('source_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='crm.quote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Optional override of the item name on this order', max_length=255)),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='scm.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.salesorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='reserved', editable=False, max_length=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_allocations', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scm.salesorderline')),
            ],
            options={
                'ordering': ['-allocated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'status'], name='scm_so_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'order_date'], name='scm_so_tnt_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='salesorderallocation',
            index=models.Index(fields=['tenant', 'status'], name='scm_soa_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderallocation',
            index=models.Index(fields=['tenant', 'location'], name='scm_soa_tnt_loc_idx'),
        ),
    ]
