# Generated by Django 5.1.15 on 2026-07-24 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0009_reorderrule_abc_class_reorderrule_avg_daily_demand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demandsignal',
            index=models.Index(fields=['tenant', 'source_reference'], name='scm_ds_tnt_ref_idx'),
        ),
    ]
