# Generated by Django 5.1.15 on 2026-07-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0010_demandsignal_scm_ds_tnt_ref_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecastperiod',
            name='baseline_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Statistical output before any adjustment — and the INPUT on a manual forecast', max_digits=14),
        ),
        migrations.AlterField(
            model_name='demandforecastperiod',
            name='event_uplift_quantity',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='demandforecastperiod',
            name='final_quantity',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='demandforecastperiod',
            name='seasonal_index_applied',
            field=models.DecimalField(decimal_places=4, default=1, editable=False, max_digits=8),
        ),
    ]
