# Generated by Django 5.1.15 on 2026-07-27 20:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0011_alter_demandforecastperiod_baseline_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('consumption', 'Consumption'), ('production', 'Production')], max_length=12),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1', max_length=20)),
                ('bom_type', models.CharField(choices=[('manufacture', 'Manufacture'), ('kit', 'Kit'), ('phantom', 'Phantom')], default='manufacture', max_length=12)),
                ('output_quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Quantity this recipe yields — component quantities scale by order qty / this', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='In-house production time. NOT ReorderRule.lead_time_days, which is the purchasing lead time for a bought item', validators=[django.core.validators.MaxValueValidator(3650)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('obsolete', 'Obsolete')], default='draft', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='The recipe chosen when a work order names no BOM')),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(help_text='The produced good this recipe makes', on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='scm.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='scm.uom')),
            ],
            options={
                'ordering': ['item__sku', 'version'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('quantity_per', models.DecimalField(decimal_places=4, help_text="Per the BOM's output quantity, before scrap", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('scrap_pct', models.DecimalField(decimal_places=2, default=0, help_text='Expected component loss — inflates the quantity a work order requires', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('issue_method', models.CharField(choices=[('manual', 'Manual'), ('backflush', 'Backflush')], default='manual', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.billofmaterials')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='scm.item')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.uom')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('center_type', models.CharField(choices=[('machine', 'Machine'), ('assembly', 'Assembly'), ('manual', 'Manual'), ('inspection', 'Inspection'), ('outsourced', 'Outsourced')], default='machine', max_length=12)),
                ('capacity_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Nominal available hours per working day', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))])),
                ('efficiency_pct', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Realised output as a % of nominal capacity', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('setup_minutes', models.PositiveIntegerField(default=0, help_text='Changeover time consumed before a run starts', validators=[django.core.validators.MaxValueValidator(10080)])),
                ('machine_cost_per_hour', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('labor_cost_per_hour', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, help_text='Stock location this centre draws from and reports into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_centers', to='scm.location')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Owning department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_work_centers', to='core.orgunit')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_supervised_work_centers', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='default_work_center',
            field=models.ForeignKey(blank=True, help_text='Stand-in for a routing until an operations master lands', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='scm.workcenter'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('quantity_planned', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('order_policy', models.CharField(choices=[('make_to_stock', 'Make to Stock'), ('make_to_order', 'Make to Order')], default='make_to_stock', max_length=14)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('schedule_direction', models.CharField(choices=[('forward', 'Forward — from the start date'), ('backward', 'Backward — from the due date')], default='forward', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=12)),
                ('actual_start', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actual_end', models.DateTimeField(blank=True, editable=False, null=True)),
                ('quantity_produced', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('quantity_scrapped', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('produced_unit_cost', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('bom', models.ForeignKey(blank=True, help_text='Recipe exploded onto the component lines — the lines, not this link, are what the run consumes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='scm.billofmaterials')),
                ('component_location', models.ForeignKey(blank=True, help_text='Where components are drawn from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wo_component_sources', to='scm.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='scm.item')),
                ('output_location', models.ForeignKey(blank=True, help_text='Where finished goods are received', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wo_output_targets', to='scm.location')),
                ('output_lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='scm.lotserial')),
                ('released_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, help_text='Make-to-order peg — the demand this run covers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='scm.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='scm.uom')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='scm.workcenter')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('operation', models.CharField(blank=True, help_text='Free-text operation name — the stand-in until a routing master lands', max_length=120)),
                ('entry_type', models.CharField(choices=[('setup', 'Setup'), ('labor', 'Labour'), ('machine', 'Machine'), ('downtime', 'Downtime')], default='labor', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('quantity_completed', models.DecimalField(decimal_places=4, default=0, help_text="Advisory progress — the run's output quantity comes from reporting production", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_scrapped', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('downtime_reason', models.CharField(blank=True, choices=[('breakdown', 'Breakdown'), ('changeover', 'Changeover'), ('material_shortage', 'Material Shortage'), ('quality_hold', 'Quality Hold'), ('no_operator', 'No Operator'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_production_time_logs', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_logs', to='scm.workcenter')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='scm.workorder')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text='From the BOM explosion, inclusive of scrap', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_issued', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('issue_method', models.CharField(choices=[('manual', 'Manual'), ('backflush', 'Backflush')], default='manual', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, help_text='Cost snapshot taken when the line was issued', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_components', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_components', to='scm.lotserial')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.uom')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='scm.workorder')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workcenter',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_wc_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workcenter',
            unique_together={('tenant', 'code'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['tenant', 'item', 'status'], name='scm_bom_tnt_item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['tenant', 'status'], name='scm_bom_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterials',
            unique_together={('tenant', 'item', 'version'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'status'], name='scm_wo_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'work_center', 'planned_start'], name='scm_wo_tnt_wc_start_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'item'], name='scm_wo_tnt_item_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='productiontimelog',
            index=models.Index(fields=['tenant', 'work_order'], name='scm_prd_tnt_wo_idx'),
        ),
        migrations.AddIndex(
            model_name='productiontimelog',
            index=models.Index(fields=['tenant', 'work_center', 'started_at'], name='scm_prd_tnt_wc_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productiontimelog',
            unique_together={('tenant', 'number')},
        ),
    ]
