# Generated by Django 5.1.15 on 2026-07-27 23:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0012_alter_stockmove_move_type_billofmaterials_bomline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcenter',
            name='labor_cost_per_hour',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='machine_cost_per_hour',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
    ]
