# Generated by Django 5.1.15 on 2026-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0014_capaaction_capatask_inspectionplan_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['tenant', 'detected_on'], name='scm_ncr_tnt_det_date_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityinspection',
            index=models.Index(fields=['tenant', 'inspected_on'], name='scm_qc_tnt_insp_date_idx'),
        ),
    ]
