# Generated by Django 5.1.15 on 2026-07-29 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0016_returnpolicy_returnauthorization_returnreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpolicy',
            name='fallback_days',
            field=models.PositiveIntegerField(default=45, help_text="Window measured from the ORDER date when the basis event never happened — Loop's documented answer to unreliable delivery events", validators=[django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AlterField(
            model_name='returnpolicy',
            name='warranty_window_days',
            field=models.PositiveIntegerField(default=365, help_text='Supplier/manufacturer warranty length used by WarrantyClaim.is_in_warranty', validators=[django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AlterField(
            model_name='returnpolicy',
            name='window_days',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(3650)]),
        ),
    ]
