# Generated by Django 5.1.15 on 2026-07-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0017_alter_returnpolicy_fallback_days_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='returnauthorization',
            index=models.Index(fields=['tenant', 'advance_refund_deadline'], name='scm_rma_tnt_advdl_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['tenant', 'created_at'], name='scm_wty_tnt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['tenant', 'submitted_on'], name='scm_wty_tnt_subon_idx'),
        ),
    ]
