# Generated by Django 5.1.15 on 2026-07-30 21:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0018_returnauthorization_scm_rma_tnt_advdl_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('metric', models.CharField(choices=[('Inventory', [('inv_turnover', 'Inventory turnover'), ('inv_days_on_hand', 'Days inventory on hand'), ('inv_dead_stock_value', 'Dead stock value'), ('inv_aging_over_days_value', 'Aging stock value (over N days)'), ('inv_expiry_risk_value', 'Expiry-risk value'), ('inv_excess_vs_policy_value', 'Excess over policy value'), ('inv_carrying_cost', 'Inventory carrying cost'), ('inv_stockout_count', 'Items at or below reorder point'), ('inv_abc_a_share_pct', 'Class-A share of stock value')]), ('Procurement', [('spend_total', 'Total spend'), ('spend_off_contract_pct', 'Off-contract spend'), ('spend_top_supplier_share_pct', 'Top-5 supplier share of spend'), ('spend_tail_share_pct', 'Tail-supplier share of spend'), ('savings_negotiated', 'Negotiated savings (awarded vs median quote)'), ('savings_price_variance_opportunity', 'Price-variance savings opportunity'), ('supplier_otd_pct', 'Supplier on-time delivery'), ('supplier_reject_rate_pct', 'Supplier reject rate'), ('supplier_score_avg', 'Average supplier scorecard'), ('procure_cycle_days', 'Requisition-to-order cycle'), ('procure_lead_days', 'Order-to-receipt lead time')]), ('Logistics', [('otd_pct', 'On-time delivery'), ('otif_pct', 'On-time in-full (OTIF)'), ('freight_cost_per_unit', 'Freight cost per unit'), ('equipment_utilization_pct', 'Equipment utilization'), ('freight_variance_pct', 'Freight billing variance'), ('carrier_otd_trend', 'Carrier on-time trend (4.6 scorecard)'), ('dwell_hours_avg', 'Average yard/dock dwell')]), ('Margin & cost', [('gross_margin_pct', 'Gross margin'), ('margin_after_cost_to_serve_pct', 'Margin after cost-to-serve'), ('supply_cost_stack', 'Supply chain cost breakdown'), ('ppv_value', 'Purchase price variance'), ('scrap_value', 'Scrap & write-off value')]), ('Risk & prediction', [('supplier_disruption_score', 'Supplier disruption risk'), ('demand_spike_count', 'Demand spikes detected'), ('projected_stockout_count', 'Projected stockouts within lead time'), ('shipments_at_risk_count', 'Shipments at risk')])], help_text="One key from the closed supply-chain metric registry. Authoring your own formula is Module 10's 10.11, not this", max_length=40)),
                ('name', models.CharField(help_text="What this target is called on the tile — the metric's own label is generic, this is the audience's words for it", max_length=120)),
                ('scope', models.CharField(choices=[('all', 'Whole network'), ('category', 'Item category'), ('location', 'Location'), ('carrier', 'Carrier'), ('vendor', 'Supplier')], default='all', help_text='Narrow the metric to one category / location / carrier / supplier, or leave it across the whole network', max_length=12)),
                ('period_grain', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('quarter', 'Quarterly')], default='month', help_text='The bucket one trend point covers', max_length=8)),
                ('date_range', models.CharField(choices=[('last_7', 'Last 7 days'), ('last_30', 'Last 30 days'), ('last_90', 'Last 90 days'), ('quarter', 'This quarter'), ('year', 'This year'), ('all', 'All time')], default='last_30', help_text='The rolling window the live figure is measured over', max_length=10)),
                ('direction', models.CharField(blank=True, choices=[('higher_is_better', 'Higher is better'), ('lower_is_better', 'Lower is better')], help_text="Leave blank to inherit the metric's own direction. Set it only for a deliberately inverted goal", max_length=16)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='The goal itself. Optional — a target row with no goal still snapshots and trends its metric, it just cannot be banded', max_digits=14, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, help_text="Crossing this bands the value 'warning'", max_digits=14, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=2, help_text="Crossing this bands the value 'critical'", max_digits=14, null=True)),
                ('parameter_days', models.PositiveIntegerField(blank=True, help_text="The N in this metric's definition — dead-stock days, expiry window, contract-expiry horizon, stale-tracking age", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('parameter_pct', models.DecimalField(blank=True, decimal_places=2, help_text="The percentage this metric's definition needs — annual carrying-cost rate, demand-spike deviation band", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('is_alerting', models.BooleanField(default=False, help_text="Let the detector raise a SupplyChainAlert when this target's bands are crossed")),
                ('min_impact_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Alert-fatigue floor: a breach worth less than this raises nothing', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', help_text='Stamped on the alerts this target raises', max_length=8)),
                ('is_pinned', models.BooleanField(default=False, help_text='Show as a tile on the analytics control tower')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Tile order — lowest first')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The person answerable for this number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_kpi_targets_owned', to=settings.AUTH_USER_MODEL)),
                ('scope_carrier', models.ForeignKey(blank=True, help_text="Only when the scope is 'Carrier'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to='scm.carrier')),
                ('scope_category', models.ForeignKey(blank=True, help_text="Only when the scope is 'Item category'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to='scm.itemcategory')),
                ('scope_location', models.ForeignKey(blank=True, help_text="Only when the scope is 'Location'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to='scm.location')),
                ('scope_vendor', models.ForeignKey(blank=True, help_text="Only when the scope is 'Supplier'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_kpi_targets', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(choices=[('Inventory', [('inv_turnover', 'Inventory turnover'), ('inv_days_on_hand', 'Days inventory on hand'), ('inv_dead_stock_value', 'Dead stock value'), ('inv_aging_over_days_value', 'Aging stock value (over N days)'), ('inv_expiry_risk_value', 'Expiry-risk value'), ('inv_excess_vs_policy_value', 'Excess over policy value'), ('inv_carrying_cost', 'Inventory carrying cost'), ('inv_stockout_count', 'Items at or below reorder point'), ('inv_abc_a_share_pct', 'Class-A share of stock value')]), ('Procurement', [('spend_total', 'Total spend'), ('spend_off_contract_pct', 'Off-contract spend'), ('spend_top_supplier_share_pct', 'Top-5 supplier share of spend'), ('spend_tail_share_pct', 'Tail-supplier share of spend'), ('savings_negotiated', 'Negotiated savings (awarded vs median quote)'), ('savings_price_variance_opportunity', 'Price-variance savings opportunity'), ('supplier_otd_pct', 'Supplier on-time delivery'), ('supplier_reject_rate_pct', 'Supplier reject rate'), ('supplier_score_avg', 'Average supplier scorecard'), ('procure_cycle_days', 'Requisition-to-order cycle'), ('procure_lead_days', 'Order-to-receipt lead time')]), ('Logistics', [('otd_pct', 'On-time delivery'), ('otif_pct', 'On-time in-full (OTIF)'), ('freight_cost_per_unit', 'Freight cost per unit'), ('equipment_utilization_pct', 'Equipment utilization'), ('freight_variance_pct', 'Freight billing variance'), ('carrier_otd_trend', 'Carrier on-time trend (4.6 scorecard)'), ('dwell_hours_avg', 'Average yard/dock dwell')]), ('Margin & cost', [('gross_margin_pct', 'Gross margin'), ('margin_after_cost_to_serve_pct', 'Margin after cost-to-serve'), ('supply_cost_stack', 'Supply chain cost breakdown'), ('ppv_value', 'Purchase price variance'), ('scrap_value', 'Scrap & write-off value')]), ('Risk & prediction', [('supplier_disruption_score', 'Supplier disruption risk'), ('demand_spike_count', 'Demand spikes detected'), ('projected_stockout_count', 'Projected stockouts within lead time'), ('shipments_at_risk_count', 'Shipments at risk')])], max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('dimension_key', models.CharField(blank=True, help_text='Blank = the roll-up; otherwise vendor:PK / carrier:PK / item:PK / category:PK / location:PK', max_length=64)),
                ('dimension_label', models.CharField(blank=True, max_length=160)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('target_value_at_time', models.DecimalField(blank=True, decimal_places=2, help_text='What the target said at capture time — a later retune must not rewrite history', max_digits=14, null=True)),
                ('status_band', models.CharField(choices=[('ok', 'On target'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'No target')], default='unknown', max_length=8)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('computed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_kpi_snapshots', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('kpi_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scm.kpitarget')),
            ],
            options={
                'ordering': ['-period_end', 'metric', 'dimension_key'],
            },
        ),
        migrations.CreateModel(
            name='SupplyChainAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('metric', models.CharField(blank=True, choices=[('Inventory', [('inv_turnover', 'Inventory turnover'), ('inv_days_on_hand', 'Days inventory on hand'), ('inv_dead_stock_value', 'Dead stock value'), ('inv_aging_over_days_value', 'Aging stock value (over N days)'), ('inv_expiry_risk_value', 'Expiry-risk value'), ('inv_excess_vs_policy_value', 'Excess over policy value'), ('inv_carrying_cost', 'Inventory carrying cost'), ('inv_stockout_count', 'Items at or below reorder point'), ('inv_abc_a_share_pct', 'Class-A share of stock value')]), ('Procurement', [('spend_total', 'Total spend'), ('spend_off_contract_pct', 'Off-contract spend'), ('spend_top_supplier_share_pct', 'Top-5 supplier share of spend'), ('spend_tail_share_pct', 'Tail-supplier share of spend'), ('savings_negotiated', 'Negotiated savings (awarded vs median quote)'), ('savings_price_variance_opportunity', 'Price-variance savings opportunity'), ('supplier_otd_pct', 'Supplier on-time delivery'), ('supplier_reject_rate_pct', 'Supplier reject rate'), ('supplier_score_avg', 'Average supplier scorecard'), ('procure_cycle_days', 'Requisition-to-order cycle'), ('procure_lead_days', 'Order-to-receipt lead time')]), ('Logistics', [('otd_pct', 'On-time delivery'), ('otif_pct', 'On-time in-full (OTIF)'), ('freight_cost_per_unit', 'Freight cost per unit'), ('equipment_utilization_pct', 'Equipment utilization'), ('freight_variance_pct', 'Freight billing variance'), ('carrier_otd_trend', 'Carrier on-time trend (4.6 scorecard)'), ('dwell_hours_avg', 'Average yard/dock dwell')]), ('Margin & cost', [('gross_margin_pct', 'Gross margin'), ('margin_after_cost_to_serve_pct', 'Margin after cost-to-serve'), ('supply_cost_stack', 'Supply chain cost breakdown'), ('ppv_value', 'Purchase price variance'), ('scrap_value', 'Scrap & write-off value')]), ('Risk & prediction', [('supplier_disruption_score', 'Supplier disruption risk'), ('demand_spike_count', 'Demand spikes detected'), ('projected_stockout_count', 'Projected stockouts within lead time'), ('shipments_at_risk_count', 'Shipments at risk')])], help_text='Registry key — blank for a pure rule-based exception', max_length=40)),
                ('alert_type', models.CharField(choices=[('kpi_breach', 'KPI breach'), ('dead_stock', 'Dead stock'), ('expiry_risk', 'Expiry risk'), ('stockout_risk', 'Projected stockout'), ('demand_spike', 'Demand spike'), ('shipment_at_risk', 'Shipment at risk'), ('stale_tracking', 'Stale tracking'), ('supplier_risk', 'Supplier risk'), ('contract_expiry', 'Contract expiry'), ('off_contract_spend', 'Off-contract spend'), ('price_variance', 'Price variance'), ('freight_variance', 'Freight variance')], default='kpi_breach', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=8)),
                ('observed_value', models.DecimalField(blank=True, decimal_places=4, help_text='What was measured', max_digits=16, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, help_text='What it was measured against', max_digits=16, null=True)),
                ('impact_value', models.DecimalField(decimal_places=2, default=0, help_text='Value at risk — what acting on this is worth', max_digits=14)),
                ('dimension_key', models.CharField(blank=True, max_length=64)),
                ('dimension_label', models.CharField(blank=True, max_length=160)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('snoozed', 'Snoozed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', editable=False, max_length=14)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('snoozed_until', models.DateField(blank=True, editable=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts_assigned', to=settings.AUTH_USER_MODEL)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts', to='scm.carrier')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts', to='scm.item')),
                ('kpi_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='scm.kpitarget')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts', to='scm.location')),
                ('party', models.ForeignKey(blank=True, help_text='Supplier or customer this exception is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_supply_alerts', to='core.party')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts', to='scm.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts_resolved', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_alerts', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-impact_value', '-raised_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='kpitarget',
            index=models.Index(fields=['tenant', 'metric'], name='scm_kpi_tnt_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='kpitarget',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_kpi_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='kpitarget',
            index=models.Index(fields=['tenant', 'is_alerting'], name='scm_kpi_tnt_alerting_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpitarget',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='kpisnapshot',
            index=models.Index(fields=['tenant', 'metric', 'period_end'], name='scm_kps_tnt_met_end_idx'),
        ),
        migrations.AddIndex(
            model_name='kpisnapshot',
            index=models.Index(fields=['tenant', 'kpi_target', 'period_end'], name='scm_kps_tnt_tgt_end_idx'),
        ),
        migrations.AddIndex(
            model_name='kpisnapshot',
            index=models.Index(fields=['tenant', 'status_band'], name='scm_kps_tnt_band_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpisnapshot',
            unique_together={('tenant', 'kpi_target', 'period_start', 'dimension_key')},
        ),
        migrations.AddIndex(
            model_name='supplychainalert',
            index=models.Index(fields=['tenant', 'status'], name='scm_alr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplychainalert',
            index=models.Index(fields=['tenant', 'severity'], name='scm_alr_tnt_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='supplychainalert',
            index=models.Index(fields=['tenant', 'raised_at'], name='scm_alr_tnt_raised_idx'),
        ),
        migrations.AddIndex(
            model_name='supplychainalert',
            index=models.Index(fields=['tenant', 'assigned_to'], name='scm_alr_tnt_asg_idx'),
        ),
        migrations.AddIndex(
            model_name='supplychainalert',
            index=models.Index(fields=['tenant', 'dedupe_key'], name='scm_alr_tnt_dedupe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplychainalert',
            unique_together={('tenant', 'number')},
        ),
    ]
