# Generated by Django 5.1.15 on 2026-08-01 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0020_suppliercontract_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sustainabilityassessment',
            index=models.Index(fields=['tenant', 'assessment_date'], name='scm_esg_tnt_asmt_idx'),
        ),
    ]
