# Generated by Django 5.1.15 on 2026-08-03 20:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0021_sustainabilityassessment_scm_esg_tnt_asmt_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_spare_part',
            field=models.BooleanField(default=False, help_text='MRO part held for maintenance; shown on the spare-parts storeroom page'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('consumption', 'Consumption'), ('production', 'Production'), ('maintenance', 'Maintenance')], max_length=12),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(help_text='Short plant code, unique in this workspace', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('machine', 'Machine'), ('vehicle', 'Vehicle'), ('forklift', 'Forklift'), ('conveyor', 'Conveyor'), ('rack', 'Rack / Storage Equipment'), ('tool', 'Tool'), ('facility', 'Facility'), ('it_equipment', 'IT Equipment'), ('other', 'Other')], default='machine', max_length=14)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_service', 'In Service'), ('under_maintenance', 'Under Maintenance'), ('standby', 'Standby'), ('idle', 'Idle'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='in_service', help_text='The operational lifecycle state — you set it; no work order changes it', max_length=18)),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='How much it hurts when this asset stops', max_length=10)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('tag_code', models.CharField(blank=True, help_text='QR / barcode value. Must be unique in this workspace', max_length=64)),
                ('specifications', models.TextField(blank=True, help_text='Capacity, voltage, rated output, ratings')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('commissioned_on', models.DateField(blank=True, help_text='When it entered service — the reliability clock starts here', null=True)),
                ('warranty_expires_on', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.99'))])),
                ('meter_name', models.CharField(blank=True, help_text='Primary meter, e.g. Running Hours, Odometer, Cycles', max_length=40)),
                ('meter_unit', models.CharField(blank=True, help_text='h, km, cycles, L', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('custodian', models.ForeignKey(blank=True, help_text='Person or team accountable for the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_custodian_assets', to='core.party')),
                ('fixed_asset', models.ForeignKey(blank=True, help_text='The capitalised record that depreciates this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_assets', to='accounting.fixedasset')),
                ('location', models.ForeignKey(blank=True, help_text='Where the asset physically sits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='scm.location')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Owning department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_assets', to='core.orgunit')),
                ('parent', models.ForeignKey(blank=True, help_text='The assembly this is a component of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scm.asset')),
                ('service_vendor', models.ForeignKey(blank=True, help_text='Default contractor for outsourced work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_serviced_assets', to='core.party')),
                ('supplier', models.ForeignKey(blank=True, help_text='Who we bought it from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_supplied_assets', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('work_center', models.ForeignKey(blank=True, help_text='Production work centre this asset serves', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='scm.workcenter')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_service', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='How many are consumed in one service', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('is_critical', models.BooleanField(default=False, help_text='Running out of this one stops the job')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='scm.asset')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_spare_parts', to='scm.item')),
            ],
            options={
                'ordering': ['item__sku'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='What the job is, in prose. Step-by-step checks belong in the tasks below')),
                ('is_active', models.BooleanField(default=True, help_text='An inactive plan never comes due and cannot generate a job')),
                ('trigger_type', models.CharField(choices=[('calendar', 'Calendar — every N days'), ('meter', 'Meter — every N meter units'), ('combined', 'Combined — calendar or meter, whichever comes first'), ('condition', 'Condition — when a reading crosses a threshold')], default='calendar', max_length=10)),
                ('schedule_basis', models.CharField(choices=[('floating', 'Floating — next due measured from the last completion'), ('fixed', 'Fixed — next due measured from the calendar regardless')], default='floating', help_text='Floating suits wear-driven work; fixed suits a statutory date', max_length=8)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Calendar cadence in days — required for a calendar or combined plan', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Raise the job this many days before it is due', validators=[django.core.validators.MaxValueValidator(365)])),
                ('meter_interval', models.DecimalField(blank=True, decimal_places=4, help_text='Usage cadence in meter units — required for a meter or combined plan', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('next_due_on', models.DateField(blank=True, help_text='Date the next occurrence is owed', null=True)),
                ('next_due_reading', models.DecimalField(blank=True, decimal_places=4, help_text='Meter value the next occurrence is owed at', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('condition_operator', models.CharField(blank=True, choices=[('gte', 'At or above'), ('lte', 'At or below')], help_text='Only for a condition plan: which way the reading has to cross the threshold', max_length=4)),
                ('condition_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Only for a condition plan: the reading that makes the work due', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('last_completed_on', models.DateField(blank=True, editable=False, help_text='Stamped by the work-order complete verb', null=True)),
                ('last_generated_on', models.DateField(blank=True, editable=False, help_text='Stamped by the generate action', null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('work_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('breakdown', 'Breakdown'), ('inspection', 'Inspection'), ('calibration', 'Calibration'), ('predictive', 'Predictive'), ('safety', 'Safety')], default='preventive', max_length=12)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Planned labour for one occurrence', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('asset', models.ForeignKey(help_text='The machine this obligation is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='scm.asset')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Default technician or crew for the jobs this plan raises', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_maintenance_plans', to='core.party')),
                ('parts_location', models.ForeignKey(blank=True, help_text='Storeroom a generated job draws its parts from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('description', models.CharField(max_length=255)),
                ('expected_result', models.CharField(blank=True, help_text="What good looks like — 'oil level between the marks', 'under 70 dB'", max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_safety_step', models.BooleanField(default=False, help_text='Isolation, lock-out/tag-out, permit — flagged so it prints first')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scm.maintenanceplan')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('breakdown', 'Breakdown'), ('inspection', 'Inspection'), ('calibration', 'Calibration'), ('predictive', 'Predictive'), ('safety', 'Safety')], default='corrective', max_length=12)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('source', models.CharField(choices=[('plan', 'Preventive plan'), ('request', 'Maintenance request'), ('condition', 'Condition trigger'), ('inspection', 'Inspection finding')], default='request', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='requested', editable=False, max_length=12)),
                ('description', models.TextField(blank=True, help_text='What was observed, or what the job covers')),
                ('resolution_notes', models.TextField(blank=True, help_text='What was actually done')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_start', models.DateTimeField(blank=True, help_text="When the job is committed to happen. For a generated PM job this is the plan's due date at generate time, and it is what is_on_time measures against", null=True)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('downtime_start', models.DateTimeField(blank=True, null=True)),
                ('downtime_end', models.DateTimeField(blank=True, null=True)),
                ('downtime_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('is_unplanned_downtime', models.BooleanField(default=False, help_text='Unplanned outage — the figure availability and MTBF are actually about')),
                ('problem_code', models.CharField(blank=True, choices=[('no_start', 'Will not start'), ('overheating', 'Overheating'), ('vibration', 'Excessive vibration'), ('leak', 'Leak'), ('noise', 'Abnormal noise'), ('jam_blockage', 'Jam / blockage'), ('electrical_fault', 'Electrical fault'), ('hydraulic_fault', 'Hydraulic / pneumatic fault'), ('wear', 'Wear / worn part'), ('corrosion', 'Corrosion'), ('calibration_drift', 'Out of calibration'), ('software_fault', 'Control / software fault'), ('other', 'Other')], help_text='The symptom observed', max_length=24)),
                ('cause_code', models.CharField(blank=True, choices=[('lack_of_lubrication', 'Lack of lubrication'), ('contamination', 'Contamination'), ('misalignment', 'Misalignment'), ('fatigue', 'Material fatigue'), ('overload', 'Overload / over-speed'), ('operator_error', 'Operator error'), ('design_defect', 'Design defect'), ('material_defect', 'Material / part defect'), ('environmental', 'Environmental (heat, dust, damp)'), ('age_wear', 'Normal age / wear'), ('improper_install', 'Improper installation or repair'), ('unknown', 'Unknown'), ('other', 'Other')], help_text='Why it happened', max_length=24)),
                ('remedy_code', models.CharField(blank=True, choices=[('repair', 'Repaired in place'), ('replace_part', 'Replaced part'), ('adjust_align', 'Adjusted / realigned'), ('lubricate', 'Lubricated'), ('clean', 'Cleaned'), ('recalibrate', 'Recalibrated'), ('software_update', 'Software / parameter update'), ('operator_retrain', 'Operator retrained'), ('no_action', 'No fault found — no action'), ('monitor', 'Monitoring, no action yet'), ('other', 'Other')], help_text='What was done about it', max_length=24)),
                ('labour_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999.99'))])),
                ('labour_rate', models.DecimalField(decimal_places=4, default=0, help_text='Charge-out rate per labour hour', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))])),
                ('external_cost', models.DecimalField(decimal_places=2, default=0, help_text="The contractor's charge. Recorded here only — 4.13 drafts no accounting document", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.99'))])),
                ('meter_reading_at_work', models.DecimalField(blank=True, decimal_places=4, help_text='Meter value at the moment of work — filed as a reading when the job completes', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='scm.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_assigned_maintenance_orders', to='core.party')),
                ('non_conformance', models.ForeignKey(blank=True, help_text='The quality non-conformance this failure fed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders', to='scm.nonconformance')),
                ('parts_location', models.ForeignKey(blank=True, help_text='Storeroom the parts are drawn from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders', to='scm.location')),
                ('plan', models.ForeignKey(blank=True, help_text='The preventive plan this job was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='scm.maintenanceplan')),
                ('reported_by', models.ForeignKey(blank=True, help_text="Who raised the fault — this plus status='requested' IS the maintenance request", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_reported_maintenance_orders', to='core.party')),
                ('service_vendor', models.ForeignKey(blank=True, help_text='External contractor, when the work is outsourced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_vendor_maintenance_orders', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('is_issued', models.BooleanField(default=False, editable=False)),
                ('issued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_parts', to='scm.item')),
                ('lot_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_parts', to='scm.lotserial')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='scm.maintenanceworkorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('description', models.CharField(max_length=255)),
                ('expected_result', models.CharField(blank=True, help_text='What a pass looks like — the tolerance or reading', max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_safety_step', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('actual_result', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scm.maintenanceworkorder')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_name', models.CharField(help_text='Which meter — Hours, Odometer, Bearing Temp. See the module note', max_length=40)),
                ('unit', models.CharField(blank=True, help_text='hrs, km, °C, bar, cycles', max_length=16)),
                ('reading', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the meter was read — back-date an observation freely')),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('work_order', 'Captured on a work order'), ('sensor', 'Sensor / IoT feed')], default='manual', max_length=12)),
                ('reference', models.CharField(blank=True, help_text='Source document number — the MWO- number when captured on a job', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='scm.asset')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_meter_readings', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-read_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'status'], name='scm_ast_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'criticality'], name='scm_ast_tnt_crit_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'location'], name='scm_ast_tnt_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'warranty_expires_on'], name='scm_ast_tnt_wty_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_ast_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('tenant', 'code'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='assetsparepart',
            index=models.Index(fields=['asset'], name='scm_asp_asset_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsparepart',
            unique_together={('asset', 'item')},
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_pm_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['tenant', 'next_due_on'], name='scm_pm_tnt_due_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['tenant', 'asset'], name='scm_pm_tnt_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['tenant', 'trigger_type'], name='scm_pm_tnt_trig_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceplan',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='maintenanceplantask',
            index=models.Index(fields=['plan', 'sequence'], name='scm_pmt_plan_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['tenant', 'status'], name='scm_mwo_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['tenant', 'asset'], name='scm_mwo_tnt_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['tenant', 'work_type'], name='scm_mwo_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['tenant', 'reported_at'], name='scm_mwo_tnt_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['tenant', 'priority'], name='scm_mwo_tnt_prio_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceworkorder',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorderpart',
            index=models.Index(fields=['work_order'], name='scm_mwop_wo_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkordertask',
            index=models.Index(fields=['work_order', 'sequence'], name='scm_mwot_wo_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['tenant', 'asset', 'read_at'], name='scm_mtr_tnt_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['tenant', 'read_at'], name='scm_mtr_tnt_read_idx'),
        ),
    ]
