# Generated by Django 5.1.15 on 2026-08-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0022_item_is_spare_part_alter_stockmove_move_type_asset_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetsparepart',
            name='scm_asp_asset_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceworkorder',
            name='scm_mwo_tnt_asset_idx',
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['tenant', 'asset', '-reported_at'], name='scm_mwo_tnt_asset_idx'),
        ),
    ]
