# Generated by Django 5.1.15 on 2026-08-07 19:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0023_remove_assetsparepart_scm_asp_asset_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('bucket', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly')], default='day', max_length=8)),
                ('volume_source', models.CharField(choices=[('stock_moves', 'Stock movement history'), ('pick_tasks', 'Pick task history'), ('goods_receipts', 'Goods receipt history'), ('demand_forecast', 'Demand forecast (4.7)'), ('manual', 'Manual entry')], default='stock_moves', help_text='Which live ledger the generator derives expected volume from', max_length=16)),
                ('method', models.CharField(choices=[('naive', 'Last period repeated'), ('moving_average', 'Moving average'), ('same_period_last_year', 'Same period last year'), ('manual', 'Manual')], default='moving_average', help_text='How that derived history becomes a per-bucket volume', max_length=24)),
                ('history_days', models.PositiveIntegerField(default=28, help_text='How far back the derived volume history reaches', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)])),
                ('hours_per_shift', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Paid hours in one shift — the divisor that turns required minutes into bodies', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('24'))])),
                ('productivity_pct', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Expected achievement against standard — 90% means the site needs 111 minutes to do 100 minutes of standard work', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', editable=False, max_length=8)),
                ('generated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_labor_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('demand_forecast', models.ForeignKey(blank=True, help_text='Required when the volume source is a demand forecast, and forbidden otherwise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_plans', to='scm.demandforecast')),
                ('location', models.ForeignKey(blank=True, help_text='The site being staffed — leave blank to plan the whole network', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_plans', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LaborSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('work_date', models.DateField(help_text="The shift's calendar day — an overnight shift keeps the day it STARTED on")),
                ('shift_label', models.CharField(blank=True, help_text="Free text, e.g. 'Nights' or 'Early' — mirrors hrm.Shift.name by convention, not by foreign key", max_length=60)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, help_text="Null while the shift is still running — attended minutes are unknown until it is set, and every figure derived from them answers 'not yet', not zero", null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='open', editable=False, max_length=10)),
                ('source', models.CharField(choices=[('web', 'Web self-service'), ('badge', 'Badge reader'), ('mobile', 'Mobile device'), ('biometric', 'Biometric terminal'), ('supervisor', 'Supervisor entry')], default='web', editable=False, help_text='How the punch reached the system — stamped by the verb, never a form field', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_labor_sessions_approved', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='The warehouse or zone worked', on_delete=django.db.models.deletion.PROTECT, related_name='labor_sessions', to='scm.location')),
                ('login', models.ForeignKey(blank=True, editable=False, help_text='The login that clocked itself in, when the worker punched in for themselves', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_labor_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, help_text="The login that FILED the session — a supervisor when filed on someone's behalf", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_labor_sessions_recorded', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('worker', models.ForeignKey(help_text="The person whose shift this is — a Party holding the 'employee' role", on_delete=django.db.models.deletion.PROTECT, related_name='scm_labor_sessions', to='core.party')),
            ],
            options={
                'ordering': ['-work_date', '-clock_in', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LaborStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('activity', models.CharField(choices=[('receive', 'Receiving'), ('putaway', 'Put-away'), ('pick', 'Picking'), ('pack', 'Packing'), ('load', 'Loading / shipping'), ('replenish', 'Replenishment'), ('cycle_count', 'Cycle counting'), ('vas', 'Value-added service'), ('break', 'Break'), ('meeting', 'Meeting / briefing'), ('training', 'Training'), ('cleaning', 'Cleaning / housekeeping'), ('equipment_wait', 'Waiting for equipment'), ('system_down', 'System down'), ('waiting_for_work', 'Waiting for work'), ('safety', 'Safety / incident'), ('other_indirect', 'Other indirect')], help_text='The work this standard measures. An INDIRECT activity may carry a standard, but no performance figure is computed against it — break time is not earned time', max_length=18)),
                ('basis', models.CharField(choices=[('per_unit', 'Per unit'), ('per_line', 'Per order line'), ('per_task', 'Per task (fixed)'), ('per_case', 'Per case'), ('per_pallet', 'Per pallet')], default='per_unit', help_text="What one 'unit' counts. 0.4 minutes is fast per pallet and absurd per case, so the basis is what makes minutes per unit mean anything", max_length=10)),
                ('source', models.CharField(choices=[('engineered', 'Engineered'), ('observed', 'Time-studied / observed'), ('benchmark', 'Benchmark library'), ('learned', 'Learned from history')], default='engineered', help_text='Where the number came from. A supervisor arguing with a standard is entitled to know whether it was time-studied here or lifted from a benchmark library', max_length=12)),
                ('minutes_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Variable time per unit of the chosen basis', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10000'))])),
                ('setup_minutes', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fixed time paid once per task, regardless of quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10000'))])),
                ('travel_minutes', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fixed travel to and from the work, once per task. Distance-derived travel needs bin coordinates that scm.Location does not have — this is the typed stand-in', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10000'))])),
                ('allowance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Personal, fatigue and delay allowance added on top of the measured time. Capped at 100% — an allowance may at most double the standard', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('labour_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="CHARGE-OUT rate per hour used for cost per unit — never a person's wage. HRM owns compensation and SCM does not read it. Leave at zero to skip costing", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', editable=False, max_length=8)),
                ('effective_from', models.DateField(help_text='First day this standard applies. Re-timing an activity means a NEW standard starting today, not an edit — that is what keeps last month reproducible')),
                ('effective_to', models.DateField(blank=True, help_text='Last day this standard applies. Blank = open-ended', null=True)),
                ('notes', models.TextField(blank=True)),
                ('item_category', models.ForeignKey(blank=True, help_text='Item class this standard is measured for. Blank = every item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_standards', to='scm.itemcategory')),
                ('location', models.ForeignKey(blank=True, help_text='Warehouse or zone this standard is measured for. Blank = the whole network', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_standards', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['activity', '-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LaborPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First day of the bucket this line plans')),
                ('activity', models.CharField(choices=[('receive', 'Receiving'), ('putaway', 'Put-away'), ('pick', 'Picking'), ('pack', 'Packing'), ('load', 'Loading / shipping'), ('replenish', 'Replenishment'), ('cycle_count', 'Cycle counting'), ('vas', 'Value-added service'), ('break', 'Break'), ('meeting', 'Meeting / briefing'), ('training', 'Training'), ('cleaning', 'Cleaning / housekeeping'), ('equipment_wait', 'Waiting for equipment'), ('system_down', 'System down'), ('waiting_for_work', 'Waiting for work'), ('safety', 'Safety / incident'), ('other_indirect', 'Other indirect')], max_length=18)),
                ('forecast_volume', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Units this bucket is expected to move, derived at generate time', max_digits=16)),
                ('standard_minutes_snapshot', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Minutes this volume costs at standard, frozen when the plan was generated', max_digits=12, null=True)),
                ('required_minutes', models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Standard minutes adjusted for the plan's expected productivity", max_digits=14)),
                ('required_headcount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Bodies the required minutes imply for one shift', max_digits=8)),
                ('planned_headcount', models.DecimalField(decimal_places=2, default=0, help_text='What you intend to roster — the only figure on this line you may change', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.laborplan')),
                ('standard', models.ForeignKey(blank=True, editable=False, help_text='Which standard priced this line — traceability only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_lines', to='scm.laborstandard')),
            ],
            options={
                'ordering': ['period_start', 'activity'],
            },
        ),
        migrations.CreateModel(
            name='LaborActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('activity_type', models.CharField(choices=[('receive', 'Receiving'), ('putaway', 'Put-away'), ('pick', 'Picking'), ('pack', 'Packing'), ('load', 'Loading / shipping'), ('replenish', 'Replenishment'), ('cycle_count', 'Cycle counting'), ('vas', 'Value-added service'), ('break', 'Break'), ('meeting', 'Meeting / briefing'), ('training', 'Training'), ('cleaning', 'Cleaning / housekeeping'), ('equipment_wait', 'Waiting for equipment'), ('system_down', 'System down'), ('waiting_for_work', 'Waiting for work'), ('safety', 'Safety / incident'), ('other_indirect', 'Other indirect')], default='pick', max_length=18)),
                ('indirect_reason', models.CharField(blank=True, choices=[('scheduled_break', 'Scheduled break'), ('sanctioned_meeting', 'Sanctioned meeting'), ('training', 'Training'), ('housekeeping', 'Housekeeping'), ('equipment_failure', 'Equipment failure'), ('system_outage', 'System outage'), ('no_work_available', 'No work available'), ('safety_incident', 'Safety incident'), ('supervisor_directed', 'Supervisor directed'), ('other', 'Other')], help_text='Why the non-productive minutes were spent — required for an indirect activity', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, help_text='Leave blank while the activity is still running', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text="Units of work completed, in the standard's basis (units, lines, cases, pallets)", max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999999.9999'))])),
                ('error_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Of those units, how many were wrong — mis-picks, mis-scans, short cartons', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference', models.CharField(blank=True, help_text='Free-text document or job reference, for work with no task record', max_length=40)),
                ('standard_fixed_snapshot', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='setup_minutes + travel_minutes as they stood at file time', max_digits=12, null=True)),
                ('standard_rate_snapshot', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='minutes_per_unit as it stood at file time', max_digits=12, null=True)),
                ('standard_allowance_snapshot', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='PF&D allowance percentage as it stood at file time', max_digits=6, null=True)),
                ('standard_minutes_snapshot', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='The earned minutes those three produce for this quantity — recomputed in save() from the snapshots, never from the live standard', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cycle_count_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_activities', to='scm.cyclecounttask')),
                ('pick_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_activities', to='scm.picktask')),
                ('putaway_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_activities', to='scm.putawaytask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='scm.laborsession')),
                ('standard', models.ForeignKey(blank=True, editable=False, help_text='Which standard was in force when this was filed — traceability only; the measurement itself lives in the snapshots below', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='scm.laborstandard')),
            ],
            options={
                'verbose_name_plural': 'labor activities',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='laborplan',
            index=models.Index(fields=['tenant', 'status'], name='scm_lpl_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborplan',
            index=models.Index(fields=['tenant', 'period_start'], name='scm_lpl_tnt_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laborplan',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='laborsession',
            index=models.Index(fields=['tenant', 'work_date'], name='scm_lsn_tnt_wkdate_idx'),
        ),
        migrations.AddIndex(
            model_name='laborsession',
            index=models.Index(fields=['tenant', 'worker', 'work_date'], name='scm_lsn_tnt_wkr_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='laborsession',
            index=models.Index(fields=['tenant', 'status'], name='scm_lsn_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborsession',
            index=models.Index(fields=['tenant', 'location'], name='scm_lsn_tnt_loc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laborsession',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='laborstandard',
            index=models.Index(fields=['tenant', 'activity'], name='scm_lst_tnt_act_idx'),
        ),
        migrations.AddIndex(
            model_name='laborstandard',
            index=models.Index(fields=['tenant', 'status'], name='scm_lst_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborstandard',
            index=models.Index(fields=['tenant', 'effective_from'], name='scm_lst_tnt_eff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laborstandard',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='laborplanline',
            index=models.Index(fields=['plan', 'period_start'], name='scm_lpll_plan_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laborplanline',
            unique_together={('plan', 'period_start', 'activity')},
        ),
        migrations.AddIndex(
            model_name='laboractivity',
            index=models.Index(fields=['tenant', 'session'], name='scm_lab_tnt_sess_idx'),
        ),
        migrations.AddIndex(
            model_name='laboractivity',
            index=models.Index(fields=['tenant', 'activity_type'], name='scm_lab_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='laboractivity',
            index=models.Index(fields=['tenant', 'started_at'], name='scm_lab_tnt_start_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laboractivity',
            unique_together={('tenant', 'number')},
        ),
    ]
