# Generated by Django 5.1.15 on 2026-08-10 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0024_laborplan_laborsession_laborstandard_laborplanline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboractivity',
            name='standard',
            field=models.ForeignKey(blank=True, editable=False, help_text='Which standard was in force when this was filed — traceability only; the measurement itself lives in the snapshots below', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_activities', to='scm.laborstandard'),
        ),
    ]
