# Generated by Django 5.1.15 on 2026-08-10 21:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0025_alter_laboractivity_standard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='storage_condition',
            field=models.CharField(blank=True, choices=[('ambient', 'Ambient (no temperature control)'), ('controlled_rt', 'Controlled Room Temperature (15 to 25 °C)'), ('cool', 'Cool (8 to 15 °C)'), ('chilled', 'Chilled / Refrigerated (2 to 8 °C)'), ('frozen', 'Frozen (-25 to -15 °C)'), ('deep_frozen', 'Deep Frozen (-45 to -25 °C)'), ('cryogenic', 'Cryogenic (-196 to -150 °C)')], help_text='Temperature class this item must be kept at; blank = not temperature-controlled', max_length=14),
        ),
        migrations.AddField(
            model_name='location',
            name='storage_condition',
            field=models.CharField(blank=True, choices=[('ambient', 'Ambient (no temperature control)'), ('controlled_rt', 'Controlled Room Temperature (15 to 25 °C)'), ('cool', 'Cool (8 to 15 °C)'), ('chilled', 'Chilled / Refrigerated (2 to 8 °C)'), ('frozen', 'Frozen (-25 to -15 °C)'), ('deep_frozen', 'Deep Frozen (-45 to -25 °C)'), ('cryogenic', 'Cryogenic (-196 to -150 °C)')], help_text='Temperature class of this zone or bin; blank = ambient / unclassified', max_length=14),
        ),
        migrations.CreateModel(
            name='ColdChainMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text="What this monitoring point is called, e.g. 'Cold Room 2 - top probe'", max_length=255)),
                ('device_serial', models.CharField(blank=True, help_text='Logger / probe serial. Re-usable devices legitimately appear on many monitors — only one may be ACTIVE', max_length=64)),
                ('device_type', models.CharField(choices=[('fixed_sensor', 'Fixed sensor / probe'), ('multi_use_logger', 'Re-usable data logger'), ('single_use_logger', 'Single-use data logger'), ('realtime_tracker', 'Real-time tracker'), ('gateway_probe', 'Gateway probe'), ('manual', 'Manual readings only')], default='fixed_sensor', max_length=20)),
                ('storage_condition', models.CharField(blank=True, choices=[('ambient', 'Ambient (no temperature control)'), ('controlled_rt', 'Controlled Room Temperature (15 to 25 °C)'), ('cool', 'Cool (8 to 15 °C)'), ('chilled', 'Chilled / Refrigerated (2 to 8 °C)'), ('frozen', 'Frozen (-25 to -15 °C)'), ('deep_frozen', 'Deep Frozen (-45 to -25 °C)'), ('cryogenic', 'Cryogenic (-196 to -150 °C)')], help_text='Temperature class this point is held at — pre-fills the limits, never overrides them', max_length=14)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Lower alarm limit in °C — blank means no lower limit', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Upper alarm limit in °C — blank means no upper limit', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('warning_margin_c', models.DecimalField(blank=True, decimal_places=2, help_text="Warn this many °C BEFORE a limit is reached (Sensitech's warning band)", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('50'))])),
                ('humidity_min', models.DecimalField(blank=True, decimal_places=2, help_text='Lower relative-humidity limit, %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('humidity_max', models.DecimalField(blank=True, decimal_places=2, help_text='Upper relative-humidity limit, %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('setpoint_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='What the unit is set to in °C — a record, not a control channel', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('excursion_grace_minutes', models.PositiveIntegerField(default=30, help_text='How long a breach may run before it counts as a reportable excursion', validators=[django.core.validators.MaxValueValidator(10080)])),
                ('logging_interval_minutes', models.PositiveSmallIntegerField(default=30, help_text='Minutes each reading summarises — SNAPSHOTTED onto every reading row as it is filed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('calibrated_on', models.DateField(blank=True, help_text='Date of the last calibration certificate', null=True)),
                ('calibration_due_on', models.DateField(blank=True, help_text='When the certificate lapses', null=True)),
                ('calibration_reference', models.CharField(blank=True, help_text='Certificate number — ISO 17025 / NIST-traceable reference', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('in_calibration', 'In Calibration'), ('retired', 'Retired'), ('lost', 'Lost')], default='active', help_text='You own this column — no detector pass ever changes it', max_length=16)),
                ('deployed_on', models.DateField(blank=True, help_text='When this deployment started — readings before it are refused', null=True)),
                ('retired_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Reefer unit, chiller or freezer being monitored', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cold_chain_monitors', to='scm.asset')),
                ('location', models.ForeignKey(blank=True, help_text='Cold room, chiller zone or bin being monitored', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cold_chain_monitors', to='scm.location')),
                ('shipment', models.ForeignKey(blank=True, help_text='In-transit consignment being monitored', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cold_chain_monitors', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('started_at', models.DateTimeField(editable=False, help_text='First reading outside the limits')),
                ('ended_at', models.DateTimeField(blank=True, editable=False, help_text='First reading back inside the limits — null while it is still breaching', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, editable=False, help_text='Minutes outside the limits, minute-weighted from the reading intervals', validators=[django.core.validators.MaxValueValidator(525600)])),
                ('breach_direction', models.CharField(choices=[('high', 'Above the upper limit'), ('low', 'Below the lower limit'), ('both', 'Both directions')], default='high', editable=False, max_length=6)),
                ('extreme_temperature', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Worst temperature reached during the episode, °C', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('limit_min', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='The lower limit in force when the episode opened', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('limit_max', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='The upper limit in force when the episode opened', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('reading_count', models.PositiveIntegerField(default=0, editable=False, help_text='How many reading rows fall inside the episode window')),
                ('mkt', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Mean kinetic temperature over the episode, °C — blank when it does not apply', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('assessed', 'Assessed'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], default='open', editable=False, max_length=16)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='major', max_length=10)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assessment', models.CharField(choices=[('pending', 'Pending assessment'), ('product_ok', 'Product unaffected — release'), ('product_affected', 'Product affected')], default='pending', max_length=20)),
                ('assessed_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cause', models.CharField(blank=True, choices=[('equipment_failure', 'Equipment failure'), ('power_loss', 'Power loss'), ('door_left_open', 'Door left open'), ('packaging_failure', 'Packaging failure'), ('transit_delay', 'Transit delay'), ('loading_delay', 'Loading / dwell delay'), ('wrong_setpoint', 'Wrong setpoint'), ('sensor_fault', 'Sensor fault'), ('unknown', 'Unknown'), ('other', 'Other')], help_text="Closed vocabulary so 'what costs us the most spoilage' is a GROUP BY rather than a pile of free text", max_length=20)),
                ('corrective_action', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_excursions_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('assessed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_excursion_assessments', to='core.party')),
                ('lot_serial', models.ForeignKey(blank=True, help_text='The affected batch — this module READS its status and never writes it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cold_chain_excursions', to='scm.lotserial')),
                ('maintenance_work_order', models.ForeignKey(blank=True, help_text='The repair job raised against the failing unit — 4.13 owns the work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cold_chain_excursions', to='scm.maintenanceworkorder')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='scm.coldchainmonitor')),
                ('non_conformance', models.ForeignKey(blank=True, help_text='The NCR raised for affected product — 4.9 owns the disposition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cold_chain_excursions', to='scm.nonconformance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_at', models.DateTimeField(help_text='End of the interval this row summarises')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Representative temperature for the interval, °C', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Relative humidity for the interval, %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Coldest sample in the interval, °C', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Warmest sample in the interval, °C', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-200')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('sample_count', models.PositiveSmallIntegerField(default=1, help_text='How many raw samples this row rolled up', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('interval_minutes', models.PositiveSmallIntegerField(default=30, editable=False, help_text='Minutes this row weighs — snapshotted from the monitor when the row was filed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('logger_import', 'Logger file import'), ('gateway', 'Gateway batch'), ('sensor_api', 'Sensor / IoT feed')], default='manual', editable=False, help_text='How the row reached the system — stamped by the verb', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='scm.coldchainmonitor')),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_temperature_readings', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-reading_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='coldchainmonitor',
            index=models.Index(fields=['tenant', 'status'], name='scm_ccm_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='coldchainmonitor',
            index=models.Index(fields=['tenant', 'device_serial'], name='scm_ccm_tnt_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='coldchainmonitor',
            index=models.Index(fields=['tenant', 'location'], name='scm_ccm_tnt_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='coldchainmonitor',
            index=models.Index(fields=['tenant', 'asset'], name='scm_ccm_tnt_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='coldchainmonitor',
            index=models.Index(fields=['tenant', 'shipment'], name='scm_ccm_tnt_shp_idx'),
        ),
        migrations.AddIndex(
            model_name='coldchainmonitor',
            index=models.Index(fields=['tenant', 'calibration_due_on'], name='scm_ccm_tnt_caldue_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coldchainmonitor',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='temperatureexcursion',
            index=models.Index(fields=['tenant', 'status'], name='scm_exc_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='temperatureexcursion',
            index=models.Index(fields=['tenant', 'monitor', 'started_at'], name='scm_exc_tnt_mon_idx'),
        ),
        migrations.AddIndex(
            model_name='temperatureexcursion',
            index=models.Index(fields=['tenant', 'started_at'], name='scm_exc_tnt_start_idx'),
        ),
        migrations.AddIndex(
            model_name='temperatureexcursion',
            index=models.Index(fields=['tenant', 'severity'], name='scm_exc_tnt_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='temperatureexcursion',
            index=models.Index(fields=['tenant', 'ended_at'], name='scm_exc_tnt_ended_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperatureexcursion',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='temperaturereading',
            index=models.Index(fields=['tenant', 'monitor', 'reading_at'], name='scm_tmp_tnt_mon_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturereading',
            index=models.Index(fields=['tenant', 'reading_at'], name='scm_tmp_tnt_read_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturereading',
            unique_together={('monitor', 'reading_at')},
        ),
    ]
