# Generated by Django 5.1.15 on 2026-08-11 01:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('crm', '0024_crmtask_crm_task_tnt_party_idx'),
        ('scm', '0026_item_storage_condition_location_storage_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Switch a customer's portal off here. Deactivating is the safe alternative to deleting: inquiries and document shares reference this row and would block it")),
                ('activated_on', models.DateField(blank=True, editable=False, null=True)),
                ('can_track_shipments', models.BooleanField(default=True, help_text='Order tracking, shipment status and proof of delivery')),
                ('can_view_invoices', models.BooleanField(default=True, help_text="Read-only invoice history. SCM computes no AR of its own — these are accounting's invoices, shown, never recalculated")),
                ('can_view_documents', models.BooleanField(default=True, help_text='The document library — only ever documents shared to THIS account')),
                ('can_raise_inquiries', models.BooleanField(default=True, help_text='Raise an order inquiry from the portal (opens a CRM case)')),
                ('can_request_returns', models.BooleanField(default=True, help_text="Routes to 4.10's existing customer return request — 4.16 builds no second returns flow")),
                ('show_credit_and_balance', models.BooleanField(default=False, help_text='OFF by default: outstanding balance, credit limit and payment terms are exposed only when someone deliberately turns them on')),
                ('stock_display', models.CharField(choices=[('hidden', 'Hidden — show nothing'), ('availability_text', 'Availability text (in stock / low / out of stock)'), ('band', 'Colour band only'), ('exact_quantity', 'Exact quantity')], default='availability_text', help_text='How much of the live stock figure this customer may see. The reason to hide a number is commercial, and it varies by who is looking — hence per account', max_length=20)),
                ('low_stock_threshold', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="At or below this quantity the catalog says 'low stock'. Only meaningful for the availability-text and colour-band displays", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('show_by_location', models.BooleanField(default=False, help_text='Break availability down by warehouse instead of one network figure. Off by default — a per-site breakdown tells a competitor where our stock sits')),
                ('catalog_scope', models.CharField(choices=[('all_active', 'All active items'), ('previously_ordered', 'Items previously ordered'), ('categories', 'Selected categories only')], default='all_active', help_text="Which items this customer's catalog contains", max_length=20)),
                ('price_basis', models.CharField(choices=[('hidden', 'Hidden — no prices'), ('last_ordered', "This customer's last ordered price")], default='hidden', help_text="'Last ordered' shows this customer's own most recent unit price for the item, derived at render time. There is no customer price master to price against yet", max_length=16)),
                ('notify_on_shipment', models.BooleanField(default=True, help_text='Preference only — no message is sent by this module')),
                ('notify_on_delivery', models.BooleanField(default=True, help_text='Preference only — no message is sent by this module')),
                ('notify_on_exception', models.BooleanField(default=True, help_text='Preference only — no message is sent by this module')),
                ('preferred_channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('none', 'No notifications')], default='email', help_text='Where this customer would prefer to hear about shipment events. Stored intent for the day a mailer exists — nothing is dispatched today', max_length=8)),
                ('welcome_message', models.TextField(blank=True, help_text="Shown on this customer's portal home page — a dealer-zone style announcement or greeting")),
                ('support_email', models.EmailField(blank=True, help_text="The address the portal tells this customer to contact. Blank falls back to the tenant's own support routing", max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Internal — never rendered on a customer page')),
                ('catalog_categories', models.ManyToManyField(blank=True, help_text="Used only when the scope is 'Selected categories only'", related_name='portal_accounts', to='scm.itemcategory')),
                ('customer', models.ForeignKey(help_text='The company this portal account belongs to. Several named users may bind to it through their CRM customer portal access — this is the COMPANY-level record', on_delete=django.db.models.deletion.PROTECT, related_name='scm_portal_accounts', to='core.party')),
                ('default_ship_to', models.ForeignKey(blank=True, help_text='Pre-selected delivery address for this customer. Must be one of their own addresses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.address')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalDocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('pod', 'Proof of delivery'), ('packing_list', 'Packing list'), ('trade_document', 'Trade document'), ('contract', 'Contract'), ('coa', 'Certificate of analysis'), ('statement', 'Statement'), ('other', 'Other document')], default='invoice', help_text='What kind of document this is — it decides which of the six pointers below is the legal one', max_length=20)),
                ('title', models.CharField(help_text='What the customer sees. Never paste an internal filename or a storage path here', max_length=255)),
                ('public_token', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this the link 404s. Blank = no expiry, at most 365 days out. A forwarded link outlives the person you sent it to — prefer a date', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('first_viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('contract', models.ForeignKey(blank=True, help_text='The customer-side contract from CRM 1.9', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contractdocument')),
                ('document', models.ForeignKey(blank=True, help_text="An uploaded file — the target for 'statement' and 'other'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('invoice', models.ForeignKey(blank=True, help_text='An AR invoice. 4.16 READS accounting and computes no AR of its own', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.invoice')),
                ('portal_account', models.ForeignKey(help_text="Who may retrieve this. The document must belong to this account's customer", on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='scm.portalaccount')),
                ('quality_inspection', models.ForeignKey(blank=True, help_text='The 4.9 inspection whose certificate of analysis is being published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.qualityinspection')),
                ('shared_by', models.ForeignKey(blank=True, editable=False, help_text='The staff member who published this — set server-side, never on the form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, help_text='The 4.6 consignment whose proof of delivery is being published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('trade_document', models.ForeignKey(blank=True, help_text='4.12 paperwork — a BoL, a commercial invoice or a packing list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.tradedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('login', 'Signed in'), ('view_order', 'Viewed an order'), ('track_shipment', 'Tracked a shipment'), ('view_catalog', 'Browsed the catalog'), ('download_document', 'Downloaded a document'), ('raise_inquiry', 'Raised an inquiry'), ('request_return', 'Requested a return'), ('update_profile', 'Updated their profile')], editable=False, max_length=20)),
                ('object_label', models.CharField(blank=True, editable=False, max_length=160)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('portal_account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='scm.portalaccount')),
                ('sales_order', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.salesorder')),
                ('shipment', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_share', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.portaldocumentshare')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalOrderInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('wismo', 'Where is my order?'), ('delivery_exception', 'Delivery exception'), ('short_shipment', 'Short shipment'), ('damaged', 'Damaged goods'), ('wrong_item', 'Wrong item received'), ('quality', 'Quality issue'), ('invoice_dispute', 'Invoice dispute'), ('return_request', 'Return request'), ('reorder_request', 'Reorder request'), ('product_question', 'Product question'), ('other', 'Other')], default='wismo', help_text="What went wrong, or what is being asked. A closed set so 'which failure mode drives our WISMO volume?' is a GROUP BY rather than a pile of free text", max_length=20)),
                ('requested_resolution', models.CharField(choices=[('information', 'Information only'), ('redeliver', 'Redeliver'), ('replace', 'Replacement'), ('credit', 'Credit note'), ('return', 'Return / collection'), ('callback', 'Call me back')], default='information', help_text="What the customer wants done. Recorded separately from the type because 'my box arrived damaged, just credit me' is a different job from the same damage with 'send another one', and an agent who has to infer it guesses wrong", max_length=16)),
                ('quantity_affected', models.DecimalField(blank=True, decimal_places=4, help_text='How many units the claim covers, for short-shipment and damage claims. Requires a line, and may not exceed what that line ordered', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('outcome', models.CharField(choices=[('open', 'Open'), ('information_provided', 'Information provided'), ('credit_drafted', 'Credit drafted'), ('rma_raised', 'RMA raised'), ('replacement_arranged', 'Replacement arranged'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='open', editable=False, max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('source', models.CharField(choices=[('portal', 'Customer portal'), ('staff', 'Raised by staff')], default='staff', editable=False, max_length=10)),
                ('case', models.ForeignKey(editable=False, help_text='The crm.Case that carries the conversation, the SLA clocks, ownership and CSAT', on_delete=django.db.models.deletion.CASCADE, related_name='scm_portal_inquiries', to='crm.case')),
                ('invoice', models.ForeignKey(blank=True, help_text="The disputed invoice. SCM computes no AR of its own — this is a READ-ONLY pointer at 2.4's document", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.invoice')),
                ('portal_account', models.ForeignKey(blank=True, help_text='The portal account this was raised under. Blank when staff file for a customer who is not on the portal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='scm.portalaccount')),
                ('raised_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('return_authorization', models.ForeignKey(blank=True, editable=False, help_text='Set only by the conversion verb, never typed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_inquiries', to='scm.returnauthorization')),
                ('sales_order', models.ForeignKey(blank=True, help_text='The order this is about', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_inquiries', to='scm.salesorder')),
                ('sales_order_line', models.ForeignKey(blank=True, help_text='The specific line, when the claim is about one item rather than the whole order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.salesorderline')),
                ('shipment', models.ForeignKey(blank=True, help_text='The shipment this is about, when known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_inquiries', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portalaccount',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_pac_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccount',
            index=models.Index(fields=['tenant', 'customer'], name='scm_pac_tnt_cust_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portalaccount',
            unique_together={('tenant', 'customer'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='portaldocumentshare',
            index=models.Index(fields=['tenant', 'portal_account'], name='scm_pds_tnt_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='portaldocumentshare',
            index=models.Index(fields=['tenant', 'doc_type'], name='scm_pds_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='portaldocumentshare',
            index=models.Index(fields=['tenant', 'revoked_at'], name='scm_pds_tnt_revoked_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portaldocumentshare',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='portalactivity',
            index=models.Index(fields=['tenant', 'portal_account', 'created_at'], name='scm_pact_tnt_acct_at_idx'),
        ),
        migrations.AddIndex(
            model_name='portalactivity',
            index=models.Index(fields=['tenant', 'action'], name='scm_pact_tnt_action_idx'),
        ),
        migrations.AddIndex(
            model_name='portalorderinquiry',
            index=models.Index(fields=['tenant', 'outcome'], name='scm_piq_tnt_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='portalorderinquiry',
            index=models.Index(fields=['tenant', 'inquiry_type'], name='scm_piq_tnt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='portalorderinquiry',
            index=models.Index(fields=['tenant', 'sales_order'], name='scm_piq_tnt_so_idx'),
        ),
        migrations.AddIndex(
            model_name='portalorderinquiry',
            index=models.Index(fields=['tenant', 'case'], name='scm_piq_tnt_case_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portalorderinquiry',
            unique_together={('tenant', 'number')},
        ),
    ]
