# Generated by Django 5.1.15 on 2026-08-12 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('crm', '0024_crmtask_crm_task_tnt_party_idx'),
        ('scm', '0027_portalaccount_portaldocumentshare_portalactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='portalactivity',
            name='scm_pact_tnt_action_idx',
        ),
        migrations.AddIndex(
            model_name='portalactivity',
            index=models.Index(fields=['tenant', 'created_at'], name='scm_pact_tnt_at_idx'),
        ),
        migrations.AddIndex(
            model_name='portalactivity',
            index=models.Index(fields=['tenant', 'action', 'created_at'], name='scm_pact_tnt_act_at_idx'),
        ),
        migrations.AddIndex(
            model_name='portaldocumentshare',
            index=models.Index(fields=['tenant', 'created_at'], name='scm_pds_tnt_at_idx'),
        ),
        migrations.AddIndex(
            model_name='portalorderinquiry',
            index=models.Index(fields=['tenant', 'created_at'], name='scm_piq_tnt_at_idx'),
        ),
        migrations.AddIndex(
            model_name='portalorderinquiry',
            index=models.Index(fields=['tenant', 'portal_account'], name='scm_piq_tnt_acct_idx'),
        ),
    ]
