# Generated by Django 5.1.15 on 2026-08-14 13:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0028_remove_portalactivity_scm_pact_tnt_action_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text="What this tariff is, e.g. 'Standard storage & handling 2026'", max_length=120)),
                ('version', models.PositiveSmallIntegerField(default=1, help_text="Bump this rather than editing a superseded card — last quarter's bill has to stay readable")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('expired', 'Expired')], default='draft', max_length=12)),
                ('effective_from', models.DateField(help_text='First day this tariff prices')),
                ('effective_to', models.DateField(blank=True, help_text='Last day this tariff prices; blank = open-ended (until it is superseded)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, help_text="Blank falls back to the client's own currency", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-effective_from', '-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientBillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('period_start', models.DateField(help_text='First day billed (inclusive)')),
                ('period_end', models.DateField(help_text='Last day billed (inclusive)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('void', 'Void')], default='draft', editable=False, max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('minimum_adjustment', models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Top-up to the client's monthly minimum, when the period is a month and the charges fell short of it", max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('calculated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_billing_runs', to='accounting.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('rate_card', models.ForeignKey(help_text='The tariff these charges were priced from', on_delete=django.db.models.deletion.PROTECT, related_name='billing_runs', to='scm.clientratecard')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientRateCardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_category', models.CharField(choices=[('storage', 'Storage'), ('receiving', 'Receiving'), ('outbound', 'Outbound'), ('value_added', 'Value-Added'), ('accessorial', 'Accessorial'), ('transportation', 'Transportation'), ('recurring', 'Recurring'), ('minimum', 'Minimum')], max_length=16)),
                ('charge_basis', models.CharField(choices=[('per_pallet_position', 'Per Pallet Position'), ('per_sqft', 'Per Sq Ft'), ('per_cbm', 'Per CBM'), ('per_unit', 'Per Unit'), ('per_order', 'Per Order'), ('per_line', 'Per Order Line'), ('per_receipt', 'Per Receipt'), ('per_carton', 'Per Carton'), ('per_shipment', 'Per Shipment'), ('per_kg', 'Per Kg'), ('per_hour', 'Per Hour'), ('flat_recurring', 'Flat Recurring'), ('dedicated_space', 'Dedicated Space'), ('pct_of_value', '% of Value')], max_length=20)),
                ('description', models.CharField(help_text='Printed on the bill — write it as the client reads it', max_length=255)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('period', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], help_text='Required on a periodic basis (storage, dedicated space, flat recurring); must be blank on a per-event one', max_length=6)),
                ('included_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Allowance netted off before the rate applies', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, help_text="Floor for this line's computed amount", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tier_from', models.DecimalField(decimal_places=4, default=0, help_text='Band start, inclusive', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tier_to', models.DecimalField(blank=True, decimal_places=4, help_text='Band end, EXCLUSIVE; blank = no upper bound', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True, help_text='Switch a charge off without losing what it priced')),
                ('applies_to_item_category', models.ForeignKey(blank=True, help_text='Price only this category; blank = every item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.itemcategory')),
                ('applies_to_location', models.ForeignKey(blank=True, help_text='Price only what sits in this location; blank = anywhere', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.location')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.glaccount')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.clientratecard')),
            ],
            options={
                'ordering': ['charge_category', 'charge_basis', 'tier_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientBillingRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_category', models.CharField(choices=[('storage', 'Storage'), ('receiving', 'Receiving'), ('outbound', 'Outbound'), ('value_added', 'Value-Added'), ('accessorial', 'Accessorial'), ('transportation', 'Transportation'), ('recurring', 'Recurring'), ('minimum', 'Minimum')], max_length=16)),
                ('charge_basis', models.CharField(choices=[('per_pallet_position', 'Per Pallet Position'), ('per_sqft', 'Per Sq Ft'), ('per_cbm', 'Per CBM'), ('per_unit', 'Per Unit'), ('per_order', 'Per Order'), ('per_line', 'Per Order Line'), ('per_receipt', 'Per Receipt'), ('per_carton', 'Per Carton'), ('per_shipment', 'Per Shipment'), ('per_kg', 'Per Kg'), ('per_hour', 'Per Hour'), ('flat_recurring', 'Flat Recurring'), ('dedicated_space', 'Dedicated Space'), ('pct_of_value', '% of Value')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('source_reference', models.CharField(blank=True, help_text="The evidence this figure came from, e.g. 'GRN-00007, GRN-00011' or 'StockMove ledger · 31 days · average daily balance'", max_length=120)),
                ('is_manual', models.BooleanField(default=False, help_text="A human's charge — never regenerated by a recalculation")),
                ('needs_manual_quantity', models.BooleanField(default=False, editable=False, help_text='Priced but not measurable — somebody has to enter the quantity')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scm.clientbillingrun')),
                ('rate_card_line', models.ForeignKey(blank=True, help_text='Blank on a manually added charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.clientratecardline')),
            ],
            options={
                'ordering': ['charge_category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('code', models.CharField(help_text='Short client code, e.g. ACME. Used on labels, reports and invoice lines', max_length=8)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='prospect', max_length=16)),
                ('onboarded_on', models.DateField(blank=True, editable=False, null=True)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=12)),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the period the invoice is raised on. Capped at 28 so every month has one', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('next_billing_date', models.DateField(blank=True, help_text='Planning note only. 4.17 ships NO scheduler and nothing in this module reads this date — billing runs are created and calculated by hand', null=True)),
                ('storage_billing_method', models.CharField(choices=[('calendar_month', 'Calendar Month'), ('anniversary', 'Anniversary'), ('split_month', 'Split Month'), ('average_daily', 'Average Daily'), ('snapshot', 'Snapshot')], default='calendar_month', help_text='How storage is measured against the stock ledger. Each method produces a different figure from the same stock — this is the most consequential setting here', max_length=16)),
                ('minimum_monthly_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Monthly floor. Applied by a billing run only when the client is billed MONTHLY and the run's period covers a whole month", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_tax_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Copied onto each drafted invoice line. Tax determination itself is Accounting's", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('space_model', models.CharField(choices=[('shared', 'Shared'), ('dedicated', 'Dedicated'), ('hybrid', 'Hybrid')], default='shared', max_length=10)),
                ('committed_sqft', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Contracted floor area. Only meaningful for a dedicated or hybrid space model', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('committed_pallet_positions', models.PositiveIntegerField(default=0, help_text='Contracted pallet positions. Only meaningful for a dedicated or hybrid space model')),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('notice_days', models.PositiveSmallIntegerField(default=0, help_text='Notice period for termination, in days')),
                ('integration_mode', models.CharField(choices=[('none', 'None'), ('manual', 'Manual'), ('csv', 'CSV'), ('api', 'API'), ('edi', 'EDI'), ('marketplace', 'Marketplace')], default='none', max_length=12)),
                ('client_system', models.CharField(blank=True, help_text='SAP, NetSuite, Dynamics, Shopify, Amazon… — the system on their side', max_length=60)),
                ('edi_partner_id', models.CharField(blank=True, help_text='Their EDI interchange id. An identifier, never a credential', max_length=32)),
                ('edi_qualifier', models.CharField(blank=True, help_text='EDI qualifier for the id above, e.g. ZZ or 01', max_length=8)),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contract_document', models.ForeignKey(blank=True, help_text='The signed agreement, uploaded to the document library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currency')),
                ('default_revenue_account', models.ForeignKey(blank=True, help_text='Fallback revenue account for drafted invoice lines whose tariff line names none', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.glaccount')),
                ('parent_client', models.ForeignKey(blank=True, help_text='For a client group with divisions or brands billed separately. Leave blank for a standalone client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_clients', to='scm.logisticsclient')),
                ('party', models.ForeignKey(help_text='The company whose goods we store and handle. Name, addresses and tax details live on the party record — this row is only the 3PL agreement', on_delete=django.db.models.deletion.PROTECT, related_name='scm_logistics_clients', to='core.party')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.paymentterm')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('metric', models.CharField(choices=[('on_time_shipment_pct', 'On-Time Shipment %'), ('otif_pct', 'OTIF %'), ('same_day_ship_pct', 'Same-Day Ship %'), ('order_accuracy_pct', 'Order Accuracy %'), ('inventory_accuracy_pct', 'Inventory Accuracy %'), ('dock_to_stock_hours', 'Dock-to-Stock Hours'), ('order_cycle_time_hours', 'Order Cycle Time Hours'), ('damage_rate_pct', 'Damage Rate %'), ('shrinkage_pct', 'Shrinkage %')], help_text='What is measured. Each metric fixes its own unit and direction — see the help below the two fields.', max_length=24)),
                ('name', models.CharField(blank=True, help_text="What the contract calls this promise; blank uses the metric's own name", max_length=120)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='The number that was agreed', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('pct', '%'), ('hours', 'Hours'), ('days', 'Days')], default='pct', max_length=6)),
                ('direction', models.CharField(choices=[('higher_is_better', 'Higher is better'), ('lower_is_better', 'Lower is better')], default='higher_is_better', max_length=16)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='The at-risk band. It must sit on the failing side of the target — BELOW it when higher is better, ABOVE it when lower is better — or it can never fire.', max_digits=10, null=True)),
                ('measurement_window', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('rolling_30', 'Rolling 30 days'), ('rolling_90', 'Rolling 90 days')], default='monthly', max_length=12)),
                ('service_credit_pct', models.DecimalField(decimal_places=2, default=0, help_text="Percentage of the period's fees suggested as a credit on a breach. SUGGESTED only — 4.17 raises no credit note.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('service_credit_cap_pct', models.DecimalField(decimal_places=2, default=0, help_text='Ceiling on that percentage; 0 means no ceiling', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_active', models.BooleanField(default=True, help_text='A paused promise is not measured by the sweep and cannot be recomputed — deactivate rather than delete to keep its history')),
                ('notes', models.TextField(blank=True)),
                ('last_measured_value', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text="NULL means never measured — render it as 'Not measured', never as 0", max_digits=14, null=True)),
                ('last_measured_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('measurement_window_start', models.DateField(blank=True, editable=False, null=True)),
                ('measurement_window_end', models.DateField(blank=True, editable=False, null=True)),
                ('measurement_summary', models.CharField(blank=True, editable=False, help_text='What was counted, in words — or WHY nothing could be', max_length=255)),
                ('sample_size', models.PositiveIntegerField(default=0, editable=False)),
                ('breach_count', models.PositiveIntegerField(default=0, editable=False, help_text='Windows this promise has been breached in; a re-run over the same window cannot count twice')),
                ('status', models.CharField(choices=[('meeting', 'Meeting'), ('at_risk', 'At Risk'), ('breached', 'Breached'), ('no_data', 'No Data')], default='no_data', editable=False, max_length=10)),
                ('scope_location', models.ForeignKey(blank=True, help_text='Narrow this promise to one site or zone; blank measures the whole workspace. Only the stock-based metrics can be narrowed this way — a shipment metric ignores it and says so in its summary.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='scm.logisticsclient')),
            ],
            options={
                'ordering': ['client__code', 'metric', 'id'],
            },
        ),
        migrations.AddField(
            model_name='clientratecard',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards', to='scm.logisticsclient'),
        ),
        migrations.AddField(
            model_name='clientbillingrun',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_runs', to='scm.logisticsclient'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_client',
            field=models.ForeignKey(blank=True, help_text='The 3PL client whose goods these are; blank = our own stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_items', to='scm.logisticsclient'),
        ),
        migrations.AddField(
            model_name='location',
            name='owner_client',
            field=models.ForeignKey(blank=True, help_text='The 3PL client this space is reserved to; blank = shared / our own space', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedicated_locations', to='scm.logisticsclient'),
        ),
        migrations.AddIndex(
            model_name='logisticsclient',
            index=models.Index(fields=['tenant', 'status'], name='scm_3pl_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticsclient',
            index=models.Index(fields=['tenant', 'code'], name='scm_3pl_tnt_code_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='logisticsclient',
            unique_together={('tenant', 'code'), ('tenant', 'number'), ('tenant', 'party')},
        ),
        migrations.AddIndex(
            model_name='clientsla',
            index=models.Index(fields=['tenant', 'client', 'status'], name='scm_sla_tnt_cli_st_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsla',
            index=models.Index(fields=['tenant', 'status'], name='scm_sla_tnt_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientsla',
            unique_together={('tenant', 'client', 'metric', 'scope_location'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='clientratecard',
            index=models.Index(fields=['tenant', 'client', 'status'], name='scm_tar_tnt_cli_st_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientratecard',
            unique_together={('tenant', 'client', 'name', 'version'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='clientbillingrun',
            index=models.Index(fields=['tenant', 'status'], name='scm_cbr_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientbillingrun',
            index=models.Index(fields=['tenant', 'client', 'period_end'], name='scm_cbr_tnt_cli_end_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientbillingrun',
            unique_together={('tenant', 'client', 'period_start', 'period_end'), ('tenant', 'number')},
        ),
    ]
