# Generated by Django 5.1.15 on 2026-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0029_clientratecard_clientbillingrun_clientratecardline_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'owner_client'], name='scm_item_tnt_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'owner_client'], name='scm_loc_tnt_owner_idx'),
        ),
    ]
