# Generated by Django 5.1.15 on 2026-08-14 20:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0030_item_scm_item_tnt_owner_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='volume_cbm',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit volume in m³; the basis for allocate-by-volume landed cost', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit weight; the basis for allocate-by-weight landed cost', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='LandedCostVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('cost_date', models.DateField(help_text='The date these charges were incurred')),
                ('allocation_basis', models.CharField(choices=[('value', 'By Value'), ('quantity', 'By Quantity'), ('weight', 'By Weight'), ('volume', 'By Volume'), ('equal', 'Equal')], default='value', help_text='Default basis for every charge that does not override it', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('allocated', 'Allocated'), ('accrued', 'Accrued'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=12)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('actual_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True)),
                ('allocated_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('accrued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('bill', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_landed_cost_vouchers', to='accounting.bill')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_landed_cost_vouchers', to='accounting.currency')),
                ('goods_receipt', models.ForeignKey(help_text='The receipt whose units these costs land on', on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_vouchers', to='scm.goodsreceiptnote')),
                ('party', models.ForeignKey(help_text='Who is paid for these charges — the forwarder, broker or carrier the vendor bill is raised to', on_delete=django.db.models.deletion.PROTECT, related_name='scm_landed_cost_vouchers', to='core.party')),
                ('shipment', models.ForeignKey(blank=True, help_text='The consignment these costs were incurred on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landed_cost_vouchers', to='scm.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('trade_document', models.ForeignKey(blank=True, help_text='Customs paperwork carrying the declared value and the incoterm these charges follow from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landed_cost_vouchers', to='scm.tradedocument')),
            ],
            options={
                'ordering': ['-cost_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('freight', 'Freight'), ('duty', 'Customs Duty'), ('brokerage', 'Customs & Brokerage'), ('insurance', 'Insurance'), ('handling', 'Handling'), ('drayage', 'Drayage / Inland'), ('port_fees', 'Port & Terminal Fees'), ('fuel_surcharge', 'Fuel Surcharge'), ('inspection', 'Inspection / Fumigation'), ('storage', 'Storage / Demurrage'), ('other', 'Other')], default='freight', max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, help_text='What this was expected to cost', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, help_text='What it actually cost, once the invoice arrives', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allocation_basis', models.CharField(blank=True, choices=[('value', 'By Value'), ('quantity', 'By Quantity'), ('weight', 'By Weight'), ('volume', 'By Volume'), ('equal', 'Equal')], help_text="Leave blank to use the voucher's basis", max_length=10)),
                ('is_recoverable', models.BooleanField(default=False, help_text='Recoverable import VAT/GST — reclaimed, so it never capitalises into stock')),
                ('capitalise_to_inventory', models.BooleanField(default=True, help_text='Uncheck to expense this charge instead of landing it on the units')),
                ('hs_code', models.CharField(blank=True, max_length=20)),
                ('country_of_origin', models.CharField(blank=True, max_length=64)),
                ('duty_rate_pct', models.DecimalField(decimal_places=3, default=0, help_text='Snapshotted from the duty tariff — a later rate change never rewrites this shipment', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(100)])),
                ('freight_invoice', models.ForeignKey(blank=True, help_text='The 4.6 audited carrier invoice this charge came from, where there is one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landed_cost_charges', to='scm.freightinvoice')),
                ('gl_account', models.ForeignKey(blank=True, help_text='Expense account carried onto the drafted bill line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_landed_cost_charges', to='accounting.glaccount')),
                ('party', models.ForeignKey(blank=True, help_text="Blank bills to the voucher's payee; a different vendor here is excluded from the drafted bill", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_landed_cost_charges', to='core.party')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_landed_cost_charges', to='accounting.taxcode')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='scm.landedcostvoucher')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('basis_value', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16)),
                ('basis_used', models.CharField(choices=[('value', 'By Value'), ('quantity', 'By Quantity'), ('weight', 'By Weight'), ('volume', 'By Volume'), ('equal', 'Equal')], default='value', editable=False, max_length=10)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('unit_cost_uplift', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='scm.item')),
                ('stock_move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='scm.stockmove')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scm.landedcostcharge')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scm.landedcostvoucher')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DutyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('hs_code', models.CharField(help_text='Harmonised System / HTS classification, e.g. 8471.30. Stored upper-cased.', max_length=20)),
                ('country_of_origin', models.CharField(blank=True, help_text='Leave blank to apply to any country of origin.', max_length=64)),
                ('description', models.CharField(blank=True, help_text='What this classification covers, in the words the broker uses.', max_length=255)),
                ('duty_rate_pct', models.DecimalField(decimal_places=3, default=0, help_text='Percentage of declared value. 3dp — duty schedules are routinely quoted to fractions of a percent.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(100)])),
                ('effective_from', models.DateField(help_text='Required — a rate with no start date cannot be looked up by transaction date.')),
                ('effective_to', models.DateField(blank=True, help_text='Last day this rate applies; blank = open-ended (until it is superseded).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Clear this to retire a rate without losing what it costed.')),
                ('tax_code', models.ForeignKey(blank=True, help_text='Recoverable import VAT/GST that accompanies this duty, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scm_duty_tariffs', to='accounting.taxcode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['hs_code', '-effective_from'],
                'indexes': [models.Index(fields=['tenant', 'hs_code'], name='scm_dty_tnt_hs_idx')],
                'unique_together': {('tenant', 'hs_code', 'country_of_origin', 'effective_from'), ('tenant', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='landedcostvoucher',
            index=models.Index(fields=['tenant', 'status'], name='scm_lcv_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='landedcostvoucher',
            index=models.Index(fields=['tenant', 'cost_date'], name='scm_lcv_tnt_date_idx'),
        ),
        migrations.AddIndex(
            model_name='landedcostvoucher',
            index=models.Index(fields=['tenant', 'goods_receipt'], name='scm_lcv_tnt_grn_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='landedcostvoucher',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='landedcostallocation',
            index=models.Index(fields=['tenant', 'item'], name='scm_lca_tnt_item_idx'),
        ),
        migrations.AddIndex(
            model_name='landedcostallocation',
            index=models.Index(fields=['tenant', 'stock_move'], name='scm_lca_tnt_move_idx'),
        ),
        migrations.AddIndex(
            model_name='landedcostallocation',
            index=models.Index(fields=['tenant', 'voucher'], name='scm_lca_tnt_vch_idx'),
        ),
    ]
