# Generated by Django 5.1.15 on 2026-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice_recurring_invoice'),
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0031_item_volume_cbm_item_weight_kg_landedcostvoucher_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='landedcostvoucher',
            index=models.Index(fields=['tenant', 'party'], name='scm_lcv_tnt_party_idx'),
        ),
    ]
