# Generated by Django 5.1.15 on 2026-08-17 20:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0032_landedcostvoucher_scm_lcv_tnt_party_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('erp', 'ERP'), ('ecommerce', 'E-commerce'), ('iot', 'IoT'), ('edi', 'EDI'), ('custom', 'Custom')], default='custom', max_length=12)),
                ('system', models.CharField(blank=True, choices=[('sap', 'SAP'), ('oracle', 'Oracle'), ('netsuite', 'NetSuite'), ('dynamics', 'Microsoft Dynamics'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('woocommerce', 'WooCommerce'), ('amazon', 'Amazon'), ('ebay', 'eBay'), ('walmart', 'Walmart'), ('rfid_reader', 'RFID Reader'), ('barcode_scanner', 'Barcode Scanner'), ('sensor_gateway', 'Sensor Gateway'), ('edi_van', 'EDI VAN'), ('custom', 'Custom')], default='', help_text='The platform on the other end. Leave blank while it is undecided', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=14)),
                ('transport', models.CharField(choices=[('api_rest', 'REST API'), ('api_soap', 'SOAP API'), ('webhook', 'Webhook'), ('sftp', 'SFTP'), ('ftps', 'FTPS'), ('as2', 'AS2'), ('van', 'VAN'), ('file_drop', 'File Drop'), ('mqtt', 'MQTT'), ('llrp', 'LLRP'), ('serial', 'Serial'), ('manual', 'Manual')], default='api_rest', max_length=12)),
                ('auth_method', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('basic', 'Basic Auth'), ('oauth2', 'OAuth 2.0'), ('mtls', 'Mutual TLS'), ('ssh_key', 'SSH Key')], default='none', max_length=10)),
                ('endpoint_url', models.CharField(blank=True, help_text='Host, path or queue this connection uses. Non-HTTP schemes (sftp://, as2://, mqtt://, llrp://) are accepted — nothing in this build connects to it', max_length=500)),
                ('external_account_ref', models.CharField(blank=True, help_text='Their identifier for our account — shop domain, seller id, marketplace region', max_length=120)),
                ('interchange_id', models.CharField(blank=True, help_text='ISA sender/receiver id. Leave blank when a 3PL client is named above — theirs is held on the client record and is read through it', max_length=32)),
                ('interchange_qualifier', models.CharField(blank=True, help_text='Qualifier for the id above, e.g. ZZ or 01', max_length=8)),
                ('device_identifier', models.CharField(blank=True, help_text='Reader / gateway / scanner registry identity, for an IoT endpoint', max_length=64)),
                ('trigger_mode', models.CharField(choices=[('realtime', 'Real-time'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', help_text='Records intent only. There is NO scheduler in this build — nothing polls and nothing fires on a clock', max_length=10)),
                ('schedule_note', models.CharField(blank=True, help_text="Free text, e.g. 'every 15 minutes, business hours'. Documentation, not a cron", max_length=200)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('sandbox', 'Sandbox')], default='sandbox', max_length=10)),
                ('lifecycle_stage', models.CharField(choices=[('setup', 'Setup'), ('testing', 'Testing'), ('certified', 'Certified'), ('live', 'Live'), ('suspended', 'Suspended')], default='setup', help_text='How far onboarding has got — a different question from whether it is up now', max_length=10)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='disconnected', max_length=14)),
                ('is_active', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, editable=False)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('credential_prefix', models.CharField(blank=True, editable=False, max_length=12)),
                ('credential_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, help_text='The zone or bin an IoT reader watches', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.location')),
                ('logistics_client', models.ForeignKey(blank=True, help_text="When this connection is a 3PL client's. Their EDI identifiers stay on THAT record and are read through this link — do not retype them below", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.logisticsclient')),
                ('partner_party', models.ForeignKey(blank=True, help_text='The counterparty. Identity lives on the party record — customer/vendor/supplier are PartyRoles there, and 4.19 adds no partner table of its own', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.party')),
                ('spec_document', models.ForeignKey(blank=True, help_text="The partner's API spec or EDI implementation guide, uploaded to the library", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('document_type', models.CharField(choices=[('edi_850', '850 Purchase Order'), ('edi_855', '855 PO Acknowledgement'), ('edi_860', '860 PO Change'), ('edi_856', '856 Advance Ship Notice'), ('edi_810', '810 Invoice'), ('edi_820', '820 Payment/Remittance'), ('edi_846', '846 Inventory Advice'), ('edi_214', '214 Shipment Status'), ('edi_864', '864 Text Message'), ('edi_940', '940 Warehouse Shipping Order'), ('edi_945', '945 Warehouse Shipping Advice'), ('edi_947', '947 Warehouse Inventory Adjustment'), ('edi_997', '997 Functional Acknowledgement'), ('order_import', 'Order Import'), ('inventory_feed', 'Inventory Feed'), ('fulfilment_export', 'Fulfilment Export'), ('item_export', 'Item Export'), ('refund_sync', 'Refund Sync'), ('customer_sync', 'Customer Sync'), ('tag_read_batch', 'Tag Read Batch'), ('scan_batch', 'Scan Batch'), ('sensor_reading', 'Sensor Reading'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=14)),
                ('control_number', models.CharField(blank=True, max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Number of records the payload carried (batch size), not a row count.')),
                ('payload_excerpt', models.TextField(blank=True, help_text='TRUNCATED excerpt only. May contain partner PII (ship-to names and addresses on an 856). A full document body is NEVER stored.')),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('source', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('goods_receipt', 'Goods Receipt'), ('sales_order', 'Sales Order'), ('shipment', 'Shipment'), ('freight_invoice', 'Freight Invoice'), ('stock_move', 'Stock Move'), ('item', 'Item'), ('trade_document', 'Trade Document'), ('return_authorization', 'Return Authorization'), ('logistics_client', 'Logistics Client'), ('none', 'None')], default='none', max_length=22)),
                ('source_reference', models.CharField(blank=True, help_text="The referenced document's own number (e.g. PO-00042). A soft pointer, not an FK — see the model docstring for why there is no GenericForeignKey here.", max_length=60)),
                ('acknowledges', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_by', to='scm.integrationmessage')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='scm.integrationendpoint')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scm.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(help_text="What this subscription is for, e.g. 'Notify WMS when a shipment is delivered'", max_length=120)),
                ('trigger_entity', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('goods_receipt', 'Goods Receipt'), ('sales_order', 'Sales Order'), ('shipment', 'Shipment'), ('stock_move', 'Stock Move'), ('return_authorization', 'Return Authorization'), ('quality_inspection', 'Quality Inspection'), ('work_order', 'Work Order'), ('asset', 'Asset'), ('supply_chain_alert', 'Supply Chain Alert')], help_text='Which supply-chain record type the event happens to', max_length=22)),
                ('trigger_event', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='created', help_text='What happened to it', max_length=16)),
                ('target_url', models.URLField(help_text='HTTPS endpoint the event payload would be POSTed to', max_length=500)),
                ('payload_format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML')], default='json', max_length=6)),
                ('filter_expression', models.CharField(blank=True, help_text='RECORDED, NEVER EVALUATED in this pass — nothing delivers, so nothing filters.', max_length=200)),
                ('include_fields', models.CharField(blank=True, help_text='Comma-separated field names. RECORDED, NEVER EVALUATED in this pass.', max_length=255)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom request headers as a JSON object, e.g. {"X-Source": "NavERP"}')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_disable_threshold', models.PositiveSmallIntegerField(default=8, help_text='Consecutive failures after which this subscription SHOULD be switched off. Recorded only — nothing enforces it in this pass, because nothing delivers', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('consecutive_failures', models.PositiveIntegerField(default=0, editable=False)),
                ('last_delivery_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('signing_secret_prefix', models.CharField(blank=True, editable=False, max_length=12)),
                ('signing_secret_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(help_text='e.g. "shipment.delivered"', max_length=60)),
                ('payload_excerpt', models.TextField(blank=True, help_text='TRUNCATED excerpt only. May contain partner PII. A full payload body is NEVER stored.')),
                ('signature', models.CharField(blank=True, help_text='The HMAC hex a real transport would compute. BLANK on every row this pass creates: there is no plaintext signing key (only a prefix + hash marker) and no transport, so nothing can compute one. The column is the home for the future transport pass — this is not a bug.', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('exhausted', 'Exhausted'), ('simulated', 'Simulated')], default='pending', max_length=10)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='scm.webhooksubscription')),
            ],
            options={
                'ordering': ['-triggered_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['tenant', 'category'], name='scm_cnx_tnt_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['tenant', 'status'], name='scm_cnx_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_cnx_tnt_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationendpoint',
            unique_together={('tenant', 'name'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['tenant', 'status'], name='scm_msg_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['tenant', 'endpoint'], name='scm_msg_tnt_endpoint_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['tenant', 'external_id'], name='scm_msg_tnt_extid_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['tenant', 'occurred_at'], name='scm_msg_tnt_occat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationmessage',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['tenant', 'is_active'], name='scm_whk_tnt_active_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['tenant', 'trigger_entity'], name='scm_whk_tnt_entity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhooksubscription',
            unique_together={('tenant', 'name'), ('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['tenant', 'subscription'], name='scm_whd_tnt_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['tenant', 'status'], name='scm_whd_tnt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['tenant', 'triggered_at'], name='scm_whd_tnt_trigat_idx'),
        ),
    ]
