# Generated by Django 5.1.15 on 2026-08-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_candidate_party_role'),
        ('scm', '0033_integrationendpoint_integrationmessage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='integrationmessage',
            name='scm_msg_tnt_status_idx',
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['tenant', 'status', 'occurred_at'], name='scm_msg_tnt_status_idx'),
        ),
    ]
