"""Seed Inventory Management (Module 5) demo data — 5.1 Product & Catalog Management.

Creates, per tenant, the catalog layer AROUND the item spine that SCM 4.3 already seeds: typed
product attributes, sell-side price rows (retail / wholesale / a dated promotional window) and
imagery & documents. This command deliberately does NOT create items — ``scm.Item`` is owned by
4.3 (L36) — so run ``seed_scm`` first; a workspace with no items is skipped with a notice rather
than seeded with a parallel master.

File rows are seeded as LINKS (``url``), not uploads: writing real artifacts into MEDIA_ROOT from
a seeder would put machine-generated bytes where user content belongs. The URLs use the RFC 2606
reserved ``example.com`` domain so they are visibly placeholders.

Idempotent: each entity block is guarded by its own per-tenant existence check, so a second run
is a no-op without ``--flush``.
"""
from decimal import Decimal

from django.core.management.base import BaseCommand

from apps.core.models import Tenant
from apps.inventory.models import ItemAttribute, ItemPrice, ProductFile
from apps.scm.models import Item

# Per-item attribute sets, cycled across the catalog. (name, value, unit)
ATTRIBUTE_SETS = [
    [("Color", "Industrial Blue", ""), ("Weight", "12.5", "kg"),
     ("Dimensions", "600 x 400 x 310", "mm"), ("Warranty", "24", "months")],
    [("Color", "Safety Yellow", ""), ("Material", "Powder-coated steel", ""),
     ("Weight", "3.2", "kg"), ("IP Rating", "IP54", "")],
    [("Voltage", "230", "V"), ("Power", "1500", "W"),
     ("Dimensions", "450 x 450 x 820", "mm"), ("Noise Level", "62", "dB")],
    [("Size", "Medium", ""), ("Color", "Charcoal", ""),
     ("Weight", "0.9", "kg"), ("Country of Origin", "IN", "")],
]

# Markup ladder applied to the item's standard cost: (price_type, multiplier, min_quantity).
PRICE_LADDER = [
    ("retail", Decimal("1.45"), Decimal("1")),
    ("wholesale", Decimal("1.20"), Decimal("10")),
]


class Command(BaseCommand):
    help = ("Seed Inventory 5.1 Product & Catalog Management demo data (attributes, prices, "
            "imagery & documents) around the SCM item spine — idempotent (skips a tenant that "
            "already has the rows each pass creates).")

    def add_arguments(self, parser):
        parser.add_argument(
            "--flush", action="store_true",
            help="Delete this module's demo rows for all tenants before seeding.")

    def handle(self, *args, **options):
        if options["flush"]:
            deleted = (ItemAttribute.objects.all().count()
                       + ItemPrice.objects.all().count()
                       + ProductFile.objects.all().count())
            ItemAttribute.objects.all().delete()
            ItemPrice.objects.all().delete()
            ProductFile.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Flushed {deleted} inventory catalog rows."))

        for tenant in Tenant.objects.order_by("name"):
            items = list(Item.objects.filter(tenant=tenant).order_by("sku"))
            if not items:
                self.stdout.write(f"  {tenant.name}: no scm.Items — run `seed_scm` first, skipping.")
                continue

            self._seed_attributes(tenant, items)
            self._seed_prices(tenant, items)
            self._seed_files(tenant, items)

    # -- entity blocks -------------------------------------------------------------------------

    def _seed_attributes(self, tenant, items):
        if ItemAttribute.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: attributes already present, skipping.")
            return
        created = 0
        for index, item in enumerate(items[:8]):
            for order, (name, value, unit) in enumerate(ATTRIBUTE_SETS[index % len(ATTRIBUTE_SETS)]):
                ItemAttribute.objects.create(
                    tenant=tenant, item=item, name=name, value=value, unit=unit,
                    sequence=(order + 1) * 10)
                created += 1
        self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: {created} product attributes."))

    def _seed_prices(self, tenant, items):
        if ItemPrice.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: prices already present, skipping.")
            return
        created = 0
        for index, item in enumerate(items[:8]):
            cost = item.standard_cost or Decimal("0")
            if cost <= Decimal("0"):
                continue  # no cost basis — a price row off it would fake a margin
            for price_type, multiplier, min_quantity in PRICE_LADDER:
                ItemPrice.objects.create(
                    tenant=tenant, item=item, price_type=price_type,
                    unit_price=(cost * multiplier).quantize(Decimal("0.01")),
                    min_quantity=min_quantity, is_active=True)
                created += 1
            # Every third SKU also carries a dated promotional window.
            if index % 3 == 0:
                ItemPrice.objects.create(
                    tenant=tenant, item=item, price_type="promotional",
                    unit_price=(cost * Decimal("1.30")).quantize(Decimal("0.01")),
                    min_quantity=Decimal("1"), is_active=True,
                    notes="Seasonal promo — auto-seeded")
                created += 1
        self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: {created} price rows."))

    def _seed_files(self, tenant, items):
        if ProductFile.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: files already present, skipping.")
            return
        created = 0
        for index, item in enumerate(items[:8]):
            slug = item.sku.lower()
            ProductFile.objects.create(
                tenant=tenant, item=item, kind="photo",
                title=f"{item.sku} product photo",
                url=f"https://files.example.com/catalog/{slug}/photo.jpg",
                is_primary=True)
            ProductFile.objects.create(
                tenant=tenant, item=item, kind="datasheet",
                title=f"{item.sku} datasheet",
                url=f"https://files.example.com/catalog/{slug}/datasheet.pdf")
            created += 2
            # Safety sheets only where they plausibly exist — every third physical SKU.
            if index % 3 == 0 and item.item_type != "service":
                ProductFile.objects.create(
                    tenant=tenant, item=item, kind="safety_sheet",
                    title=f"{item.sku} safety data sheet",
                    url=f"https://files.example.com/catalog/{slug}/sds.pdf")
                created += 1
        self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: {created} images & documents."))
