"""Seed Inventory Management (Module 5) demo data — 5.1 Product & Catalog Management,
5.2 Vendor / Supplier Management, 5.3 Purchase Order (PO) Management,
5.5 Warehousing & Bin Management and 5.6 Inventory Tracking & Control.

Creates, per tenant, the catalog layer AROUND the item spine that SCM 4.3 already seeds: typed
product attributes, sell-side price rows (retail / wholesale / a dated promotional window) and
imagery & documents. 5.2 adds the vendor communication log over the supplier Parties that
``seed_scm``/``seed_core`` create. 5.3 adds the PO management layer around 4.1's purchase-order
spine: approval routing rules by value band (+ department), one email dispatch row against an
already-sent spine order, and a freshly submitted order sitting in the multi-tier approval
queue — this command deliberately does NOT create items or parties: ``scm.Item`` is owned by
4.3 and the vendor ``core.Party`` roles by core/SCM (L36) — so run ``seed_scm`` first; a
workspace with no items (or no supplier-role parties) is skipped with a notice rather than
seeded with a parallel master. 5.5 adds bin capacity envelopes over the ``seed_scm``
location tree and four cross-dock orders whose lifecycle is walked through the REAL
receive/ship/cancel actions, so the ledger legs they show are genuine StockMove rows.
5.6 adds stock-status classifications over spots that actually hold stock (read from the
ledger) and three reservations walked through the REAL release/cancel actions.

File rows are seeded as LINKS (``url``), not uploads: writing real artifacts into MEDIA_ROOT from
a seeder would put machine-generated bytes where user content belongs. The URLs use the RFC 2606
reserved ``example.com`` domain so they are visibly placeholders.

Idempotent: each entity block is guarded by its own per-tenant existence check, so a second run
is a no-op without ``--flush``.
"""
from decimal import Decimal

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.management.base import BaseCommand
from django.db.models import Sum
from django.utils import timezone

from apps.core.models import OrgUnit, Tenant
from apps.inventory.models import (
    BinCapacity,
    CrossDockOrder,
    InventoryReservation,
    ItemAttribute,
    ItemPrice,
    ProductFile,
    PurchaseOrderApproval,
    PurchaseOrderApprovalRule,
    PurchaseOrderDispatch,
    PutawayRule,
    StockStatus,
    VendorCommunication,
)
from apps.inventory.forms._common import _vendor_parties
from apps.scm.models import (
    Item,
    ItemCategory,
    Location,
    PurchaseOrder,
    PurchaseOrderLine,
    PutawayTask,
    StockMove,
)

# Per-item attribute sets, cycled across the catalog. (name, value, unit)
ATTRIBUTE_SETS = [
    [("Color", "Industrial Blue", ""), ("Weight", "12.5", "kg"),
     ("Dimensions", "600 x 400 x 310", "mm"), ("Warranty", "24", "months")],
    [("Color", "Safety Yellow", ""), ("Material", "Powder-coated steel", ""),
     ("Weight", "3.2", "kg"), ("IP Rating", "IP54", "")],
    [("Voltage", "230", "V"), ("Power", "1500", "W"),
     ("Dimensions", "450 x 450 x 820", "mm"), ("Noise Level", "62", "dB")],
    [("Size", "Medium", ""), ("Color", "Charcoal", ""),
     ("Weight", "0.9", "kg"), ("Country of Origin", "IN", "")],
]

# Markup ladder applied to the item's standard cost: (price_type, multiplier, min_quantity).
PRICE_LADDER = [
    ("retail", Decimal("1.45"), Decimal("1")),
    ("wholesale", Decimal("1.20"), Decimal("10")),
]

# Status-classification scripts cycled across the spots that hold stock. Small quantities
# only, so every classified spot keeps a visible remainder and availability stays honest.
STATUS_SCRIPTS = [
    ("damaged", "Fork puncture — case split while unloading."),
    ("on_hold", "Held pending QC disposition after a customer complaint."),
    ("expired", "Past shelf life — awaiting write-off approval."),
]

# Vendor-interaction scripts cycled across the supplier parties. (channel, direction, subject,
# body, follow_up_offset_days — None = no follow-up; negative = already overdue.)
INTERACTION_SCRIPTS = [
    ("call", "outbound", "Quarterly capacity check",
     "Confirmed they can hold the Q4 volume; asked for a revised lead-time commitment in writing.",
     7),
    ("email", "inbound", "Revised price list for next quarter",
     "Their 3% increase lands in January — flagged for the contract renewal discussion.",
     None),
    ("meeting", "outbound", "Annual supplier review",
     "Walked the scorecard together. Delivery reliability is the improvement area for this year.",
     30),
    ("site_visit", "outbound", "Line 2 audit walkthrough",
     "New inspection station installed. Two minor findings, both closed on site.",
     None),
    ("note", "inbound", "Payment terms query",
     "Accounts team asked to move from Net 30 to Net 45 — needs the AP owner's decision.",
     -3),
    ("email", "outbound", "Packaging specification change request",
     "Requested the recycled-content variant from March; awaiting their engineering sign-off.",
     14),
]


class Command(BaseCommand):
    help = ("Seed Inventory Module 5 demo data (catalog, vendor log, PO management, "
            "warehousing, tracking & control) around the SCM spines — idempotent (skips a "
            "tenant that already has the rows each pass creates).")

    def add_arguments(self, parser):
        parser.add_argument(
            "--flush", action="store_true",
            help=("Delete ALL inventory rows (attributes, prices, files, vendor communications, "
                  "PO approval rules/dispatches, bin capacities, cross-dock orders, stock "
                  "statuses, reservations) for ALL tenants before seeding — not just "
                  "seeder-created ones."))

    def handle(self, *args, **options):
        if options["flush"]:
            deleted = (ItemAttribute.objects.all().count()
                       + ItemPrice.objects.all().count()
                       + ProductFile.objects.all().count()
                        + VendorCommunication.objects.all().count()
                        + PurchaseOrderDispatch.objects.all().count()
                        + PurchaseOrderApproval.objects.all().count()
                        + PurchaseOrderApprovalRule.objects.all().count()
                       + PutawayRule.objects.all().count()
                       + StockStatus.objects.all().count()
                       + InventoryReservation.objects.all().count())
            ItemAttribute.objects.all().delete()
            ItemPrice.objects.all().delete()
            ProductFile.objects.all().delete()
            VendorCommunication.objects.all().delete()
            PurchaseOrderDispatch.objects.all().delete()  # child rows first: FKs to spine POs
            PurchaseOrderApproval.objects.all().delete()
            PurchaseOrderApprovalRule.objects.all().delete()
            PutawayRule.objects.all().delete()
            BinCapacity.objects.all().delete()
            CrossDockOrder.objects.all().delete()
            StockStatus.objects.all().delete()
            InventoryReservation.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Flushed {deleted} inventory rows."))

        for tenant in Tenant.objects.order_by("name"):
            items = list(Item.objects.filter(tenant=tenant).order_by("sku"))
            if not items:
                self.stdout.write(f"  {tenant.name}: no scm.Items — run `seed_scm` first, skipping.")
                continue

            self._seed_attributes(tenant, items)
            self._seed_prices(tenant, items)
            self._seed_files(tenant, items)
            self._seed_vendor_communications(tenant)
            self._seed_purchase_orders(tenant, items)
            self._seed_putaway_rules(tenant, items)
            self._seed_warehousing(tenant, items)
            self._seed_tracking(tenant, items)

    # -- entity blocks -------------------------------------------------------------------------

    def _seed_attributes(self, tenant, items):
        if ItemAttribute.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: attributes already present, skipping.")
            return
        created = 0
        for index, item in enumerate(items[:8]):
            for order, (name, value, unit) in enumerate(ATTRIBUTE_SETS[index % len(ATTRIBUTE_SETS)]):
                ItemAttribute.objects.create(
                    tenant=tenant, item=item, name=name, value=value, unit=unit,
                    sequence=(order + 1) * 10)
                created += 1
        self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: {created} product attributes."))

    def _seed_prices(self, tenant, items):
        if ItemPrice.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: prices already present, skipping.")
            return
        created = 0
        for index, item in enumerate(items[:8]):
            cost = item.standard_cost or Decimal("0")
            if cost <= Decimal("0"):
                continue  # no cost basis — a price row off it would fake a margin
            for price_type, multiplier, min_quantity in PRICE_LADDER:
                ItemPrice.objects.create(
                    tenant=tenant, item=item, price_type=price_type,
                    unit_price=(cost * multiplier).quantize(Decimal("0.01")),
                    min_quantity=min_quantity, is_active=True)
                created += 1
            # Every third SKU also carries a dated promotional window.
            if index % 3 == 0:
                ItemPrice.objects.create(
                    tenant=tenant, item=item, price_type="promotional",
                    unit_price=(cost * Decimal("1.30")).quantize(Decimal("0.01")),
                    min_quantity=Decimal("1"), is_active=True,
                    notes="Seasonal promo — auto-seeded")
                created += 1
        self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: {created} price rows."))

    def _seed_files(self, tenant, items):
        if ProductFile.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: files already present, skipping.")
            return
        created = 0
        for index, item in enumerate(items[:8]):
            slug = item.sku.lower()
            ProductFile.objects.create(
                tenant=tenant, item=item, kind="photo",
                title=f"{item.sku} product photo",
                url=f"https://files.example.com/catalog/{slug}/photo.jpg",
                is_primary=True)
            ProductFile.objects.create(
                tenant=tenant, item=item, kind="datasheet",
                title=f"{item.sku} datasheet",
                url=f"https://files.example.com/catalog/{slug}/datasheet.pdf")
            created += 2
            # Safety sheets only where they plausibly exist — every third physical SKU.
            if index % 3 == 0 and item.item_type != "service":
                ProductFile.objects.create(
                    tenant=tenant, item=item, kind="safety_sheet",
                    title=f"{item.sku} safety data sheet",
                    url=f"https://files.example.com/catalog/{slug}/sds.pdf")
                created += 1
        self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: {created} images & documents."))

    def _seed_vendor_communications(self, tenant):
        if VendorCommunication.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: vendor communications already present, skipping.")
            return
        vendors = list(_vendor_parties(tenant).order_by("name")[:6])
        if not vendors:
            self.stdout.write(
                f"  {tenant.name}: no supplier/vendor-role parties — run `seed_core`/`seed_scm` "
                "first, skipping the communication log.")
            return
        created = 0
        today = timezone.localdate()
        for index, (channel, direction, subject, body, follow_up_offset) in enumerate(INTERACTION_SCRIPTS):
            party = vendors[index % len(vendors)]
            occurred_at = timezone.now() - datetime.timedelta(days=(index + 1) * 3)
            follow_up_on = None
            if follow_up_offset is not None:
                follow_up_on = today + datetime.timedelta(days=follow_up_offset)
            VendorCommunication.objects.create(
                tenant=tenant, party=party, channel=channel, direction=direction,
                subject=subject, body=body, occurred_at=occurred_at, follow_up_on=follow_up_on)
            created += 1
        self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: {created} vendor communications."))

    def _seed_purchase_orders(self, tenant, items):
        """5.3 Purchase Order (PO) Management — the layer AROUND 4.1's order spine.

        Three routing rules (value bands, one department-scoped), one dispatch row against an
        already-transmitted spine order, and one freshly submitted order parked in the
        multi-tier approval queue. The PO document itself is NEVER invented here beyond that
        one demo order — the spine belongs to 4.1/``seed_scm``.
        """
        if PurchaseOrderApprovalRule.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: purchase-order management rows already present, skipping.")
            return

        created = 0
        # Routing policy: three value bands + one department-scoped override. Half-open
        # bands (min inclusive, max exclusive) so adjacent rules never both match.
        rules = [
            ("Standard purchases", Decimal("0"), Decimal("10000"), None, 1),
            ("Major purchases", Decimal("10000"), Decimal("100000"), None, 2),
            ("Capital purchases", Decimal("100000"), None, None, 3),
        ]
        org_unit = OrgUnit.objects.filter(tenant=tenant).order_by("name").first()
        if org_unit is not None:
            rules.append(("Site-critical purchases", Decimal("0"), Decimal("25000"),
                          org_unit.pk, 2))
        for name, min_amount, max_amount, org_pk, tiers in rules:
            PurchaseOrderApprovalRule.objects.create(
                tenant=tenant, name=name, min_amount=min_amount, max_amount=max_amount,
                org_unit_id=org_pk, tier_count=tiers)
            created += 1

        vendors = list(_vendor_parties(tenant).order_by("name"))
        if not vendors:
            self.stdout.write(
                f"  {tenant.name}: {created} approval rules; no supplier/vendor-role parties "
                "for the queue/dispatch demos — run `seed_core`/`seed_scm` first.")
            return

        # One dispatch row against a spine order already past approval (the 4.1 seeded order
        # ends partially received). Recipient is an RFC 2606 placeholder — no real mail is sent.
        dispatched_po = (PurchaseOrder.objects.filter(tenant=tenant)
                         .exclude(status__in=["draft", "pending_approval", "cancelled", "closed"])
                         .select_related("vendor").order_by("-id").first())
        if dispatched_po is not None:
            slug = "".join(ch for ch in dispatched_po.vendor.name.lower() if ch.isalnum())[:24]
            PurchaseOrderDispatch.objects.create(
                tenant=tenant, purchase_order=dispatched_po, channel="email",
                recipient=f"orders@{slug or 'vendor'}.example.com",
                reference=f"MSG-{dispatched_po.number}",
                note="Seeded transmission record.")
            created += 1

        # One freshly submitted order in the approval queue: item-based line over the first
        # supplier party. Submitted straight to pending_approval so the queue has content;
        # its tier decisions are left for the person clicking through the demo.
        po = PurchaseOrder(
            tenant=tenant, vendor=vendors[0], order_date=timezone.localdate(),
            status="draft",
            notes="Seeded reorder replenishment — awaiting multi-tier approval.",
        )
        po.save()
        item = items[0]
        PurchaseOrderLine.objects.create(
            purchase_order=po,
            item_description=item.name,
            sku_hint=item.sku,
            uom_hint=item.uom.code if item.uom_id else "",
            quantity=Decimal("40"),
            unit_price=item.standard_cost or Decimal("0"),
        )
        po.recalc_totals()
        po.status = "pending_approval"
        po.save(update_fields=["status", "updated_at"])
        created += 1
        self.stdout.write(self.style.SUCCESS(
            f"  {tenant.name}: {created} purchase-order management rows "
            f"(rules/dispatch/{po.number} pending approval)."))

    def _seed_putaway_rules(self, tenant, items):
        """5.4 Receiving & Putaway — the directed-putaway RULES behind the suggestion engine.

        Four standing instructions over the seeded location tree, chosen so every resolver
        tier shows on one suggestions page: an item rule (MON-27) that beats its own
        category rule (IT Equipment) beats the catch-all — plus a guarded cold-chain row
        for when a chilled item ever exists. Also guarantees exactly ONE open putaway
        task off DOCK-1 so /inventory/putaway-suggestions/ renders with real candidates.
        Reuses seed_scm rows only; no items are invented here.
        """
        if PutawayRule.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: putaway rules already present, skipping.")
            return

        warehouse = Location.objects.filter(tenant=tenant, code="WH-MAIN",
                                            location_type="warehouse").first()
        dock = Location.objects.filter(tenant=tenant, code="DOCK-1").first()
        bin_a1 = Location.objects.filter(tenant=tenant, code="WH-MAIN-A1").first()
        if not (warehouse and dock and bin_a1):
            self.stdout.write(
                f"  {tenant.name}: WH-MAIN/DOCK-1/WH-MAIN-A1 missing — run `seed_scm` "
                "first, skipping putaway rules.")
            return

        created = 0

        def sku(s):
            return Item.objects.filter(tenant=tenant, sku=s).first()

        # 1. Item-specific cold-chain rule — seeded only when such an item exists at all;
        #    an absent cold chain must not invent one.
        vac = sku("VAC-10")
        if vac is not None:
            cold_zone, _ = Location.objects.get_or_create(
                tenant=tenant, code="CR-01",
                defaults={"name": "Cold Room 1", "location_type": "zone",
                          "parent": warehouse, "storage_condition": "chilled"})
            PutawayRule.objects.create(
                tenant=tenant, item=vac, source_location=dock,
                destination=cold_zone, priority=10,
                notes="Cold-chain arrivals go straight to the cold room.")
            created += 1

        # 2. The specificity demo: this item rule out-ranks rule 3 despite its priority.
        mon = sku("MON-27")
        if mon is not None:
            PutawayRule.objects.create(
                tenant=tenant, item=mon, source_location=dock,
                destination=bin_a1, priority=20)
            created += 1
            open_task = (PutawayTask.objects.filter(
                tenant=tenant, item=mon, from_location=dock,
                status__in=PutawayTask.OPEN_STATUSES).order_by("id").first())
            if open_task is None:
                PutawayTask.objects.create(
                    tenant=tenant, item=mon, from_location=dock, to_location=bin_a1,
                    quantity=Decimal("12"), strategy="directed", status="pending",
                    notes="Seeded receiving queue demo.")

        # 3. Category fallback for everything else in IT Equipment.
        it_cat = ItemCategory.objects.filter(tenant=tenant, name="IT Equipment").first()
        if it_cat is not None:
            PutawayRule.objects.create(
                tenant=tenant, category=it_cat, source_location=dock,
                destination=bin_a1, priority=30)
            created += 1

        # 4. Odoo's documented catch-all best practice: an empty rule so nothing arrives
        #    without guidance.
        PutawayRule.objects.create(
            tenant=tenant, source_location=dock, destination=warehouse,
            priority=900, notes="Catch-all: anything else lands under WH-MAIN.")
        created += 1

        self.stdout.write(self.style.SUCCESS(
            f"  {tenant.name}: {created} putaway rules (+1 open putaway task)."))

    def _seed_warehousing(self, tenant, items):
        """5.5 Warehousing & Bin Management — capacity envelopes + cross-dock flows.

        Extends the location tree ``seed_scm`` created (WH-MAIN / DOCK-1 / WH-MAIN-A1)
        with one zone, two more bins and a second dock — get_or_create, so re-runs and
        partially-built trees are safe. The four cross-dock orders are walked through the
        REAL ``receive``/``ship``/``cancel`` actions rather than hand-stamped statuses, so
        every stage on the list page has the genuine StockMove legs behind it and the
        ledger-derived utilisation bars read true.
        """
        main = Location.objects.filter(tenant=tenant, code="WH-MAIN").first()
        if main is None:
            self.stdout.write(
                f"  {tenant.name}: no WH-MAIN location — run `seed_scm` first, skipping "
                "the warehousing seed.")
            return

        # --- structure: a zone, two bins and a second dock under the seeded warehouse ------
        zone, _ = Location.objects.get_or_create(
            tenant=tenant, code="WH-MAIN-ZA",
            defaults={"name": "Zone A", "location_type": "zone", "parent": main})
        bin_a1, _ = Location.objects.get_or_create(
            tenant=tenant, code="WH-MAIN-A1",
            defaults={"name": "Aisle A Bin 1", "location_type": "bin", "parent": zone,
                      "pick_sequence": 10, "abc_class": "a", "capacity": Decimal("500")})
        bin_a2, _ = Location.objects.get_or_create(
            tenant=tenant, code="WH-MAIN-A2",
            defaults={"name": "Aisle A Bin 2", "location_type": "bin", "parent": zone,
                      "pick_sequence": 20, "abc_class": "b"})
        bin_b1, _ = Location.objects.get_or_create(
            tenant=tenant, code="WH-MAIN-B1",
            defaults={"name": "Bulk Rack B1", "location_type": "bin", "parent": main,
                      "pick_sequence": 30, "abc_class": "c"})
        dock1, _ = Location.objects.get_or_create(
            tenant=tenant, code="DOCK-1",
            defaults={"name": "Dock Door 1", "location_type": "staging", "parent": main,
                      "is_pickable": False})
        Location.objects.get_or_create(
            tenant=tenant, code="DOCK-2",
            defaults={"name": "Dock Door 2", "location_type": "staging", "parent": main,
                      "is_pickable": False})

        # --- capacity envelopes --------------------------------------------------------------
        if BinCapacity.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: bin capacities already present, skipping.")
        else:
            profiles = [
                # A deliberately small dock cap: the received cross-dock below lands 10
                # units here, so the map shows one genuinely over-limit bin instead of
                # five rows all reading a flattering single-digit percent.
                (dock1, None, None, Decimal("8"), "Overflow cap while a trailer is being worked."),
                (bin_a1, Decimal("750.00"), Decimal("3.500"), Decimal("500"),
                 "Fast-mover pick face — full envelope declared."),
                (bin_a2, None, None, Decimal("240"), ""),
                (bin_b1, Decimal("2000.00"), None, None,
                 "Bulk rack limited by floor loading, not count."),
            ]
            for location, weight, volume, quantity, notes in profiles:
                BinCapacity.objects.create(tenant=tenant, location=location,
                                           max_weight_kg=weight, max_volume_m3=volume,
                                           max_quantity=quantity, notes=notes)
            self.stdout.write(self.style.SUCCESS(f"  {tenant.name}: 4 bin capacity profiles."))

        # --- cross-dock orders, walked through the real actions -------------------------------
        if CrossDockOrder.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: cross-dock orders already present, skipping.")
            return
        User = get_user_model()
        user = User.objects.filter(tenant=tenant).order_by("pk").first()
        if user is None:
            self.stdout.write(self.style.WARNING(
                f"  {tenant.name}: no workspace user to attribute the cross-dock actions "
                "to — skipping that seed."))
            return
        today = timezone.localdate()

        def _order(item, qty, day_offset, inbound, outbound):
            return CrossDockOrder(
                tenant=tenant, item=item, dock_location=dock1,
                quantity=Decimal(qty), unit_cost=item.standard_cost or Decimal("0"),
                scheduled_date=today + datetime.timedelta(days=day_offset),
                inbound_reference=inbound, outbound_reference=outbound)

        orders = [
            (_order(items[0], "25", 5, "PO-SEED-101", "SO-SEED-201"), None),
            # Lands 10 units on DOCK-1 whose cap is 8 -> the honest over-limit demo.
            (_order(items[1 % len(items)], "10", 0, "PO-SEED-102", "SO-SEED-202"), "received"),
            (_order(items[2 % len(items)], "12", -1, "PO-SEED-103", "SO-SEED-203"), "shipped"),
            (_order(items[3 % len(items)], "6", -2, "PO-SEED-104", "SO-SEED-204"),
             "cancelled"),
        ]
        for order, target in orders:
            order.save()
            if target == "received":
                order.receive(user)
            elif target == "shipped":
                order.receive(user)
                order.ship(user)
            elif target == "cancelled":
                order.receive(user)
                try:
                    order.cancel(user)
                except ValidationError:
                    pass  # stock moved on since planning — leave it received rather than fake it
        self.stdout.write(self.style.SUCCESS(
            f"  {tenant.name}: 4 cross-dock orders (draft/received/shipped/cancelled) with "
            "real ledger legs."))

    def _stocked_spots(self, tenant):
        """(item_id, location_id, qty) for every spot the ledger says actually holds stock,
        positive totals only — the honest pool the 5.6 classifications draw from."""
        return [
            combo for combo in (StockMove.objects.filter(tenant=tenant)
                                .values("item_id", "location_id")
                                .annotate(qty=Sum("quantity")))
            if combo["qty"] and combo["qty"] > 0
        ]

    def _seed_tracking(self, tenant, items):
        """5.6 Inventory Tracking & Control — status classifications + reservations.

        Classifications land only on spots the ledger shows holding stock (read live via
        ``_stocked_spots``), each for a SMALL slice of that spot so a visible remainder
        stays unclassified and availability never reads as fabricated. Reservations are
        walked through the REAL release/cancel actions like 5.5's cross-docks, so their
        statuses carry genuine audit rows. Quantities are kept modest against typical
        seeded receipts; direct model creation deliberately bypasses the form's ATP check
        (that guard is for user input), so the numbers stay small to keep the demo true.
        """
        spots = self._stocked_spots(tenant)
        items_by_pk = {i.pk: i for i in items}
        locations_by_pk = {loc.pk: loc for loc in Location.objects.filter(tenant=tenant)}

        # --- stock status classifications ---------------------------------------------------
        if StockStatus.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: stock statuses already present, skipping.")
        elif not spots:
            self.stdout.write(
                f"  {tenant.name}: no stocked locations yet — run `seed_scm` first, "
                "skipping stock-status classifications.")
        else:
            created = 0
            for index, spot in enumerate(spots[:6]):
                status, reason = STATUS_SCRIPTS[index % len(STATUS_SCRIPTS)]
                item = items_by_pk.get(spot["item_id"])
                location = locations_by_pk.get(spot["location_id"])
                if item is None or location is None:
                    continue
                quantity = min(Decimal("3"), spot["qty"])
                if quantity <= Decimal("0"):
                    continue
                StockStatus.objects.create(
                    tenant=tenant, item=item, location=location, status=status,
                    quantity=quantity, reason=reason)
                created += 1
            self.stdout.write(self.style.SUCCESS(
                f"  {tenant.name}: {created} stock-status classifications."))

        # --- reservations, walked through the real actions -------------------------------------
        if InventoryReservation.objects.filter(tenant=tenant).exists():
            self.stdout.write(f"  {tenant.name}: reservations already present, skipping.")
            return
        User = get_user_model()
        user = User.objects.filter(tenant=tenant).order_by("pk").first()
        if user is None:
            self.stdout.write(self.style.WARNING(
                f"  {tenant.name}: no workspace user to attribute reservations to — "
                "skipping that seed."))
            return

        if spots:
            anchor = spots[0]
            demo_item = items_by_pk.get(anchor["item_id"]) or items[0]
            demo_location = (locations_by_pk.get(anchor["location_id"])
                             or Location.objects.filter(tenant=tenant).first())
        else:
            demo_item = items[0]
            demo_location = Location.objects.filter(tenant=tenant).first()
        if demo_location is None:
            self.stdout.write(
                f"  {tenant.name}: no locations — run `seed_scm` first, skipping reservations.")
            return

        reserved = InventoryReservation.objects.create(
            tenant=tenant, item=demo_item, location=demo_location,
            purpose="sales_order", reference="SO-SEED-301", quantity=Decimal("4"),
            reserved_by=user, notes="Seeded hold for an open customer order.")

        released = InventoryReservation(
            tenant=tenant, item=demo_item, location=demo_location,
            purpose="job", reference="JOB-0042", quantity=Decimal("3"),
            reserved_by=user, notes="Seeded lock handed to the floor.")
        released.save()
        released.release(user)

        cancelled = InventoryReservation(
            tenant=tenant, item=demo_item, location=demo_location,
            purpose="project", reference="PRJ-2026-Q3", quantity=Decimal("2"),
            reserved_by=user, notes="Seeded claim dropped when the project paused.")
        cancelled.save()
        cancelled.cancel(user)

        self.stdout.write(self.style.SUCCESS(
            f"  {tenant.name}: 3 reservations ({reserved.number} reserved / "
            f"{released.number} released / {cancelled.number} cancelled)."))
