"""core views package — split from apps/core/views.py.

core is a Module 0 foundation app with no NavERP sub-modules, so entity files are FLAT
at the package root. This __init__ re-exports every symbol, so
``from apps.core.views import X`` (and the 78+ modules that do it) is unchanged.
"""
from ._common import *  # noqa: F401,F403
from ._common import _parties  # noqa: F401
from .OrgUnit import (
    orgunit_list,
    orgunit_create,
    orgunit_detail,
    orgunit_edit,
    orgunit_delete,
)  # noqa: F401
from .Party import (
    party_list,
    party_create,
    party_detail,
    party_edit,
    party_delete,
)  # noqa: F401
from .PartyRole import (
    partyrole_list,
    partyrole_create,
    partyrole_detail,
    partyrole_edit,
    partyrole_delete,
)  # noqa: F401
from .Address import (
    address_list,
    address_create,
    address_detail,
    address_edit,
    address_delete,
)  # noqa: F401
from .ContactMethod import (
    contactmethod_list,
    contactmethod_create,
    contactmethod_detail,
    contactmethod_edit,
    contactmethod_delete,
)  # noqa: F401
from .PartyRelationship import (
    partyrelationship_list,
    partyrelationship_create,
    partyrelationship_detail,
    partyrelationship_edit,
    partyrelationship_delete,
)  # noqa: F401
from .Employment import (
    employment_list,
    employment_create,
    employment_detail,
    employment_edit,
    employment_delete,
)  # noqa: F401
from .Activity import (
    activity_list,
    activity_create,
    activity_detail,
    activity_edit,
    activity_delete,
)  # noqa: F401
from .Document import (
    document_list,
    document_create,
    document_detail,
    document_edit,
    document_delete,
)  # noqa: F401
from .AuditLog import (
    auditlog_list,
    auditlog_detail,
)  # noqa: F401
from .Search import (
    global_search_suggest,
    global_search,
)  # noqa: F401
from .ModuleAccessScope import (
    module_scope_list,
    module_scope_detail,
    module_scope_create,
    module_scope_edit,
    module_scope_delete,
    module_scope_sync,
    field_mask_list,
    field_mask_create,
    field_mask_edit,
    field_mask_delete,
    access_matrix,
)  # noqa: F401
from .Privacy import (
    consent_purpose_list,
    consent_purpose_create,
    consent_purpose_edit,
    consent_purpose_delete,
    consent_record_list,
    consent_record_create,
    consent_record_delete,
    consent_matrix,
    dsar_list,
    dsar_detail,
    dsar_create,
    dsar_edit,
    dsar_delete,
    dsar_verify,
    dsar_complete,
    dsar_refuse,
    dsar_withdraw,
    retention_policy_list,
    retention_policy_create,
    retention_policy_edit,
    retention_policy_delete,
    disposal_list,
    disposal_create,
    retention_board,
    pii_map,
    pii_scan,
    pii_classify,
    regulatory_list,
    regulatory_sync,
    regulatory_edit,
    privacy_overview,
)  # noqa: F401
from .Settings import (
    setting_definition_list,
    setting_definition_create,
    setting_definition_edit,
    setting_definition_delete,
    settings_overview,
    setting_value_edit,
    feature_flag_list,
    feature_flag_create,
    feature_flag_edit,
    feature_flag_delete,
    numbering_scheme_list,
    numbering_scheme_create,
    numbering_scheme_edit,
    numbering_scheme_delete,
    numbering_board,
    calendar_edit,
    calendar_board,
    holiday_list,
    holiday_create,
    holiday_edit,
    holiday_delete,
    custom_field_list,
    custom_field_create,
    custom_field_edit,
    custom_field_delete,
    custom_field_detail,
    custom_field_value_create,
    custom_field_value_delete,
    config_overview,
)  # noqa: F401
from .Workflow import (
    workflow_definition_list,
    workflow_definition_detail,
    workflow_definition_create,
    workflow_definition_edit,
    workflow_definition_delete,
    workflow_step_create,
    workflow_step_edit,
    workflow_step_delete,
    approval_limit_list,
    approval_limit_create,
    approval_limit_edit,
    approval_limit_delete,
    sla_rule_list,
    sla_rule_create,
    sla_rule_edit,
    sla_rule_delete,
    business_rule_list,
    business_rule_detail,
    business_rule_create,
    business_rule_edit,
    business_rule_delete,
    business_rule_test,
    rule_log_list,
    process_monitor,
    workflow_overview,
)  # noqa: F401
from .Notification import (
    channel_list,
    channel_create,
    channel_edit,
    channel_delete,
    template_list,
    template_detail,
    template_create,
    template_edit,
    template_delete,
    template_preview,
    rule_list,
    rule_create,
    rule_edit,
    rule_delete,
    rule_resolve,
    my_preferences,
    preference_list,
    preference_create,
    preference_edit,
    preference_delete,
    provider_list,
    provider_create,
    provider_edit,
    provider_delete,
    delivery_board,
    notification_overview,
)  # noqa: F401
from .Integration import (
    credential_list,
    credential_issue,
    credential_edit,
    credential_revoke,
    credential_delete,
    rate_limit_list,
    rate_limit_create,
    rate_limit_edit,
    rate_limit_delete,
    connector_list,
    connector_create,
    connector_edit,
    connector_delete,
    mapping_list,
    mapping_detail,
    mapping_create,
    mapping_edit,
    mapping_delete,
    sync_list,
    sync_create,
    sync_edit,
    sync_delete,
    integration_board,
    integration_overview,
)  # noqa: F401
from .Localization import (
    language_list,
    timezone_list,
    locale_profile_edit,
    user_locale_edit,
    statutory_rule_list,
    statutory_rule_create,
    statutory_rule_detail,
    statutory_rule_edit,
    statutory_rule_delete,
    localization_board,
    localization_overview,
)  # noqa: F401
